execute positioned as @s unless block ~-10~-1~-10 air at @s run setblock~-10~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-10 air at @s run setblock~-10~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-10 air at @s run setblock~-10~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-10 air at @s run setblock~-10~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-10 air at @s run setblock~-10~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-9 air at @s run setblock~-10~-1~-9 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-9 air at @s run setblock~-10~-2~-9 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-9 air at @s run setblock~-10~-3~-9 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-9 air at @s run setblock~-10~-4~-9 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-9 air at @s run setblock~-10~-5~-9 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-8 air at @s run setblock~-10~-1~-8 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-8 air at @s run setblock~-10~-2~-8 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-8 air at @s run setblock~-10~-3~-8 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-8 air at @s run setblock~-10~-4~-8 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-8 air at @s run setblock~-10~-5~-8 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-7 air at @s run setblock~-10~-1~-7 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-7 air at @s run setblock~-10~-2~-7 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-7 air at @s run setblock~-10~-3~-7 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-7 air at @s run setblock~-10~-4~-7 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-7 air at @s run setblock~-10~-5~-7 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-6 air at @s run setblock~-10~-1~-6 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-6 air at @s run setblock~-10~-2~-6 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-6 air at @s run setblock~-10~-3~-6 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-6 air at @s run setblock~-10~-4~-6 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-6 air at @s run setblock~-10~-5~-6 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-5 air at @s run setblock~-10~-1~-5 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-5 air at @s run setblock~-10~-2~-5 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-5 air at @s run setblock~-10~-3~-5 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-5 air at @s run setblock~-10~-4~-5 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-5 air at @s run setblock~-10~-5~-5 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-4 air at @s run setblock~-10~-1~-4 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-4 air at @s run setblock~-10~-2~-4 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-4 air at @s run setblock~-10~-3~-4 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-4 air at @s run setblock~-10~-4~-4 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-4 air at @s run setblock~-10~-5~-4 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-3 air at @s run setblock~-10~-1~-3 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-3 air at @s run setblock~-10~-2~-3 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-3 air at @s run setblock~-10~-3~-3 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-3 air at @s run setblock~-10~-4~-3 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-3 air at @s run setblock~-10~-5~-3 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-2 air at @s run setblock~-10~-1~-2 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-2 air at @s run setblock~-10~-2~-2 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-2 air at @s run setblock~-10~-3~-2 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-2 air at @s run setblock~-10~-4~-2 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-2 air at @s run setblock~-10~-5~-2 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~-1 air at @s run setblock~-10~-1~-1 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~-1 air at @s run setblock~-10~-2~-1 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~-1 air at @s run setblock~-10~-3~-1 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~-1 air at @s run setblock~-10~-4~-1 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~-1 air at @s run setblock~-10~-5~-1 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~0 air at @s run setblock~-10~-1~0 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~0 air at @s run setblock~-10~-2~0 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~0 air at @s run setblock~-10~-3~0 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~0 air at @s run setblock~-10~-4~0 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~0 air at @s run setblock~-10~-5~0 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~1 air at @s run setblock~-10~-1~1 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~1 air at @s run setblock~-10~-2~1 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~1 air at @s run setblock~-10~-3~1 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~1 air at @s run setblock~-10~-4~1 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~1 air at @s run setblock~-10~-5~1 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~2 air at @s run setblock~-10~-1~2 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~2 air at @s run setblock~-10~-2~2 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~2 air at @s run setblock~-10~-3~2 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~2 air at @s run setblock~-10~-4~2 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~2 air at @s run setblock~-10~-5~2 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~3 air at @s run setblock~-10~-1~3 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~3 air at @s run setblock~-10~-2~3 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~3 air at @s run setblock~-10~-3~3 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~3 air at @s run setblock~-10~-4~3 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~3 air at @s run setblock~-10~-5~3 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~4 air at @s run setblock~-10~-1~4 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~4 air at @s run setblock~-10~-2~4 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~4 air at @s run setblock~-10~-3~4 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~4 air at @s run setblock~-10~-4~4 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~4 air at @s run setblock~-10~-5~4 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~5 air at @s run setblock~-10~-1~5 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~5 air at @s run setblock~-10~-2~5 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~5 air at @s run setblock~-10~-3~5 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~5 air at @s run setblock~-10~-4~5 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~5 air at @s run setblock~-10~-5~5 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~6 air at @s run setblock~-10~-1~6 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~6 air at @s run setblock~-10~-2~6 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~6 air at @s run setblock~-10~-3~6 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~6 air at @s run setblock~-10~-4~6 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~6 air at @s run setblock~-10~-5~6 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~7 air at @s run setblock~-10~-1~7 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~7 air at @s run setblock~-10~-2~7 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~7 air at @s run setblock~-10~-3~7 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~7 air at @s run setblock~-10~-4~7 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~7 air at @s run setblock~-10~-5~7 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~8 air at @s run setblock~-10~-1~8 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~8 air at @s run setblock~-10~-2~8 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~8 air at @s run setblock~-10~-3~8 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~8 air at @s run setblock~-10~-4~8 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~8 air at @s run setblock~-10~-5~8 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~9 air at @s run setblock~-10~-1~9 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~9 air at @s run setblock~-10~-2~9 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~9 air at @s run setblock~-10~-3~9 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~9 air at @s run setblock~-10~-4~9 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~9 air at @s run setblock~-10~-5~9 sandstone 0 replace
execute positioned as @s unless block ~-10~-1~10 air at @s run setblock~-10~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-10~-2~10 air at @s run setblock~-10~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-10~-3~10 air at @s run setblock~-10~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-10~-4~10 air at @s run setblock~-10~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-10~-5~10 air at @s run setblock~-10~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-9~-1~-10 air at @s run setblock~-9~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-9~-2~-10 air at @s run setblock~-9~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-9~-3~-10 air at @s run setblock~-9~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-9~-4~-10 air at @s run setblock~-9~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-9~-5~-10 air at @s run setblock~-9~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-9~-1~10 air at @s run setblock~-9~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-9~-2~10 air at @s run setblock~-9~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-9~-3~10 air at @s run setblock~-9~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-9~-4~10 air at @s run setblock~-9~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-9~-5~10 air at @s run setblock~-9~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-8~-1~-10 air at @s run setblock~-8~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-8~-2~-10 air at @s run setblock~-8~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-8~-3~-10 air at @s run setblock~-8~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-8~-4~-10 air at @s run setblock~-8~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-8~-5~-10 air at @s run setblock~-8~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-8~-1~10 air at @s run setblock~-8~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-8~-2~10 air at @s run setblock~-8~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-8~-3~10 air at @s run setblock~-8~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-8~-4~10 air at @s run setblock~-8~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-8~-5~10 air at @s run setblock~-8~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-7~-1~-10 air at @s run setblock~-7~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-7~-2~-10 air at @s run setblock~-7~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-7~-3~-10 air at @s run setblock~-7~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-7~-4~-10 air at @s run setblock~-7~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-7~-5~-10 air at @s run setblock~-7~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-7~-1~10 air at @s run setblock~-7~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-7~-2~10 air at @s run setblock~-7~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-7~-3~10 air at @s run setblock~-7~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-7~-4~10 air at @s run setblock~-7~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-7~-5~10 air at @s run setblock~-7~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-6~-1~-10 air at @s run setblock~-6~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-6~-2~-10 air at @s run setblock~-6~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-6~-3~-10 air at @s run setblock~-6~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-6~-4~-10 air at @s run setblock~-6~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-6~-5~-10 air at @s run setblock~-6~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-6~-1~10 air at @s run setblock~-6~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-6~-2~10 air at @s run setblock~-6~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-6~-3~10 air at @s run setblock~-6~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-6~-4~10 air at @s run setblock~-6~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-6~-5~10 air at @s run setblock~-6~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-5~-1~-10 air at @s run setblock~-5~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-5~-2~-10 air at @s run setblock~-5~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-5~-3~-10 air at @s run setblock~-5~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-5~-4~-10 air at @s run setblock~-5~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-5~-5~-10 air at @s run setblock~-5~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-5~-1~10 air at @s run setblock~-5~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-5~-2~10 air at @s run setblock~-5~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-5~-3~10 air at @s run setblock~-5~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-5~-4~10 air at @s run setblock~-5~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-5~-5~10 air at @s run setblock~-5~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-4~-1~-10 air at @s run setblock~-4~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-4~-2~-10 air at @s run setblock~-4~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-4~-3~-10 air at @s run setblock~-4~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-4~-4~-10 air at @s run setblock~-4~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-4~-5~-10 air at @s run setblock~-4~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-4~-1~10 air at @s run setblock~-4~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-4~-2~10 air at @s run setblock~-4~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-4~-3~10 air at @s run setblock~-4~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-4~-4~10 air at @s run setblock~-4~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-4~-5~10 air at @s run setblock~-4~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-3~-1~-10 air at @s run setblock~-3~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-3~-2~-10 air at @s run setblock~-3~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-3~-3~-10 air at @s run setblock~-3~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-3~-4~-10 air at @s run setblock~-3~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-3~-5~-10 air at @s run setblock~-3~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-3~-1~10 air at @s run setblock~-3~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-3~-2~10 air at @s run setblock~-3~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-3~-3~10 air at @s run setblock~-3~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-3~-4~10 air at @s run setblock~-3~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-3~-5~10 air at @s run setblock~-3~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-2~-1~-10 air at @s run setblock~-2~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-2~-2~-10 air at @s run setblock~-2~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-2~-3~-10 air at @s run setblock~-2~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-2~-4~-10 air at @s run setblock~-2~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-2~-5~-10 air at @s run setblock~-2~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-2~-1~10 air at @s run setblock~-2~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-2~-2~10 air at @s run setblock~-2~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-2~-3~10 air at @s run setblock~-2~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-2~-4~10 air at @s run setblock~-2~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-2~-5~10 air at @s run setblock~-2~-5~10 sandstone 0 replace
execute positioned as @s unless block ~-1~-1~-10 air at @s run setblock~-1~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~-1~-2~-10 air at @s run setblock~-1~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~-1~-3~-10 air at @s run setblock~-1~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~-1~-4~-10 air at @s run setblock~-1~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~-1~-5~-10 air at @s run setblock~-1~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~-1~-1~10 air at @s run setblock~-1~-1~10 sandstone 0 replace
execute positioned as @s unless block ~-1~-2~10 air at @s run setblock~-1~-2~10 sandstone 0 replace
execute positioned as @s unless block ~-1~-3~10 air at @s run setblock~-1~-3~10 sandstone 0 replace
execute positioned as @s unless block ~-1~-4~10 air at @s run setblock~-1~-4~10 sandstone 0 replace
execute positioned as @s unless block ~-1~-5~10 air at @s run setblock~-1~-5~10 sandstone 0 replace
execute positioned as @s unless block ~0~-1~-10 air at @s run setblock~0~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~0~-2~-10 air at @s run setblock~0~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~0~-3~-10 air at @s run setblock~0~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~0~-4~-10 air at @s run setblock~0~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~0~-5~-10 air at @s run setblock~0~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~0~-1~10 air at @s run setblock~0~-1~10 sandstone 0 replace
execute positioned as @s unless block ~0~-2~10 air at @s run setblock~0~-2~10 sandstone 0 replace
execute positioned as @s unless block ~0~-3~10 air at @s run setblock~0~-3~10 sandstone 0 replace
execute positioned as @s unless block ~0~-4~10 air at @s run setblock~0~-4~10 sandstone 0 replace
execute positioned as @s unless block ~0~-5~10 air at @s run setblock~0~-5~10 sandstone 0 replace
execute positioned as @s unless block ~1~-1~-10 air at @s run setblock~1~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~1~-2~-10 air at @s run setblock~1~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~1~-3~-10 air at @s run setblock~1~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~1~-4~-10 air at @s run setblock~1~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~1~-5~-10 air at @s run setblock~1~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~1~-1~10 air at @s run setblock~1~-1~10 sandstone 0 replace
execute positioned as @s unless block ~1~-2~10 air at @s run setblock~1~-2~10 sandstone 0 replace
execute positioned as @s unless block ~1~-3~10 air at @s run setblock~1~-3~10 sandstone 0 replace
execute positioned as @s unless block ~1~-4~10 air at @s run setblock~1~-4~10 sandstone 0 replace
execute positioned as @s unless block ~1~-5~10 air at @s run setblock~1~-5~10 sandstone 0 replace
execute positioned as @s unless block ~2~-1~-10 air at @s run setblock~2~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~2~-2~-10 air at @s run setblock~2~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~2~-3~-10 air at @s run setblock~2~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~2~-4~-10 air at @s run setblock~2~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~2~-5~-10 air at @s run setblock~2~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~2~-1~10 air at @s run setblock~2~-1~10 sandstone 0 replace
execute positioned as @s unless block ~2~-2~10 air at @s run setblock~2~-2~10 sandstone 0 replace
execute positioned as @s unless block ~2~-3~10 air at @s run setblock~2~-3~10 sandstone 0 replace
execute positioned as @s unless block ~2~-4~10 air at @s run setblock~2~-4~10 sandstone 0 replace
execute positioned as @s unless block ~2~-5~10 air at @s run setblock~2~-5~10 sandstone 0 replace
execute positioned as @s unless block ~3~-1~-10 air at @s run setblock~3~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~3~-2~-10 air at @s run setblock~3~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~3~-3~-10 air at @s run setblock~3~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~3~-4~-10 air at @s run setblock~3~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~3~-5~-10 air at @s run setblock~3~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~3~-1~10 air at @s run setblock~3~-1~10 sandstone 0 replace
execute positioned as @s unless block ~3~-2~10 air at @s run setblock~3~-2~10 sandstone 0 replace
execute positioned as @s unless block ~3~-3~10 air at @s run setblock~3~-3~10 sandstone 0 replace
execute positioned as @s unless block ~3~-4~10 air at @s run setblock~3~-4~10 sandstone 0 replace
execute positioned as @s unless block ~3~-5~10 air at @s run setblock~3~-5~10 sandstone 0 replace
execute positioned as @s unless block ~4~-1~-10 air at @s run setblock~4~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~4~-2~-10 air at @s run setblock~4~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~4~-3~-10 air at @s run setblock~4~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~4~-4~-10 air at @s run setblock~4~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~4~-5~-10 air at @s run setblock~4~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~4~-1~10 air at @s run setblock~4~-1~10 sandstone 0 replace
execute positioned as @s unless block ~4~-2~10 air at @s run setblock~4~-2~10 sandstone 0 replace
execute positioned as @s unless block ~4~-3~10 air at @s run setblock~4~-3~10 sandstone 0 replace
execute positioned as @s unless block ~4~-4~10 air at @s run setblock~4~-4~10 sandstone 0 replace
execute positioned as @s unless block ~4~-5~10 air at @s run setblock~4~-5~10 sandstone 0 replace
execute positioned as @s unless block ~5~-1~-10 air at @s run setblock~5~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~5~-2~-10 air at @s run setblock~5~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~5~-3~-10 air at @s run setblock~5~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~5~-4~-10 air at @s run setblock~5~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~5~-5~-10 air at @s run setblock~5~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~5~-1~10 air at @s run setblock~5~-1~10 sandstone 0 replace
execute positioned as @s unless block ~5~-2~10 air at @s run setblock~5~-2~10 sandstone 0 replace
execute positioned as @s unless block ~5~-3~10 air at @s run setblock~5~-3~10 sandstone 0 replace
execute positioned as @s unless block ~5~-4~10 air at @s run setblock~5~-4~10 sandstone 0 replace
execute positioned as @s unless block ~5~-5~10 air at @s run setblock~5~-5~10 sandstone 0 replace
execute positioned as @s unless block ~6~-1~-10 air at @s run setblock~6~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~6~-2~-10 air at @s run setblock~6~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~6~-3~-10 air at @s run setblock~6~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~6~-4~-10 air at @s run setblock~6~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~6~-5~-10 air at @s run setblock~6~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~6~-1~10 air at @s run setblock~6~-1~10 sandstone 0 replace
execute positioned as @s unless block ~6~-2~10 air at @s run setblock~6~-2~10 sandstone 0 replace
execute positioned as @s unless block ~6~-3~10 air at @s run setblock~6~-3~10 sandstone 0 replace
execute positioned as @s unless block ~6~-4~10 air at @s run setblock~6~-4~10 sandstone 0 replace
execute positioned as @s unless block ~6~-5~10 air at @s run setblock~6~-5~10 sandstone 0 replace
execute positioned as @s unless block ~7~-1~-10 air at @s run setblock~7~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~7~-2~-10 air at @s run setblock~7~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~7~-3~-10 air at @s run setblock~7~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~7~-4~-10 air at @s run setblock~7~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~7~-5~-10 air at @s run setblock~7~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~7~-1~10 air at @s run setblock~7~-1~10 sandstone 0 replace
execute positioned as @s unless block ~7~-2~10 air at @s run setblock~7~-2~10 sandstone 0 replace
execute positioned as @s unless block ~7~-3~10 air at @s run setblock~7~-3~10 sandstone 0 replace
execute positioned as @s unless block ~7~-4~10 air at @s run setblock~7~-4~10 sandstone 0 replace
execute positioned as @s unless block ~7~-5~10 air at @s run setblock~7~-5~10 sandstone 0 replace
execute positioned as @s unless block ~8~-1~-10 air at @s run setblock~8~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~8~-2~-10 air at @s run setblock~8~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~8~-3~-10 air at @s run setblock~8~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~8~-4~-10 air at @s run setblock~8~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~8~-5~-10 air at @s run setblock~8~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~8~-1~10 air at @s run setblock~8~-1~10 sandstone 0 replace
execute positioned as @s unless block ~8~-2~10 air at @s run setblock~8~-2~10 sandstone 0 replace
execute positioned as @s unless block ~8~-3~10 air at @s run setblock~8~-3~10 sandstone 0 replace
execute positioned as @s unless block ~8~-4~10 air at @s run setblock~8~-4~10 sandstone 0 replace
execute positioned as @s unless block ~8~-5~10 air at @s run setblock~8~-5~10 sandstone 0 replace
execute positioned as @s unless block ~9~-1~-10 air at @s run setblock~9~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~9~-2~-10 air at @s run setblock~9~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~9~-3~-10 air at @s run setblock~9~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~9~-4~-10 air at @s run setblock~9~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~9~-5~-10 air at @s run setblock~9~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~9~-1~10 air at @s run setblock~9~-1~10 sandstone 0 replace
execute positioned as @s unless block ~9~-2~10 air at @s run setblock~9~-2~10 sandstone 0 replace
execute positioned as @s unless block ~9~-3~10 air at @s run setblock~9~-3~10 sandstone 0 replace
execute positioned as @s unless block ~9~-4~10 air at @s run setblock~9~-4~10 sandstone 0 replace
execute positioned as @s unless block ~9~-5~10 air at @s run setblock~9~-5~10 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-10 air at @s run setblock~10~-1~-10 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-10 air at @s run setblock~10~-2~-10 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-10 air at @s run setblock~10~-3~-10 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-10 air at @s run setblock~10~-4~-10 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-10 air at @s run setblock~10~-5~-10 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-9 air at @s run setblock~10~-1~-9 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-9 air at @s run setblock~10~-2~-9 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-9 air at @s run setblock~10~-3~-9 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-9 air at @s run setblock~10~-4~-9 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-9 air at @s run setblock~10~-5~-9 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-8 air at @s run setblock~10~-1~-8 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-8 air at @s run setblock~10~-2~-8 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-8 air at @s run setblock~10~-3~-8 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-8 air at @s run setblock~10~-4~-8 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-8 air at @s run setblock~10~-5~-8 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-7 air at @s run setblock~10~-1~-7 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-7 air at @s run setblock~10~-2~-7 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-7 air at @s run setblock~10~-3~-7 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-7 air at @s run setblock~10~-4~-7 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-7 air at @s run setblock~10~-5~-7 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-6 air at @s run setblock~10~-1~-6 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-6 air at @s run setblock~10~-2~-6 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-6 air at @s run setblock~10~-3~-6 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-6 air at @s run setblock~10~-4~-6 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-6 air at @s run setblock~10~-5~-6 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-5 air at @s run setblock~10~-1~-5 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-5 air at @s run setblock~10~-2~-5 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-5 air at @s run setblock~10~-3~-5 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-5 air at @s run setblock~10~-4~-5 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-5 air at @s run setblock~10~-5~-5 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-4 air at @s run setblock~10~-1~-4 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-4 air at @s run setblock~10~-2~-4 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-4 air at @s run setblock~10~-3~-4 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-4 air at @s run setblock~10~-4~-4 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-4 air at @s run setblock~10~-5~-4 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-3 air at @s run setblock~10~-1~-3 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-3 air at @s run setblock~10~-2~-3 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-3 air at @s run setblock~10~-3~-3 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-3 air at @s run setblock~10~-4~-3 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-3 air at @s run setblock~10~-5~-3 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-2 air at @s run setblock~10~-1~-2 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-2 air at @s run setblock~10~-2~-2 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-2 air at @s run setblock~10~-3~-2 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-2 air at @s run setblock~10~-4~-2 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-2 air at @s run setblock~10~-5~-2 sandstone 0 replace
execute positioned as @s unless block ~10~-1~-1 air at @s run setblock~10~-1~-1 sandstone 0 replace
execute positioned as @s unless block ~10~-2~-1 air at @s run setblock~10~-2~-1 sandstone 0 replace
execute positioned as @s unless block ~10~-3~-1 air at @s run setblock~10~-3~-1 sandstone 0 replace
execute positioned as @s unless block ~10~-4~-1 air at @s run setblock~10~-4~-1 sandstone 0 replace
execute positioned as @s unless block ~10~-5~-1 air at @s run setblock~10~-5~-1 sandstone 0 replace
execute positioned as @s unless block ~10~-1~0 air at @s run setblock~10~-1~0 sandstone 0 replace
execute positioned as @s unless block ~10~-2~0 air at @s run setblock~10~-2~0 sandstone 0 replace
execute positioned as @s unless block ~10~-3~0 air at @s run setblock~10~-3~0 sandstone 0 replace
execute positioned as @s unless block ~10~-4~0 air at @s run setblock~10~-4~0 sandstone 0 replace
execute positioned as @s unless block ~10~-5~0 air at @s run setblock~10~-5~0 sandstone 0 replace
execute positioned as @s unless block ~10~-1~1 air at @s run setblock~10~-1~1 sandstone 0 replace
execute positioned as @s unless block ~10~-2~1 air at @s run setblock~10~-2~1 sandstone 0 replace
execute positioned as @s unless block ~10~-3~1 air at @s run setblock~10~-3~1 sandstone 0 replace
execute positioned as @s unless block ~10~-4~1 air at @s run setblock~10~-4~1 sandstone 0 replace
execute positioned as @s unless block ~10~-5~1 air at @s run setblock~10~-5~1 sandstone 0 replace
execute positioned as @s unless block ~10~-1~2 air at @s run setblock~10~-1~2 sandstone 0 replace
execute positioned as @s unless block ~10~-2~2 air at @s run setblock~10~-2~2 sandstone 0 replace
execute positioned as @s unless block ~10~-3~2 air at @s run setblock~10~-3~2 sandstone 0 replace
execute positioned as @s unless block ~10~-4~2 air at @s run setblock~10~-4~2 sandstone 0 replace
execute positioned as @s unless block ~10~-5~2 air at @s run setblock~10~-5~2 sandstone 0 replace
execute positioned as @s unless block ~10~-1~3 air at @s run setblock~10~-1~3 sandstone 0 replace
execute positioned as @s unless block ~10~-2~3 air at @s run setblock~10~-2~3 sandstone 0 replace
execute positioned as @s unless block ~10~-3~3 air at @s run setblock~10~-3~3 sandstone 0 replace
execute positioned as @s unless block ~10~-4~3 air at @s run setblock~10~-4~3 sandstone 0 replace
execute positioned as @s unless block ~10~-5~3 air at @s run setblock~10~-5~3 sandstone 0 replace
execute positioned as @s unless block ~10~-1~4 air at @s run setblock~10~-1~4 sandstone 0 replace
execute positioned as @s unless block ~10~-2~4 air at @s run setblock~10~-2~4 sandstone 0 replace
execute positioned as @s unless block ~10~-3~4 air at @s run setblock~10~-3~4 sandstone 0 replace
execute positioned as @s unless block ~10~-4~4 air at @s run setblock~10~-4~4 sandstone 0 replace
execute positioned as @s unless block ~10~-5~4 air at @s run setblock~10~-5~4 sandstone 0 replace
execute positioned as @s unless block ~10~-1~5 air at @s run setblock~10~-1~5 sandstone 0 replace
execute positioned as @s unless block ~10~-2~5 air at @s run setblock~10~-2~5 sandstone 0 replace
execute positioned as @s unless block ~10~-3~5 air at @s run setblock~10~-3~5 sandstone 0 replace
execute positioned as @s unless block ~10~-4~5 air at @s run setblock~10~-4~5 sandstone 0 replace
execute positioned as @s unless block ~10~-5~5 air at @s run setblock~10~-5~5 sandstone 0 replace
execute positioned as @s unless block ~10~-1~6 air at @s run setblock~10~-1~6 sandstone 0 replace
execute positioned as @s unless block ~10~-2~6 air at @s run setblock~10~-2~6 sandstone 0 replace
execute positioned as @s unless block ~10~-3~6 air at @s run setblock~10~-3~6 sandstone 0 replace
execute positioned as @s unless block ~10~-4~6 air at @s run setblock~10~-4~6 sandstone 0 replace
execute positioned as @s unless block ~10~-5~6 air at @s run setblock~10~-5~6 sandstone 0 replace
execute positioned as @s unless block ~10~-1~7 air at @s run setblock~10~-1~7 sandstone 0 replace
execute positioned as @s unless block ~10~-2~7 air at @s run setblock~10~-2~7 sandstone 0 replace
execute positioned as @s unless block ~10~-3~7 air at @s run setblock~10~-3~7 sandstone 0 replace
execute positioned as @s unless block ~10~-4~7 air at @s run setblock~10~-4~7 sandstone 0 replace
execute positioned as @s unless block ~10~-5~7 air at @s run setblock~10~-5~7 sandstone 0 replace
execute positioned as @s unless block ~10~-1~8 air at @s run setblock~10~-1~8 sandstone 0 replace
execute positioned as @s unless block ~10~-2~8 air at @s run setblock~10~-2~8 sandstone 0 replace
execute positioned as @s unless block ~10~-3~8 air at @s run setblock~10~-3~8 sandstone 0 replace
execute positioned as @s unless block ~10~-4~8 air at @s run setblock~10~-4~8 sandstone 0 replace
execute positioned as @s unless block ~10~-5~8 air at @s run setblock~10~-5~8 sandstone 0 replace
execute positioned as @s unless block ~10~-1~9 air at @s run setblock~10~-1~9 sandstone 0 replace
execute positioned as @s unless block ~10~-2~9 air at @s run setblock~10~-2~9 sandstone 0 replace
execute positioned as @s unless block ~10~-3~9 air at @s run setblock~10~-3~9 sandstone 0 replace
execute positioned as @s unless block ~10~-4~9 air at @s run setblock~10~-4~9 sandstone 0 replace
execute positioned as @s unless block ~10~-5~9 air at @s run setblock~10~-5~9 sandstone 0 replace
execute positioned as @s unless block ~10~-1~10 air at @s run setblock~10~-1~10 sandstone 0 replace
execute positioned as @s unless block ~10~-2~10 air at @s run setblock~10~-2~10 sandstone 0 replace
execute positioned as @s unless block ~10~-3~10 air at @s run setblock~10~-3~10 sandstone 0 replace
execute positioned as @s unless block ~10~-4~10 air at @s run setblock~10~-4~10 sandstone 0 replace
execute positioned as @s unless block ~10~-5~10 air at @s run setblock~10~-5~10 sandstone 0 replace
