execute as @s unless block ~-4~-1~-4 air at @s run setblock ~-4~-1~-4 sandstone 0 replace
execute as @s unless block ~-4~-2~-4 air at @s run setblock ~-4~-2~-4 sandstone 0 replace
execute as @s unless block ~-4~-3~-4 air at @s run setblock ~-4~-3~-4 sandstone 0 replace
execute as @s unless block ~-4~-4~-4 air at @s run setblock ~-4~-4~-4 sandstone 0 replace
execute as @s unless block ~-4~-5~-4 air at @s run setblock ~-4~-5~-4 sandstone 0 replace
execute as @s unless block ~-4~-1~-3 air at @s run setblock ~-4~-1~-3 sandstone 0 replace
execute as @s unless block ~-4~-2~-3 air at @s run setblock ~-4~-2~-3 sandstone 0 replace
execute as @s unless block ~-4~-3~-3 air at @s run setblock ~-4~-3~-3 sandstone 0 replace
execute as @s unless block ~-4~-4~-3 air at @s run setblock ~-4~-4~-3 sandstone 0 replace
execute as @s unless block ~-4~-5~-3 air at @s run setblock ~-4~-5~-3 sandstone 0 replace
execute as @s unless block ~-4~-1~-2 air at @s run setblock ~-4~-1~-2 sandstone 0 replace
execute as @s unless block ~-4~-2~-2 air at @s run setblock ~-4~-2~-2 sandstone 0 replace
execute as @s unless block ~-4~-3~-2 air at @s run setblock ~-4~-3~-2 sandstone 0 replace
execute as @s unless block ~-4~-4~-2 air at @s run setblock ~-4~-4~-2 sandstone 0 replace
execute as @s unless block ~-4~-5~-2 air at @s run setblock ~-4~-5~-2 sandstone 0 replace
execute as @s unless block ~-4~-1~-1 air at @s run setblock ~-4~-1~-1 sandstone 0 replace
execute as @s unless block ~-4~-2~-1 air at @s run setblock ~-4~-2~-1 sandstone 0 replace
execute as @s unless block ~-4~-3~-1 air at @s run setblock ~-4~-3~-1 sandstone 0 replace
execute as @s unless block ~-4~-4~-1 air at @s run setblock ~-4~-4~-1 sandstone 0 replace
execute as @s unless block ~-4~-5~-1 air at @s run setblock ~-4~-5~-1 sandstone 0 replace
execute as @s unless block ~-4~-1~0 air at @s run setblock ~-4~-1~0 sandstone 0 replace
execute as @s unless block ~-4~-2~0 air at @s run setblock ~-4~-2~0 sandstone 0 replace
execute as @s unless block ~-4~-3~0 air at @s run setblock ~-4~-3~0 sandstone 0 replace
execute as @s unless block ~-4~-4~0 air at @s run setblock ~-4~-4~0 sandstone 0 replace
execute as @s unless block ~-4~-5~0 air at @s run setblock ~-4~-5~0 sandstone 0 replace
execute as @s unless block ~-4~-1~1 air at @s run setblock ~-4~-1~1 sandstone 0 replace
execute as @s unless block ~-4~-2~1 air at @s run setblock ~-4~-2~1 sandstone 0 replace
execute as @s unless block ~-4~-3~1 air at @s run setblock ~-4~-3~1 sandstone 0 replace
execute as @s unless block ~-4~-4~1 air at @s run setblock ~-4~-4~1 sandstone 0 replace
execute as @s unless block ~-4~-5~1 air at @s run setblock ~-4~-5~1 sandstone 0 replace
execute as @s unless block ~-4~-1~2 air at @s run setblock ~-4~-1~2 sandstone 0 replace
execute as @s unless block ~-4~-2~2 air at @s run setblock ~-4~-2~2 sandstone 0 replace
execute as @s unless block ~-4~-3~2 air at @s run setblock ~-4~-3~2 sandstone 0 replace
execute as @s unless block ~-4~-4~2 air at @s run setblock ~-4~-4~2 sandstone 0 replace
execute as @s unless block ~-4~-5~2 air at @s run setblock ~-4~-5~2 sandstone 0 replace
execute as @s unless block ~-4~-1~3 air at @s run setblock ~-4~-1~3 sandstone 0 replace
execute as @s unless block ~-4~-2~3 air at @s run setblock ~-4~-2~3 sandstone 0 replace
execute as @s unless block ~-4~-3~3 air at @s run setblock ~-4~-3~3 sandstone 0 replace
execute as @s unless block ~-4~-4~3 air at @s run setblock ~-4~-4~3 sandstone 0 replace
execute as @s unless block ~-4~-5~3 air at @s run setblock ~-4~-5~3 sandstone 0 replace
execute as @s unless block ~-4~-1~4 air at @s run setblock ~-4~-1~4 sandstone 0 replace
execute as @s unless block ~-4~-2~4 air at @s run setblock ~-4~-2~4 sandstone 0 replace
execute as @s unless block ~-4~-3~4 air at @s run setblock ~-4~-3~4 sandstone 0 replace
execute as @s unless block ~-4~-4~4 air at @s run setblock ~-4~-4~4 sandstone 0 replace
execute as @s unless block ~-4~-5~4 air at @s run setblock ~-4~-5~4 sandstone 0 replace
execute as @s unless block ~-3~-1~-4 air at @s run setblock ~-3~-1~-4 sandstone 0 replace
execute as @s unless block ~-3~-2~-4 air at @s run setblock ~-3~-2~-4 sandstone 0 replace
execute as @s unless block ~-3~-3~-4 air at @s run setblock ~-3~-3~-4 sandstone 0 replace
execute as @s unless block ~-3~-4~-4 air at @s run setblock ~-3~-4~-4 sandstone 0 replace
execute as @s unless block ~-3~-5~-4 air at @s run setblock ~-3~-5~-4 sandstone 0 replace
execute as @s unless block ~-3~-1~4 air at @s run setblock ~-3~-1~4 sandstone 0 replace
execute as @s unless block ~-3~-2~4 air at @s run setblock ~-3~-2~4 sandstone 0 replace
execute as @s unless block ~-3~-3~4 air at @s run setblock ~-3~-3~4 sandstone 0 replace
execute as @s unless block ~-3~-4~4 air at @s run setblock ~-3~-4~4 sandstone 0 replace
execute as @s unless block ~-3~-5~4 air at @s run setblock ~-3~-5~4 sandstone 0 replace
execute as @s unless block ~-2~-1~-4 air at @s run setblock ~-2~-1~-4 sandstone 0 replace
execute as @s unless block ~-2~-2~-4 air at @s run setblock ~-2~-2~-4 sandstone 0 replace
execute as @s unless block ~-2~-3~-4 air at @s run setblock ~-2~-3~-4 sandstone 0 replace
execute as @s unless block ~-2~-4~-4 air at @s run setblock ~-2~-4~-4 sandstone 0 replace
execute as @s unless block ~-2~-5~-4 air at @s run setblock ~-2~-5~-4 sandstone 0 replace
execute as @s unless block ~-2~-1~4 air at @s run setblock ~-2~-1~4 sandstone 0 replace
execute as @s unless block ~-2~-2~4 air at @s run setblock ~-2~-2~4 sandstone 0 replace
execute as @s unless block ~-2~-3~4 air at @s run setblock ~-2~-3~4 sandstone 0 replace
execute as @s unless block ~-2~-4~4 air at @s run setblock ~-2~-4~4 sandstone 0 replace
execute as @s unless block ~-2~-5~4 air at @s run setblock ~-2~-5~4 sandstone 0 replace
execute as @s unless block ~-1~-1~-4 air at @s run setblock ~-1~-1~-4 sandstone 0 replace
execute as @s unless block ~-1~-2~-4 air at @s run setblock ~-1~-2~-4 sandstone 0 replace
execute as @s unless block ~-1~-3~-4 air at @s run setblock ~-1~-3~-4 sandstone 0 replace
execute as @s unless block ~-1~-4~-4 air at @s run setblock ~-1~-4~-4 sandstone 0 replace
execute as @s unless block ~-1~-5~-4 air at @s run setblock ~-1~-5~-4 sandstone 0 replace
execute as @s unless block ~-1~-1~4 air at @s run setblock ~-1~-1~4 sandstone 0 replace
execute as @s unless block ~-1~-2~4 air at @s run setblock ~-1~-2~4 sandstone 0 replace
execute as @s unless block ~-1~-3~4 air at @s run setblock ~-1~-3~4 sandstone 0 replace
execute as @s unless block ~-1~-4~4 air at @s run setblock ~-1~-4~4 sandstone 0 replace
execute as @s unless block ~-1~-5~4 air at @s run setblock ~-1~-5~4 sandstone 0 replace
execute as @s unless block ~0~-1~-4 air at @s run setblock ~0~-1~-4 sandstone 0 replace
execute as @s unless block ~0~-2~-4 air at @s run setblock ~0~-2~-4 sandstone 0 replace
execute as @s unless block ~0~-3~-4 air at @s run setblock ~0~-3~-4 sandstone 0 replace
execute as @s unless block ~0~-4~-4 air at @s run setblock ~0~-4~-4 sandstone 0 replace
execute as @s unless block ~0~-5~-4 air at @s run setblock ~0~-5~-4 sandstone 0 replace
execute as @s unless block ~0~-1~4 air at @s run setblock ~0~-1~4 sandstone 0 replace
execute as @s unless block ~0~-2~4 air at @s run setblock ~0~-2~4 sandstone 0 replace
execute as @s unless block ~0~-3~4 air at @s run setblock ~0~-3~4 sandstone 0 replace
execute as @s unless block ~0~-4~4 air at @s run setblock ~0~-4~4 sandstone 0 replace
execute as @s unless block ~0~-5~4 air at @s run setblock ~0~-5~4 sandstone 0 replace
execute as @s unless block ~1~-1~-4 air at @s run setblock ~1~-1~-4 sandstone 0 replace
execute as @s unless block ~1~-2~-4 air at @s run setblock ~1~-2~-4 sandstone 0 replace
execute as @s unless block ~1~-3~-4 air at @s run setblock ~1~-3~-4 sandstone 0 replace
execute as @s unless block ~1~-4~-4 air at @s run setblock ~1~-4~-4 sandstone 0 replace
execute as @s unless block ~1~-5~-4 air at @s run setblock ~1~-5~-4 sandstone 0 replace
execute as @s unless block ~1~-1~4 air at @s run setblock ~1~-1~4 sandstone 0 replace
execute as @s unless block ~1~-2~4 air at @s run setblock ~1~-2~4 sandstone 0 replace
execute as @s unless block ~1~-3~4 air at @s run setblock ~1~-3~4 sandstone 0 replace
execute as @s unless block ~1~-4~4 air at @s run setblock ~1~-4~4 sandstone 0 replace
execute as @s unless block ~1~-5~4 air at @s run setblock ~1~-5~4 sandstone 0 replace
execute as @s unless block ~2~-1~-4 air at @s run setblock ~2~-1~-4 sandstone 0 replace
execute as @s unless block ~2~-2~-4 air at @s run setblock ~2~-2~-4 sandstone 0 replace
execute as @s unless block ~2~-3~-4 air at @s run setblock ~2~-3~-4 sandstone 0 replace
execute as @s unless block ~2~-4~-4 air at @s run setblock ~2~-4~-4 sandstone 0 replace
execute as @s unless block ~2~-5~-4 air at @s run setblock ~2~-5~-4 sandstone 0 replace
execute as @s unless block ~2~-1~4 air at @s run setblock ~2~-1~4 sandstone 0 replace
execute as @s unless block ~2~-2~4 air at @s run setblock ~2~-2~4 sandstone 0 replace
execute as @s unless block ~2~-3~4 air at @s run setblock ~2~-3~4 sandstone 0 replace
execute as @s unless block ~2~-4~4 air at @s run setblock ~2~-4~4 sandstone 0 replace
execute as @s unless block ~2~-5~4 air at @s run setblock ~2~-5~4 sandstone 0 replace
execute as @s unless block ~3~-1~-4 air at @s run setblock ~3~-1~-4 sandstone 0 replace
execute as @s unless block ~3~-2~-4 air at @s run setblock ~3~-2~-4 sandstone 0 replace
execute as @s unless block ~3~-3~-4 air at @s run setblock ~3~-3~-4 sandstone 0 replace
execute as @s unless block ~3~-4~-4 air at @s run setblock ~3~-4~-4 sandstone 0 replace
execute as @s unless block ~3~-5~-4 air at @s run setblock ~3~-5~-4 sandstone 0 replace
execute as @s unless block ~3~-1~4 air at @s run setblock ~3~-1~4 sandstone 0 replace
execute as @s unless block ~3~-2~4 air at @s run setblock ~3~-2~4 sandstone 0 replace
execute as @s unless block ~3~-3~4 air at @s run setblock ~3~-3~4 sandstone 0 replace
execute as @s unless block ~3~-4~4 air at @s run setblock ~3~-4~4 sandstone 0 replace
execute as @s unless block ~3~-5~4 air at @s run setblock ~3~-5~4 sandstone 0 replace
execute as @s unless block ~4~-1~-4 air at @s run setblock ~4~-1~-4 sandstone 0 replace
execute as @s unless block ~4~-2~-4 air at @s run setblock ~4~-2~-4 sandstone 0 replace
execute as @s unless block ~4~-3~-4 air at @s run setblock ~4~-3~-4 sandstone 0 replace
execute as @s unless block ~4~-4~-4 air at @s run setblock ~4~-4~-4 sandstone 0 replace
execute as @s unless block ~4~-5~-4 air at @s run setblock ~4~-5~-4 sandstone 0 replace
execute as @s unless block ~4~-1~-3 air at @s run setblock ~4~-1~-3 sandstone 0 replace
execute as @s unless block ~4~-2~-3 air at @s run setblock ~4~-2~-3 sandstone 0 replace
execute as @s unless block ~4~-3~-3 air at @s run setblock ~4~-3~-3 sandstone 0 replace
execute as @s unless block ~4~-4~-3 air at @s run setblock ~4~-4~-3 sandstone 0 replace
execute as @s unless block ~4~-5~-3 air at @s run setblock ~4~-5~-3 sandstone 0 replace
execute as @s unless block ~4~-1~-2 air at @s run setblock ~4~-1~-2 sandstone 0 replace
execute as @s unless block ~4~-2~-2 air at @s run setblock ~4~-2~-2 sandstone 0 replace
execute as @s unless block ~4~-3~-2 air at @s run setblock ~4~-3~-2 sandstone 0 replace
execute as @s unless block ~4~-4~-2 air at @s run setblock ~4~-4~-2 sandstone 0 replace
execute as @s unless block ~4~-5~-2 air at @s run setblock ~4~-5~-2 sandstone 0 replace
execute as @s unless block ~4~-1~-1 air at @s run setblock ~4~-1~-1 sandstone 0 replace
execute as @s unless block ~4~-2~-1 air at @s run setblock ~4~-2~-1 sandstone 0 replace
execute as @s unless block ~4~-3~-1 air at @s run setblock ~4~-3~-1 sandstone 0 replace
execute as @s unless block ~4~-4~-1 air at @s run setblock ~4~-4~-1 sandstone 0 replace
execute as @s unless block ~4~-5~-1 air at @s run setblock ~4~-5~-1 sandstone 0 replace
execute as @s unless block ~4~-1~0 air at @s run setblock ~4~-1~0 sandstone 0 replace
execute as @s unless block ~4~-2~0 air at @s run setblock ~4~-2~0 sandstone 0 replace
execute as @s unless block ~4~-3~0 air at @s run setblock ~4~-3~0 sandstone 0 replace
execute as @s unless block ~4~-4~0 air at @s run setblock ~4~-4~0 sandstone 0 replace
execute as @s unless block ~4~-5~0 air at @s run setblock ~4~-5~0 sandstone 0 replace
execute as @s unless block ~4~-1~1 air at @s run setblock ~4~-1~1 sandstone 0 replace
execute as @s unless block ~4~-2~1 air at @s run setblock ~4~-2~1 sandstone 0 replace
execute as @s unless block ~4~-3~1 air at @s run setblock ~4~-3~1 sandstone 0 replace
execute as @s unless block ~4~-4~1 air at @s run setblock ~4~-4~1 sandstone 0 replace
execute as @s unless block ~4~-5~1 air at @s run setblock ~4~-5~1 sandstone 0 replace
execute as @s unless block ~4~-1~2 air at @s run setblock ~4~-1~2 sandstone 0 replace
execute as @s unless block ~4~-2~2 air at @s run setblock ~4~-2~2 sandstone 0 replace
execute as @s unless block ~4~-3~2 air at @s run setblock ~4~-3~2 sandstone 0 replace
execute as @s unless block ~4~-4~2 air at @s run setblock ~4~-4~2 sandstone 0 replace
execute as @s unless block ~4~-5~2 air at @s run setblock ~4~-5~2 sandstone 0 replace
execute as @s unless block ~4~-1~3 air at @s run setblock ~4~-1~3 sandstone 0 replace
execute as @s unless block ~4~-2~3 air at @s run setblock ~4~-2~3 sandstone 0 replace
execute as @s unless block ~4~-3~3 air at @s run setblock ~4~-3~3 sandstone 0 replace
execute as @s unless block ~4~-4~3 air at @s run setblock ~4~-4~3 sandstone 0 replace
execute as @s unless block ~4~-5~3 air at @s run setblock ~4~-5~3 sandstone 0 replace
execute as @s unless block ~4~-1~4 air at @s run setblock ~4~-1~4 sandstone 0 replace
execute as @s unless block ~4~-2~4 air at @s run setblock ~4~-2~4 sandstone 0 replace
execute as @s unless block ~4~-3~4 air at @s run setblock ~4~-3~4 sandstone 0 replace
execute as @s unless block ~4~-4~4 air at @s run setblock ~4~-4~4 sandstone 0 replace
execute as @s unless block ~4~-5~4 air at @s run setblock ~4~-5~4 sandstone 0 replace
