execute at positioned as @s unless block ~-3~-1~-3 air at @s run setblock~-3~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~-3 air at @s run setblock~-3~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~-3 air at @s run setblock~-3~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~-3 air at @s run setblock~-3~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~-3 air at @s run setblock~-3~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-1~-2 air at @s run setblock~-3~-1~-2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~-2 air at @s run setblock~-3~-2~-2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~-2 air at @s run setblock~-3~-3~-2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~-2 air at @s run setblock~-3~-4~-2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~-2 air at @s run setblock~-3~-5~-2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-1~-1 air at @s run setblock~-3~-1~-1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~-1 air at @s run setblock~-3~-2~-1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~-1 air at @s run setblock~-3~-3~-1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~-1 air at @s run setblock~-3~-4~-1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~-1 air at @s run setblock~-3~-5~-1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-1~0 air at @s run setblock~-3~-1~0 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~0 air at @s run setblock~-3~-2~0 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~0 air at @s run setblock~-3~-3~0 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~0 air at @s run setblock~-3~-4~0 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~0 air at @s run setblock~-3~-5~0 sandstone 0 replace
execute at positioned as @s unless block ~-3~-1~1 air at @s run setblock~-3~-1~1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~1 air at @s run setblock~-3~-2~1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~1 air at @s run setblock~-3~-3~1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~1 air at @s run setblock~-3~-4~1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~1 air at @s run setblock~-3~-5~1 sandstone 0 replace
execute at positioned as @s unless block ~-3~-1~2 air at @s run setblock~-3~-1~2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~2 air at @s run setblock~-3~-2~2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~2 air at @s run setblock~-3~-3~2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~2 air at @s run setblock~-3~-4~2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~2 air at @s run setblock~-3~-5~2 sandstone 0 replace
execute at positioned as @s unless block ~-3~-1~3 air at @s run setblock~-3~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-2~3 air at @s run setblock~-3~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-3~3 air at @s run setblock~-3~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-4~3 air at @s run setblock~-3~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~-3~-5~3 air at @s run setblock~-3~-5~3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-1~-3 air at @s run setblock~-2~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-2~-3 air at @s run setblock~-2~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-3~-3 air at @s run setblock~-2~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-4~-3 air at @s run setblock~-2~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-5~-3 air at @s run setblock~-2~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-1~3 air at @s run setblock~-2~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-2~3 air at @s run setblock~-2~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-3~3 air at @s run setblock~-2~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-4~3 air at @s run setblock~-2~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~-2~-5~3 air at @s run setblock~-2~-5~3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-1~-3 air at @s run setblock~-1~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-2~-3 air at @s run setblock~-1~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-3~-3 air at @s run setblock~-1~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-4~-3 air at @s run setblock~-1~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-5~-3 air at @s run setblock~-1~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-1~3 air at @s run setblock~-1~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-2~3 air at @s run setblock~-1~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-3~3 air at @s run setblock~-1~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-4~3 air at @s run setblock~-1~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~-1~-5~3 air at @s run setblock~-1~-5~3 sandstone 0 replace
execute at positioned as @s unless block ~0~-1~-3 air at @s run setblock~0~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~0~-2~-3 air at @s run setblock~0~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~0~-3~-3 air at @s run setblock~0~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~0~-4~-3 air at @s run setblock~0~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~0~-5~-3 air at @s run setblock~0~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~0~-1~3 air at @s run setblock~0~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~0~-2~3 air at @s run setblock~0~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~0~-3~3 air at @s run setblock~0~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~0~-4~3 air at @s run setblock~0~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~0~-5~3 air at @s run setblock~0~-5~3 sandstone 0 replace
execute at positioned as @s unless block ~1~-1~-3 air at @s run setblock~1~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~1~-2~-3 air at @s run setblock~1~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~1~-3~-3 air at @s run setblock~1~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~1~-4~-3 air at @s run setblock~1~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~1~-5~-3 air at @s run setblock~1~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~1~-1~3 air at @s run setblock~1~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~1~-2~3 air at @s run setblock~1~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~1~-3~3 air at @s run setblock~1~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~1~-4~3 air at @s run setblock~1~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~1~-5~3 air at @s run setblock~1~-5~3 sandstone 0 replace
execute at positioned as @s unless block ~2~-1~-3 air at @s run setblock~2~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~2~-2~-3 air at @s run setblock~2~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~2~-3~-3 air at @s run setblock~2~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~2~-4~-3 air at @s run setblock~2~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~2~-5~-3 air at @s run setblock~2~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~2~-1~3 air at @s run setblock~2~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~2~-2~3 air at @s run setblock~2~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~2~-3~3 air at @s run setblock~2~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~2~-4~3 air at @s run setblock~2~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~2~-5~3 air at @s run setblock~2~-5~3 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~-3 air at @s run setblock~3~-1~-3 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~-3 air at @s run setblock~3~-2~-3 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~-3 air at @s run setblock~3~-3~-3 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~-3 air at @s run setblock~3~-4~-3 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~-3 air at @s run setblock~3~-5~-3 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~-2 air at @s run setblock~3~-1~-2 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~-2 air at @s run setblock~3~-2~-2 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~-2 air at @s run setblock~3~-3~-2 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~-2 air at @s run setblock~3~-4~-2 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~-2 air at @s run setblock~3~-5~-2 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~-1 air at @s run setblock~3~-1~-1 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~-1 air at @s run setblock~3~-2~-1 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~-1 air at @s run setblock~3~-3~-1 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~-1 air at @s run setblock~3~-4~-1 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~-1 air at @s run setblock~3~-5~-1 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~0 air at @s run setblock~3~-1~0 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~0 air at @s run setblock~3~-2~0 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~0 air at @s run setblock~3~-3~0 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~0 air at @s run setblock~3~-4~0 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~0 air at @s run setblock~3~-5~0 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~1 air at @s run setblock~3~-1~1 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~1 air at @s run setblock~3~-2~1 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~1 air at @s run setblock~3~-3~1 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~1 air at @s run setblock~3~-4~1 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~1 air at @s run setblock~3~-5~1 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~2 air at @s run setblock~3~-1~2 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~2 air at @s run setblock~3~-2~2 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~2 air at @s run setblock~3~-3~2 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~2 air at @s run setblock~3~-4~2 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~2 air at @s run setblock~3~-5~2 sandstone 0 replace
execute at positioned as @s unless block ~3~-1~3 air at @s run setblock~3~-1~3 sandstone 0 replace
execute at positioned as @s unless block ~3~-2~3 air at @s run setblock~3~-2~3 sandstone 0 replace
execute at positioned as @s unless block ~3~-3~3 air at @s run setblock~3~-3~3 sandstone 0 replace
execute at positioned as @s unless block ~3~-4~3 air at @s run setblock~3~-4~3 sandstone 0 replace
execute at positioned as @s unless block ~3~-5~3 air at @s run setblock~3~-5~3 sandstone 0 replace
