execute as @s unless block ~-8~-1~-8 air at @s run setblock ~-8~-1~-8 sandstone 0 replace
execute as @s unless block ~-8~-2~-8 air at @s run setblock ~-8~-2~-8 sandstone 0 replace
execute as @s unless block ~-8~-3~-8 air at @s run setblock ~-8~-3~-8 sandstone 0 replace
execute as @s unless block ~-8~-4~-8 air at @s run setblock ~-8~-4~-8 sandstone 0 replace
execute as @s unless block ~-8~-5~-8 air at @s run setblock ~-8~-5~-8 sandstone 0 replace
execute as @s unless block ~-8~-1~-7 air at @s run setblock ~-8~-1~-7 sandstone 0 replace
execute as @s unless block ~-8~-2~-7 air at @s run setblock ~-8~-2~-7 sandstone 0 replace
execute as @s unless block ~-8~-3~-7 air at @s run setblock ~-8~-3~-7 sandstone 0 replace
execute as @s unless block ~-8~-4~-7 air at @s run setblock ~-8~-4~-7 sandstone 0 replace
execute as @s unless block ~-8~-5~-7 air at @s run setblock ~-8~-5~-7 sandstone 0 replace
execute as @s unless block ~-8~-1~-6 air at @s run setblock ~-8~-1~-6 sandstone 0 replace
execute as @s unless block ~-8~-2~-6 air at @s run setblock ~-8~-2~-6 sandstone 0 replace
execute as @s unless block ~-8~-3~-6 air at @s run setblock ~-8~-3~-6 sandstone 0 replace
execute as @s unless block ~-8~-4~-6 air at @s run setblock ~-8~-4~-6 sandstone 0 replace
execute as @s unless block ~-8~-5~-6 air at @s run setblock ~-8~-5~-6 sandstone 0 replace
execute as @s unless block ~-8~-1~-5 air at @s run setblock ~-8~-1~-5 sandstone 0 replace
execute as @s unless block ~-8~-2~-5 air at @s run setblock ~-8~-2~-5 sandstone 0 replace
execute as @s unless block ~-8~-3~-5 air at @s run setblock ~-8~-3~-5 sandstone 0 replace
execute as @s unless block ~-8~-4~-5 air at @s run setblock ~-8~-4~-5 sandstone 0 replace
execute as @s unless block ~-8~-5~-5 air at @s run setblock ~-8~-5~-5 sandstone 0 replace
execute as @s unless block ~-8~-1~-4 air at @s run setblock ~-8~-1~-4 sandstone 0 replace
execute as @s unless block ~-8~-2~-4 air at @s run setblock ~-8~-2~-4 sandstone 0 replace
execute as @s unless block ~-8~-3~-4 air at @s run setblock ~-8~-3~-4 sandstone 0 replace
execute as @s unless block ~-8~-4~-4 air at @s run setblock ~-8~-4~-4 sandstone 0 replace
execute as @s unless block ~-8~-5~-4 air at @s run setblock ~-8~-5~-4 sandstone 0 replace
execute as @s unless block ~-8~-1~-3 air at @s run setblock ~-8~-1~-3 sandstone 0 replace
execute as @s unless block ~-8~-2~-3 air at @s run setblock ~-8~-2~-3 sandstone 0 replace
execute as @s unless block ~-8~-3~-3 air at @s run setblock ~-8~-3~-3 sandstone 0 replace
execute as @s unless block ~-8~-4~-3 air at @s run setblock ~-8~-4~-3 sandstone 0 replace
execute as @s unless block ~-8~-5~-3 air at @s run setblock ~-8~-5~-3 sandstone 0 replace
execute as @s unless block ~-8~-1~-2 air at @s run setblock ~-8~-1~-2 sandstone 0 replace
execute as @s unless block ~-8~-2~-2 air at @s run setblock ~-8~-2~-2 sandstone 0 replace
execute as @s unless block ~-8~-3~-2 air at @s run setblock ~-8~-3~-2 sandstone 0 replace
execute as @s unless block ~-8~-4~-2 air at @s run setblock ~-8~-4~-2 sandstone 0 replace
execute as @s unless block ~-8~-5~-2 air at @s run setblock ~-8~-5~-2 sandstone 0 replace
execute as @s unless block ~-8~-1~-1 air at @s run setblock ~-8~-1~-1 sandstone 0 replace
execute as @s unless block ~-8~-2~-1 air at @s run setblock ~-8~-2~-1 sandstone 0 replace
execute as @s unless block ~-8~-3~-1 air at @s run setblock ~-8~-3~-1 sandstone 0 replace
execute as @s unless block ~-8~-4~-1 air at @s run setblock ~-8~-4~-1 sandstone 0 replace
execute as @s unless block ~-8~-5~-1 air at @s run setblock ~-8~-5~-1 sandstone 0 replace
execute as @s unless block ~-8~-1~0 air at @s run setblock ~-8~-1~0 sandstone 0 replace
execute as @s unless block ~-8~-2~0 air at @s run setblock ~-8~-2~0 sandstone 0 replace
execute as @s unless block ~-8~-3~0 air at @s run setblock ~-8~-3~0 sandstone 0 replace
execute as @s unless block ~-8~-4~0 air at @s run setblock ~-8~-4~0 sandstone 0 replace
execute as @s unless block ~-8~-5~0 air at @s run setblock ~-8~-5~0 sandstone 0 replace
execute as @s unless block ~-8~-1~1 air at @s run setblock ~-8~-1~1 sandstone 0 replace
execute as @s unless block ~-8~-2~1 air at @s run setblock ~-8~-2~1 sandstone 0 replace
execute as @s unless block ~-8~-3~1 air at @s run setblock ~-8~-3~1 sandstone 0 replace
execute as @s unless block ~-8~-4~1 air at @s run setblock ~-8~-4~1 sandstone 0 replace
execute as @s unless block ~-8~-5~1 air at @s run setblock ~-8~-5~1 sandstone 0 replace
execute as @s unless block ~-8~-1~2 air at @s run setblock ~-8~-1~2 sandstone 0 replace
execute as @s unless block ~-8~-2~2 air at @s run setblock ~-8~-2~2 sandstone 0 replace
execute as @s unless block ~-8~-3~2 air at @s run setblock ~-8~-3~2 sandstone 0 replace
execute as @s unless block ~-8~-4~2 air at @s run setblock ~-8~-4~2 sandstone 0 replace
execute as @s unless block ~-8~-5~2 air at @s run setblock ~-8~-5~2 sandstone 0 replace
execute as @s unless block ~-8~-1~3 air at @s run setblock ~-8~-1~3 sandstone 0 replace
execute as @s unless block ~-8~-2~3 air at @s run setblock ~-8~-2~3 sandstone 0 replace
execute as @s unless block ~-8~-3~3 air at @s run setblock ~-8~-3~3 sandstone 0 replace
execute as @s unless block ~-8~-4~3 air at @s run setblock ~-8~-4~3 sandstone 0 replace
execute as @s unless block ~-8~-5~3 air at @s run setblock ~-8~-5~3 sandstone 0 replace
execute as @s unless block ~-8~-1~4 air at @s run setblock ~-8~-1~4 sandstone 0 replace
execute as @s unless block ~-8~-2~4 air at @s run setblock ~-8~-2~4 sandstone 0 replace
execute as @s unless block ~-8~-3~4 air at @s run setblock ~-8~-3~4 sandstone 0 replace
execute as @s unless block ~-8~-4~4 air at @s run setblock ~-8~-4~4 sandstone 0 replace
execute as @s unless block ~-8~-5~4 air at @s run setblock ~-8~-5~4 sandstone 0 replace
execute as @s unless block ~-8~-1~5 air at @s run setblock ~-8~-1~5 sandstone 0 replace
execute as @s unless block ~-8~-2~5 air at @s run setblock ~-8~-2~5 sandstone 0 replace
execute as @s unless block ~-8~-3~5 air at @s run setblock ~-8~-3~5 sandstone 0 replace
execute as @s unless block ~-8~-4~5 air at @s run setblock ~-8~-4~5 sandstone 0 replace
execute as @s unless block ~-8~-5~5 air at @s run setblock ~-8~-5~5 sandstone 0 replace
execute as @s unless block ~-8~-1~6 air at @s run setblock ~-8~-1~6 sandstone 0 replace
execute as @s unless block ~-8~-2~6 air at @s run setblock ~-8~-2~6 sandstone 0 replace
execute as @s unless block ~-8~-3~6 air at @s run setblock ~-8~-3~6 sandstone 0 replace
execute as @s unless block ~-8~-4~6 air at @s run setblock ~-8~-4~6 sandstone 0 replace
execute as @s unless block ~-8~-5~6 air at @s run setblock ~-8~-5~6 sandstone 0 replace
execute as @s unless block ~-8~-1~7 air at @s run setblock ~-8~-1~7 sandstone 0 replace
execute as @s unless block ~-8~-2~7 air at @s run setblock ~-8~-2~7 sandstone 0 replace
execute as @s unless block ~-8~-3~7 air at @s run setblock ~-8~-3~7 sandstone 0 replace
execute as @s unless block ~-8~-4~7 air at @s run setblock ~-8~-4~7 sandstone 0 replace
execute as @s unless block ~-8~-5~7 air at @s run setblock ~-8~-5~7 sandstone 0 replace
execute as @s unless block ~-8~-1~8 air at @s run setblock ~-8~-1~8 sandstone 0 replace
execute as @s unless block ~-8~-2~8 air at @s run setblock ~-8~-2~8 sandstone 0 replace
execute as @s unless block ~-8~-3~8 air at @s run setblock ~-8~-3~8 sandstone 0 replace
execute as @s unless block ~-8~-4~8 air at @s run setblock ~-8~-4~8 sandstone 0 replace
execute as @s unless block ~-8~-5~8 air at @s run setblock ~-8~-5~8 sandstone 0 replace
execute as @s unless block ~-7~-1~-8 air at @s run setblock ~-7~-1~-8 sandstone 0 replace
execute as @s unless block ~-7~-2~-8 air at @s run setblock ~-7~-2~-8 sandstone 0 replace
execute as @s unless block ~-7~-3~-8 air at @s run setblock ~-7~-3~-8 sandstone 0 replace
execute as @s unless block ~-7~-4~-8 air at @s run setblock ~-7~-4~-8 sandstone 0 replace
execute as @s unless block ~-7~-5~-8 air at @s run setblock ~-7~-5~-8 sandstone 0 replace
execute as @s unless block ~-7~-1~8 air at @s run setblock ~-7~-1~8 sandstone 0 replace
execute as @s unless block ~-7~-2~8 air at @s run setblock ~-7~-2~8 sandstone 0 replace
execute as @s unless block ~-7~-3~8 air at @s run setblock ~-7~-3~8 sandstone 0 replace
execute as @s unless block ~-7~-4~8 air at @s run setblock ~-7~-4~8 sandstone 0 replace
execute as @s unless block ~-7~-5~8 air at @s run setblock ~-7~-5~8 sandstone 0 replace
execute as @s unless block ~-6~-1~-8 air at @s run setblock ~-6~-1~-8 sandstone 0 replace
execute as @s unless block ~-6~-2~-8 air at @s run setblock ~-6~-2~-8 sandstone 0 replace
execute as @s unless block ~-6~-3~-8 air at @s run setblock ~-6~-3~-8 sandstone 0 replace
execute as @s unless block ~-6~-4~-8 air at @s run setblock ~-6~-4~-8 sandstone 0 replace
execute as @s unless block ~-6~-5~-8 air at @s run setblock ~-6~-5~-8 sandstone 0 replace
execute as @s unless block ~-6~-1~8 air at @s run setblock ~-6~-1~8 sandstone 0 replace
execute as @s unless block ~-6~-2~8 air at @s run setblock ~-6~-2~8 sandstone 0 replace
execute as @s unless block ~-6~-3~8 air at @s run setblock ~-6~-3~8 sandstone 0 replace
execute as @s unless block ~-6~-4~8 air at @s run setblock ~-6~-4~8 sandstone 0 replace
execute as @s unless block ~-6~-5~8 air at @s run setblock ~-6~-5~8 sandstone 0 replace
execute as @s unless block ~-5~-1~-8 air at @s run setblock ~-5~-1~-8 sandstone 0 replace
execute as @s unless block ~-5~-2~-8 air at @s run setblock ~-5~-2~-8 sandstone 0 replace
execute as @s unless block ~-5~-3~-8 air at @s run setblock ~-5~-3~-8 sandstone 0 replace
execute as @s unless block ~-5~-4~-8 air at @s run setblock ~-5~-4~-8 sandstone 0 replace
execute as @s unless block ~-5~-5~-8 air at @s run setblock ~-5~-5~-8 sandstone 0 replace
execute as @s unless block ~-5~-1~8 air at @s run setblock ~-5~-1~8 sandstone 0 replace
execute as @s unless block ~-5~-2~8 air at @s run setblock ~-5~-2~8 sandstone 0 replace
execute as @s unless block ~-5~-3~8 air at @s run setblock ~-5~-3~8 sandstone 0 replace
execute as @s unless block ~-5~-4~8 air at @s run setblock ~-5~-4~8 sandstone 0 replace
execute as @s unless block ~-5~-5~8 air at @s run setblock ~-5~-5~8 sandstone 0 replace
execute as @s unless block ~-4~-1~-8 air at @s run setblock ~-4~-1~-8 sandstone 0 replace
execute as @s unless block ~-4~-2~-8 air at @s run setblock ~-4~-2~-8 sandstone 0 replace
execute as @s unless block ~-4~-3~-8 air at @s run setblock ~-4~-3~-8 sandstone 0 replace
execute as @s unless block ~-4~-4~-8 air at @s run setblock ~-4~-4~-8 sandstone 0 replace
execute as @s unless block ~-4~-5~-8 air at @s run setblock ~-4~-5~-8 sandstone 0 replace
execute as @s unless block ~-4~-1~8 air at @s run setblock ~-4~-1~8 sandstone 0 replace
execute as @s unless block ~-4~-2~8 air at @s run setblock ~-4~-2~8 sandstone 0 replace
execute as @s unless block ~-4~-3~8 air at @s run setblock ~-4~-3~8 sandstone 0 replace
execute as @s unless block ~-4~-4~8 air at @s run setblock ~-4~-4~8 sandstone 0 replace
execute as @s unless block ~-4~-5~8 air at @s run setblock ~-4~-5~8 sandstone 0 replace
execute as @s unless block ~-3~-1~-8 air at @s run setblock ~-3~-1~-8 sandstone 0 replace
execute as @s unless block ~-3~-2~-8 air at @s run setblock ~-3~-2~-8 sandstone 0 replace
execute as @s unless block ~-3~-3~-8 air at @s run setblock ~-3~-3~-8 sandstone 0 replace
execute as @s unless block ~-3~-4~-8 air at @s run setblock ~-3~-4~-8 sandstone 0 replace
execute as @s unless block ~-3~-5~-8 air at @s run setblock ~-3~-5~-8 sandstone 0 replace
execute as @s unless block ~-3~-1~8 air at @s run setblock ~-3~-1~8 sandstone 0 replace
execute as @s unless block ~-3~-2~8 air at @s run setblock ~-3~-2~8 sandstone 0 replace
execute as @s unless block ~-3~-3~8 air at @s run setblock ~-3~-3~8 sandstone 0 replace
execute as @s unless block ~-3~-4~8 air at @s run setblock ~-3~-4~8 sandstone 0 replace
execute as @s unless block ~-3~-5~8 air at @s run setblock ~-3~-5~8 sandstone 0 replace
execute as @s unless block ~-2~-1~-8 air at @s run setblock ~-2~-1~-8 sandstone 0 replace
execute as @s unless block ~-2~-2~-8 air at @s run setblock ~-2~-2~-8 sandstone 0 replace
execute as @s unless block ~-2~-3~-8 air at @s run setblock ~-2~-3~-8 sandstone 0 replace
execute as @s unless block ~-2~-4~-8 air at @s run setblock ~-2~-4~-8 sandstone 0 replace
execute as @s unless block ~-2~-5~-8 air at @s run setblock ~-2~-5~-8 sandstone 0 replace
execute as @s unless block ~-2~-1~8 air at @s run setblock ~-2~-1~8 sandstone 0 replace
execute as @s unless block ~-2~-2~8 air at @s run setblock ~-2~-2~8 sandstone 0 replace
execute as @s unless block ~-2~-3~8 air at @s run setblock ~-2~-3~8 sandstone 0 replace
execute as @s unless block ~-2~-4~8 air at @s run setblock ~-2~-4~8 sandstone 0 replace
execute as @s unless block ~-2~-5~8 air at @s run setblock ~-2~-5~8 sandstone 0 replace
execute as @s unless block ~-1~-1~-8 air at @s run setblock ~-1~-1~-8 sandstone 0 replace
execute as @s unless block ~-1~-2~-8 air at @s run setblock ~-1~-2~-8 sandstone 0 replace
execute as @s unless block ~-1~-3~-8 air at @s run setblock ~-1~-3~-8 sandstone 0 replace
execute as @s unless block ~-1~-4~-8 air at @s run setblock ~-1~-4~-8 sandstone 0 replace
execute as @s unless block ~-1~-5~-8 air at @s run setblock ~-1~-5~-8 sandstone 0 replace
execute as @s unless block ~-1~-1~8 air at @s run setblock ~-1~-1~8 sandstone 0 replace
execute as @s unless block ~-1~-2~8 air at @s run setblock ~-1~-2~8 sandstone 0 replace
execute as @s unless block ~-1~-3~8 air at @s run setblock ~-1~-3~8 sandstone 0 replace
execute as @s unless block ~-1~-4~8 air at @s run setblock ~-1~-4~8 sandstone 0 replace
execute as @s unless block ~-1~-5~8 air at @s run setblock ~-1~-5~8 sandstone 0 replace
execute as @s unless block ~0~-1~-8 air at @s run setblock ~0~-1~-8 sandstone 0 replace
execute as @s unless block ~0~-2~-8 air at @s run setblock ~0~-2~-8 sandstone 0 replace
execute as @s unless block ~0~-3~-8 air at @s run setblock ~0~-3~-8 sandstone 0 replace
execute as @s unless block ~0~-4~-8 air at @s run setblock ~0~-4~-8 sandstone 0 replace
execute as @s unless block ~0~-5~-8 air at @s run setblock ~0~-5~-8 sandstone 0 replace
execute as @s unless block ~0~-1~8 air at @s run setblock ~0~-1~8 sandstone 0 replace
execute as @s unless block ~0~-2~8 air at @s run setblock ~0~-2~8 sandstone 0 replace
execute as @s unless block ~0~-3~8 air at @s run setblock ~0~-3~8 sandstone 0 replace
execute as @s unless block ~0~-4~8 air at @s run setblock ~0~-4~8 sandstone 0 replace
execute as @s unless block ~0~-5~8 air at @s run setblock ~0~-5~8 sandstone 0 replace
execute as @s unless block ~1~-1~-8 air at @s run setblock ~1~-1~-8 sandstone 0 replace
execute as @s unless block ~1~-2~-8 air at @s run setblock ~1~-2~-8 sandstone 0 replace
execute as @s unless block ~1~-3~-8 air at @s run setblock ~1~-3~-8 sandstone 0 replace
execute as @s unless block ~1~-4~-8 air at @s run setblock ~1~-4~-8 sandstone 0 replace
execute as @s unless block ~1~-5~-8 air at @s run setblock ~1~-5~-8 sandstone 0 replace
execute as @s unless block ~1~-1~8 air at @s run setblock ~1~-1~8 sandstone 0 replace
execute as @s unless block ~1~-2~8 air at @s run setblock ~1~-2~8 sandstone 0 replace
execute as @s unless block ~1~-3~8 air at @s run setblock ~1~-3~8 sandstone 0 replace
execute as @s unless block ~1~-4~8 air at @s run setblock ~1~-4~8 sandstone 0 replace
execute as @s unless block ~1~-5~8 air at @s run setblock ~1~-5~8 sandstone 0 replace
execute as @s unless block ~2~-1~-8 air at @s run setblock ~2~-1~-8 sandstone 0 replace
execute as @s unless block ~2~-2~-8 air at @s run setblock ~2~-2~-8 sandstone 0 replace
execute as @s unless block ~2~-3~-8 air at @s run setblock ~2~-3~-8 sandstone 0 replace
execute as @s unless block ~2~-4~-8 air at @s run setblock ~2~-4~-8 sandstone 0 replace
execute as @s unless block ~2~-5~-8 air at @s run setblock ~2~-5~-8 sandstone 0 replace
execute as @s unless block ~2~-1~8 air at @s run setblock ~2~-1~8 sandstone 0 replace
execute as @s unless block ~2~-2~8 air at @s run setblock ~2~-2~8 sandstone 0 replace
execute as @s unless block ~2~-3~8 air at @s run setblock ~2~-3~8 sandstone 0 replace
execute as @s unless block ~2~-4~8 air at @s run setblock ~2~-4~8 sandstone 0 replace
execute as @s unless block ~2~-5~8 air at @s run setblock ~2~-5~8 sandstone 0 replace
execute as @s unless block ~3~-1~-8 air at @s run setblock ~3~-1~-8 sandstone 0 replace
execute as @s unless block ~3~-2~-8 air at @s run setblock ~3~-2~-8 sandstone 0 replace
execute as @s unless block ~3~-3~-8 air at @s run setblock ~3~-3~-8 sandstone 0 replace
execute as @s unless block ~3~-4~-8 air at @s run setblock ~3~-4~-8 sandstone 0 replace
execute as @s unless block ~3~-5~-8 air at @s run setblock ~3~-5~-8 sandstone 0 replace
execute as @s unless block ~3~-1~8 air at @s run setblock ~3~-1~8 sandstone 0 replace
execute as @s unless block ~3~-2~8 air at @s run setblock ~3~-2~8 sandstone 0 replace
execute as @s unless block ~3~-3~8 air at @s run setblock ~3~-3~8 sandstone 0 replace
execute as @s unless block ~3~-4~8 air at @s run setblock ~3~-4~8 sandstone 0 replace
execute as @s unless block ~3~-5~8 air at @s run setblock ~3~-5~8 sandstone 0 replace
execute as @s unless block ~4~-1~-8 air at @s run setblock ~4~-1~-8 sandstone 0 replace
execute as @s unless block ~4~-2~-8 air at @s run setblock ~4~-2~-8 sandstone 0 replace
execute as @s unless block ~4~-3~-8 air at @s run setblock ~4~-3~-8 sandstone 0 replace
execute as @s unless block ~4~-4~-8 air at @s run setblock ~4~-4~-8 sandstone 0 replace
execute as @s unless block ~4~-5~-8 air at @s run setblock ~4~-5~-8 sandstone 0 replace
execute as @s unless block ~4~-1~8 air at @s run setblock ~4~-1~8 sandstone 0 replace
execute as @s unless block ~4~-2~8 air at @s run setblock ~4~-2~8 sandstone 0 replace
execute as @s unless block ~4~-3~8 air at @s run setblock ~4~-3~8 sandstone 0 replace
execute as @s unless block ~4~-4~8 air at @s run setblock ~4~-4~8 sandstone 0 replace
execute as @s unless block ~4~-5~8 air at @s run setblock ~4~-5~8 sandstone 0 replace
execute as @s unless block ~5~-1~-8 air at @s run setblock ~5~-1~-8 sandstone 0 replace
execute as @s unless block ~5~-2~-8 air at @s run setblock ~5~-2~-8 sandstone 0 replace
execute as @s unless block ~5~-3~-8 air at @s run setblock ~5~-3~-8 sandstone 0 replace
execute as @s unless block ~5~-4~-8 air at @s run setblock ~5~-4~-8 sandstone 0 replace
execute as @s unless block ~5~-5~-8 air at @s run setblock ~5~-5~-8 sandstone 0 replace
execute as @s unless block ~5~-1~8 air at @s run setblock ~5~-1~8 sandstone 0 replace
execute as @s unless block ~5~-2~8 air at @s run setblock ~5~-2~8 sandstone 0 replace
execute as @s unless block ~5~-3~8 air at @s run setblock ~5~-3~8 sandstone 0 replace
execute as @s unless block ~5~-4~8 air at @s run setblock ~5~-4~8 sandstone 0 replace
execute as @s unless block ~5~-5~8 air at @s run setblock ~5~-5~8 sandstone 0 replace
execute as @s unless block ~6~-1~-8 air at @s run setblock ~6~-1~-8 sandstone 0 replace
execute as @s unless block ~6~-2~-8 air at @s run setblock ~6~-2~-8 sandstone 0 replace
execute as @s unless block ~6~-3~-8 air at @s run setblock ~6~-3~-8 sandstone 0 replace
execute as @s unless block ~6~-4~-8 air at @s run setblock ~6~-4~-8 sandstone 0 replace
execute as @s unless block ~6~-5~-8 air at @s run setblock ~6~-5~-8 sandstone 0 replace
execute as @s unless block ~6~-1~8 air at @s run setblock ~6~-1~8 sandstone 0 replace
execute as @s unless block ~6~-2~8 air at @s run setblock ~6~-2~8 sandstone 0 replace
execute as @s unless block ~6~-3~8 air at @s run setblock ~6~-3~8 sandstone 0 replace
execute as @s unless block ~6~-4~8 air at @s run setblock ~6~-4~8 sandstone 0 replace
execute as @s unless block ~6~-5~8 air at @s run setblock ~6~-5~8 sandstone 0 replace
execute as @s unless block ~7~-1~-8 air at @s run setblock ~7~-1~-8 sandstone 0 replace
execute as @s unless block ~7~-2~-8 air at @s run setblock ~7~-2~-8 sandstone 0 replace
execute as @s unless block ~7~-3~-8 air at @s run setblock ~7~-3~-8 sandstone 0 replace
execute as @s unless block ~7~-4~-8 air at @s run setblock ~7~-4~-8 sandstone 0 replace
execute as @s unless block ~7~-5~-8 air at @s run setblock ~7~-5~-8 sandstone 0 replace
execute as @s unless block ~7~-1~8 air at @s run setblock ~7~-1~8 sandstone 0 replace
execute as @s unless block ~7~-2~8 air at @s run setblock ~7~-2~8 sandstone 0 replace
execute as @s unless block ~7~-3~8 air at @s run setblock ~7~-3~8 sandstone 0 replace
execute as @s unless block ~7~-4~8 air at @s run setblock ~7~-4~8 sandstone 0 replace
execute as @s unless block ~7~-5~8 air at @s run setblock ~7~-5~8 sandstone 0 replace
execute as @s unless block ~8~-1~-8 air at @s run setblock ~8~-1~-8 sandstone 0 replace
execute as @s unless block ~8~-2~-8 air at @s run setblock ~8~-2~-8 sandstone 0 replace
execute as @s unless block ~8~-3~-8 air at @s run setblock ~8~-3~-8 sandstone 0 replace
execute as @s unless block ~8~-4~-8 air at @s run setblock ~8~-4~-8 sandstone 0 replace
execute as @s unless block ~8~-5~-8 air at @s run setblock ~8~-5~-8 sandstone 0 replace
execute as @s unless block ~8~-1~-7 air at @s run setblock ~8~-1~-7 sandstone 0 replace
execute as @s unless block ~8~-2~-7 air at @s run setblock ~8~-2~-7 sandstone 0 replace
execute as @s unless block ~8~-3~-7 air at @s run setblock ~8~-3~-7 sandstone 0 replace
execute as @s unless block ~8~-4~-7 air at @s run setblock ~8~-4~-7 sandstone 0 replace
execute as @s unless block ~8~-5~-7 air at @s run setblock ~8~-5~-7 sandstone 0 replace
execute as @s unless block ~8~-1~-6 air at @s run setblock ~8~-1~-6 sandstone 0 replace
execute as @s unless block ~8~-2~-6 air at @s run setblock ~8~-2~-6 sandstone 0 replace
execute as @s unless block ~8~-3~-6 air at @s run setblock ~8~-3~-6 sandstone 0 replace
execute as @s unless block ~8~-4~-6 air at @s run setblock ~8~-4~-6 sandstone 0 replace
execute as @s unless block ~8~-5~-6 air at @s run setblock ~8~-5~-6 sandstone 0 replace
execute as @s unless block ~8~-1~-5 air at @s run setblock ~8~-1~-5 sandstone 0 replace
execute as @s unless block ~8~-2~-5 air at @s run setblock ~8~-2~-5 sandstone 0 replace
execute as @s unless block ~8~-3~-5 air at @s run setblock ~8~-3~-5 sandstone 0 replace
execute as @s unless block ~8~-4~-5 air at @s run setblock ~8~-4~-5 sandstone 0 replace
execute as @s unless block ~8~-5~-5 air at @s run setblock ~8~-5~-5 sandstone 0 replace
execute as @s unless block ~8~-1~-4 air at @s run setblock ~8~-1~-4 sandstone 0 replace
execute as @s unless block ~8~-2~-4 air at @s run setblock ~8~-2~-4 sandstone 0 replace
execute as @s unless block ~8~-3~-4 air at @s run setblock ~8~-3~-4 sandstone 0 replace
execute as @s unless block ~8~-4~-4 air at @s run setblock ~8~-4~-4 sandstone 0 replace
execute as @s unless block ~8~-5~-4 air at @s run setblock ~8~-5~-4 sandstone 0 replace
execute as @s unless block ~8~-1~-3 air at @s run setblock ~8~-1~-3 sandstone 0 replace
execute as @s unless block ~8~-2~-3 air at @s run setblock ~8~-2~-3 sandstone 0 replace
execute as @s unless block ~8~-3~-3 air at @s run setblock ~8~-3~-3 sandstone 0 replace
execute as @s unless block ~8~-4~-3 air at @s run setblock ~8~-4~-3 sandstone 0 replace
execute as @s unless block ~8~-5~-3 air at @s run setblock ~8~-5~-3 sandstone 0 replace
execute as @s unless block ~8~-1~-2 air at @s run setblock ~8~-1~-2 sandstone 0 replace
execute as @s unless block ~8~-2~-2 air at @s run setblock ~8~-2~-2 sandstone 0 replace
execute as @s unless block ~8~-3~-2 air at @s run setblock ~8~-3~-2 sandstone 0 replace
execute as @s unless block ~8~-4~-2 air at @s run setblock ~8~-4~-2 sandstone 0 replace
execute as @s unless block ~8~-5~-2 air at @s run setblock ~8~-5~-2 sandstone 0 replace
execute as @s unless block ~8~-1~-1 air at @s run setblock ~8~-1~-1 sandstone 0 replace
execute as @s unless block ~8~-2~-1 air at @s run setblock ~8~-2~-1 sandstone 0 replace
execute as @s unless block ~8~-3~-1 air at @s run setblock ~8~-3~-1 sandstone 0 replace
execute as @s unless block ~8~-4~-1 air at @s run setblock ~8~-4~-1 sandstone 0 replace
execute as @s unless block ~8~-5~-1 air at @s run setblock ~8~-5~-1 sandstone 0 replace
execute as @s unless block ~8~-1~0 air at @s run setblock ~8~-1~0 sandstone 0 replace
execute as @s unless block ~8~-2~0 air at @s run setblock ~8~-2~0 sandstone 0 replace
execute as @s unless block ~8~-3~0 air at @s run setblock ~8~-3~0 sandstone 0 replace
execute as @s unless block ~8~-4~0 air at @s run setblock ~8~-4~0 sandstone 0 replace
execute as @s unless block ~8~-5~0 air at @s run setblock ~8~-5~0 sandstone 0 replace
execute as @s unless block ~8~-1~1 air at @s run setblock ~8~-1~1 sandstone 0 replace
execute as @s unless block ~8~-2~1 air at @s run setblock ~8~-2~1 sandstone 0 replace
execute as @s unless block ~8~-3~1 air at @s run setblock ~8~-3~1 sandstone 0 replace
execute as @s unless block ~8~-4~1 air at @s run setblock ~8~-4~1 sandstone 0 replace
execute as @s unless block ~8~-5~1 air at @s run setblock ~8~-5~1 sandstone 0 replace
execute as @s unless block ~8~-1~2 air at @s run setblock ~8~-1~2 sandstone 0 replace
execute as @s unless block ~8~-2~2 air at @s run setblock ~8~-2~2 sandstone 0 replace
execute as @s unless block ~8~-3~2 air at @s run setblock ~8~-3~2 sandstone 0 replace
execute as @s unless block ~8~-4~2 air at @s run setblock ~8~-4~2 sandstone 0 replace
execute as @s unless block ~8~-5~2 air at @s run setblock ~8~-5~2 sandstone 0 replace
execute as @s unless block ~8~-1~3 air at @s run setblock ~8~-1~3 sandstone 0 replace
execute as @s unless block ~8~-2~3 air at @s run setblock ~8~-2~3 sandstone 0 replace
execute as @s unless block ~8~-3~3 air at @s run setblock ~8~-3~3 sandstone 0 replace
execute as @s unless block ~8~-4~3 air at @s run setblock ~8~-4~3 sandstone 0 replace
execute as @s unless block ~8~-5~3 air at @s run setblock ~8~-5~3 sandstone 0 replace
execute as @s unless block ~8~-1~4 air at @s run setblock ~8~-1~4 sandstone 0 replace
execute as @s unless block ~8~-2~4 air at @s run setblock ~8~-2~4 sandstone 0 replace
execute as @s unless block ~8~-3~4 air at @s run setblock ~8~-3~4 sandstone 0 replace
execute as @s unless block ~8~-4~4 air at @s run setblock ~8~-4~4 sandstone 0 replace
execute as @s unless block ~8~-5~4 air at @s run setblock ~8~-5~4 sandstone 0 replace
execute as @s unless block ~8~-1~5 air at @s run setblock ~8~-1~5 sandstone 0 replace
execute as @s unless block ~8~-2~5 air at @s run setblock ~8~-2~5 sandstone 0 replace
execute as @s unless block ~8~-3~5 air at @s run setblock ~8~-3~5 sandstone 0 replace
execute as @s unless block ~8~-4~5 air at @s run setblock ~8~-4~5 sandstone 0 replace
execute as @s unless block ~8~-5~5 air at @s run setblock ~8~-5~5 sandstone 0 replace
execute as @s unless block ~8~-1~6 air at @s run setblock ~8~-1~6 sandstone 0 replace
execute as @s unless block ~8~-2~6 air at @s run setblock ~8~-2~6 sandstone 0 replace
execute as @s unless block ~8~-3~6 air at @s run setblock ~8~-3~6 sandstone 0 replace
execute as @s unless block ~8~-4~6 air at @s run setblock ~8~-4~6 sandstone 0 replace
execute as @s unless block ~8~-5~6 air at @s run setblock ~8~-5~6 sandstone 0 replace
execute as @s unless block ~8~-1~7 air at @s run setblock ~8~-1~7 sandstone 0 replace
execute as @s unless block ~8~-2~7 air at @s run setblock ~8~-2~7 sandstone 0 replace
execute as @s unless block ~8~-3~7 air at @s run setblock ~8~-3~7 sandstone 0 replace
execute as @s unless block ~8~-4~7 air at @s run setblock ~8~-4~7 sandstone 0 replace
execute as @s unless block ~8~-5~7 air at @s run setblock ~8~-5~7 sandstone 0 replace
execute as @s unless block ~8~-1~8 air at @s run setblock ~8~-1~8 sandstone 0 replace
execute as @s unless block ~8~-2~8 air at @s run setblock ~8~-2~8 sandstone 0 replace
execute as @s unless block ~8~-3~8 air at @s run setblock ~8~-3~8 sandstone 0 replace
execute as @s unless block ~8~-4~8 air at @s run setblock ~8~-4~8 sandstone 0 replace
execute as @s unless block ~8~-5~8 air at @s run setblock ~8~-5~8 sandstone 0 replace
