execute positioned as @s unless block ~-4~7~-4 air at @s run setblock ~-4~7~-4 sand 0 replace
execute positioned as @s unless block ~-4~6~-4 air at @s run setblock ~-4~6~-4 sand 0 replace
execute positioned as @s unless block ~-4~5~-4 air at @s run setblock ~-4~5~-4 sand 0 replace
execute positioned as @s unless block ~-4~4~-4 air at @s run setblock ~-4~4~-4 sand 0 replace
execute positioned as @s unless block ~-4~3~-4 air at @s run setblock ~-4~3~-4 sand 0 replace
execute positioned as @s unless block ~-4~2~-4 air at @s run setblock ~-4~2~-4 sand 0 replace
execute positioned as @s unless block ~-4~1~-4 air at @s run setblock ~-4~1~-4 sand 0 replace
execute positioned as @s unless block ~-4~0~-4 air at @s run setblock ~-4~0~-4 sand 0 replace
execute positioned as @s unless block ~-4~-1~-4 air at @s run setblock ~-4~-1~-4 sand 0 replace
execute positioned as @s unless block ~-4~-2~-4 air at @s run setblock ~-4~-2~-4 sand 0 replace
execute positioned as @s unless block ~-4~-3~-4 air at @s run setblock ~-4~-3~-4 sand 0 replace
execute positioned as @s unless block ~-4~-4~-4 air at @s run setblock ~-4~-4~-4 sand 0 replace
execute positioned as @s unless block ~-4~-5~-4 air at @s run setblock ~-4~-5~-4 sand 0 replace
execute positioned as @s unless block ~-4~7~-3 air at @s run setblock ~-4~7~-3 sand 0 replace
execute positioned as @s unless block ~-4~6~-3 air at @s run setblock ~-4~6~-3 sand 0 replace
execute positioned as @s unless block ~-4~5~-3 air at @s run setblock ~-4~5~-3 sand 0 replace
execute positioned as @s unless block ~-4~4~-3 air at @s run setblock ~-4~4~-3 sand 0 replace
execute positioned as @s unless block ~-4~3~-3 air at @s run setblock ~-4~3~-3 sand 0 replace
execute positioned as @s unless block ~-4~2~-3 air at @s run setblock ~-4~2~-3 sand 0 replace
execute positioned as @s unless block ~-4~1~-3 air at @s run setblock ~-4~1~-3 sand 0 replace
execute positioned as @s unless block ~-4~0~-3 air at @s run setblock ~-4~0~-3 sand 0 replace
execute positioned as @s unless block ~-4~-1~-3 air at @s run setblock ~-4~-1~-3 sand 0 replace
execute positioned as @s unless block ~-4~-2~-3 air at @s run setblock ~-4~-2~-3 sand 0 replace
execute positioned as @s unless block ~-4~-3~-3 air at @s run setblock ~-4~-3~-3 sand 0 replace
execute positioned as @s unless block ~-4~-4~-3 air at @s run setblock ~-4~-4~-3 sand 0 replace
execute positioned as @s unless block ~-4~-5~-3 air at @s run setblock ~-4~-5~-3 sand 0 replace
execute positioned as @s unless block ~-4~7~-2 air at @s run setblock ~-4~7~-2 sand 0 replace
execute positioned as @s unless block ~-4~6~-2 air at @s run setblock ~-4~6~-2 sand 0 replace
execute positioned as @s unless block ~-4~5~-2 air at @s run setblock ~-4~5~-2 sand 0 replace
execute positioned as @s unless block ~-4~4~-2 air at @s run setblock ~-4~4~-2 sand 0 replace
execute positioned as @s unless block ~-4~3~-2 air at @s run setblock ~-4~3~-2 sand 0 replace
execute positioned as @s unless block ~-4~2~-2 air at @s run setblock ~-4~2~-2 sand 0 replace
execute positioned as @s unless block ~-4~1~-2 air at @s run setblock ~-4~1~-2 sand 0 replace
execute positioned as @s unless block ~-4~0~-2 air at @s run setblock ~-4~0~-2 sand 0 replace
execute positioned as @s unless block ~-4~-1~-2 air at @s run setblock ~-4~-1~-2 sand 0 replace
execute positioned as @s unless block ~-4~-2~-2 air at @s run setblock ~-4~-2~-2 sand 0 replace
execute positioned as @s unless block ~-4~-3~-2 air at @s run setblock ~-4~-3~-2 sand 0 replace
execute positioned as @s unless block ~-4~-4~-2 air at @s run setblock ~-4~-4~-2 sand 0 replace
execute positioned as @s unless block ~-4~-5~-2 air at @s run setblock ~-4~-5~-2 sand 0 replace
execute positioned as @s unless block ~-4~7~-1 air at @s run setblock ~-4~7~-1 sand 0 replace
execute positioned as @s unless block ~-4~6~-1 air at @s run setblock ~-4~6~-1 sand 0 replace
execute positioned as @s unless block ~-4~5~-1 air at @s run setblock ~-4~5~-1 sand 0 replace
execute positioned as @s unless block ~-4~4~-1 air at @s run setblock ~-4~4~-1 sand 0 replace
execute positioned as @s unless block ~-4~3~-1 air at @s run setblock ~-4~3~-1 sand 0 replace
execute positioned as @s unless block ~-4~2~-1 air at @s run setblock ~-4~2~-1 sand 0 replace
execute positioned as @s unless block ~-4~1~-1 air at @s run setblock ~-4~1~-1 sand 0 replace
execute positioned as @s unless block ~-4~0~-1 air at @s run setblock ~-4~0~-1 sand 0 replace
execute positioned as @s unless block ~-4~-1~-1 air at @s run setblock ~-4~-1~-1 sand 0 replace
execute positioned as @s unless block ~-4~-2~-1 air at @s run setblock ~-4~-2~-1 sand 0 replace
execute positioned as @s unless block ~-4~-3~-1 air at @s run setblock ~-4~-3~-1 sand 0 replace
execute positioned as @s unless block ~-4~-4~-1 air at @s run setblock ~-4~-4~-1 sand 0 replace
execute positioned as @s unless block ~-4~-5~-1 air at @s run setblock ~-4~-5~-1 sand 0 replace
execute positioned as @s unless block ~-4~7~0 air at @s run setblock ~-4~7~0 sand 0 replace
execute positioned as @s unless block ~-4~6~0 air at @s run setblock ~-4~6~0 sand 0 replace
execute positioned as @s unless block ~-4~5~0 air at @s run setblock ~-4~5~0 sand 0 replace
execute positioned as @s unless block ~-4~4~0 air at @s run setblock ~-4~4~0 sand 0 replace
execute positioned as @s unless block ~-4~3~0 air at @s run setblock ~-4~3~0 sand 0 replace
execute positioned as @s unless block ~-4~2~0 air at @s run setblock ~-4~2~0 sand 0 replace
execute positioned as @s unless block ~-4~1~0 air at @s run setblock ~-4~1~0 sand 0 replace
execute positioned as @s unless block ~-4~0~0 air at @s run setblock ~-4~0~0 sand 0 replace
execute positioned as @s unless block ~-4~-1~0 air at @s run setblock ~-4~-1~0 sand 0 replace
execute positioned as @s unless block ~-4~-2~0 air at @s run setblock ~-4~-2~0 sand 0 replace
execute positioned as @s unless block ~-4~-3~0 air at @s run setblock ~-4~-3~0 sand 0 replace
execute positioned as @s unless block ~-4~-4~0 air at @s run setblock ~-4~-4~0 sand 0 replace
execute positioned as @s unless block ~-4~-5~0 air at @s run setblock ~-4~-5~0 sand 0 replace
execute positioned as @s unless block ~-4~7~1 air at @s run setblock ~-4~7~1 sand 0 replace
execute positioned as @s unless block ~-4~6~1 air at @s run setblock ~-4~6~1 sand 0 replace
execute positioned as @s unless block ~-4~5~1 air at @s run setblock ~-4~5~1 sand 0 replace
execute positioned as @s unless block ~-4~4~1 air at @s run setblock ~-4~4~1 sand 0 replace
execute positioned as @s unless block ~-4~3~1 air at @s run setblock ~-4~3~1 sand 0 replace
execute positioned as @s unless block ~-4~2~1 air at @s run setblock ~-4~2~1 sand 0 replace
execute positioned as @s unless block ~-4~1~1 air at @s run setblock ~-4~1~1 sand 0 replace
execute positioned as @s unless block ~-4~0~1 air at @s run setblock ~-4~0~1 sand 0 replace
execute positioned as @s unless block ~-4~-1~1 air at @s run setblock ~-4~-1~1 sand 0 replace
execute positioned as @s unless block ~-4~-2~1 air at @s run setblock ~-4~-2~1 sand 0 replace
execute positioned as @s unless block ~-4~-3~1 air at @s run setblock ~-4~-3~1 sand 0 replace
execute positioned as @s unless block ~-4~-4~1 air at @s run setblock ~-4~-4~1 sand 0 replace
execute positioned as @s unless block ~-4~-5~1 air at @s run setblock ~-4~-5~1 sand 0 replace
execute positioned as @s unless block ~-4~7~2 air at @s run setblock ~-4~7~2 sand 0 replace
execute positioned as @s unless block ~-4~6~2 air at @s run setblock ~-4~6~2 sand 0 replace
execute positioned as @s unless block ~-4~5~2 air at @s run setblock ~-4~5~2 sand 0 replace
execute positioned as @s unless block ~-4~4~2 air at @s run setblock ~-4~4~2 sand 0 replace
execute positioned as @s unless block ~-4~3~2 air at @s run setblock ~-4~3~2 sand 0 replace
execute positioned as @s unless block ~-4~2~2 air at @s run setblock ~-4~2~2 sand 0 replace
execute positioned as @s unless block ~-4~1~2 air at @s run setblock ~-4~1~2 sand 0 replace
execute positioned as @s unless block ~-4~0~2 air at @s run setblock ~-4~0~2 sand 0 replace
execute positioned as @s unless block ~-4~-1~2 air at @s run setblock ~-4~-1~2 sand 0 replace
execute positioned as @s unless block ~-4~-2~2 air at @s run setblock ~-4~-2~2 sand 0 replace
execute positioned as @s unless block ~-4~-3~2 air at @s run setblock ~-4~-3~2 sand 0 replace
execute positioned as @s unless block ~-4~-4~2 air at @s run setblock ~-4~-4~2 sand 0 replace
execute positioned as @s unless block ~-4~-5~2 air at @s run setblock ~-4~-5~2 sand 0 replace
execute positioned as @s unless block ~-4~7~3 air at @s run setblock ~-4~7~3 sand 0 replace
execute positioned as @s unless block ~-4~6~3 air at @s run setblock ~-4~6~3 sand 0 replace
execute positioned as @s unless block ~-4~5~3 air at @s run setblock ~-4~5~3 sand 0 replace
execute positioned as @s unless block ~-4~4~3 air at @s run setblock ~-4~4~3 sand 0 replace
execute positioned as @s unless block ~-4~3~3 air at @s run setblock ~-4~3~3 sand 0 replace
execute positioned as @s unless block ~-4~2~3 air at @s run setblock ~-4~2~3 sand 0 replace
execute positioned as @s unless block ~-4~1~3 air at @s run setblock ~-4~1~3 sand 0 replace
execute positioned as @s unless block ~-4~0~3 air at @s run setblock ~-4~0~3 sand 0 replace
execute positioned as @s unless block ~-4~-1~3 air at @s run setblock ~-4~-1~3 sand 0 replace
execute positioned as @s unless block ~-4~-2~3 air at @s run setblock ~-4~-2~3 sand 0 replace
execute positioned as @s unless block ~-4~-3~3 air at @s run setblock ~-4~-3~3 sand 0 replace
execute positioned as @s unless block ~-4~-4~3 air at @s run setblock ~-4~-4~3 sand 0 replace
execute positioned as @s unless block ~-4~-5~3 air at @s run setblock ~-4~-5~3 sand 0 replace
execute positioned as @s unless block ~-4~7~4 air at @s run setblock ~-4~7~4 sand 0 replace
execute positioned as @s unless block ~-4~6~4 air at @s run setblock ~-4~6~4 sand 0 replace
execute positioned as @s unless block ~-4~5~4 air at @s run setblock ~-4~5~4 sand 0 replace
execute positioned as @s unless block ~-4~4~4 air at @s run setblock ~-4~4~4 sand 0 replace
execute positioned as @s unless block ~-4~3~4 air at @s run setblock ~-4~3~4 sand 0 replace
execute positioned as @s unless block ~-4~2~4 air at @s run setblock ~-4~2~4 sand 0 replace
execute positioned as @s unless block ~-4~1~4 air at @s run setblock ~-4~1~4 sand 0 replace
execute positioned as @s unless block ~-4~0~4 air at @s run setblock ~-4~0~4 sand 0 replace
execute positioned as @s unless block ~-4~-1~4 air at @s run setblock ~-4~-1~4 sand 0 replace
execute positioned as @s unless block ~-4~-2~4 air at @s run setblock ~-4~-2~4 sand 0 replace
execute positioned as @s unless block ~-4~-3~4 air at @s run setblock ~-4~-3~4 sand 0 replace
execute positioned as @s unless block ~-4~-4~4 air at @s run setblock ~-4~-4~4 sand 0 replace
execute positioned as @s unless block ~-4~-5~4 air at @s run setblock ~-4~-5~4 sand 0 replace
execute positioned as @s unless block ~-3~7~-4 air at @s run setblock ~-3~7~-4 sand 0 replace
execute positioned as @s unless block ~-3~6~-4 air at @s run setblock ~-3~6~-4 sand 0 replace
execute positioned as @s unless block ~-3~5~-4 air at @s run setblock ~-3~5~-4 sand 0 replace
execute positioned as @s unless block ~-3~4~-4 air at @s run setblock ~-3~4~-4 sand 0 replace
execute positioned as @s unless block ~-3~3~-4 air at @s run setblock ~-3~3~-4 sand 0 replace
execute positioned as @s unless block ~-3~2~-4 air at @s run setblock ~-3~2~-4 sand 0 replace
execute positioned as @s unless block ~-3~1~-4 air at @s run setblock ~-3~1~-4 sand 0 replace
execute positioned as @s unless block ~-3~0~-4 air at @s run setblock ~-3~0~-4 sand 0 replace
execute positioned as @s unless block ~-3~-1~-4 air at @s run setblock ~-3~-1~-4 sand 0 replace
execute positioned as @s unless block ~-3~-2~-4 air at @s run setblock ~-3~-2~-4 sand 0 replace
execute positioned as @s unless block ~-3~-3~-4 air at @s run setblock ~-3~-3~-4 sand 0 replace
execute positioned as @s unless block ~-3~-4~-4 air at @s run setblock ~-3~-4~-4 sand 0 replace
execute positioned as @s unless block ~-3~-5~-4 air at @s run setblock ~-3~-5~-4 sand 0 replace
execute positioned as @s unless block ~-3~7~4 air at @s run setblock ~-3~7~4 sand 0 replace
execute positioned as @s unless block ~-3~6~4 air at @s run setblock ~-3~6~4 sand 0 replace
execute positioned as @s unless block ~-3~5~4 air at @s run setblock ~-3~5~4 sand 0 replace
execute positioned as @s unless block ~-3~4~4 air at @s run setblock ~-3~4~4 sand 0 replace
execute positioned as @s unless block ~-3~3~4 air at @s run setblock ~-3~3~4 sand 0 replace
execute positioned as @s unless block ~-3~2~4 air at @s run setblock ~-3~2~4 sand 0 replace
execute positioned as @s unless block ~-3~1~4 air at @s run setblock ~-3~1~4 sand 0 replace
execute positioned as @s unless block ~-3~0~4 air at @s run setblock ~-3~0~4 sand 0 replace
execute positioned as @s unless block ~-3~-1~4 air at @s run setblock ~-3~-1~4 sand 0 replace
execute positioned as @s unless block ~-3~-2~4 air at @s run setblock ~-3~-2~4 sand 0 replace
execute positioned as @s unless block ~-3~-3~4 air at @s run setblock ~-3~-3~4 sand 0 replace
execute positioned as @s unless block ~-3~-4~4 air at @s run setblock ~-3~-4~4 sand 0 replace
execute positioned as @s unless block ~-3~-5~4 air at @s run setblock ~-3~-5~4 sand 0 replace
execute positioned as @s unless block ~-2~7~-4 air at @s run setblock ~-2~7~-4 sand 0 replace
execute positioned as @s unless block ~-2~6~-4 air at @s run setblock ~-2~6~-4 sand 0 replace
execute positioned as @s unless block ~-2~5~-4 air at @s run setblock ~-2~5~-4 sand 0 replace
execute positioned as @s unless block ~-2~4~-4 air at @s run setblock ~-2~4~-4 sand 0 replace
execute positioned as @s unless block ~-2~3~-4 air at @s run setblock ~-2~3~-4 sand 0 replace
execute positioned as @s unless block ~-2~2~-4 air at @s run setblock ~-2~2~-4 sand 0 replace
execute positioned as @s unless block ~-2~1~-4 air at @s run setblock ~-2~1~-4 sand 0 replace
execute positioned as @s unless block ~-2~0~-4 air at @s run setblock ~-2~0~-4 sand 0 replace
execute positioned as @s unless block ~-2~-1~-4 air at @s run setblock ~-2~-1~-4 sand 0 replace
execute positioned as @s unless block ~-2~-2~-4 air at @s run setblock ~-2~-2~-4 sand 0 replace
execute positioned as @s unless block ~-2~-3~-4 air at @s run setblock ~-2~-3~-4 sand 0 replace
execute positioned as @s unless block ~-2~-4~-4 air at @s run setblock ~-2~-4~-4 sand 0 replace
execute positioned as @s unless block ~-2~-5~-4 air at @s run setblock ~-2~-5~-4 sand 0 replace
execute positioned as @s unless block ~-2~7~4 air at @s run setblock ~-2~7~4 sand 0 replace
execute positioned as @s unless block ~-2~6~4 air at @s run setblock ~-2~6~4 sand 0 replace
execute positioned as @s unless block ~-2~5~4 air at @s run setblock ~-2~5~4 sand 0 replace
execute positioned as @s unless block ~-2~4~4 air at @s run setblock ~-2~4~4 sand 0 replace
execute positioned as @s unless block ~-2~3~4 air at @s run setblock ~-2~3~4 sand 0 replace
execute positioned as @s unless block ~-2~2~4 air at @s run setblock ~-2~2~4 sand 0 replace
execute positioned as @s unless block ~-2~1~4 air at @s run setblock ~-2~1~4 sand 0 replace
execute positioned as @s unless block ~-2~0~4 air at @s run setblock ~-2~0~4 sand 0 replace
execute positioned as @s unless block ~-2~-1~4 air at @s run setblock ~-2~-1~4 sand 0 replace
execute positioned as @s unless block ~-2~-2~4 air at @s run setblock ~-2~-2~4 sand 0 replace
execute positioned as @s unless block ~-2~-3~4 air at @s run setblock ~-2~-3~4 sand 0 replace
execute positioned as @s unless block ~-2~-4~4 air at @s run setblock ~-2~-4~4 sand 0 replace
execute positioned as @s unless block ~-2~-5~4 air at @s run setblock ~-2~-5~4 sand 0 replace
execute positioned as @s unless block ~-1~7~-4 air at @s run setblock ~-1~7~-4 sand 0 replace
execute positioned as @s unless block ~-1~6~-4 air at @s run setblock ~-1~6~-4 sand 0 replace
execute positioned as @s unless block ~-1~5~-4 air at @s run setblock ~-1~5~-4 sand 0 replace
execute positioned as @s unless block ~-1~4~-4 air at @s run setblock ~-1~4~-4 sand 0 replace
execute positioned as @s unless block ~-1~3~-4 air at @s run setblock ~-1~3~-4 sand 0 replace
execute positioned as @s unless block ~-1~2~-4 air at @s run setblock ~-1~2~-4 sand 0 replace
execute positioned as @s unless block ~-1~1~-4 air at @s run setblock ~-1~1~-4 sand 0 replace
execute positioned as @s unless block ~-1~0~-4 air at @s run setblock ~-1~0~-4 sand 0 replace
execute positioned as @s unless block ~-1~-1~-4 air at @s run setblock ~-1~-1~-4 sand 0 replace
execute positioned as @s unless block ~-1~-2~-4 air at @s run setblock ~-1~-2~-4 sand 0 replace
execute positioned as @s unless block ~-1~-3~-4 air at @s run setblock ~-1~-3~-4 sand 0 replace
execute positioned as @s unless block ~-1~-4~-4 air at @s run setblock ~-1~-4~-4 sand 0 replace
execute positioned as @s unless block ~-1~-5~-4 air at @s run setblock ~-1~-5~-4 sand 0 replace
execute positioned as @s unless block ~-1~7~4 air at @s run setblock ~-1~7~4 sand 0 replace
execute positioned as @s unless block ~-1~6~4 air at @s run setblock ~-1~6~4 sand 0 replace
execute positioned as @s unless block ~-1~5~4 air at @s run setblock ~-1~5~4 sand 0 replace
execute positioned as @s unless block ~-1~4~4 air at @s run setblock ~-1~4~4 sand 0 replace
execute positioned as @s unless block ~-1~3~4 air at @s run setblock ~-1~3~4 sand 0 replace
execute positioned as @s unless block ~-1~2~4 air at @s run setblock ~-1~2~4 sand 0 replace
execute positioned as @s unless block ~-1~1~4 air at @s run setblock ~-1~1~4 sand 0 replace
execute positioned as @s unless block ~-1~0~4 air at @s run setblock ~-1~0~4 sand 0 replace
execute positioned as @s unless block ~-1~-1~4 air at @s run setblock ~-1~-1~4 sand 0 replace
execute positioned as @s unless block ~-1~-2~4 air at @s run setblock ~-1~-2~4 sand 0 replace
execute positioned as @s unless block ~-1~-3~4 air at @s run setblock ~-1~-3~4 sand 0 replace
execute positioned as @s unless block ~-1~-4~4 air at @s run setblock ~-1~-4~4 sand 0 replace
execute positioned as @s unless block ~-1~-5~4 air at @s run setblock ~-1~-5~4 sand 0 replace
execute positioned as @s unless block ~0~7~-4 air at @s run setblock ~0~7~-4 sand 0 replace
execute positioned as @s unless block ~0~6~-4 air at @s run setblock ~0~6~-4 sand 0 replace
execute positioned as @s unless block ~0~5~-4 air at @s run setblock ~0~5~-4 sand 0 replace
execute positioned as @s unless block ~0~4~-4 air at @s run setblock ~0~4~-4 sand 0 replace
execute positioned as @s unless block ~0~3~-4 air at @s run setblock ~0~3~-4 sand 0 replace
execute positioned as @s unless block ~0~2~-4 air at @s run setblock ~0~2~-4 sand 0 replace
execute positioned as @s unless block ~0~1~-4 air at @s run setblock ~0~1~-4 sand 0 replace
execute positioned as @s unless block ~0~0~-4 air at @s run setblock ~0~0~-4 sand 0 replace
execute positioned as @s unless block ~0~-1~-4 air at @s run setblock ~0~-1~-4 sand 0 replace
execute positioned as @s unless block ~0~-2~-4 air at @s run setblock ~0~-2~-4 sand 0 replace
execute positioned as @s unless block ~0~-3~-4 air at @s run setblock ~0~-3~-4 sand 0 replace
execute positioned as @s unless block ~0~-4~-4 air at @s run setblock ~0~-4~-4 sand 0 replace
execute positioned as @s unless block ~0~-5~-4 air at @s run setblock ~0~-5~-4 sand 0 replace
execute positioned as @s unless block ~0~7~4 air at @s run setblock ~0~7~4 sand 0 replace
execute positioned as @s unless block ~0~6~4 air at @s run setblock ~0~6~4 sand 0 replace
execute positioned as @s unless block ~0~5~4 air at @s run setblock ~0~5~4 sand 0 replace
execute positioned as @s unless block ~0~4~4 air at @s run setblock ~0~4~4 sand 0 replace
execute positioned as @s unless block ~0~3~4 air at @s run setblock ~0~3~4 sand 0 replace
execute positioned as @s unless block ~0~2~4 air at @s run setblock ~0~2~4 sand 0 replace
execute positioned as @s unless block ~0~1~4 air at @s run setblock ~0~1~4 sand 0 replace
execute positioned as @s unless block ~0~0~4 air at @s run setblock ~0~0~4 sand 0 replace
execute positioned as @s unless block ~0~-1~4 air at @s run setblock ~0~-1~4 sand 0 replace
execute positioned as @s unless block ~0~-2~4 air at @s run setblock ~0~-2~4 sand 0 replace
execute positioned as @s unless block ~0~-3~4 air at @s run setblock ~0~-3~4 sand 0 replace
execute positioned as @s unless block ~0~-4~4 air at @s run setblock ~0~-4~4 sand 0 replace
execute positioned as @s unless block ~0~-5~4 air at @s run setblock ~0~-5~4 sand 0 replace
execute positioned as @s unless block ~1~7~-4 air at @s run setblock ~1~7~-4 sand 0 replace
execute positioned as @s unless block ~1~6~-4 air at @s run setblock ~1~6~-4 sand 0 replace
execute positioned as @s unless block ~1~5~-4 air at @s run setblock ~1~5~-4 sand 0 replace
execute positioned as @s unless block ~1~4~-4 air at @s run setblock ~1~4~-4 sand 0 replace
execute positioned as @s unless block ~1~3~-4 air at @s run setblock ~1~3~-4 sand 0 replace
execute positioned as @s unless block ~1~2~-4 air at @s run setblock ~1~2~-4 sand 0 replace
execute positioned as @s unless block ~1~1~-4 air at @s run setblock ~1~1~-4 sand 0 replace
execute positioned as @s unless block ~1~0~-4 air at @s run setblock ~1~0~-4 sand 0 replace
execute positioned as @s unless block ~1~-1~-4 air at @s run setblock ~1~-1~-4 sand 0 replace
execute positioned as @s unless block ~1~-2~-4 air at @s run setblock ~1~-2~-4 sand 0 replace
execute positioned as @s unless block ~1~-3~-4 air at @s run setblock ~1~-3~-4 sand 0 replace
execute positioned as @s unless block ~1~-4~-4 air at @s run setblock ~1~-4~-4 sand 0 replace
execute positioned as @s unless block ~1~-5~-4 air at @s run setblock ~1~-5~-4 sand 0 replace
execute positioned as @s unless block ~1~7~4 air at @s run setblock ~1~7~4 sand 0 replace
execute positioned as @s unless block ~1~6~4 air at @s run setblock ~1~6~4 sand 0 replace
execute positioned as @s unless block ~1~5~4 air at @s run setblock ~1~5~4 sand 0 replace
execute positioned as @s unless block ~1~4~4 air at @s run setblock ~1~4~4 sand 0 replace
execute positioned as @s unless block ~1~3~4 air at @s run setblock ~1~3~4 sand 0 replace
execute positioned as @s unless block ~1~2~4 air at @s run setblock ~1~2~4 sand 0 replace
execute positioned as @s unless block ~1~1~4 air at @s run setblock ~1~1~4 sand 0 replace
execute positioned as @s unless block ~1~0~4 air at @s run setblock ~1~0~4 sand 0 replace
execute positioned as @s unless block ~1~-1~4 air at @s run setblock ~1~-1~4 sand 0 replace
execute positioned as @s unless block ~1~-2~4 air at @s run setblock ~1~-2~4 sand 0 replace
execute positioned as @s unless block ~1~-3~4 air at @s run setblock ~1~-3~4 sand 0 replace
execute positioned as @s unless block ~1~-4~4 air at @s run setblock ~1~-4~4 sand 0 replace
execute positioned as @s unless block ~1~-5~4 air at @s run setblock ~1~-5~4 sand 0 replace
execute positioned as @s unless block ~2~7~-4 air at @s run setblock ~2~7~-4 sand 0 replace
execute positioned as @s unless block ~2~6~-4 air at @s run setblock ~2~6~-4 sand 0 replace
execute positioned as @s unless block ~2~5~-4 air at @s run setblock ~2~5~-4 sand 0 replace
execute positioned as @s unless block ~2~4~-4 air at @s run setblock ~2~4~-4 sand 0 replace
execute positioned as @s unless block ~2~3~-4 air at @s run setblock ~2~3~-4 sand 0 replace
execute positioned as @s unless block ~2~2~-4 air at @s run setblock ~2~2~-4 sand 0 replace
execute positioned as @s unless block ~2~1~-4 air at @s run setblock ~2~1~-4 sand 0 replace
execute positioned as @s unless block ~2~0~-4 air at @s run setblock ~2~0~-4 sand 0 replace
execute positioned as @s unless block ~2~-1~-4 air at @s run setblock ~2~-1~-4 sand 0 replace
execute positioned as @s unless block ~2~-2~-4 air at @s run setblock ~2~-2~-4 sand 0 replace
execute positioned as @s unless block ~2~-3~-4 air at @s run setblock ~2~-3~-4 sand 0 replace
execute positioned as @s unless block ~2~-4~-4 air at @s run setblock ~2~-4~-4 sand 0 replace
execute positioned as @s unless block ~2~-5~-4 air at @s run setblock ~2~-5~-4 sand 0 replace
execute positioned as @s unless block ~2~7~4 air at @s run setblock ~2~7~4 sand 0 replace
execute positioned as @s unless block ~2~6~4 air at @s run setblock ~2~6~4 sand 0 replace
execute positioned as @s unless block ~2~5~4 air at @s run setblock ~2~5~4 sand 0 replace
execute positioned as @s unless block ~2~4~4 air at @s run setblock ~2~4~4 sand 0 replace
execute positioned as @s unless block ~2~3~4 air at @s run setblock ~2~3~4 sand 0 replace
execute positioned as @s unless block ~2~2~4 air at @s run setblock ~2~2~4 sand 0 replace
execute positioned as @s unless block ~2~1~4 air at @s run setblock ~2~1~4 sand 0 replace
execute positioned as @s unless block ~2~0~4 air at @s run setblock ~2~0~4 sand 0 replace
execute positioned as @s unless block ~2~-1~4 air at @s run setblock ~2~-1~4 sand 0 replace
execute positioned as @s unless block ~2~-2~4 air at @s run setblock ~2~-2~4 sand 0 replace
execute positioned as @s unless block ~2~-3~4 air at @s run setblock ~2~-3~4 sand 0 replace
execute positioned as @s unless block ~2~-4~4 air at @s run setblock ~2~-4~4 sand 0 replace
execute positioned as @s unless block ~2~-5~4 air at @s run setblock ~2~-5~4 sand 0 replace
execute positioned as @s unless block ~3~7~-4 air at @s run setblock ~3~7~-4 sand 0 replace
execute positioned as @s unless block ~3~6~-4 air at @s run setblock ~3~6~-4 sand 0 replace
execute positioned as @s unless block ~3~5~-4 air at @s run setblock ~3~5~-4 sand 0 replace
execute positioned as @s unless block ~3~4~-4 air at @s run setblock ~3~4~-4 sand 0 replace
execute positioned as @s unless block ~3~3~-4 air at @s run setblock ~3~3~-4 sand 0 replace
execute positioned as @s unless block ~3~2~-4 air at @s run setblock ~3~2~-4 sand 0 replace
execute positioned as @s unless block ~3~1~-4 air at @s run setblock ~3~1~-4 sand 0 replace
execute positioned as @s unless block ~3~0~-4 air at @s run setblock ~3~0~-4 sand 0 replace
execute positioned as @s unless block ~3~-1~-4 air at @s run setblock ~3~-1~-4 sand 0 replace
execute positioned as @s unless block ~3~-2~-4 air at @s run setblock ~3~-2~-4 sand 0 replace
execute positioned as @s unless block ~3~-3~-4 air at @s run setblock ~3~-3~-4 sand 0 replace
execute positioned as @s unless block ~3~-4~-4 air at @s run setblock ~3~-4~-4 sand 0 replace
execute positioned as @s unless block ~3~-5~-4 air at @s run setblock ~3~-5~-4 sand 0 replace
execute positioned as @s unless block ~3~7~4 air at @s run setblock ~3~7~4 sand 0 replace
execute positioned as @s unless block ~3~6~4 air at @s run setblock ~3~6~4 sand 0 replace
execute positioned as @s unless block ~3~5~4 air at @s run setblock ~3~5~4 sand 0 replace
execute positioned as @s unless block ~3~4~4 air at @s run setblock ~3~4~4 sand 0 replace
execute positioned as @s unless block ~3~3~4 air at @s run setblock ~3~3~4 sand 0 replace
execute positioned as @s unless block ~3~2~4 air at @s run setblock ~3~2~4 sand 0 replace
execute positioned as @s unless block ~3~1~4 air at @s run setblock ~3~1~4 sand 0 replace
execute positioned as @s unless block ~3~0~4 air at @s run setblock ~3~0~4 sand 0 replace
execute positioned as @s unless block ~3~-1~4 air at @s run setblock ~3~-1~4 sand 0 replace
execute positioned as @s unless block ~3~-2~4 air at @s run setblock ~3~-2~4 sand 0 replace
execute positioned as @s unless block ~3~-3~4 air at @s run setblock ~3~-3~4 sand 0 replace
execute positioned as @s unless block ~3~-4~4 air at @s run setblock ~3~-4~4 sand 0 replace
execute positioned as @s unless block ~3~-5~4 air at @s run setblock ~3~-5~4 sand 0 replace
execute positioned as @s unless block ~4~7~-4 air at @s run setblock ~4~7~-4 sand 0 replace
execute positioned as @s unless block ~4~6~-4 air at @s run setblock ~4~6~-4 sand 0 replace
execute positioned as @s unless block ~4~5~-4 air at @s run setblock ~4~5~-4 sand 0 replace
execute positioned as @s unless block ~4~4~-4 air at @s run setblock ~4~4~-4 sand 0 replace
execute positioned as @s unless block ~4~3~-4 air at @s run setblock ~4~3~-4 sand 0 replace
execute positioned as @s unless block ~4~2~-4 air at @s run setblock ~4~2~-4 sand 0 replace
execute positioned as @s unless block ~4~1~-4 air at @s run setblock ~4~1~-4 sand 0 replace
execute positioned as @s unless block ~4~0~-4 air at @s run setblock ~4~0~-4 sand 0 replace
execute positioned as @s unless block ~4~-1~-4 air at @s run setblock ~4~-1~-4 sand 0 replace
execute positioned as @s unless block ~4~-2~-4 air at @s run setblock ~4~-2~-4 sand 0 replace
execute positioned as @s unless block ~4~-3~-4 air at @s run setblock ~4~-3~-4 sand 0 replace
execute positioned as @s unless block ~4~-4~-4 air at @s run setblock ~4~-4~-4 sand 0 replace
execute positioned as @s unless block ~4~-5~-4 air at @s run setblock ~4~-5~-4 sand 0 replace
execute positioned as @s unless block ~4~7~-3 air at @s run setblock ~4~7~-3 sand 0 replace
execute positioned as @s unless block ~4~6~-3 air at @s run setblock ~4~6~-3 sand 0 replace
execute positioned as @s unless block ~4~5~-3 air at @s run setblock ~4~5~-3 sand 0 replace
execute positioned as @s unless block ~4~4~-3 air at @s run setblock ~4~4~-3 sand 0 replace
execute positioned as @s unless block ~4~3~-3 air at @s run setblock ~4~3~-3 sand 0 replace
execute positioned as @s unless block ~4~2~-3 air at @s run setblock ~4~2~-3 sand 0 replace
execute positioned as @s unless block ~4~1~-3 air at @s run setblock ~4~1~-3 sand 0 replace
execute positioned as @s unless block ~4~0~-3 air at @s run setblock ~4~0~-3 sand 0 replace
execute positioned as @s unless block ~4~-1~-3 air at @s run setblock ~4~-1~-3 sand 0 replace
execute positioned as @s unless block ~4~-2~-3 air at @s run setblock ~4~-2~-3 sand 0 replace
execute positioned as @s unless block ~4~-3~-3 air at @s run setblock ~4~-3~-3 sand 0 replace
execute positioned as @s unless block ~4~-4~-3 air at @s run setblock ~4~-4~-3 sand 0 replace
execute positioned as @s unless block ~4~-5~-3 air at @s run setblock ~4~-5~-3 sand 0 replace
execute positioned as @s unless block ~4~7~-2 air at @s run setblock ~4~7~-2 sand 0 replace
execute positioned as @s unless block ~4~6~-2 air at @s run setblock ~4~6~-2 sand 0 replace
execute positioned as @s unless block ~4~5~-2 air at @s run setblock ~4~5~-2 sand 0 replace
execute positioned as @s unless block ~4~4~-2 air at @s run setblock ~4~4~-2 sand 0 replace
execute positioned as @s unless block ~4~3~-2 air at @s run setblock ~4~3~-2 sand 0 replace
execute positioned as @s unless block ~4~2~-2 air at @s run setblock ~4~2~-2 sand 0 replace
execute positioned as @s unless block ~4~1~-2 air at @s run setblock ~4~1~-2 sand 0 replace
execute positioned as @s unless block ~4~0~-2 air at @s run setblock ~4~0~-2 sand 0 replace
execute positioned as @s unless block ~4~-1~-2 air at @s run setblock ~4~-1~-2 sand 0 replace
execute positioned as @s unless block ~4~-2~-2 air at @s run setblock ~4~-2~-2 sand 0 replace
execute positioned as @s unless block ~4~-3~-2 air at @s run setblock ~4~-3~-2 sand 0 replace
execute positioned as @s unless block ~4~-4~-2 air at @s run setblock ~4~-4~-2 sand 0 replace
execute positioned as @s unless block ~4~-5~-2 air at @s run setblock ~4~-5~-2 sand 0 replace
execute positioned as @s unless block ~4~7~-1 air at @s run setblock ~4~7~-1 sand 0 replace
execute positioned as @s unless block ~4~6~-1 air at @s run setblock ~4~6~-1 sand 0 replace
execute positioned as @s unless block ~4~5~-1 air at @s run setblock ~4~5~-1 sand 0 replace
execute positioned as @s unless block ~4~4~-1 air at @s run setblock ~4~4~-1 sand 0 replace
execute positioned as @s unless block ~4~3~-1 air at @s run setblock ~4~3~-1 sand 0 replace
execute positioned as @s unless block ~4~2~-1 air at @s run setblock ~4~2~-1 sand 0 replace
execute positioned as @s unless block ~4~1~-1 air at @s run setblock ~4~1~-1 sand 0 replace
execute positioned as @s unless block ~4~0~-1 air at @s run setblock ~4~0~-1 sand 0 replace
execute positioned as @s unless block ~4~-1~-1 air at @s run setblock ~4~-1~-1 sand 0 replace
execute positioned as @s unless block ~4~-2~-1 air at @s run setblock ~4~-2~-1 sand 0 replace
execute positioned as @s unless block ~4~-3~-1 air at @s run setblock ~4~-3~-1 sand 0 replace
execute positioned as @s unless block ~4~-4~-1 air at @s run setblock ~4~-4~-1 sand 0 replace
execute positioned as @s unless block ~4~-5~-1 air at @s run setblock ~4~-5~-1 sand 0 replace
execute positioned as @s unless block ~4~7~0 air at @s run setblock ~4~7~0 sand 0 replace
execute positioned as @s unless block ~4~6~0 air at @s run setblock ~4~6~0 sand 0 replace
execute positioned as @s unless block ~4~5~0 air at @s run setblock ~4~5~0 sand 0 replace
execute positioned as @s unless block ~4~4~0 air at @s run setblock ~4~4~0 sand 0 replace
execute positioned as @s unless block ~4~3~0 air at @s run setblock ~4~3~0 sand 0 replace
execute positioned as @s unless block ~4~2~0 air at @s run setblock ~4~2~0 sand 0 replace
execute positioned as @s unless block ~4~1~0 air at @s run setblock ~4~1~0 sand 0 replace
execute positioned as @s unless block ~4~0~0 air at @s run setblock ~4~0~0 sand 0 replace
execute positioned as @s unless block ~4~-1~0 air at @s run setblock ~4~-1~0 sand 0 replace
execute positioned as @s unless block ~4~-2~0 air at @s run setblock ~4~-2~0 sand 0 replace
execute positioned as @s unless block ~4~-3~0 air at @s run setblock ~4~-3~0 sand 0 replace
execute positioned as @s unless block ~4~-4~0 air at @s run setblock ~4~-4~0 sand 0 replace
execute positioned as @s unless block ~4~-5~0 air at @s run setblock ~4~-5~0 sand 0 replace
execute positioned as @s unless block ~4~7~1 air at @s run setblock ~4~7~1 sand 0 replace
execute positioned as @s unless block ~4~6~1 air at @s run setblock ~4~6~1 sand 0 replace
execute positioned as @s unless block ~4~5~1 air at @s run setblock ~4~5~1 sand 0 replace
execute positioned as @s unless block ~4~4~1 air at @s run setblock ~4~4~1 sand 0 replace
execute positioned as @s unless block ~4~3~1 air at @s run setblock ~4~3~1 sand 0 replace
execute positioned as @s unless block ~4~2~1 air at @s run setblock ~4~2~1 sand 0 replace
execute positioned as @s unless block ~4~1~1 air at @s run setblock ~4~1~1 sand 0 replace
execute positioned as @s unless block ~4~0~1 air at @s run setblock ~4~0~1 sand 0 replace
execute positioned as @s unless block ~4~-1~1 air at @s run setblock ~4~-1~1 sand 0 replace
execute positioned as @s unless block ~4~-2~1 air at @s run setblock ~4~-2~1 sand 0 replace
execute positioned as @s unless block ~4~-3~1 air at @s run setblock ~4~-3~1 sand 0 replace
execute positioned as @s unless block ~4~-4~1 air at @s run setblock ~4~-4~1 sand 0 replace
execute positioned as @s unless block ~4~-5~1 air at @s run setblock ~4~-5~1 sand 0 replace
execute positioned as @s unless block ~4~7~2 air at @s run setblock ~4~7~2 sand 0 replace
execute positioned as @s unless block ~4~6~2 air at @s run setblock ~4~6~2 sand 0 replace
execute positioned as @s unless block ~4~5~2 air at @s run setblock ~4~5~2 sand 0 replace
execute positioned as @s unless block ~4~4~2 air at @s run setblock ~4~4~2 sand 0 replace
execute positioned as @s unless block ~4~3~2 air at @s run setblock ~4~3~2 sand 0 replace
execute positioned as @s unless block ~4~2~2 air at @s run setblock ~4~2~2 sand 0 replace
execute positioned as @s unless block ~4~1~2 air at @s run setblock ~4~1~2 sand 0 replace
execute positioned as @s unless block ~4~0~2 air at @s run setblock ~4~0~2 sand 0 replace
execute positioned as @s unless block ~4~-1~2 air at @s run setblock ~4~-1~2 sand 0 replace
execute positioned as @s unless block ~4~-2~2 air at @s run setblock ~4~-2~2 sand 0 replace
execute positioned as @s unless block ~4~-3~2 air at @s run setblock ~4~-3~2 sand 0 replace
execute positioned as @s unless block ~4~-4~2 air at @s run setblock ~4~-4~2 sand 0 replace
execute positioned as @s unless block ~4~-5~2 air at @s run setblock ~4~-5~2 sand 0 replace
execute positioned as @s unless block ~4~7~3 air at @s run setblock ~4~7~3 sand 0 replace
execute positioned as @s unless block ~4~6~3 air at @s run setblock ~4~6~3 sand 0 replace
execute positioned as @s unless block ~4~5~3 air at @s run setblock ~4~5~3 sand 0 replace
execute positioned as @s unless block ~4~4~3 air at @s run setblock ~4~4~3 sand 0 replace
execute positioned as @s unless block ~4~3~3 air at @s run setblock ~4~3~3 sand 0 replace
execute positioned as @s unless block ~4~2~3 air at @s run setblock ~4~2~3 sand 0 replace
execute positioned as @s unless block ~4~1~3 air at @s run setblock ~4~1~3 sand 0 replace
execute positioned as @s unless block ~4~0~3 air at @s run setblock ~4~0~3 sand 0 replace
execute positioned as @s unless block ~4~-1~3 air at @s run setblock ~4~-1~3 sand 0 replace
execute positioned as @s unless block ~4~-2~3 air at @s run setblock ~4~-2~3 sand 0 replace
execute positioned as @s unless block ~4~-3~3 air at @s run setblock ~4~-3~3 sand 0 replace
execute positioned as @s unless block ~4~-4~3 air at @s run setblock ~4~-4~3 sand 0 replace
execute positioned as @s unless block ~4~-5~3 air at @s run setblock ~4~-5~3 sand 0 replace
execute positioned as @s unless block ~4~7~4 air at @s run setblock ~4~7~4 sand 0 replace
execute positioned as @s unless block ~4~6~4 air at @s run setblock ~4~6~4 sand 0 replace
execute positioned as @s unless block ~4~5~4 air at @s run setblock ~4~5~4 sand 0 replace
execute positioned as @s unless block ~4~4~4 air at @s run setblock ~4~4~4 sand 0 replace
execute positioned as @s unless block ~4~3~4 air at @s run setblock ~4~3~4 sand 0 replace
execute positioned as @s unless block ~4~2~4 air at @s run setblock ~4~2~4 sand 0 replace
execute positioned as @s unless block ~4~1~4 air at @s run setblock ~4~1~4 sand 0 replace
execute positioned as @s unless block ~4~0~4 air at @s run setblock ~4~0~4 sand 0 replace
execute positioned as @s unless block ~4~-1~4 air at @s run setblock ~4~-1~4 sand 0 replace
execute positioned as @s unless block ~4~-2~4 air at @s run setblock ~4~-2~4 sand 0 replace
execute positioned as @s unless block ~4~-3~4 air at @s run setblock ~4~-3~4 sand 0 replace
execute positioned as @s unless block ~4~-4~4 air at @s run setblock ~4~-4~4 sand 0 replace
execute positioned as @s unless block ~4~-5~4 air at @s run setblock ~4~-5~4 sand 0 replace
