execute as @s unless block ~-5~7~-5 air at @s run setblock ~-5~7~-5 sand 0 replace
execute as @s unless block ~-5~6~-5 air at @s run setblock ~-5~6~-5 sand 0 replace
execute as @s unless block ~-5~5~-5 air at @s run setblock ~-5~5~-5 sand 0 replace
execute as @s unless block ~-5~4~-5 air at @s run setblock ~-5~4~-5 sand 0 replace
execute as @s unless block ~-5~3~-5 air at @s run setblock ~-5~3~-5 sand 0 replace
execute as @s unless block ~-5~2~-5 air at @s run setblock ~-5~2~-5 sand 0 replace
execute as @s unless block ~-5~1~-5 air at @s run setblock ~-5~1~-5 sand 0 replace
execute as @s unless block ~-5~0~-5 air at @s run setblock ~-5~0~-5 sand 0 replace
execute as @s unless block ~-5~-1~-5 air at @s run setblock ~-5~-1~-5 sand 0 replace
execute as @s unless block ~-5~-2~-5 air at @s run setblock ~-5~-2~-5 sand 0 replace
execute as @s unless block ~-5~-3~-5 air at @s run setblock ~-5~-3~-5 sand 0 replace
execute as @s unless block ~-5~-4~-5 air at @s run setblock ~-5~-4~-5 sand 0 replace
execute as @s unless block ~-5~-5~-5 air at @s run setblock ~-5~-5~-5 sand 0 replace
execute as @s unless block ~-5~7~-4 air at @s run setblock ~-5~7~-4 sand 0 replace
execute as @s unless block ~-5~6~-4 air at @s run setblock ~-5~6~-4 sand 0 replace
execute as @s unless block ~-5~5~-4 air at @s run setblock ~-5~5~-4 sand 0 replace
execute as @s unless block ~-5~4~-4 air at @s run setblock ~-5~4~-4 sand 0 replace
execute as @s unless block ~-5~3~-4 air at @s run setblock ~-5~3~-4 sand 0 replace
execute as @s unless block ~-5~2~-4 air at @s run setblock ~-5~2~-4 sand 0 replace
execute as @s unless block ~-5~1~-4 air at @s run setblock ~-5~1~-4 sand 0 replace
execute as @s unless block ~-5~0~-4 air at @s run setblock ~-5~0~-4 sand 0 replace
execute as @s unless block ~-5~-1~-4 air at @s run setblock ~-5~-1~-4 sand 0 replace
execute as @s unless block ~-5~-2~-4 air at @s run setblock ~-5~-2~-4 sand 0 replace
execute as @s unless block ~-5~-3~-4 air at @s run setblock ~-5~-3~-4 sand 0 replace
execute as @s unless block ~-5~-4~-4 air at @s run setblock ~-5~-4~-4 sand 0 replace
execute as @s unless block ~-5~-5~-4 air at @s run setblock ~-5~-5~-4 sand 0 replace
execute as @s unless block ~-5~7~-3 air at @s run setblock ~-5~7~-3 sand 0 replace
execute as @s unless block ~-5~6~-3 air at @s run setblock ~-5~6~-3 sand 0 replace
execute as @s unless block ~-5~5~-3 air at @s run setblock ~-5~5~-3 sand 0 replace
execute as @s unless block ~-5~4~-3 air at @s run setblock ~-5~4~-3 sand 0 replace
execute as @s unless block ~-5~3~-3 air at @s run setblock ~-5~3~-3 sand 0 replace
execute as @s unless block ~-5~2~-3 air at @s run setblock ~-5~2~-3 sand 0 replace
execute as @s unless block ~-5~1~-3 air at @s run setblock ~-5~1~-3 sand 0 replace
execute as @s unless block ~-5~0~-3 air at @s run setblock ~-5~0~-3 sand 0 replace
execute as @s unless block ~-5~-1~-3 air at @s run setblock ~-5~-1~-3 sand 0 replace
execute as @s unless block ~-5~-2~-3 air at @s run setblock ~-5~-2~-3 sand 0 replace
execute as @s unless block ~-5~-3~-3 air at @s run setblock ~-5~-3~-3 sand 0 replace
execute as @s unless block ~-5~-4~-3 air at @s run setblock ~-5~-4~-3 sand 0 replace
execute as @s unless block ~-5~-5~-3 air at @s run setblock ~-5~-5~-3 sand 0 replace
execute as @s unless block ~-5~7~-2 air at @s run setblock ~-5~7~-2 sand 0 replace
execute as @s unless block ~-5~6~-2 air at @s run setblock ~-5~6~-2 sand 0 replace
execute as @s unless block ~-5~5~-2 air at @s run setblock ~-5~5~-2 sand 0 replace
execute as @s unless block ~-5~4~-2 air at @s run setblock ~-5~4~-2 sand 0 replace
execute as @s unless block ~-5~3~-2 air at @s run setblock ~-5~3~-2 sand 0 replace
execute as @s unless block ~-5~2~-2 air at @s run setblock ~-5~2~-2 sand 0 replace
execute as @s unless block ~-5~1~-2 air at @s run setblock ~-5~1~-2 sand 0 replace
execute as @s unless block ~-5~0~-2 air at @s run setblock ~-5~0~-2 sand 0 replace
execute as @s unless block ~-5~-1~-2 air at @s run setblock ~-5~-1~-2 sand 0 replace
execute as @s unless block ~-5~-2~-2 air at @s run setblock ~-5~-2~-2 sand 0 replace
execute as @s unless block ~-5~-3~-2 air at @s run setblock ~-5~-3~-2 sand 0 replace
execute as @s unless block ~-5~-4~-2 air at @s run setblock ~-5~-4~-2 sand 0 replace
execute as @s unless block ~-5~-5~-2 air at @s run setblock ~-5~-5~-2 sand 0 replace
execute as @s unless block ~-5~7~-1 air at @s run setblock ~-5~7~-1 sand 0 replace
execute as @s unless block ~-5~6~-1 air at @s run setblock ~-5~6~-1 sand 0 replace
execute as @s unless block ~-5~5~-1 air at @s run setblock ~-5~5~-1 sand 0 replace
execute as @s unless block ~-5~4~-1 air at @s run setblock ~-5~4~-1 sand 0 replace
execute as @s unless block ~-5~3~-1 air at @s run setblock ~-5~3~-1 sand 0 replace
execute as @s unless block ~-5~2~-1 air at @s run setblock ~-5~2~-1 sand 0 replace
execute as @s unless block ~-5~1~-1 air at @s run setblock ~-5~1~-1 sand 0 replace
execute as @s unless block ~-5~0~-1 air at @s run setblock ~-5~0~-1 sand 0 replace
execute as @s unless block ~-5~-1~-1 air at @s run setblock ~-5~-1~-1 sand 0 replace
execute as @s unless block ~-5~-2~-1 air at @s run setblock ~-5~-2~-1 sand 0 replace
execute as @s unless block ~-5~-3~-1 air at @s run setblock ~-5~-3~-1 sand 0 replace
execute as @s unless block ~-5~-4~-1 air at @s run setblock ~-5~-4~-1 sand 0 replace
execute as @s unless block ~-5~-5~-1 air at @s run setblock ~-5~-5~-1 sand 0 replace
execute as @s unless block ~-5~7~0 air at @s run setblock ~-5~7~0 sand 0 replace
execute as @s unless block ~-5~6~0 air at @s run setblock ~-5~6~0 sand 0 replace
execute as @s unless block ~-5~5~0 air at @s run setblock ~-5~5~0 sand 0 replace
execute as @s unless block ~-5~4~0 air at @s run setblock ~-5~4~0 sand 0 replace
execute as @s unless block ~-5~3~0 air at @s run setblock ~-5~3~0 sand 0 replace
execute as @s unless block ~-5~2~0 air at @s run setblock ~-5~2~0 sand 0 replace
execute as @s unless block ~-5~1~0 air at @s run setblock ~-5~1~0 sand 0 replace
execute as @s unless block ~-5~0~0 air at @s run setblock ~-5~0~0 sand 0 replace
execute as @s unless block ~-5~-1~0 air at @s run setblock ~-5~-1~0 sand 0 replace
execute as @s unless block ~-5~-2~0 air at @s run setblock ~-5~-2~0 sand 0 replace
execute as @s unless block ~-5~-3~0 air at @s run setblock ~-5~-3~0 sand 0 replace
execute as @s unless block ~-5~-4~0 air at @s run setblock ~-5~-4~0 sand 0 replace
execute as @s unless block ~-5~-5~0 air at @s run setblock ~-5~-5~0 sand 0 replace
execute as @s unless block ~-5~7~1 air at @s run setblock ~-5~7~1 sand 0 replace
execute as @s unless block ~-5~6~1 air at @s run setblock ~-5~6~1 sand 0 replace
execute as @s unless block ~-5~5~1 air at @s run setblock ~-5~5~1 sand 0 replace
execute as @s unless block ~-5~4~1 air at @s run setblock ~-5~4~1 sand 0 replace
execute as @s unless block ~-5~3~1 air at @s run setblock ~-5~3~1 sand 0 replace
execute as @s unless block ~-5~2~1 air at @s run setblock ~-5~2~1 sand 0 replace
execute as @s unless block ~-5~1~1 air at @s run setblock ~-5~1~1 sand 0 replace
execute as @s unless block ~-5~0~1 air at @s run setblock ~-5~0~1 sand 0 replace
execute as @s unless block ~-5~-1~1 air at @s run setblock ~-5~-1~1 sand 0 replace
execute as @s unless block ~-5~-2~1 air at @s run setblock ~-5~-2~1 sand 0 replace
execute as @s unless block ~-5~-3~1 air at @s run setblock ~-5~-3~1 sand 0 replace
execute as @s unless block ~-5~-4~1 air at @s run setblock ~-5~-4~1 sand 0 replace
execute as @s unless block ~-5~-5~1 air at @s run setblock ~-5~-5~1 sand 0 replace
execute as @s unless block ~-5~7~2 air at @s run setblock ~-5~7~2 sand 0 replace
execute as @s unless block ~-5~6~2 air at @s run setblock ~-5~6~2 sand 0 replace
execute as @s unless block ~-5~5~2 air at @s run setblock ~-5~5~2 sand 0 replace
execute as @s unless block ~-5~4~2 air at @s run setblock ~-5~4~2 sand 0 replace
execute as @s unless block ~-5~3~2 air at @s run setblock ~-5~3~2 sand 0 replace
execute as @s unless block ~-5~2~2 air at @s run setblock ~-5~2~2 sand 0 replace
execute as @s unless block ~-5~1~2 air at @s run setblock ~-5~1~2 sand 0 replace
execute as @s unless block ~-5~0~2 air at @s run setblock ~-5~0~2 sand 0 replace
execute as @s unless block ~-5~-1~2 air at @s run setblock ~-5~-1~2 sand 0 replace
execute as @s unless block ~-5~-2~2 air at @s run setblock ~-5~-2~2 sand 0 replace
execute as @s unless block ~-5~-3~2 air at @s run setblock ~-5~-3~2 sand 0 replace
execute as @s unless block ~-5~-4~2 air at @s run setblock ~-5~-4~2 sand 0 replace
execute as @s unless block ~-5~-5~2 air at @s run setblock ~-5~-5~2 sand 0 replace
execute as @s unless block ~-5~7~3 air at @s run setblock ~-5~7~3 sand 0 replace
execute as @s unless block ~-5~6~3 air at @s run setblock ~-5~6~3 sand 0 replace
execute as @s unless block ~-5~5~3 air at @s run setblock ~-5~5~3 sand 0 replace
execute as @s unless block ~-5~4~3 air at @s run setblock ~-5~4~3 sand 0 replace
execute as @s unless block ~-5~3~3 air at @s run setblock ~-5~3~3 sand 0 replace
execute as @s unless block ~-5~2~3 air at @s run setblock ~-5~2~3 sand 0 replace
execute as @s unless block ~-5~1~3 air at @s run setblock ~-5~1~3 sand 0 replace
execute as @s unless block ~-5~0~3 air at @s run setblock ~-5~0~3 sand 0 replace
execute as @s unless block ~-5~-1~3 air at @s run setblock ~-5~-1~3 sand 0 replace
execute as @s unless block ~-5~-2~3 air at @s run setblock ~-5~-2~3 sand 0 replace
execute as @s unless block ~-5~-3~3 air at @s run setblock ~-5~-3~3 sand 0 replace
execute as @s unless block ~-5~-4~3 air at @s run setblock ~-5~-4~3 sand 0 replace
execute as @s unless block ~-5~-5~3 air at @s run setblock ~-5~-5~3 sand 0 replace
execute as @s unless block ~-5~7~4 air at @s run setblock ~-5~7~4 sand 0 replace
execute as @s unless block ~-5~6~4 air at @s run setblock ~-5~6~4 sand 0 replace
execute as @s unless block ~-5~5~4 air at @s run setblock ~-5~5~4 sand 0 replace
execute as @s unless block ~-5~4~4 air at @s run setblock ~-5~4~4 sand 0 replace
execute as @s unless block ~-5~3~4 air at @s run setblock ~-5~3~4 sand 0 replace
execute as @s unless block ~-5~2~4 air at @s run setblock ~-5~2~4 sand 0 replace
execute as @s unless block ~-5~1~4 air at @s run setblock ~-5~1~4 sand 0 replace
execute as @s unless block ~-5~0~4 air at @s run setblock ~-5~0~4 sand 0 replace
execute as @s unless block ~-5~-1~4 air at @s run setblock ~-5~-1~4 sand 0 replace
execute as @s unless block ~-5~-2~4 air at @s run setblock ~-5~-2~4 sand 0 replace
execute as @s unless block ~-5~-3~4 air at @s run setblock ~-5~-3~4 sand 0 replace
execute as @s unless block ~-5~-4~4 air at @s run setblock ~-5~-4~4 sand 0 replace
execute as @s unless block ~-5~-5~4 air at @s run setblock ~-5~-5~4 sand 0 replace
execute as @s unless block ~-5~7~5 air at @s run setblock ~-5~7~5 sand 0 replace
execute as @s unless block ~-5~6~5 air at @s run setblock ~-5~6~5 sand 0 replace
execute as @s unless block ~-5~5~5 air at @s run setblock ~-5~5~5 sand 0 replace
execute as @s unless block ~-5~4~5 air at @s run setblock ~-5~4~5 sand 0 replace
execute as @s unless block ~-5~3~5 air at @s run setblock ~-5~3~5 sand 0 replace
execute as @s unless block ~-5~2~5 air at @s run setblock ~-5~2~5 sand 0 replace
execute as @s unless block ~-5~1~5 air at @s run setblock ~-5~1~5 sand 0 replace
execute as @s unless block ~-5~0~5 air at @s run setblock ~-5~0~5 sand 0 replace
execute as @s unless block ~-5~-1~5 air at @s run setblock ~-5~-1~5 sand 0 replace
execute as @s unless block ~-5~-2~5 air at @s run setblock ~-5~-2~5 sand 0 replace
execute as @s unless block ~-5~-3~5 air at @s run setblock ~-5~-3~5 sand 0 replace
execute as @s unless block ~-5~-4~5 air at @s run setblock ~-5~-4~5 sand 0 replace
execute as @s unless block ~-5~-5~5 air at @s run setblock ~-5~-5~5 sand 0 replace
execute as @s unless block ~-4~7~-5 air at @s run setblock ~-4~7~-5 sand 0 replace
execute as @s unless block ~-4~6~-5 air at @s run setblock ~-4~6~-5 sand 0 replace
execute as @s unless block ~-4~5~-5 air at @s run setblock ~-4~5~-5 sand 0 replace
execute as @s unless block ~-4~4~-5 air at @s run setblock ~-4~4~-5 sand 0 replace
execute as @s unless block ~-4~3~-5 air at @s run setblock ~-4~3~-5 sand 0 replace
execute as @s unless block ~-4~2~-5 air at @s run setblock ~-4~2~-5 sand 0 replace
execute as @s unless block ~-4~1~-5 air at @s run setblock ~-4~1~-5 sand 0 replace
execute as @s unless block ~-4~0~-5 air at @s run setblock ~-4~0~-5 sand 0 replace
execute as @s unless block ~-4~-1~-5 air at @s run setblock ~-4~-1~-5 sand 0 replace
execute as @s unless block ~-4~-2~-5 air at @s run setblock ~-4~-2~-5 sand 0 replace
execute as @s unless block ~-4~-3~-5 air at @s run setblock ~-4~-3~-5 sand 0 replace
execute as @s unless block ~-4~-4~-5 air at @s run setblock ~-4~-4~-5 sand 0 replace
execute as @s unless block ~-4~-5~-5 air at @s run setblock ~-4~-5~-5 sand 0 replace
execute as @s unless block ~-4~7~5 air at @s run setblock ~-4~7~5 sand 0 replace
execute as @s unless block ~-4~6~5 air at @s run setblock ~-4~6~5 sand 0 replace
execute as @s unless block ~-4~5~5 air at @s run setblock ~-4~5~5 sand 0 replace
execute as @s unless block ~-4~4~5 air at @s run setblock ~-4~4~5 sand 0 replace
execute as @s unless block ~-4~3~5 air at @s run setblock ~-4~3~5 sand 0 replace
execute as @s unless block ~-4~2~5 air at @s run setblock ~-4~2~5 sand 0 replace
execute as @s unless block ~-4~1~5 air at @s run setblock ~-4~1~5 sand 0 replace
execute as @s unless block ~-4~0~5 air at @s run setblock ~-4~0~5 sand 0 replace
execute as @s unless block ~-4~-1~5 air at @s run setblock ~-4~-1~5 sand 0 replace
execute as @s unless block ~-4~-2~5 air at @s run setblock ~-4~-2~5 sand 0 replace
execute as @s unless block ~-4~-3~5 air at @s run setblock ~-4~-3~5 sand 0 replace
execute as @s unless block ~-4~-4~5 air at @s run setblock ~-4~-4~5 sand 0 replace
execute as @s unless block ~-4~-5~5 air at @s run setblock ~-4~-5~5 sand 0 replace
execute as @s unless block ~-3~7~-5 air at @s run setblock ~-3~7~-5 sand 0 replace
execute as @s unless block ~-3~6~-5 air at @s run setblock ~-3~6~-5 sand 0 replace
execute as @s unless block ~-3~5~-5 air at @s run setblock ~-3~5~-5 sand 0 replace
execute as @s unless block ~-3~4~-5 air at @s run setblock ~-3~4~-5 sand 0 replace
execute as @s unless block ~-3~3~-5 air at @s run setblock ~-3~3~-5 sand 0 replace
execute as @s unless block ~-3~2~-5 air at @s run setblock ~-3~2~-5 sand 0 replace
execute as @s unless block ~-3~1~-5 air at @s run setblock ~-3~1~-5 sand 0 replace
execute as @s unless block ~-3~0~-5 air at @s run setblock ~-3~0~-5 sand 0 replace
execute as @s unless block ~-3~-1~-5 air at @s run setblock ~-3~-1~-5 sand 0 replace
execute as @s unless block ~-3~-2~-5 air at @s run setblock ~-3~-2~-5 sand 0 replace
execute as @s unless block ~-3~-3~-5 air at @s run setblock ~-3~-3~-5 sand 0 replace
execute as @s unless block ~-3~-4~-5 air at @s run setblock ~-3~-4~-5 sand 0 replace
execute as @s unless block ~-3~-5~-5 air at @s run setblock ~-3~-5~-5 sand 0 replace
execute as @s unless block ~-3~7~5 air at @s run setblock ~-3~7~5 sand 0 replace
execute as @s unless block ~-3~6~5 air at @s run setblock ~-3~6~5 sand 0 replace
execute as @s unless block ~-3~5~5 air at @s run setblock ~-3~5~5 sand 0 replace
execute as @s unless block ~-3~4~5 air at @s run setblock ~-3~4~5 sand 0 replace
execute as @s unless block ~-3~3~5 air at @s run setblock ~-3~3~5 sand 0 replace
execute as @s unless block ~-3~2~5 air at @s run setblock ~-3~2~5 sand 0 replace
execute as @s unless block ~-3~1~5 air at @s run setblock ~-3~1~5 sand 0 replace
execute as @s unless block ~-3~0~5 air at @s run setblock ~-3~0~5 sand 0 replace
execute as @s unless block ~-3~-1~5 air at @s run setblock ~-3~-1~5 sand 0 replace
execute as @s unless block ~-3~-2~5 air at @s run setblock ~-3~-2~5 sand 0 replace
execute as @s unless block ~-3~-3~5 air at @s run setblock ~-3~-3~5 sand 0 replace
execute as @s unless block ~-3~-4~5 air at @s run setblock ~-3~-4~5 sand 0 replace
execute as @s unless block ~-3~-5~5 air at @s run setblock ~-3~-5~5 sand 0 replace
execute as @s unless block ~-2~7~-5 air at @s run setblock ~-2~7~-5 sand 0 replace
execute as @s unless block ~-2~6~-5 air at @s run setblock ~-2~6~-5 sand 0 replace
execute as @s unless block ~-2~5~-5 air at @s run setblock ~-2~5~-5 sand 0 replace
execute as @s unless block ~-2~4~-5 air at @s run setblock ~-2~4~-5 sand 0 replace
execute as @s unless block ~-2~3~-5 air at @s run setblock ~-2~3~-5 sand 0 replace
execute as @s unless block ~-2~2~-5 air at @s run setblock ~-2~2~-5 sand 0 replace
execute as @s unless block ~-2~1~-5 air at @s run setblock ~-2~1~-5 sand 0 replace
execute as @s unless block ~-2~0~-5 air at @s run setblock ~-2~0~-5 sand 0 replace
execute as @s unless block ~-2~-1~-5 air at @s run setblock ~-2~-1~-5 sand 0 replace
execute as @s unless block ~-2~-2~-5 air at @s run setblock ~-2~-2~-5 sand 0 replace
execute as @s unless block ~-2~-3~-5 air at @s run setblock ~-2~-3~-5 sand 0 replace
execute as @s unless block ~-2~-4~-5 air at @s run setblock ~-2~-4~-5 sand 0 replace
execute as @s unless block ~-2~-5~-5 air at @s run setblock ~-2~-5~-5 sand 0 replace
execute as @s unless block ~-2~7~5 air at @s run setblock ~-2~7~5 sand 0 replace
execute as @s unless block ~-2~6~5 air at @s run setblock ~-2~6~5 sand 0 replace
execute as @s unless block ~-2~5~5 air at @s run setblock ~-2~5~5 sand 0 replace
execute as @s unless block ~-2~4~5 air at @s run setblock ~-2~4~5 sand 0 replace
execute as @s unless block ~-2~3~5 air at @s run setblock ~-2~3~5 sand 0 replace
execute as @s unless block ~-2~2~5 air at @s run setblock ~-2~2~5 sand 0 replace
execute as @s unless block ~-2~1~5 air at @s run setblock ~-2~1~5 sand 0 replace
execute as @s unless block ~-2~0~5 air at @s run setblock ~-2~0~5 sand 0 replace
execute as @s unless block ~-2~-1~5 air at @s run setblock ~-2~-1~5 sand 0 replace
execute as @s unless block ~-2~-2~5 air at @s run setblock ~-2~-2~5 sand 0 replace
execute as @s unless block ~-2~-3~5 air at @s run setblock ~-2~-3~5 sand 0 replace
execute as @s unless block ~-2~-4~5 air at @s run setblock ~-2~-4~5 sand 0 replace
execute as @s unless block ~-2~-5~5 air at @s run setblock ~-2~-5~5 sand 0 replace
execute as @s unless block ~-1~7~-5 air at @s run setblock ~-1~7~-5 sand 0 replace
execute as @s unless block ~-1~6~-5 air at @s run setblock ~-1~6~-5 sand 0 replace
execute as @s unless block ~-1~5~-5 air at @s run setblock ~-1~5~-5 sand 0 replace
execute as @s unless block ~-1~4~-5 air at @s run setblock ~-1~4~-5 sand 0 replace
execute as @s unless block ~-1~3~-5 air at @s run setblock ~-1~3~-5 sand 0 replace
execute as @s unless block ~-1~2~-5 air at @s run setblock ~-1~2~-5 sand 0 replace
execute as @s unless block ~-1~1~-5 air at @s run setblock ~-1~1~-5 sand 0 replace
execute as @s unless block ~-1~0~-5 air at @s run setblock ~-1~0~-5 sand 0 replace
execute as @s unless block ~-1~-1~-5 air at @s run setblock ~-1~-1~-5 sand 0 replace
execute as @s unless block ~-1~-2~-5 air at @s run setblock ~-1~-2~-5 sand 0 replace
execute as @s unless block ~-1~-3~-5 air at @s run setblock ~-1~-3~-5 sand 0 replace
execute as @s unless block ~-1~-4~-5 air at @s run setblock ~-1~-4~-5 sand 0 replace
execute as @s unless block ~-1~-5~-5 air at @s run setblock ~-1~-5~-5 sand 0 replace
execute as @s unless block ~-1~7~5 air at @s run setblock ~-1~7~5 sand 0 replace
execute as @s unless block ~-1~6~5 air at @s run setblock ~-1~6~5 sand 0 replace
execute as @s unless block ~-1~5~5 air at @s run setblock ~-1~5~5 sand 0 replace
execute as @s unless block ~-1~4~5 air at @s run setblock ~-1~4~5 sand 0 replace
execute as @s unless block ~-1~3~5 air at @s run setblock ~-1~3~5 sand 0 replace
execute as @s unless block ~-1~2~5 air at @s run setblock ~-1~2~5 sand 0 replace
execute as @s unless block ~-1~1~5 air at @s run setblock ~-1~1~5 sand 0 replace
execute as @s unless block ~-1~0~5 air at @s run setblock ~-1~0~5 sand 0 replace
execute as @s unless block ~-1~-1~5 air at @s run setblock ~-1~-1~5 sand 0 replace
execute as @s unless block ~-1~-2~5 air at @s run setblock ~-1~-2~5 sand 0 replace
execute as @s unless block ~-1~-3~5 air at @s run setblock ~-1~-3~5 sand 0 replace
execute as @s unless block ~-1~-4~5 air at @s run setblock ~-1~-4~5 sand 0 replace
execute as @s unless block ~-1~-5~5 air at @s run setblock ~-1~-5~5 sand 0 replace
execute as @s unless block ~0~7~-5 air at @s run setblock ~0~7~-5 sand 0 replace
execute as @s unless block ~0~6~-5 air at @s run setblock ~0~6~-5 sand 0 replace
execute as @s unless block ~0~5~-5 air at @s run setblock ~0~5~-5 sand 0 replace
execute as @s unless block ~0~4~-5 air at @s run setblock ~0~4~-5 sand 0 replace
execute as @s unless block ~0~3~-5 air at @s run setblock ~0~3~-5 sand 0 replace
execute as @s unless block ~0~2~-5 air at @s run setblock ~0~2~-5 sand 0 replace
execute as @s unless block ~0~1~-5 air at @s run setblock ~0~1~-5 sand 0 replace
execute as @s unless block ~0~0~-5 air at @s run setblock ~0~0~-5 sand 0 replace
execute as @s unless block ~0~-1~-5 air at @s run setblock ~0~-1~-5 sand 0 replace
execute as @s unless block ~0~-2~-5 air at @s run setblock ~0~-2~-5 sand 0 replace
execute as @s unless block ~0~-3~-5 air at @s run setblock ~0~-3~-5 sand 0 replace
execute as @s unless block ~0~-4~-5 air at @s run setblock ~0~-4~-5 sand 0 replace
execute as @s unless block ~0~-5~-5 air at @s run setblock ~0~-5~-5 sand 0 replace
execute as @s unless block ~0~7~5 air at @s run setblock ~0~7~5 sand 0 replace
execute as @s unless block ~0~6~5 air at @s run setblock ~0~6~5 sand 0 replace
execute as @s unless block ~0~5~5 air at @s run setblock ~0~5~5 sand 0 replace
execute as @s unless block ~0~4~5 air at @s run setblock ~0~4~5 sand 0 replace
execute as @s unless block ~0~3~5 air at @s run setblock ~0~3~5 sand 0 replace
execute as @s unless block ~0~2~5 air at @s run setblock ~0~2~5 sand 0 replace
execute as @s unless block ~0~1~5 air at @s run setblock ~0~1~5 sand 0 replace
execute as @s unless block ~0~0~5 air at @s run setblock ~0~0~5 sand 0 replace
execute as @s unless block ~0~-1~5 air at @s run setblock ~0~-1~5 sand 0 replace
execute as @s unless block ~0~-2~5 air at @s run setblock ~0~-2~5 sand 0 replace
execute as @s unless block ~0~-3~5 air at @s run setblock ~0~-3~5 sand 0 replace
execute as @s unless block ~0~-4~5 air at @s run setblock ~0~-4~5 sand 0 replace
execute as @s unless block ~0~-5~5 air at @s run setblock ~0~-5~5 sand 0 replace
execute as @s unless block ~1~7~-5 air at @s run setblock ~1~7~-5 sand 0 replace
execute as @s unless block ~1~6~-5 air at @s run setblock ~1~6~-5 sand 0 replace
execute as @s unless block ~1~5~-5 air at @s run setblock ~1~5~-5 sand 0 replace
execute as @s unless block ~1~4~-5 air at @s run setblock ~1~4~-5 sand 0 replace
execute as @s unless block ~1~3~-5 air at @s run setblock ~1~3~-5 sand 0 replace
execute as @s unless block ~1~2~-5 air at @s run setblock ~1~2~-5 sand 0 replace
execute as @s unless block ~1~1~-5 air at @s run setblock ~1~1~-5 sand 0 replace
execute as @s unless block ~1~0~-5 air at @s run setblock ~1~0~-5 sand 0 replace
execute as @s unless block ~1~-1~-5 air at @s run setblock ~1~-1~-5 sand 0 replace
execute as @s unless block ~1~-2~-5 air at @s run setblock ~1~-2~-5 sand 0 replace
execute as @s unless block ~1~-3~-5 air at @s run setblock ~1~-3~-5 sand 0 replace
execute as @s unless block ~1~-4~-5 air at @s run setblock ~1~-4~-5 sand 0 replace
execute as @s unless block ~1~-5~-5 air at @s run setblock ~1~-5~-5 sand 0 replace
execute as @s unless block ~1~7~5 air at @s run setblock ~1~7~5 sand 0 replace
execute as @s unless block ~1~6~5 air at @s run setblock ~1~6~5 sand 0 replace
execute as @s unless block ~1~5~5 air at @s run setblock ~1~5~5 sand 0 replace
execute as @s unless block ~1~4~5 air at @s run setblock ~1~4~5 sand 0 replace
execute as @s unless block ~1~3~5 air at @s run setblock ~1~3~5 sand 0 replace
execute as @s unless block ~1~2~5 air at @s run setblock ~1~2~5 sand 0 replace
execute as @s unless block ~1~1~5 air at @s run setblock ~1~1~5 sand 0 replace
execute as @s unless block ~1~0~5 air at @s run setblock ~1~0~5 sand 0 replace
execute as @s unless block ~1~-1~5 air at @s run setblock ~1~-1~5 sand 0 replace
execute as @s unless block ~1~-2~5 air at @s run setblock ~1~-2~5 sand 0 replace
execute as @s unless block ~1~-3~5 air at @s run setblock ~1~-3~5 sand 0 replace
execute as @s unless block ~1~-4~5 air at @s run setblock ~1~-4~5 sand 0 replace
execute as @s unless block ~1~-5~5 air at @s run setblock ~1~-5~5 sand 0 replace
execute as @s unless block ~2~7~-5 air at @s run setblock ~2~7~-5 sand 0 replace
execute as @s unless block ~2~6~-5 air at @s run setblock ~2~6~-5 sand 0 replace
execute as @s unless block ~2~5~-5 air at @s run setblock ~2~5~-5 sand 0 replace
execute as @s unless block ~2~4~-5 air at @s run setblock ~2~4~-5 sand 0 replace
execute as @s unless block ~2~3~-5 air at @s run setblock ~2~3~-5 sand 0 replace
execute as @s unless block ~2~2~-5 air at @s run setblock ~2~2~-5 sand 0 replace
execute as @s unless block ~2~1~-5 air at @s run setblock ~2~1~-5 sand 0 replace
execute as @s unless block ~2~0~-5 air at @s run setblock ~2~0~-5 sand 0 replace
execute as @s unless block ~2~-1~-5 air at @s run setblock ~2~-1~-5 sand 0 replace
execute as @s unless block ~2~-2~-5 air at @s run setblock ~2~-2~-5 sand 0 replace
execute as @s unless block ~2~-3~-5 air at @s run setblock ~2~-3~-5 sand 0 replace
execute as @s unless block ~2~-4~-5 air at @s run setblock ~2~-4~-5 sand 0 replace
execute as @s unless block ~2~-5~-5 air at @s run setblock ~2~-5~-5 sand 0 replace
execute as @s unless block ~2~7~5 air at @s run setblock ~2~7~5 sand 0 replace
execute as @s unless block ~2~6~5 air at @s run setblock ~2~6~5 sand 0 replace
execute as @s unless block ~2~5~5 air at @s run setblock ~2~5~5 sand 0 replace
execute as @s unless block ~2~4~5 air at @s run setblock ~2~4~5 sand 0 replace
execute as @s unless block ~2~3~5 air at @s run setblock ~2~3~5 sand 0 replace
execute as @s unless block ~2~2~5 air at @s run setblock ~2~2~5 sand 0 replace
execute as @s unless block ~2~1~5 air at @s run setblock ~2~1~5 sand 0 replace
execute as @s unless block ~2~0~5 air at @s run setblock ~2~0~5 sand 0 replace
execute as @s unless block ~2~-1~5 air at @s run setblock ~2~-1~5 sand 0 replace
execute as @s unless block ~2~-2~5 air at @s run setblock ~2~-2~5 sand 0 replace
execute as @s unless block ~2~-3~5 air at @s run setblock ~2~-3~5 sand 0 replace
execute as @s unless block ~2~-4~5 air at @s run setblock ~2~-4~5 sand 0 replace
execute as @s unless block ~2~-5~5 air at @s run setblock ~2~-5~5 sand 0 replace
execute as @s unless block ~3~7~-5 air at @s run setblock ~3~7~-5 sand 0 replace
execute as @s unless block ~3~6~-5 air at @s run setblock ~3~6~-5 sand 0 replace
execute as @s unless block ~3~5~-5 air at @s run setblock ~3~5~-5 sand 0 replace
execute as @s unless block ~3~4~-5 air at @s run setblock ~3~4~-5 sand 0 replace
execute as @s unless block ~3~3~-5 air at @s run setblock ~3~3~-5 sand 0 replace
execute as @s unless block ~3~2~-5 air at @s run setblock ~3~2~-5 sand 0 replace
execute as @s unless block ~3~1~-5 air at @s run setblock ~3~1~-5 sand 0 replace
execute as @s unless block ~3~0~-5 air at @s run setblock ~3~0~-5 sand 0 replace
execute as @s unless block ~3~-1~-5 air at @s run setblock ~3~-1~-5 sand 0 replace
execute as @s unless block ~3~-2~-5 air at @s run setblock ~3~-2~-5 sand 0 replace
execute as @s unless block ~3~-3~-5 air at @s run setblock ~3~-3~-5 sand 0 replace
execute as @s unless block ~3~-4~-5 air at @s run setblock ~3~-4~-5 sand 0 replace
execute as @s unless block ~3~-5~-5 air at @s run setblock ~3~-5~-5 sand 0 replace
execute as @s unless block ~3~7~5 air at @s run setblock ~3~7~5 sand 0 replace
execute as @s unless block ~3~6~5 air at @s run setblock ~3~6~5 sand 0 replace
execute as @s unless block ~3~5~5 air at @s run setblock ~3~5~5 sand 0 replace
execute as @s unless block ~3~4~5 air at @s run setblock ~3~4~5 sand 0 replace
execute as @s unless block ~3~3~5 air at @s run setblock ~3~3~5 sand 0 replace
execute as @s unless block ~3~2~5 air at @s run setblock ~3~2~5 sand 0 replace
execute as @s unless block ~3~1~5 air at @s run setblock ~3~1~5 sand 0 replace
execute as @s unless block ~3~0~5 air at @s run setblock ~3~0~5 sand 0 replace
execute as @s unless block ~3~-1~5 air at @s run setblock ~3~-1~5 sand 0 replace
execute as @s unless block ~3~-2~5 air at @s run setblock ~3~-2~5 sand 0 replace
execute as @s unless block ~3~-3~5 air at @s run setblock ~3~-3~5 sand 0 replace
execute as @s unless block ~3~-4~5 air at @s run setblock ~3~-4~5 sand 0 replace
execute as @s unless block ~3~-5~5 air at @s run setblock ~3~-5~5 sand 0 replace
execute as @s unless block ~4~7~-5 air at @s run setblock ~4~7~-5 sand 0 replace
execute as @s unless block ~4~6~-5 air at @s run setblock ~4~6~-5 sand 0 replace
execute as @s unless block ~4~5~-5 air at @s run setblock ~4~5~-5 sand 0 replace
execute as @s unless block ~4~4~-5 air at @s run setblock ~4~4~-5 sand 0 replace
execute as @s unless block ~4~3~-5 air at @s run setblock ~4~3~-5 sand 0 replace
execute as @s unless block ~4~2~-5 air at @s run setblock ~4~2~-5 sand 0 replace
execute as @s unless block ~4~1~-5 air at @s run setblock ~4~1~-5 sand 0 replace
execute as @s unless block ~4~0~-5 air at @s run setblock ~4~0~-5 sand 0 replace
execute as @s unless block ~4~-1~-5 air at @s run setblock ~4~-1~-5 sand 0 replace
execute as @s unless block ~4~-2~-5 air at @s run setblock ~4~-2~-5 sand 0 replace
execute as @s unless block ~4~-3~-5 air at @s run setblock ~4~-3~-5 sand 0 replace
execute as @s unless block ~4~-4~-5 air at @s run setblock ~4~-4~-5 sand 0 replace
execute as @s unless block ~4~-5~-5 air at @s run setblock ~4~-5~-5 sand 0 replace
execute as @s unless block ~4~7~5 air at @s run setblock ~4~7~5 sand 0 replace
execute as @s unless block ~4~6~5 air at @s run setblock ~4~6~5 sand 0 replace
execute as @s unless block ~4~5~5 air at @s run setblock ~4~5~5 sand 0 replace
execute as @s unless block ~4~4~5 air at @s run setblock ~4~4~5 sand 0 replace
execute as @s unless block ~4~3~5 air at @s run setblock ~4~3~5 sand 0 replace
execute as @s unless block ~4~2~5 air at @s run setblock ~4~2~5 sand 0 replace
execute as @s unless block ~4~1~5 air at @s run setblock ~4~1~5 sand 0 replace
execute as @s unless block ~4~0~5 air at @s run setblock ~4~0~5 sand 0 replace
execute as @s unless block ~4~-1~5 air at @s run setblock ~4~-1~5 sand 0 replace
execute as @s unless block ~4~-2~5 air at @s run setblock ~4~-2~5 sand 0 replace
execute as @s unless block ~4~-3~5 air at @s run setblock ~4~-3~5 sand 0 replace
execute as @s unless block ~4~-4~5 air at @s run setblock ~4~-4~5 sand 0 replace
execute as @s unless block ~4~-5~5 air at @s run setblock ~4~-5~5 sand 0 replace
execute as @s unless block ~5~7~-5 air at @s run setblock ~5~7~-5 sand 0 replace
execute as @s unless block ~5~6~-5 air at @s run setblock ~5~6~-5 sand 0 replace
execute as @s unless block ~5~5~-5 air at @s run setblock ~5~5~-5 sand 0 replace
execute as @s unless block ~5~4~-5 air at @s run setblock ~5~4~-5 sand 0 replace
execute as @s unless block ~5~3~-5 air at @s run setblock ~5~3~-5 sand 0 replace
execute as @s unless block ~5~2~-5 air at @s run setblock ~5~2~-5 sand 0 replace
execute as @s unless block ~5~1~-5 air at @s run setblock ~5~1~-5 sand 0 replace
execute as @s unless block ~5~0~-5 air at @s run setblock ~5~0~-5 sand 0 replace
execute as @s unless block ~5~-1~-5 air at @s run setblock ~5~-1~-5 sand 0 replace
execute as @s unless block ~5~-2~-5 air at @s run setblock ~5~-2~-5 sand 0 replace
execute as @s unless block ~5~-3~-5 air at @s run setblock ~5~-3~-5 sand 0 replace
execute as @s unless block ~5~-4~-5 air at @s run setblock ~5~-4~-5 sand 0 replace
execute as @s unless block ~5~-5~-5 air at @s run setblock ~5~-5~-5 sand 0 replace
execute as @s unless block ~5~7~-4 air at @s run setblock ~5~7~-4 sand 0 replace
execute as @s unless block ~5~6~-4 air at @s run setblock ~5~6~-4 sand 0 replace
execute as @s unless block ~5~5~-4 air at @s run setblock ~5~5~-4 sand 0 replace
execute as @s unless block ~5~4~-4 air at @s run setblock ~5~4~-4 sand 0 replace
execute as @s unless block ~5~3~-4 air at @s run setblock ~5~3~-4 sand 0 replace
execute as @s unless block ~5~2~-4 air at @s run setblock ~5~2~-4 sand 0 replace
execute as @s unless block ~5~1~-4 air at @s run setblock ~5~1~-4 sand 0 replace
execute as @s unless block ~5~0~-4 air at @s run setblock ~5~0~-4 sand 0 replace
execute as @s unless block ~5~-1~-4 air at @s run setblock ~5~-1~-4 sand 0 replace
execute as @s unless block ~5~-2~-4 air at @s run setblock ~5~-2~-4 sand 0 replace
execute as @s unless block ~5~-3~-4 air at @s run setblock ~5~-3~-4 sand 0 replace
execute as @s unless block ~5~-4~-4 air at @s run setblock ~5~-4~-4 sand 0 replace
execute as @s unless block ~5~-5~-4 air at @s run setblock ~5~-5~-4 sand 0 replace
execute as @s unless block ~5~7~-3 air at @s run setblock ~5~7~-3 sand 0 replace
execute as @s unless block ~5~6~-3 air at @s run setblock ~5~6~-3 sand 0 replace
execute as @s unless block ~5~5~-3 air at @s run setblock ~5~5~-3 sand 0 replace
execute as @s unless block ~5~4~-3 air at @s run setblock ~5~4~-3 sand 0 replace
execute as @s unless block ~5~3~-3 air at @s run setblock ~5~3~-3 sand 0 replace
execute as @s unless block ~5~2~-3 air at @s run setblock ~5~2~-3 sand 0 replace
execute as @s unless block ~5~1~-3 air at @s run setblock ~5~1~-3 sand 0 replace
execute as @s unless block ~5~0~-3 air at @s run setblock ~5~0~-3 sand 0 replace
execute as @s unless block ~5~-1~-3 air at @s run setblock ~5~-1~-3 sand 0 replace
execute as @s unless block ~5~-2~-3 air at @s run setblock ~5~-2~-3 sand 0 replace
execute as @s unless block ~5~-3~-3 air at @s run setblock ~5~-3~-3 sand 0 replace
execute as @s unless block ~5~-4~-3 air at @s run setblock ~5~-4~-3 sand 0 replace
execute as @s unless block ~5~-5~-3 air at @s run setblock ~5~-5~-3 sand 0 replace
execute as @s unless block ~5~7~-2 air at @s run setblock ~5~7~-2 sand 0 replace
execute as @s unless block ~5~6~-2 air at @s run setblock ~5~6~-2 sand 0 replace
execute as @s unless block ~5~5~-2 air at @s run setblock ~5~5~-2 sand 0 replace
execute as @s unless block ~5~4~-2 air at @s run setblock ~5~4~-2 sand 0 replace
execute as @s unless block ~5~3~-2 air at @s run setblock ~5~3~-2 sand 0 replace
execute as @s unless block ~5~2~-2 air at @s run setblock ~5~2~-2 sand 0 replace
execute as @s unless block ~5~1~-2 air at @s run setblock ~5~1~-2 sand 0 replace
execute as @s unless block ~5~0~-2 air at @s run setblock ~5~0~-2 sand 0 replace
execute as @s unless block ~5~-1~-2 air at @s run setblock ~5~-1~-2 sand 0 replace
execute as @s unless block ~5~-2~-2 air at @s run setblock ~5~-2~-2 sand 0 replace
execute as @s unless block ~5~-3~-2 air at @s run setblock ~5~-3~-2 sand 0 replace
execute as @s unless block ~5~-4~-2 air at @s run setblock ~5~-4~-2 sand 0 replace
execute as @s unless block ~5~-5~-2 air at @s run setblock ~5~-5~-2 sand 0 replace
execute as @s unless block ~5~7~-1 air at @s run setblock ~5~7~-1 sand 0 replace
execute as @s unless block ~5~6~-1 air at @s run setblock ~5~6~-1 sand 0 replace
execute as @s unless block ~5~5~-1 air at @s run setblock ~5~5~-1 sand 0 replace
execute as @s unless block ~5~4~-1 air at @s run setblock ~5~4~-1 sand 0 replace
execute as @s unless block ~5~3~-1 air at @s run setblock ~5~3~-1 sand 0 replace
execute as @s unless block ~5~2~-1 air at @s run setblock ~5~2~-1 sand 0 replace
execute as @s unless block ~5~1~-1 air at @s run setblock ~5~1~-1 sand 0 replace
execute as @s unless block ~5~0~-1 air at @s run setblock ~5~0~-1 sand 0 replace
execute as @s unless block ~5~-1~-1 air at @s run setblock ~5~-1~-1 sand 0 replace
execute as @s unless block ~5~-2~-1 air at @s run setblock ~5~-2~-1 sand 0 replace
execute as @s unless block ~5~-3~-1 air at @s run setblock ~5~-3~-1 sand 0 replace
execute as @s unless block ~5~-4~-1 air at @s run setblock ~5~-4~-1 sand 0 replace
execute as @s unless block ~5~-5~-1 air at @s run setblock ~5~-5~-1 sand 0 replace
execute as @s unless block ~5~7~0 air at @s run setblock ~5~7~0 sand 0 replace
execute as @s unless block ~5~6~0 air at @s run setblock ~5~6~0 sand 0 replace
execute as @s unless block ~5~5~0 air at @s run setblock ~5~5~0 sand 0 replace
execute as @s unless block ~5~4~0 air at @s run setblock ~5~4~0 sand 0 replace
execute as @s unless block ~5~3~0 air at @s run setblock ~5~3~0 sand 0 replace
execute as @s unless block ~5~2~0 air at @s run setblock ~5~2~0 sand 0 replace
execute as @s unless block ~5~1~0 air at @s run setblock ~5~1~0 sand 0 replace
execute as @s unless block ~5~0~0 air at @s run setblock ~5~0~0 sand 0 replace
execute as @s unless block ~5~-1~0 air at @s run setblock ~5~-1~0 sand 0 replace
execute as @s unless block ~5~-2~0 air at @s run setblock ~5~-2~0 sand 0 replace
execute as @s unless block ~5~-3~0 air at @s run setblock ~5~-3~0 sand 0 replace
execute as @s unless block ~5~-4~0 air at @s run setblock ~5~-4~0 sand 0 replace
execute as @s unless block ~5~-5~0 air at @s run setblock ~5~-5~0 sand 0 replace
execute as @s unless block ~5~7~1 air at @s run setblock ~5~7~1 sand 0 replace
execute as @s unless block ~5~6~1 air at @s run setblock ~5~6~1 sand 0 replace
execute as @s unless block ~5~5~1 air at @s run setblock ~5~5~1 sand 0 replace
execute as @s unless block ~5~4~1 air at @s run setblock ~5~4~1 sand 0 replace
execute as @s unless block ~5~3~1 air at @s run setblock ~5~3~1 sand 0 replace
execute as @s unless block ~5~2~1 air at @s run setblock ~5~2~1 sand 0 replace
execute as @s unless block ~5~1~1 air at @s run setblock ~5~1~1 sand 0 replace
execute as @s unless block ~5~0~1 air at @s run setblock ~5~0~1 sand 0 replace
execute as @s unless block ~5~-1~1 air at @s run setblock ~5~-1~1 sand 0 replace
execute as @s unless block ~5~-2~1 air at @s run setblock ~5~-2~1 sand 0 replace
execute as @s unless block ~5~-3~1 air at @s run setblock ~5~-3~1 sand 0 replace
execute as @s unless block ~5~-4~1 air at @s run setblock ~5~-4~1 sand 0 replace
execute as @s unless block ~5~-5~1 air at @s run setblock ~5~-5~1 sand 0 replace
execute as @s unless block ~5~7~2 air at @s run setblock ~5~7~2 sand 0 replace
execute as @s unless block ~5~6~2 air at @s run setblock ~5~6~2 sand 0 replace
execute as @s unless block ~5~5~2 air at @s run setblock ~5~5~2 sand 0 replace
execute as @s unless block ~5~4~2 air at @s run setblock ~5~4~2 sand 0 replace
execute as @s unless block ~5~3~2 air at @s run setblock ~5~3~2 sand 0 replace
execute as @s unless block ~5~2~2 air at @s run setblock ~5~2~2 sand 0 replace
execute as @s unless block ~5~1~2 air at @s run setblock ~5~1~2 sand 0 replace
execute as @s unless block ~5~0~2 air at @s run setblock ~5~0~2 sand 0 replace
execute as @s unless block ~5~-1~2 air at @s run setblock ~5~-1~2 sand 0 replace
execute as @s unless block ~5~-2~2 air at @s run setblock ~5~-2~2 sand 0 replace
execute as @s unless block ~5~-3~2 air at @s run setblock ~5~-3~2 sand 0 replace
execute as @s unless block ~5~-4~2 air at @s run setblock ~5~-4~2 sand 0 replace
execute as @s unless block ~5~-5~2 air at @s run setblock ~5~-5~2 sand 0 replace
execute as @s unless block ~5~7~3 air at @s run setblock ~5~7~3 sand 0 replace
execute as @s unless block ~5~6~3 air at @s run setblock ~5~6~3 sand 0 replace
execute as @s unless block ~5~5~3 air at @s run setblock ~5~5~3 sand 0 replace
execute as @s unless block ~5~4~3 air at @s run setblock ~5~4~3 sand 0 replace
execute as @s unless block ~5~3~3 air at @s run setblock ~5~3~3 sand 0 replace
execute as @s unless block ~5~2~3 air at @s run setblock ~5~2~3 sand 0 replace
execute as @s unless block ~5~1~3 air at @s run setblock ~5~1~3 sand 0 replace
execute as @s unless block ~5~0~3 air at @s run setblock ~5~0~3 sand 0 replace
execute as @s unless block ~5~-1~3 air at @s run setblock ~5~-1~3 sand 0 replace
execute as @s unless block ~5~-2~3 air at @s run setblock ~5~-2~3 sand 0 replace
execute as @s unless block ~5~-3~3 air at @s run setblock ~5~-3~3 sand 0 replace
execute as @s unless block ~5~-4~3 air at @s run setblock ~5~-4~3 sand 0 replace
execute as @s unless block ~5~-5~3 air at @s run setblock ~5~-5~3 sand 0 replace
execute as @s unless block ~5~7~4 air at @s run setblock ~5~7~4 sand 0 replace
execute as @s unless block ~5~6~4 air at @s run setblock ~5~6~4 sand 0 replace
execute as @s unless block ~5~5~4 air at @s run setblock ~5~5~4 sand 0 replace
execute as @s unless block ~5~4~4 air at @s run setblock ~5~4~4 sand 0 replace
execute as @s unless block ~5~3~4 air at @s run setblock ~5~3~4 sand 0 replace
execute as @s unless block ~5~2~4 air at @s run setblock ~5~2~4 sand 0 replace
execute as @s unless block ~5~1~4 air at @s run setblock ~5~1~4 sand 0 replace
execute as @s unless block ~5~0~4 air at @s run setblock ~5~0~4 sand 0 replace
execute as @s unless block ~5~-1~4 air at @s run setblock ~5~-1~4 sand 0 replace
execute as @s unless block ~5~-2~4 air at @s run setblock ~5~-2~4 sand 0 replace
execute as @s unless block ~5~-3~4 air at @s run setblock ~5~-3~4 sand 0 replace
execute as @s unless block ~5~-4~4 air at @s run setblock ~5~-4~4 sand 0 replace
execute as @s unless block ~5~-5~4 air at @s run setblock ~5~-5~4 sand 0 replace
execute as @s unless block ~5~7~5 air at @s run setblock ~5~7~5 sand 0 replace
execute as @s unless block ~5~6~5 air at @s run setblock ~5~6~5 sand 0 replace
execute as @s unless block ~5~5~5 air at @s run setblock ~5~5~5 sand 0 replace
execute as @s unless block ~5~4~5 air at @s run setblock ~5~4~5 sand 0 replace
execute as @s unless block ~5~3~5 air at @s run setblock ~5~3~5 sand 0 replace
execute as @s unless block ~5~2~5 air at @s run setblock ~5~2~5 sand 0 replace
execute as @s unless block ~5~1~5 air at @s run setblock ~5~1~5 sand 0 replace
execute as @s unless block ~5~0~5 air at @s run setblock ~5~0~5 sand 0 replace
execute as @s unless block ~5~-1~5 air at @s run setblock ~5~-1~5 sand 0 replace
execute as @s unless block ~5~-2~5 air at @s run setblock ~5~-2~5 sand 0 replace
execute as @s unless block ~5~-3~5 air at @s run setblock ~5~-3~5 sand 0 replace
execute as @s unless block ~5~-4~5 air at @s run setblock ~5~-4~5 sand 0 replace
execute as @s unless block ~5~-5~5 air at @s run setblock ~5~-5~5 sand 0 replace
