execute at positioned as @s unless block ~-7~7~-7 air at @s run setblock ~-7~7~-7 sand 0 replace
execute at positioned as @s unless block ~-7~6~-7 air at @s run setblock ~-7~6~-7 sand 0 replace
execute at positioned as @s unless block ~-7~5~-7 air at @s run setblock ~-7~5~-7 sand 0 replace
execute at positioned as @s unless block ~-7~4~-7 air at @s run setblock ~-7~4~-7 sand 0 replace
execute at positioned as @s unless block ~-7~3~-7 air at @s run setblock ~-7~3~-7 sand 0 replace
execute at positioned as @s unless block ~-7~2~-7 air at @s run setblock ~-7~2~-7 sand 0 replace
execute at positioned as @s unless block ~-7~1~-7 air at @s run setblock ~-7~1~-7 sand 0 replace
execute at positioned as @s unless block ~-7~0~-7 air at @s run setblock ~-7~0~-7 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-7 air at @s run setblock ~-7~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-7 air at @s run setblock ~-7~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-7 air at @s run setblock ~-7~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-7 air at @s run setblock ~-7~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-7 air at @s run setblock ~-7~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-7~7~-6 air at @s run setblock ~-7~7~-6 sand 0 replace
execute at positioned as @s unless block ~-7~6~-6 air at @s run setblock ~-7~6~-6 sand 0 replace
execute at positioned as @s unless block ~-7~5~-6 air at @s run setblock ~-7~5~-6 sand 0 replace
execute at positioned as @s unless block ~-7~4~-6 air at @s run setblock ~-7~4~-6 sand 0 replace
execute at positioned as @s unless block ~-7~3~-6 air at @s run setblock ~-7~3~-6 sand 0 replace
execute at positioned as @s unless block ~-7~2~-6 air at @s run setblock ~-7~2~-6 sand 0 replace
execute at positioned as @s unless block ~-7~1~-6 air at @s run setblock ~-7~1~-6 sand 0 replace
execute at positioned as @s unless block ~-7~0~-6 air at @s run setblock ~-7~0~-6 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-6 air at @s run setblock ~-7~-1~-6 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-6 air at @s run setblock ~-7~-2~-6 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-6 air at @s run setblock ~-7~-3~-6 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-6 air at @s run setblock ~-7~-4~-6 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-6 air at @s run setblock ~-7~-5~-6 sand 0 replace
execute at positioned as @s unless block ~-7~7~-5 air at @s run setblock ~-7~7~-5 sand 0 replace
execute at positioned as @s unless block ~-7~6~-5 air at @s run setblock ~-7~6~-5 sand 0 replace
execute at positioned as @s unless block ~-7~5~-5 air at @s run setblock ~-7~5~-5 sand 0 replace
execute at positioned as @s unless block ~-7~4~-5 air at @s run setblock ~-7~4~-5 sand 0 replace
execute at positioned as @s unless block ~-7~3~-5 air at @s run setblock ~-7~3~-5 sand 0 replace
execute at positioned as @s unless block ~-7~2~-5 air at @s run setblock ~-7~2~-5 sand 0 replace
execute at positioned as @s unless block ~-7~1~-5 air at @s run setblock ~-7~1~-5 sand 0 replace
execute at positioned as @s unless block ~-7~0~-5 air at @s run setblock ~-7~0~-5 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-5 air at @s run setblock ~-7~-1~-5 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-5 air at @s run setblock ~-7~-2~-5 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-5 air at @s run setblock ~-7~-3~-5 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-5 air at @s run setblock ~-7~-4~-5 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-5 air at @s run setblock ~-7~-5~-5 sand 0 replace
execute at positioned as @s unless block ~-7~7~-4 air at @s run setblock ~-7~7~-4 sand 0 replace
execute at positioned as @s unless block ~-7~6~-4 air at @s run setblock ~-7~6~-4 sand 0 replace
execute at positioned as @s unless block ~-7~5~-4 air at @s run setblock ~-7~5~-4 sand 0 replace
execute at positioned as @s unless block ~-7~4~-4 air at @s run setblock ~-7~4~-4 sand 0 replace
execute at positioned as @s unless block ~-7~3~-4 air at @s run setblock ~-7~3~-4 sand 0 replace
execute at positioned as @s unless block ~-7~2~-4 air at @s run setblock ~-7~2~-4 sand 0 replace
execute at positioned as @s unless block ~-7~1~-4 air at @s run setblock ~-7~1~-4 sand 0 replace
execute at positioned as @s unless block ~-7~0~-4 air at @s run setblock ~-7~0~-4 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-4 air at @s run setblock ~-7~-1~-4 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-4 air at @s run setblock ~-7~-2~-4 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-4 air at @s run setblock ~-7~-3~-4 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-4 air at @s run setblock ~-7~-4~-4 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-4 air at @s run setblock ~-7~-5~-4 sand 0 replace
execute at positioned as @s unless block ~-7~7~-3 air at @s run setblock ~-7~7~-3 sand 0 replace
execute at positioned as @s unless block ~-7~6~-3 air at @s run setblock ~-7~6~-3 sand 0 replace
execute at positioned as @s unless block ~-7~5~-3 air at @s run setblock ~-7~5~-3 sand 0 replace
execute at positioned as @s unless block ~-7~4~-3 air at @s run setblock ~-7~4~-3 sand 0 replace
execute at positioned as @s unless block ~-7~3~-3 air at @s run setblock ~-7~3~-3 sand 0 replace
execute at positioned as @s unless block ~-7~2~-3 air at @s run setblock ~-7~2~-3 sand 0 replace
execute at positioned as @s unless block ~-7~1~-3 air at @s run setblock ~-7~1~-3 sand 0 replace
execute at positioned as @s unless block ~-7~0~-3 air at @s run setblock ~-7~0~-3 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-3 air at @s run setblock ~-7~-1~-3 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-3 air at @s run setblock ~-7~-2~-3 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-3 air at @s run setblock ~-7~-3~-3 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-3 air at @s run setblock ~-7~-4~-3 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-3 air at @s run setblock ~-7~-5~-3 sand 0 replace
execute at positioned as @s unless block ~-7~7~-2 air at @s run setblock ~-7~7~-2 sand 0 replace
execute at positioned as @s unless block ~-7~6~-2 air at @s run setblock ~-7~6~-2 sand 0 replace
execute at positioned as @s unless block ~-7~5~-2 air at @s run setblock ~-7~5~-2 sand 0 replace
execute at positioned as @s unless block ~-7~4~-2 air at @s run setblock ~-7~4~-2 sand 0 replace
execute at positioned as @s unless block ~-7~3~-2 air at @s run setblock ~-7~3~-2 sand 0 replace
execute at positioned as @s unless block ~-7~2~-2 air at @s run setblock ~-7~2~-2 sand 0 replace
execute at positioned as @s unless block ~-7~1~-2 air at @s run setblock ~-7~1~-2 sand 0 replace
execute at positioned as @s unless block ~-7~0~-2 air at @s run setblock ~-7~0~-2 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-2 air at @s run setblock ~-7~-1~-2 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-2 air at @s run setblock ~-7~-2~-2 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-2 air at @s run setblock ~-7~-3~-2 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-2 air at @s run setblock ~-7~-4~-2 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-2 air at @s run setblock ~-7~-5~-2 sand 0 replace
execute at positioned as @s unless block ~-7~7~-1 air at @s run setblock ~-7~7~-1 sand 0 replace
execute at positioned as @s unless block ~-7~6~-1 air at @s run setblock ~-7~6~-1 sand 0 replace
execute at positioned as @s unless block ~-7~5~-1 air at @s run setblock ~-7~5~-1 sand 0 replace
execute at positioned as @s unless block ~-7~4~-1 air at @s run setblock ~-7~4~-1 sand 0 replace
execute at positioned as @s unless block ~-7~3~-1 air at @s run setblock ~-7~3~-1 sand 0 replace
execute at positioned as @s unless block ~-7~2~-1 air at @s run setblock ~-7~2~-1 sand 0 replace
execute at positioned as @s unless block ~-7~1~-1 air at @s run setblock ~-7~1~-1 sand 0 replace
execute at positioned as @s unless block ~-7~0~-1 air at @s run setblock ~-7~0~-1 sand 0 replace
execute at positioned as @s unless block ~-7~-1~-1 air at @s run setblock ~-7~-1~-1 sand 0 replace
execute at positioned as @s unless block ~-7~-2~-1 air at @s run setblock ~-7~-2~-1 sand 0 replace
execute at positioned as @s unless block ~-7~-3~-1 air at @s run setblock ~-7~-3~-1 sand 0 replace
execute at positioned as @s unless block ~-7~-4~-1 air at @s run setblock ~-7~-4~-1 sand 0 replace
execute at positioned as @s unless block ~-7~-5~-1 air at @s run setblock ~-7~-5~-1 sand 0 replace
execute at positioned as @s unless block ~-7~7~0 air at @s run setblock ~-7~7~0 sand 0 replace
execute at positioned as @s unless block ~-7~6~0 air at @s run setblock ~-7~6~0 sand 0 replace
execute at positioned as @s unless block ~-7~5~0 air at @s run setblock ~-7~5~0 sand 0 replace
execute at positioned as @s unless block ~-7~4~0 air at @s run setblock ~-7~4~0 sand 0 replace
execute at positioned as @s unless block ~-7~3~0 air at @s run setblock ~-7~3~0 sand 0 replace
execute at positioned as @s unless block ~-7~2~0 air at @s run setblock ~-7~2~0 sand 0 replace
execute at positioned as @s unless block ~-7~1~0 air at @s run setblock ~-7~1~0 sand 0 replace
execute at positioned as @s unless block ~-7~0~0 air at @s run setblock ~-7~0~0 sand 0 replace
execute at positioned as @s unless block ~-7~-1~0 air at @s run setblock ~-7~-1~0 sand 0 replace
execute at positioned as @s unless block ~-7~-2~0 air at @s run setblock ~-7~-2~0 sand 0 replace
execute at positioned as @s unless block ~-7~-3~0 air at @s run setblock ~-7~-3~0 sand 0 replace
execute at positioned as @s unless block ~-7~-4~0 air at @s run setblock ~-7~-4~0 sand 0 replace
execute at positioned as @s unless block ~-7~-5~0 air at @s run setblock ~-7~-5~0 sand 0 replace
execute at positioned as @s unless block ~-7~7~1 air at @s run setblock ~-7~7~1 sand 0 replace
execute at positioned as @s unless block ~-7~6~1 air at @s run setblock ~-7~6~1 sand 0 replace
execute at positioned as @s unless block ~-7~5~1 air at @s run setblock ~-7~5~1 sand 0 replace
execute at positioned as @s unless block ~-7~4~1 air at @s run setblock ~-7~4~1 sand 0 replace
execute at positioned as @s unless block ~-7~3~1 air at @s run setblock ~-7~3~1 sand 0 replace
execute at positioned as @s unless block ~-7~2~1 air at @s run setblock ~-7~2~1 sand 0 replace
execute at positioned as @s unless block ~-7~1~1 air at @s run setblock ~-7~1~1 sand 0 replace
execute at positioned as @s unless block ~-7~0~1 air at @s run setblock ~-7~0~1 sand 0 replace
execute at positioned as @s unless block ~-7~-1~1 air at @s run setblock ~-7~-1~1 sand 0 replace
execute at positioned as @s unless block ~-7~-2~1 air at @s run setblock ~-7~-2~1 sand 0 replace
execute at positioned as @s unless block ~-7~-3~1 air at @s run setblock ~-7~-3~1 sand 0 replace
execute at positioned as @s unless block ~-7~-4~1 air at @s run setblock ~-7~-4~1 sand 0 replace
execute at positioned as @s unless block ~-7~-5~1 air at @s run setblock ~-7~-5~1 sand 0 replace
execute at positioned as @s unless block ~-7~7~2 air at @s run setblock ~-7~7~2 sand 0 replace
execute at positioned as @s unless block ~-7~6~2 air at @s run setblock ~-7~6~2 sand 0 replace
execute at positioned as @s unless block ~-7~5~2 air at @s run setblock ~-7~5~2 sand 0 replace
execute at positioned as @s unless block ~-7~4~2 air at @s run setblock ~-7~4~2 sand 0 replace
execute at positioned as @s unless block ~-7~3~2 air at @s run setblock ~-7~3~2 sand 0 replace
execute at positioned as @s unless block ~-7~2~2 air at @s run setblock ~-7~2~2 sand 0 replace
execute at positioned as @s unless block ~-7~1~2 air at @s run setblock ~-7~1~2 sand 0 replace
execute at positioned as @s unless block ~-7~0~2 air at @s run setblock ~-7~0~2 sand 0 replace
execute at positioned as @s unless block ~-7~-1~2 air at @s run setblock ~-7~-1~2 sand 0 replace
execute at positioned as @s unless block ~-7~-2~2 air at @s run setblock ~-7~-2~2 sand 0 replace
execute at positioned as @s unless block ~-7~-3~2 air at @s run setblock ~-7~-3~2 sand 0 replace
execute at positioned as @s unless block ~-7~-4~2 air at @s run setblock ~-7~-4~2 sand 0 replace
execute at positioned as @s unless block ~-7~-5~2 air at @s run setblock ~-7~-5~2 sand 0 replace
execute at positioned as @s unless block ~-7~7~3 air at @s run setblock ~-7~7~3 sand 0 replace
execute at positioned as @s unless block ~-7~6~3 air at @s run setblock ~-7~6~3 sand 0 replace
execute at positioned as @s unless block ~-7~5~3 air at @s run setblock ~-7~5~3 sand 0 replace
execute at positioned as @s unless block ~-7~4~3 air at @s run setblock ~-7~4~3 sand 0 replace
execute at positioned as @s unless block ~-7~3~3 air at @s run setblock ~-7~3~3 sand 0 replace
execute at positioned as @s unless block ~-7~2~3 air at @s run setblock ~-7~2~3 sand 0 replace
execute at positioned as @s unless block ~-7~1~3 air at @s run setblock ~-7~1~3 sand 0 replace
execute at positioned as @s unless block ~-7~0~3 air at @s run setblock ~-7~0~3 sand 0 replace
execute at positioned as @s unless block ~-7~-1~3 air at @s run setblock ~-7~-1~3 sand 0 replace
execute at positioned as @s unless block ~-7~-2~3 air at @s run setblock ~-7~-2~3 sand 0 replace
execute at positioned as @s unless block ~-7~-3~3 air at @s run setblock ~-7~-3~3 sand 0 replace
execute at positioned as @s unless block ~-7~-4~3 air at @s run setblock ~-7~-4~3 sand 0 replace
execute at positioned as @s unless block ~-7~-5~3 air at @s run setblock ~-7~-5~3 sand 0 replace
execute at positioned as @s unless block ~-7~7~4 air at @s run setblock ~-7~7~4 sand 0 replace
execute at positioned as @s unless block ~-7~6~4 air at @s run setblock ~-7~6~4 sand 0 replace
execute at positioned as @s unless block ~-7~5~4 air at @s run setblock ~-7~5~4 sand 0 replace
execute at positioned as @s unless block ~-7~4~4 air at @s run setblock ~-7~4~4 sand 0 replace
execute at positioned as @s unless block ~-7~3~4 air at @s run setblock ~-7~3~4 sand 0 replace
execute at positioned as @s unless block ~-7~2~4 air at @s run setblock ~-7~2~4 sand 0 replace
execute at positioned as @s unless block ~-7~1~4 air at @s run setblock ~-7~1~4 sand 0 replace
execute at positioned as @s unless block ~-7~0~4 air at @s run setblock ~-7~0~4 sand 0 replace
execute at positioned as @s unless block ~-7~-1~4 air at @s run setblock ~-7~-1~4 sand 0 replace
execute at positioned as @s unless block ~-7~-2~4 air at @s run setblock ~-7~-2~4 sand 0 replace
execute at positioned as @s unless block ~-7~-3~4 air at @s run setblock ~-7~-3~4 sand 0 replace
execute at positioned as @s unless block ~-7~-4~4 air at @s run setblock ~-7~-4~4 sand 0 replace
execute at positioned as @s unless block ~-7~-5~4 air at @s run setblock ~-7~-5~4 sand 0 replace
execute at positioned as @s unless block ~-7~7~5 air at @s run setblock ~-7~7~5 sand 0 replace
execute at positioned as @s unless block ~-7~6~5 air at @s run setblock ~-7~6~5 sand 0 replace
execute at positioned as @s unless block ~-7~5~5 air at @s run setblock ~-7~5~5 sand 0 replace
execute at positioned as @s unless block ~-7~4~5 air at @s run setblock ~-7~4~5 sand 0 replace
execute at positioned as @s unless block ~-7~3~5 air at @s run setblock ~-7~3~5 sand 0 replace
execute at positioned as @s unless block ~-7~2~5 air at @s run setblock ~-7~2~5 sand 0 replace
execute at positioned as @s unless block ~-7~1~5 air at @s run setblock ~-7~1~5 sand 0 replace
execute at positioned as @s unless block ~-7~0~5 air at @s run setblock ~-7~0~5 sand 0 replace
execute at positioned as @s unless block ~-7~-1~5 air at @s run setblock ~-7~-1~5 sand 0 replace
execute at positioned as @s unless block ~-7~-2~5 air at @s run setblock ~-7~-2~5 sand 0 replace
execute at positioned as @s unless block ~-7~-3~5 air at @s run setblock ~-7~-3~5 sand 0 replace
execute at positioned as @s unless block ~-7~-4~5 air at @s run setblock ~-7~-4~5 sand 0 replace
execute at positioned as @s unless block ~-7~-5~5 air at @s run setblock ~-7~-5~5 sand 0 replace
execute at positioned as @s unless block ~-7~7~6 air at @s run setblock ~-7~7~6 sand 0 replace
execute at positioned as @s unless block ~-7~6~6 air at @s run setblock ~-7~6~6 sand 0 replace
execute at positioned as @s unless block ~-7~5~6 air at @s run setblock ~-7~5~6 sand 0 replace
execute at positioned as @s unless block ~-7~4~6 air at @s run setblock ~-7~4~6 sand 0 replace
execute at positioned as @s unless block ~-7~3~6 air at @s run setblock ~-7~3~6 sand 0 replace
execute at positioned as @s unless block ~-7~2~6 air at @s run setblock ~-7~2~6 sand 0 replace
execute at positioned as @s unless block ~-7~1~6 air at @s run setblock ~-7~1~6 sand 0 replace
execute at positioned as @s unless block ~-7~0~6 air at @s run setblock ~-7~0~6 sand 0 replace
execute at positioned as @s unless block ~-7~-1~6 air at @s run setblock ~-7~-1~6 sand 0 replace
execute at positioned as @s unless block ~-7~-2~6 air at @s run setblock ~-7~-2~6 sand 0 replace
execute at positioned as @s unless block ~-7~-3~6 air at @s run setblock ~-7~-3~6 sand 0 replace
execute at positioned as @s unless block ~-7~-4~6 air at @s run setblock ~-7~-4~6 sand 0 replace
execute at positioned as @s unless block ~-7~-5~6 air at @s run setblock ~-7~-5~6 sand 0 replace
execute at positioned as @s unless block ~-7~7~7 air at @s run setblock ~-7~7~7 sand 0 replace
execute at positioned as @s unless block ~-7~6~7 air at @s run setblock ~-7~6~7 sand 0 replace
execute at positioned as @s unless block ~-7~5~7 air at @s run setblock ~-7~5~7 sand 0 replace
execute at positioned as @s unless block ~-7~4~7 air at @s run setblock ~-7~4~7 sand 0 replace
execute at positioned as @s unless block ~-7~3~7 air at @s run setblock ~-7~3~7 sand 0 replace
execute at positioned as @s unless block ~-7~2~7 air at @s run setblock ~-7~2~7 sand 0 replace
execute at positioned as @s unless block ~-7~1~7 air at @s run setblock ~-7~1~7 sand 0 replace
execute at positioned as @s unless block ~-7~0~7 air at @s run setblock ~-7~0~7 sand 0 replace
execute at positioned as @s unless block ~-7~-1~7 air at @s run setblock ~-7~-1~7 sand 0 replace
execute at positioned as @s unless block ~-7~-2~7 air at @s run setblock ~-7~-2~7 sand 0 replace
execute at positioned as @s unless block ~-7~-3~7 air at @s run setblock ~-7~-3~7 sand 0 replace
execute at positioned as @s unless block ~-7~-4~7 air at @s run setblock ~-7~-4~7 sand 0 replace
execute at positioned as @s unless block ~-7~-5~7 air at @s run setblock ~-7~-5~7 sand 0 replace
execute at positioned as @s unless block ~-6~7~-7 air at @s run setblock ~-6~7~-7 sand 0 replace
execute at positioned as @s unless block ~-6~6~-7 air at @s run setblock ~-6~6~-7 sand 0 replace
execute at positioned as @s unless block ~-6~5~-7 air at @s run setblock ~-6~5~-7 sand 0 replace
execute at positioned as @s unless block ~-6~4~-7 air at @s run setblock ~-6~4~-7 sand 0 replace
execute at positioned as @s unless block ~-6~3~-7 air at @s run setblock ~-6~3~-7 sand 0 replace
execute at positioned as @s unless block ~-6~2~-7 air at @s run setblock ~-6~2~-7 sand 0 replace
execute at positioned as @s unless block ~-6~1~-7 air at @s run setblock ~-6~1~-7 sand 0 replace
execute at positioned as @s unless block ~-6~0~-7 air at @s run setblock ~-6~0~-7 sand 0 replace
execute at positioned as @s unless block ~-6~-1~-7 air at @s run setblock ~-6~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-6~-2~-7 air at @s run setblock ~-6~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-6~-3~-7 air at @s run setblock ~-6~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-6~-4~-7 air at @s run setblock ~-6~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-6~-5~-7 air at @s run setblock ~-6~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-6~7~7 air at @s run setblock ~-6~7~7 sand 0 replace
execute at positioned as @s unless block ~-6~6~7 air at @s run setblock ~-6~6~7 sand 0 replace
execute at positioned as @s unless block ~-6~5~7 air at @s run setblock ~-6~5~7 sand 0 replace
execute at positioned as @s unless block ~-6~4~7 air at @s run setblock ~-6~4~7 sand 0 replace
execute at positioned as @s unless block ~-6~3~7 air at @s run setblock ~-6~3~7 sand 0 replace
execute at positioned as @s unless block ~-6~2~7 air at @s run setblock ~-6~2~7 sand 0 replace
execute at positioned as @s unless block ~-6~1~7 air at @s run setblock ~-6~1~7 sand 0 replace
execute at positioned as @s unless block ~-6~0~7 air at @s run setblock ~-6~0~7 sand 0 replace
execute at positioned as @s unless block ~-6~-1~7 air at @s run setblock ~-6~-1~7 sand 0 replace
execute at positioned as @s unless block ~-6~-2~7 air at @s run setblock ~-6~-2~7 sand 0 replace
execute at positioned as @s unless block ~-6~-3~7 air at @s run setblock ~-6~-3~7 sand 0 replace
execute at positioned as @s unless block ~-6~-4~7 air at @s run setblock ~-6~-4~7 sand 0 replace
execute at positioned as @s unless block ~-6~-5~7 air at @s run setblock ~-6~-5~7 sand 0 replace
execute at positioned as @s unless block ~-5~7~-7 air at @s run setblock ~-5~7~-7 sand 0 replace
execute at positioned as @s unless block ~-5~6~-7 air at @s run setblock ~-5~6~-7 sand 0 replace
execute at positioned as @s unless block ~-5~5~-7 air at @s run setblock ~-5~5~-7 sand 0 replace
execute at positioned as @s unless block ~-5~4~-7 air at @s run setblock ~-5~4~-7 sand 0 replace
execute at positioned as @s unless block ~-5~3~-7 air at @s run setblock ~-5~3~-7 sand 0 replace
execute at positioned as @s unless block ~-5~2~-7 air at @s run setblock ~-5~2~-7 sand 0 replace
execute at positioned as @s unless block ~-5~1~-7 air at @s run setblock ~-5~1~-7 sand 0 replace
execute at positioned as @s unless block ~-5~0~-7 air at @s run setblock ~-5~0~-7 sand 0 replace
execute at positioned as @s unless block ~-5~-1~-7 air at @s run setblock ~-5~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-5~-2~-7 air at @s run setblock ~-5~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-5~-3~-7 air at @s run setblock ~-5~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-5~-4~-7 air at @s run setblock ~-5~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-5~-5~-7 air at @s run setblock ~-5~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-5~7~7 air at @s run setblock ~-5~7~7 sand 0 replace
execute at positioned as @s unless block ~-5~6~7 air at @s run setblock ~-5~6~7 sand 0 replace
execute at positioned as @s unless block ~-5~5~7 air at @s run setblock ~-5~5~7 sand 0 replace
execute at positioned as @s unless block ~-5~4~7 air at @s run setblock ~-5~4~7 sand 0 replace
execute at positioned as @s unless block ~-5~3~7 air at @s run setblock ~-5~3~7 sand 0 replace
execute at positioned as @s unless block ~-5~2~7 air at @s run setblock ~-5~2~7 sand 0 replace
execute at positioned as @s unless block ~-5~1~7 air at @s run setblock ~-5~1~7 sand 0 replace
execute at positioned as @s unless block ~-5~0~7 air at @s run setblock ~-5~0~7 sand 0 replace
execute at positioned as @s unless block ~-5~-1~7 air at @s run setblock ~-5~-1~7 sand 0 replace
execute at positioned as @s unless block ~-5~-2~7 air at @s run setblock ~-5~-2~7 sand 0 replace
execute at positioned as @s unless block ~-5~-3~7 air at @s run setblock ~-5~-3~7 sand 0 replace
execute at positioned as @s unless block ~-5~-4~7 air at @s run setblock ~-5~-4~7 sand 0 replace
execute at positioned as @s unless block ~-5~-5~7 air at @s run setblock ~-5~-5~7 sand 0 replace
execute at positioned as @s unless block ~-4~7~-7 air at @s run setblock ~-4~7~-7 sand 0 replace
execute at positioned as @s unless block ~-4~6~-7 air at @s run setblock ~-4~6~-7 sand 0 replace
execute at positioned as @s unless block ~-4~5~-7 air at @s run setblock ~-4~5~-7 sand 0 replace
execute at positioned as @s unless block ~-4~4~-7 air at @s run setblock ~-4~4~-7 sand 0 replace
execute at positioned as @s unless block ~-4~3~-7 air at @s run setblock ~-4~3~-7 sand 0 replace
execute at positioned as @s unless block ~-4~2~-7 air at @s run setblock ~-4~2~-7 sand 0 replace
execute at positioned as @s unless block ~-4~1~-7 air at @s run setblock ~-4~1~-7 sand 0 replace
execute at positioned as @s unless block ~-4~0~-7 air at @s run setblock ~-4~0~-7 sand 0 replace
execute at positioned as @s unless block ~-4~-1~-7 air at @s run setblock ~-4~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-4~-2~-7 air at @s run setblock ~-4~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-4~-3~-7 air at @s run setblock ~-4~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-4~-4~-7 air at @s run setblock ~-4~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-4~-5~-7 air at @s run setblock ~-4~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-4~7~7 air at @s run setblock ~-4~7~7 sand 0 replace
execute at positioned as @s unless block ~-4~6~7 air at @s run setblock ~-4~6~7 sand 0 replace
execute at positioned as @s unless block ~-4~5~7 air at @s run setblock ~-4~5~7 sand 0 replace
execute at positioned as @s unless block ~-4~4~7 air at @s run setblock ~-4~4~7 sand 0 replace
execute at positioned as @s unless block ~-4~3~7 air at @s run setblock ~-4~3~7 sand 0 replace
execute at positioned as @s unless block ~-4~2~7 air at @s run setblock ~-4~2~7 sand 0 replace
execute at positioned as @s unless block ~-4~1~7 air at @s run setblock ~-4~1~7 sand 0 replace
execute at positioned as @s unless block ~-4~0~7 air at @s run setblock ~-4~0~7 sand 0 replace
execute at positioned as @s unless block ~-4~-1~7 air at @s run setblock ~-4~-1~7 sand 0 replace
execute at positioned as @s unless block ~-4~-2~7 air at @s run setblock ~-4~-2~7 sand 0 replace
execute at positioned as @s unless block ~-4~-3~7 air at @s run setblock ~-4~-3~7 sand 0 replace
execute at positioned as @s unless block ~-4~-4~7 air at @s run setblock ~-4~-4~7 sand 0 replace
execute at positioned as @s unless block ~-4~-5~7 air at @s run setblock ~-4~-5~7 sand 0 replace
execute at positioned as @s unless block ~-3~7~-7 air at @s run setblock ~-3~7~-7 sand 0 replace
execute at positioned as @s unless block ~-3~6~-7 air at @s run setblock ~-3~6~-7 sand 0 replace
execute at positioned as @s unless block ~-3~5~-7 air at @s run setblock ~-3~5~-7 sand 0 replace
execute at positioned as @s unless block ~-3~4~-7 air at @s run setblock ~-3~4~-7 sand 0 replace
execute at positioned as @s unless block ~-3~3~-7 air at @s run setblock ~-3~3~-7 sand 0 replace
execute at positioned as @s unless block ~-3~2~-7 air at @s run setblock ~-3~2~-7 sand 0 replace
execute at positioned as @s unless block ~-3~1~-7 air at @s run setblock ~-3~1~-7 sand 0 replace
execute at positioned as @s unless block ~-3~0~-7 air at @s run setblock ~-3~0~-7 sand 0 replace
execute at positioned as @s unless block ~-3~-1~-7 air at @s run setblock ~-3~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-3~-2~-7 air at @s run setblock ~-3~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-3~-3~-7 air at @s run setblock ~-3~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-3~-4~-7 air at @s run setblock ~-3~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-3~-5~-7 air at @s run setblock ~-3~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-3~7~7 air at @s run setblock ~-3~7~7 sand 0 replace
execute at positioned as @s unless block ~-3~6~7 air at @s run setblock ~-3~6~7 sand 0 replace
execute at positioned as @s unless block ~-3~5~7 air at @s run setblock ~-3~5~7 sand 0 replace
execute at positioned as @s unless block ~-3~4~7 air at @s run setblock ~-3~4~7 sand 0 replace
execute at positioned as @s unless block ~-3~3~7 air at @s run setblock ~-3~3~7 sand 0 replace
execute at positioned as @s unless block ~-3~2~7 air at @s run setblock ~-3~2~7 sand 0 replace
execute at positioned as @s unless block ~-3~1~7 air at @s run setblock ~-3~1~7 sand 0 replace
execute at positioned as @s unless block ~-3~0~7 air at @s run setblock ~-3~0~7 sand 0 replace
execute at positioned as @s unless block ~-3~-1~7 air at @s run setblock ~-3~-1~7 sand 0 replace
execute at positioned as @s unless block ~-3~-2~7 air at @s run setblock ~-3~-2~7 sand 0 replace
execute at positioned as @s unless block ~-3~-3~7 air at @s run setblock ~-3~-3~7 sand 0 replace
execute at positioned as @s unless block ~-3~-4~7 air at @s run setblock ~-3~-4~7 sand 0 replace
execute at positioned as @s unless block ~-3~-5~7 air at @s run setblock ~-3~-5~7 sand 0 replace
execute at positioned as @s unless block ~-2~7~-7 air at @s run setblock ~-2~7~-7 sand 0 replace
execute at positioned as @s unless block ~-2~6~-7 air at @s run setblock ~-2~6~-7 sand 0 replace
execute at positioned as @s unless block ~-2~5~-7 air at @s run setblock ~-2~5~-7 sand 0 replace
execute at positioned as @s unless block ~-2~4~-7 air at @s run setblock ~-2~4~-7 sand 0 replace
execute at positioned as @s unless block ~-2~3~-7 air at @s run setblock ~-2~3~-7 sand 0 replace
execute at positioned as @s unless block ~-2~2~-7 air at @s run setblock ~-2~2~-7 sand 0 replace
execute at positioned as @s unless block ~-2~1~-7 air at @s run setblock ~-2~1~-7 sand 0 replace
execute at positioned as @s unless block ~-2~0~-7 air at @s run setblock ~-2~0~-7 sand 0 replace
execute at positioned as @s unless block ~-2~-1~-7 air at @s run setblock ~-2~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-2~-2~-7 air at @s run setblock ~-2~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-2~-3~-7 air at @s run setblock ~-2~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-2~-4~-7 air at @s run setblock ~-2~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-2~-5~-7 air at @s run setblock ~-2~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-2~7~7 air at @s run setblock ~-2~7~7 sand 0 replace
execute at positioned as @s unless block ~-2~6~7 air at @s run setblock ~-2~6~7 sand 0 replace
execute at positioned as @s unless block ~-2~5~7 air at @s run setblock ~-2~5~7 sand 0 replace
execute at positioned as @s unless block ~-2~4~7 air at @s run setblock ~-2~4~7 sand 0 replace
execute at positioned as @s unless block ~-2~3~7 air at @s run setblock ~-2~3~7 sand 0 replace
execute at positioned as @s unless block ~-2~2~7 air at @s run setblock ~-2~2~7 sand 0 replace
execute at positioned as @s unless block ~-2~1~7 air at @s run setblock ~-2~1~7 sand 0 replace
execute at positioned as @s unless block ~-2~0~7 air at @s run setblock ~-2~0~7 sand 0 replace
execute at positioned as @s unless block ~-2~-1~7 air at @s run setblock ~-2~-1~7 sand 0 replace
execute at positioned as @s unless block ~-2~-2~7 air at @s run setblock ~-2~-2~7 sand 0 replace
execute at positioned as @s unless block ~-2~-3~7 air at @s run setblock ~-2~-3~7 sand 0 replace
execute at positioned as @s unless block ~-2~-4~7 air at @s run setblock ~-2~-4~7 sand 0 replace
execute at positioned as @s unless block ~-2~-5~7 air at @s run setblock ~-2~-5~7 sand 0 replace
execute at positioned as @s unless block ~-1~7~-7 air at @s run setblock ~-1~7~-7 sand 0 replace
execute at positioned as @s unless block ~-1~6~-7 air at @s run setblock ~-1~6~-7 sand 0 replace
execute at positioned as @s unless block ~-1~5~-7 air at @s run setblock ~-1~5~-7 sand 0 replace
execute at positioned as @s unless block ~-1~4~-7 air at @s run setblock ~-1~4~-7 sand 0 replace
execute at positioned as @s unless block ~-1~3~-7 air at @s run setblock ~-1~3~-7 sand 0 replace
execute at positioned as @s unless block ~-1~2~-7 air at @s run setblock ~-1~2~-7 sand 0 replace
execute at positioned as @s unless block ~-1~1~-7 air at @s run setblock ~-1~1~-7 sand 0 replace
execute at positioned as @s unless block ~-1~0~-7 air at @s run setblock ~-1~0~-7 sand 0 replace
execute at positioned as @s unless block ~-1~-1~-7 air at @s run setblock ~-1~-1~-7 sand 0 replace
execute at positioned as @s unless block ~-1~-2~-7 air at @s run setblock ~-1~-2~-7 sand 0 replace
execute at positioned as @s unless block ~-1~-3~-7 air at @s run setblock ~-1~-3~-7 sand 0 replace
execute at positioned as @s unless block ~-1~-4~-7 air at @s run setblock ~-1~-4~-7 sand 0 replace
execute at positioned as @s unless block ~-1~-5~-7 air at @s run setblock ~-1~-5~-7 sand 0 replace
execute at positioned as @s unless block ~-1~7~7 air at @s run setblock ~-1~7~7 sand 0 replace
execute at positioned as @s unless block ~-1~6~7 air at @s run setblock ~-1~6~7 sand 0 replace
execute at positioned as @s unless block ~-1~5~7 air at @s run setblock ~-1~5~7 sand 0 replace
execute at positioned as @s unless block ~-1~4~7 air at @s run setblock ~-1~4~7 sand 0 replace
execute at positioned as @s unless block ~-1~3~7 air at @s run setblock ~-1~3~7 sand 0 replace
execute at positioned as @s unless block ~-1~2~7 air at @s run setblock ~-1~2~7 sand 0 replace
execute at positioned as @s unless block ~-1~1~7 air at @s run setblock ~-1~1~7 sand 0 replace
execute at positioned as @s unless block ~-1~0~7 air at @s run setblock ~-1~0~7 sand 0 replace
execute at positioned as @s unless block ~-1~-1~7 air at @s run setblock ~-1~-1~7 sand 0 replace
execute at positioned as @s unless block ~-1~-2~7 air at @s run setblock ~-1~-2~7 sand 0 replace
execute at positioned as @s unless block ~-1~-3~7 air at @s run setblock ~-1~-3~7 sand 0 replace
execute at positioned as @s unless block ~-1~-4~7 air at @s run setblock ~-1~-4~7 sand 0 replace
execute at positioned as @s unless block ~-1~-5~7 air at @s run setblock ~-1~-5~7 sand 0 replace
execute at positioned as @s unless block ~0~7~-7 air at @s run setblock ~0~7~-7 sand 0 replace
execute at positioned as @s unless block ~0~6~-7 air at @s run setblock ~0~6~-7 sand 0 replace
execute at positioned as @s unless block ~0~5~-7 air at @s run setblock ~0~5~-7 sand 0 replace
execute at positioned as @s unless block ~0~4~-7 air at @s run setblock ~0~4~-7 sand 0 replace
execute at positioned as @s unless block ~0~3~-7 air at @s run setblock ~0~3~-7 sand 0 replace
execute at positioned as @s unless block ~0~2~-7 air at @s run setblock ~0~2~-7 sand 0 replace
execute at positioned as @s unless block ~0~1~-7 air at @s run setblock ~0~1~-7 sand 0 replace
execute at positioned as @s unless block ~0~0~-7 air at @s run setblock ~0~0~-7 sand 0 replace
execute at positioned as @s unless block ~0~-1~-7 air at @s run setblock ~0~-1~-7 sand 0 replace
execute at positioned as @s unless block ~0~-2~-7 air at @s run setblock ~0~-2~-7 sand 0 replace
execute at positioned as @s unless block ~0~-3~-7 air at @s run setblock ~0~-3~-7 sand 0 replace
execute at positioned as @s unless block ~0~-4~-7 air at @s run setblock ~0~-4~-7 sand 0 replace
execute at positioned as @s unless block ~0~-5~-7 air at @s run setblock ~0~-5~-7 sand 0 replace
execute at positioned as @s unless block ~0~7~7 air at @s run setblock ~0~7~7 sand 0 replace
execute at positioned as @s unless block ~0~6~7 air at @s run setblock ~0~6~7 sand 0 replace
execute at positioned as @s unless block ~0~5~7 air at @s run setblock ~0~5~7 sand 0 replace
execute at positioned as @s unless block ~0~4~7 air at @s run setblock ~0~4~7 sand 0 replace
execute at positioned as @s unless block ~0~3~7 air at @s run setblock ~0~3~7 sand 0 replace
execute at positioned as @s unless block ~0~2~7 air at @s run setblock ~0~2~7 sand 0 replace
execute at positioned as @s unless block ~0~1~7 air at @s run setblock ~0~1~7 sand 0 replace
execute at positioned as @s unless block ~0~0~7 air at @s run setblock ~0~0~7 sand 0 replace
execute at positioned as @s unless block ~0~-1~7 air at @s run setblock ~0~-1~7 sand 0 replace
execute at positioned as @s unless block ~0~-2~7 air at @s run setblock ~0~-2~7 sand 0 replace
execute at positioned as @s unless block ~0~-3~7 air at @s run setblock ~0~-3~7 sand 0 replace
execute at positioned as @s unless block ~0~-4~7 air at @s run setblock ~0~-4~7 sand 0 replace
execute at positioned as @s unless block ~0~-5~7 air at @s run setblock ~0~-5~7 sand 0 replace
execute at positioned as @s unless block ~1~7~-7 air at @s run setblock ~1~7~-7 sand 0 replace
execute at positioned as @s unless block ~1~6~-7 air at @s run setblock ~1~6~-7 sand 0 replace
execute at positioned as @s unless block ~1~5~-7 air at @s run setblock ~1~5~-7 sand 0 replace
execute at positioned as @s unless block ~1~4~-7 air at @s run setblock ~1~4~-7 sand 0 replace
execute at positioned as @s unless block ~1~3~-7 air at @s run setblock ~1~3~-7 sand 0 replace
execute at positioned as @s unless block ~1~2~-7 air at @s run setblock ~1~2~-7 sand 0 replace
execute at positioned as @s unless block ~1~1~-7 air at @s run setblock ~1~1~-7 sand 0 replace
execute at positioned as @s unless block ~1~0~-7 air at @s run setblock ~1~0~-7 sand 0 replace
execute at positioned as @s unless block ~1~-1~-7 air at @s run setblock ~1~-1~-7 sand 0 replace
execute at positioned as @s unless block ~1~-2~-7 air at @s run setblock ~1~-2~-7 sand 0 replace
execute at positioned as @s unless block ~1~-3~-7 air at @s run setblock ~1~-3~-7 sand 0 replace
execute at positioned as @s unless block ~1~-4~-7 air at @s run setblock ~1~-4~-7 sand 0 replace
execute at positioned as @s unless block ~1~-5~-7 air at @s run setblock ~1~-5~-7 sand 0 replace
execute at positioned as @s unless block ~1~7~7 air at @s run setblock ~1~7~7 sand 0 replace
execute at positioned as @s unless block ~1~6~7 air at @s run setblock ~1~6~7 sand 0 replace
execute at positioned as @s unless block ~1~5~7 air at @s run setblock ~1~5~7 sand 0 replace
execute at positioned as @s unless block ~1~4~7 air at @s run setblock ~1~4~7 sand 0 replace
execute at positioned as @s unless block ~1~3~7 air at @s run setblock ~1~3~7 sand 0 replace
execute at positioned as @s unless block ~1~2~7 air at @s run setblock ~1~2~7 sand 0 replace
execute at positioned as @s unless block ~1~1~7 air at @s run setblock ~1~1~7 sand 0 replace
execute at positioned as @s unless block ~1~0~7 air at @s run setblock ~1~0~7 sand 0 replace
execute at positioned as @s unless block ~1~-1~7 air at @s run setblock ~1~-1~7 sand 0 replace
execute at positioned as @s unless block ~1~-2~7 air at @s run setblock ~1~-2~7 sand 0 replace
execute at positioned as @s unless block ~1~-3~7 air at @s run setblock ~1~-3~7 sand 0 replace
execute at positioned as @s unless block ~1~-4~7 air at @s run setblock ~1~-4~7 sand 0 replace
execute at positioned as @s unless block ~1~-5~7 air at @s run setblock ~1~-5~7 sand 0 replace
execute at positioned as @s unless block ~2~7~-7 air at @s run setblock ~2~7~-7 sand 0 replace
execute at positioned as @s unless block ~2~6~-7 air at @s run setblock ~2~6~-7 sand 0 replace
execute at positioned as @s unless block ~2~5~-7 air at @s run setblock ~2~5~-7 sand 0 replace
execute at positioned as @s unless block ~2~4~-7 air at @s run setblock ~2~4~-7 sand 0 replace
execute at positioned as @s unless block ~2~3~-7 air at @s run setblock ~2~3~-7 sand 0 replace
execute at positioned as @s unless block ~2~2~-7 air at @s run setblock ~2~2~-7 sand 0 replace
execute at positioned as @s unless block ~2~1~-7 air at @s run setblock ~2~1~-7 sand 0 replace
execute at positioned as @s unless block ~2~0~-7 air at @s run setblock ~2~0~-7 sand 0 replace
execute at positioned as @s unless block ~2~-1~-7 air at @s run setblock ~2~-1~-7 sand 0 replace
execute at positioned as @s unless block ~2~-2~-7 air at @s run setblock ~2~-2~-7 sand 0 replace
execute at positioned as @s unless block ~2~-3~-7 air at @s run setblock ~2~-3~-7 sand 0 replace
execute at positioned as @s unless block ~2~-4~-7 air at @s run setblock ~2~-4~-7 sand 0 replace
execute at positioned as @s unless block ~2~-5~-7 air at @s run setblock ~2~-5~-7 sand 0 replace
execute at positioned as @s unless block ~2~7~7 air at @s run setblock ~2~7~7 sand 0 replace
execute at positioned as @s unless block ~2~6~7 air at @s run setblock ~2~6~7 sand 0 replace
execute at positioned as @s unless block ~2~5~7 air at @s run setblock ~2~5~7 sand 0 replace
execute at positioned as @s unless block ~2~4~7 air at @s run setblock ~2~4~7 sand 0 replace
execute at positioned as @s unless block ~2~3~7 air at @s run setblock ~2~3~7 sand 0 replace
execute at positioned as @s unless block ~2~2~7 air at @s run setblock ~2~2~7 sand 0 replace
execute at positioned as @s unless block ~2~1~7 air at @s run setblock ~2~1~7 sand 0 replace
execute at positioned as @s unless block ~2~0~7 air at @s run setblock ~2~0~7 sand 0 replace
execute at positioned as @s unless block ~2~-1~7 air at @s run setblock ~2~-1~7 sand 0 replace
execute at positioned as @s unless block ~2~-2~7 air at @s run setblock ~2~-2~7 sand 0 replace
execute at positioned as @s unless block ~2~-3~7 air at @s run setblock ~2~-3~7 sand 0 replace
execute at positioned as @s unless block ~2~-4~7 air at @s run setblock ~2~-4~7 sand 0 replace
execute at positioned as @s unless block ~2~-5~7 air at @s run setblock ~2~-5~7 sand 0 replace
execute at positioned as @s unless block ~3~7~-7 air at @s run setblock ~3~7~-7 sand 0 replace
execute at positioned as @s unless block ~3~6~-7 air at @s run setblock ~3~6~-7 sand 0 replace
execute at positioned as @s unless block ~3~5~-7 air at @s run setblock ~3~5~-7 sand 0 replace
execute at positioned as @s unless block ~3~4~-7 air at @s run setblock ~3~4~-7 sand 0 replace
execute at positioned as @s unless block ~3~3~-7 air at @s run setblock ~3~3~-7 sand 0 replace
execute at positioned as @s unless block ~3~2~-7 air at @s run setblock ~3~2~-7 sand 0 replace
execute at positioned as @s unless block ~3~1~-7 air at @s run setblock ~3~1~-7 sand 0 replace
execute at positioned as @s unless block ~3~0~-7 air at @s run setblock ~3~0~-7 sand 0 replace
execute at positioned as @s unless block ~3~-1~-7 air at @s run setblock ~3~-1~-7 sand 0 replace
execute at positioned as @s unless block ~3~-2~-7 air at @s run setblock ~3~-2~-7 sand 0 replace
execute at positioned as @s unless block ~3~-3~-7 air at @s run setblock ~3~-3~-7 sand 0 replace
execute at positioned as @s unless block ~3~-4~-7 air at @s run setblock ~3~-4~-7 sand 0 replace
execute at positioned as @s unless block ~3~-5~-7 air at @s run setblock ~3~-5~-7 sand 0 replace
execute at positioned as @s unless block ~3~7~7 air at @s run setblock ~3~7~7 sand 0 replace
execute at positioned as @s unless block ~3~6~7 air at @s run setblock ~3~6~7 sand 0 replace
execute at positioned as @s unless block ~3~5~7 air at @s run setblock ~3~5~7 sand 0 replace
execute at positioned as @s unless block ~3~4~7 air at @s run setblock ~3~4~7 sand 0 replace
execute at positioned as @s unless block ~3~3~7 air at @s run setblock ~3~3~7 sand 0 replace
execute at positioned as @s unless block ~3~2~7 air at @s run setblock ~3~2~7 sand 0 replace
execute at positioned as @s unless block ~3~1~7 air at @s run setblock ~3~1~7 sand 0 replace
execute at positioned as @s unless block ~3~0~7 air at @s run setblock ~3~0~7 sand 0 replace
execute at positioned as @s unless block ~3~-1~7 air at @s run setblock ~3~-1~7 sand 0 replace
execute at positioned as @s unless block ~3~-2~7 air at @s run setblock ~3~-2~7 sand 0 replace
execute at positioned as @s unless block ~3~-3~7 air at @s run setblock ~3~-3~7 sand 0 replace
execute at positioned as @s unless block ~3~-4~7 air at @s run setblock ~3~-4~7 sand 0 replace
execute at positioned as @s unless block ~3~-5~7 air at @s run setblock ~3~-5~7 sand 0 replace
execute at positioned as @s unless block ~4~7~-7 air at @s run setblock ~4~7~-7 sand 0 replace
execute at positioned as @s unless block ~4~6~-7 air at @s run setblock ~4~6~-7 sand 0 replace
execute at positioned as @s unless block ~4~5~-7 air at @s run setblock ~4~5~-7 sand 0 replace
execute at positioned as @s unless block ~4~4~-7 air at @s run setblock ~4~4~-7 sand 0 replace
execute at positioned as @s unless block ~4~3~-7 air at @s run setblock ~4~3~-7 sand 0 replace
execute at positioned as @s unless block ~4~2~-7 air at @s run setblock ~4~2~-7 sand 0 replace
execute at positioned as @s unless block ~4~1~-7 air at @s run setblock ~4~1~-7 sand 0 replace
execute at positioned as @s unless block ~4~0~-7 air at @s run setblock ~4~0~-7 sand 0 replace
execute at positioned as @s unless block ~4~-1~-7 air at @s run setblock ~4~-1~-7 sand 0 replace
execute at positioned as @s unless block ~4~-2~-7 air at @s run setblock ~4~-2~-7 sand 0 replace
execute at positioned as @s unless block ~4~-3~-7 air at @s run setblock ~4~-3~-7 sand 0 replace
execute at positioned as @s unless block ~4~-4~-7 air at @s run setblock ~4~-4~-7 sand 0 replace
execute at positioned as @s unless block ~4~-5~-7 air at @s run setblock ~4~-5~-7 sand 0 replace
execute at positioned as @s unless block ~4~7~7 air at @s run setblock ~4~7~7 sand 0 replace
execute at positioned as @s unless block ~4~6~7 air at @s run setblock ~4~6~7 sand 0 replace
execute at positioned as @s unless block ~4~5~7 air at @s run setblock ~4~5~7 sand 0 replace
execute at positioned as @s unless block ~4~4~7 air at @s run setblock ~4~4~7 sand 0 replace
execute at positioned as @s unless block ~4~3~7 air at @s run setblock ~4~3~7 sand 0 replace
execute at positioned as @s unless block ~4~2~7 air at @s run setblock ~4~2~7 sand 0 replace
execute at positioned as @s unless block ~4~1~7 air at @s run setblock ~4~1~7 sand 0 replace
execute at positioned as @s unless block ~4~0~7 air at @s run setblock ~4~0~7 sand 0 replace
execute at positioned as @s unless block ~4~-1~7 air at @s run setblock ~4~-1~7 sand 0 replace
execute at positioned as @s unless block ~4~-2~7 air at @s run setblock ~4~-2~7 sand 0 replace
execute at positioned as @s unless block ~4~-3~7 air at @s run setblock ~4~-3~7 sand 0 replace
execute at positioned as @s unless block ~4~-4~7 air at @s run setblock ~4~-4~7 sand 0 replace
execute at positioned as @s unless block ~4~-5~7 air at @s run setblock ~4~-5~7 sand 0 replace
execute at positioned as @s unless block ~5~7~-7 air at @s run setblock ~5~7~-7 sand 0 replace
execute at positioned as @s unless block ~5~6~-7 air at @s run setblock ~5~6~-7 sand 0 replace
execute at positioned as @s unless block ~5~5~-7 air at @s run setblock ~5~5~-7 sand 0 replace
execute at positioned as @s unless block ~5~4~-7 air at @s run setblock ~5~4~-7 sand 0 replace
execute at positioned as @s unless block ~5~3~-7 air at @s run setblock ~5~3~-7 sand 0 replace
execute at positioned as @s unless block ~5~2~-7 air at @s run setblock ~5~2~-7 sand 0 replace
execute at positioned as @s unless block ~5~1~-7 air at @s run setblock ~5~1~-7 sand 0 replace
execute at positioned as @s unless block ~5~0~-7 air at @s run setblock ~5~0~-7 sand 0 replace
execute at positioned as @s unless block ~5~-1~-7 air at @s run setblock ~5~-1~-7 sand 0 replace
execute at positioned as @s unless block ~5~-2~-7 air at @s run setblock ~5~-2~-7 sand 0 replace
execute at positioned as @s unless block ~5~-3~-7 air at @s run setblock ~5~-3~-7 sand 0 replace
execute at positioned as @s unless block ~5~-4~-7 air at @s run setblock ~5~-4~-7 sand 0 replace
execute at positioned as @s unless block ~5~-5~-7 air at @s run setblock ~5~-5~-7 sand 0 replace
execute at positioned as @s unless block ~5~7~7 air at @s run setblock ~5~7~7 sand 0 replace
execute at positioned as @s unless block ~5~6~7 air at @s run setblock ~5~6~7 sand 0 replace
execute at positioned as @s unless block ~5~5~7 air at @s run setblock ~5~5~7 sand 0 replace
execute at positioned as @s unless block ~5~4~7 air at @s run setblock ~5~4~7 sand 0 replace
execute at positioned as @s unless block ~5~3~7 air at @s run setblock ~5~3~7 sand 0 replace
execute at positioned as @s unless block ~5~2~7 air at @s run setblock ~5~2~7 sand 0 replace
execute at positioned as @s unless block ~5~1~7 air at @s run setblock ~5~1~7 sand 0 replace
execute at positioned as @s unless block ~5~0~7 air at @s run setblock ~5~0~7 sand 0 replace
execute at positioned as @s unless block ~5~-1~7 air at @s run setblock ~5~-1~7 sand 0 replace
execute at positioned as @s unless block ~5~-2~7 air at @s run setblock ~5~-2~7 sand 0 replace
execute at positioned as @s unless block ~5~-3~7 air at @s run setblock ~5~-3~7 sand 0 replace
execute at positioned as @s unless block ~5~-4~7 air at @s run setblock ~5~-4~7 sand 0 replace
execute at positioned as @s unless block ~5~-5~7 air at @s run setblock ~5~-5~7 sand 0 replace
execute at positioned as @s unless block ~6~7~-7 air at @s run setblock ~6~7~-7 sand 0 replace
execute at positioned as @s unless block ~6~6~-7 air at @s run setblock ~6~6~-7 sand 0 replace
execute at positioned as @s unless block ~6~5~-7 air at @s run setblock ~6~5~-7 sand 0 replace
execute at positioned as @s unless block ~6~4~-7 air at @s run setblock ~6~4~-7 sand 0 replace
execute at positioned as @s unless block ~6~3~-7 air at @s run setblock ~6~3~-7 sand 0 replace
execute at positioned as @s unless block ~6~2~-7 air at @s run setblock ~6~2~-7 sand 0 replace
execute at positioned as @s unless block ~6~1~-7 air at @s run setblock ~6~1~-7 sand 0 replace
execute at positioned as @s unless block ~6~0~-7 air at @s run setblock ~6~0~-7 sand 0 replace
execute at positioned as @s unless block ~6~-1~-7 air at @s run setblock ~6~-1~-7 sand 0 replace
execute at positioned as @s unless block ~6~-2~-7 air at @s run setblock ~6~-2~-7 sand 0 replace
execute at positioned as @s unless block ~6~-3~-7 air at @s run setblock ~6~-3~-7 sand 0 replace
execute at positioned as @s unless block ~6~-4~-7 air at @s run setblock ~6~-4~-7 sand 0 replace
execute at positioned as @s unless block ~6~-5~-7 air at @s run setblock ~6~-5~-7 sand 0 replace
execute at positioned as @s unless block ~6~7~7 air at @s run setblock ~6~7~7 sand 0 replace
execute at positioned as @s unless block ~6~6~7 air at @s run setblock ~6~6~7 sand 0 replace
execute at positioned as @s unless block ~6~5~7 air at @s run setblock ~6~5~7 sand 0 replace
execute at positioned as @s unless block ~6~4~7 air at @s run setblock ~6~4~7 sand 0 replace
execute at positioned as @s unless block ~6~3~7 air at @s run setblock ~6~3~7 sand 0 replace
execute at positioned as @s unless block ~6~2~7 air at @s run setblock ~6~2~7 sand 0 replace
execute at positioned as @s unless block ~6~1~7 air at @s run setblock ~6~1~7 sand 0 replace
execute at positioned as @s unless block ~6~0~7 air at @s run setblock ~6~0~7 sand 0 replace
execute at positioned as @s unless block ~6~-1~7 air at @s run setblock ~6~-1~7 sand 0 replace
execute at positioned as @s unless block ~6~-2~7 air at @s run setblock ~6~-2~7 sand 0 replace
execute at positioned as @s unless block ~6~-3~7 air at @s run setblock ~6~-3~7 sand 0 replace
execute at positioned as @s unless block ~6~-4~7 air at @s run setblock ~6~-4~7 sand 0 replace
execute at positioned as @s unless block ~6~-5~7 air at @s run setblock ~6~-5~7 sand 0 replace
execute at positioned as @s unless block ~7~7~-7 air at @s run setblock ~7~7~-7 sand 0 replace
execute at positioned as @s unless block ~7~6~-7 air at @s run setblock ~7~6~-7 sand 0 replace
execute at positioned as @s unless block ~7~5~-7 air at @s run setblock ~7~5~-7 sand 0 replace
execute at positioned as @s unless block ~7~4~-7 air at @s run setblock ~7~4~-7 sand 0 replace
execute at positioned as @s unless block ~7~3~-7 air at @s run setblock ~7~3~-7 sand 0 replace
execute at positioned as @s unless block ~7~2~-7 air at @s run setblock ~7~2~-7 sand 0 replace
execute at positioned as @s unless block ~7~1~-7 air at @s run setblock ~7~1~-7 sand 0 replace
execute at positioned as @s unless block ~7~0~-7 air at @s run setblock ~7~0~-7 sand 0 replace
execute at positioned as @s unless block ~7~-1~-7 air at @s run setblock ~7~-1~-7 sand 0 replace
execute at positioned as @s unless block ~7~-2~-7 air at @s run setblock ~7~-2~-7 sand 0 replace
execute at positioned as @s unless block ~7~-3~-7 air at @s run setblock ~7~-3~-7 sand 0 replace
execute at positioned as @s unless block ~7~-4~-7 air at @s run setblock ~7~-4~-7 sand 0 replace
execute at positioned as @s unless block ~7~-5~-7 air at @s run setblock ~7~-5~-7 sand 0 replace
execute at positioned as @s unless block ~7~7~-6 air at @s run setblock ~7~7~-6 sand 0 replace
execute at positioned as @s unless block ~7~6~-6 air at @s run setblock ~7~6~-6 sand 0 replace
execute at positioned as @s unless block ~7~5~-6 air at @s run setblock ~7~5~-6 sand 0 replace
execute at positioned as @s unless block ~7~4~-6 air at @s run setblock ~7~4~-6 sand 0 replace
execute at positioned as @s unless block ~7~3~-6 air at @s run setblock ~7~3~-6 sand 0 replace
execute at positioned as @s unless block ~7~2~-6 air at @s run setblock ~7~2~-6 sand 0 replace
execute at positioned as @s unless block ~7~1~-6 air at @s run setblock ~7~1~-6 sand 0 replace
execute at positioned as @s unless block ~7~0~-6 air at @s run setblock ~7~0~-6 sand 0 replace
execute at positioned as @s unless block ~7~-1~-6 air at @s run setblock ~7~-1~-6 sand 0 replace
execute at positioned as @s unless block ~7~-2~-6 air at @s run setblock ~7~-2~-6 sand 0 replace
execute at positioned as @s unless block ~7~-3~-6 air at @s run setblock ~7~-3~-6 sand 0 replace
execute at positioned as @s unless block ~7~-4~-6 air at @s run setblock ~7~-4~-6 sand 0 replace
execute at positioned as @s unless block ~7~-5~-6 air at @s run setblock ~7~-5~-6 sand 0 replace
execute at positioned as @s unless block ~7~7~-5 air at @s run setblock ~7~7~-5 sand 0 replace
execute at positioned as @s unless block ~7~6~-5 air at @s run setblock ~7~6~-5 sand 0 replace
execute at positioned as @s unless block ~7~5~-5 air at @s run setblock ~7~5~-5 sand 0 replace
execute at positioned as @s unless block ~7~4~-5 air at @s run setblock ~7~4~-5 sand 0 replace
execute at positioned as @s unless block ~7~3~-5 air at @s run setblock ~7~3~-5 sand 0 replace
execute at positioned as @s unless block ~7~2~-5 air at @s run setblock ~7~2~-5 sand 0 replace
execute at positioned as @s unless block ~7~1~-5 air at @s run setblock ~7~1~-5 sand 0 replace
execute at positioned as @s unless block ~7~0~-5 air at @s run setblock ~7~0~-5 sand 0 replace
execute at positioned as @s unless block ~7~-1~-5 air at @s run setblock ~7~-1~-5 sand 0 replace
execute at positioned as @s unless block ~7~-2~-5 air at @s run setblock ~7~-2~-5 sand 0 replace
execute at positioned as @s unless block ~7~-3~-5 air at @s run setblock ~7~-3~-5 sand 0 replace
execute at positioned as @s unless block ~7~-4~-5 air at @s run setblock ~7~-4~-5 sand 0 replace
execute at positioned as @s unless block ~7~-5~-5 air at @s run setblock ~7~-5~-5 sand 0 replace
execute at positioned as @s unless block ~7~7~-4 air at @s run setblock ~7~7~-4 sand 0 replace
execute at positioned as @s unless block ~7~6~-4 air at @s run setblock ~7~6~-4 sand 0 replace
execute at positioned as @s unless block ~7~5~-4 air at @s run setblock ~7~5~-4 sand 0 replace
execute at positioned as @s unless block ~7~4~-4 air at @s run setblock ~7~4~-4 sand 0 replace
execute at positioned as @s unless block ~7~3~-4 air at @s run setblock ~7~3~-4 sand 0 replace
execute at positioned as @s unless block ~7~2~-4 air at @s run setblock ~7~2~-4 sand 0 replace
execute at positioned as @s unless block ~7~1~-4 air at @s run setblock ~7~1~-4 sand 0 replace
execute at positioned as @s unless block ~7~0~-4 air at @s run setblock ~7~0~-4 sand 0 replace
execute at positioned as @s unless block ~7~-1~-4 air at @s run setblock ~7~-1~-4 sand 0 replace
execute at positioned as @s unless block ~7~-2~-4 air at @s run setblock ~7~-2~-4 sand 0 replace
execute at positioned as @s unless block ~7~-3~-4 air at @s run setblock ~7~-3~-4 sand 0 replace
execute at positioned as @s unless block ~7~-4~-4 air at @s run setblock ~7~-4~-4 sand 0 replace
execute at positioned as @s unless block ~7~-5~-4 air at @s run setblock ~7~-5~-4 sand 0 replace
execute at positioned as @s unless block ~7~7~-3 air at @s run setblock ~7~7~-3 sand 0 replace
execute at positioned as @s unless block ~7~6~-3 air at @s run setblock ~7~6~-3 sand 0 replace
execute at positioned as @s unless block ~7~5~-3 air at @s run setblock ~7~5~-3 sand 0 replace
execute at positioned as @s unless block ~7~4~-3 air at @s run setblock ~7~4~-3 sand 0 replace
execute at positioned as @s unless block ~7~3~-3 air at @s run setblock ~7~3~-3 sand 0 replace
execute at positioned as @s unless block ~7~2~-3 air at @s run setblock ~7~2~-3 sand 0 replace
execute at positioned as @s unless block ~7~1~-3 air at @s run setblock ~7~1~-3 sand 0 replace
execute at positioned as @s unless block ~7~0~-3 air at @s run setblock ~7~0~-3 sand 0 replace
execute at positioned as @s unless block ~7~-1~-3 air at @s run setblock ~7~-1~-3 sand 0 replace
execute at positioned as @s unless block ~7~-2~-3 air at @s run setblock ~7~-2~-3 sand 0 replace
execute at positioned as @s unless block ~7~-3~-3 air at @s run setblock ~7~-3~-3 sand 0 replace
execute at positioned as @s unless block ~7~-4~-3 air at @s run setblock ~7~-4~-3 sand 0 replace
execute at positioned as @s unless block ~7~-5~-3 air at @s run setblock ~7~-5~-3 sand 0 replace
execute at positioned as @s unless block ~7~7~-2 air at @s run setblock ~7~7~-2 sand 0 replace
execute at positioned as @s unless block ~7~6~-2 air at @s run setblock ~7~6~-2 sand 0 replace
execute at positioned as @s unless block ~7~5~-2 air at @s run setblock ~7~5~-2 sand 0 replace
execute at positioned as @s unless block ~7~4~-2 air at @s run setblock ~7~4~-2 sand 0 replace
execute at positioned as @s unless block ~7~3~-2 air at @s run setblock ~7~3~-2 sand 0 replace
execute at positioned as @s unless block ~7~2~-2 air at @s run setblock ~7~2~-2 sand 0 replace
execute at positioned as @s unless block ~7~1~-2 air at @s run setblock ~7~1~-2 sand 0 replace
execute at positioned as @s unless block ~7~0~-2 air at @s run setblock ~7~0~-2 sand 0 replace
execute at positioned as @s unless block ~7~-1~-2 air at @s run setblock ~7~-1~-2 sand 0 replace
execute at positioned as @s unless block ~7~-2~-2 air at @s run setblock ~7~-2~-2 sand 0 replace
execute at positioned as @s unless block ~7~-3~-2 air at @s run setblock ~7~-3~-2 sand 0 replace
execute at positioned as @s unless block ~7~-4~-2 air at @s run setblock ~7~-4~-2 sand 0 replace
execute at positioned as @s unless block ~7~-5~-2 air at @s run setblock ~7~-5~-2 sand 0 replace
execute at positioned as @s unless block ~7~7~-1 air at @s run setblock ~7~7~-1 sand 0 replace
execute at positioned as @s unless block ~7~6~-1 air at @s run setblock ~7~6~-1 sand 0 replace
execute at positioned as @s unless block ~7~5~-1 air at @s run setblock ~7~5~-1 sand 0 replace
execute at positioned as @s unless block ~7~4~-1 air at @s run setblock ~7~4~-1 sand 0 replace
execute at positioned as @s unless block ~7~3~-1 air at @s run setblock ~7~3~-1 sand 0 replace
execute at positioned as @s unless block ~7~2~-1 air at @s run setblock ~7~2~-1 sand 0 replace
execute at positioned as @s unless block ~7~1~-1 air at @s run setblock ~7~1~-1 sand 0 replace
execute at positioned as @s unless block ~7~0~-1 air at @s run setblock ~7~0~-1 sand 0 replace
execute at positioned as @s unless block ~7~-1~-1 air at @s run setblock ~7~-1~-1 sand 0 replace
execute at positioned as @s unless block ~7~-2~-1 air at @s run setblock ~7~-2~-1 sand 0 replace
execute at positioned as @s unless block ~7~-3~-1 air at @s run setblock ~7~-3~-1 sand 0 replace
execute at positioned as @s unless block ~7~-4~-1 air at @s run setblock ~7~-4~-1 sand 0 replace
execute at positioned as @s unless block ~7~-5~-1 air at @s run setblock ~7~-5~-1 sand 0 replace
execute at positioned as @s unless block ~7~7~0 air at @s run setblock ~7~7~0 sand 0 replace
execute at positioned as @s unless block ~7~6~0 air at @s run setblock ~7~6~0 sand 0 replace
execute at positioned as @s unless block ~7~5~0 air at @s run setblock ~7~5~0 sand 0 replace
execute at positioned as @s unless block ~7~4~0 air at @s run setblock ~7~4~0 sand 0 replace
execute at positioned as @s unless block ~7~3~0 air at @s run setblock ~7~3~0 sand 0 replace
execute at positioned as @s unless block ~7~2~0 air at @s run setblock ~7~2~0 sand 0 replace
execute at positioned as @s unless block ~7~1~0 air at @s run setblock ~7~1~0 sand 0 replace
execute at positioned as @s unless block ~7~0~0 air at @s run setblock ~7~0~0 sand 0 replace
execute at positioned as @s unless block ~7~-1~0 air at @s run setblock ~7~-1~0 sand 0 replace
execute at positioned as @s unless block ~7~-2~0 air at @s run setblock ~7~-2~0 sand 0 replace
execute at positioned as @s unless block ~7~-3~0 air at @s run setblock ~7~-3~0 sand 0 replace
execute at positioned as @s unless block ~7~-4~0 air at @s run setblock ~7~-4~0 sand 0 replace
execute at positioned as @s unless block ~7~-5~0 air at @s run setblock ~7~-5~0 sand 0 replace
execute at positioned as @s unless block ~7~7~1 air at @s run setblock ~7~7~1 sand 0 replace
execute at positioned as @s unless block ~7~6~1 air at @s run setblock ~7~6~1 sand 0 replace
execute at positioned as @s unless block ~7~5~1 air at @s run setblock ~7~5~1 sand 0 replace
execute at positioned as @s unless block ~7~4~1 air at @s run setblock ~7~4~1 sand 0 replace
execute at positioned as @s unless block ~7~3~1 air at @s run setblock ~7~3~1 sand 0 replace
execute at positioned as @s unless block ~7~2~1 air at @s run setblock ~7~2~1 sand 0 replace
execute at positioned as @s unless block ~7~1~1 air at @s run setblock ~7~1~1 sand 0 replace
execute at positioned as @s unless block ~7~0~1 air at @s run setblock ~7~0~1 sand 0 replace
execute at positioned as @s unless block ~7~-1~1 air at @s run setblock ~7~-1~1 sand 0 replace
execute at positioned as @s unless block ~7~-2~1 air at @s run setblock ~7~-2~1 sand 0 replace
execute at positioned as @s unless block ~7~-3~1 air at @s run setblock ~7~-3~1 sand 0 replace
execute at positioned as @s unless block ~7~-4~1 air at @s run setblock ~7~-4~1 sand 0 replace
execute at positioned as @s unless block ~7~-5~1 air at @s run setblock ~7~-5~1 sand 0 replace
execute at positioned as @s unless block ~7~7~2 air at @s run setblock ~7~7~2 sand 0 replace
execute at positioned as @s unless block ~7~6~2 air at @s run setblock ~7~6~2 sand 0 replace
execute at positioned as @s unless block ~7~5~2 air at @s run setblock ~7~5~2 sand 0 replace
execute at positioned as @s unless block ~7~4~2 air at @s run setblock ~7~4~2 sand 0 replace
execute at positioned as @s unless block ~7~3~2 air at @s run setblock ~7~3~2 sand 0 replace
execute at positioned as @s unless block ~7~2~2 air at @s run setblock ~7~2~2 sand 0 replace
execute at positioned as @s unless block ~7~1~2 air at @s run setblock ~7~1~2 sand 0 replace
execute at positioned as @s unless block ~7~0~2 air at @s run setblock ~7~0~2 sand 0 replace
execute at positioned as @s unless block ~7~-1~2 air at @s run setblock ~7~-1~2 sand 0 replace
execute at positioned as @s unless block ~7~-2~2 air at @s run setblock ~7~-2~2 sand 0 replace
execute at positioned as @s unless block ~7~-3~2 air at @s run setblock ~7~-3~2 sand 0 replace
execute at positioned as @s unless block ~7~-4~2 air at @s run setblock ~7~-4~2 sand 0 replace
execute at positioned as @s unless block ~7~-5~2 air at @s run setblock ~7~-5~2 sand 0 replace
execute at positioned as @s unless block ~7~7~3 air at @s run setblock ~7~7~3 sand 0 replace
execute at positioned as @s unless block ~7~6~3 air at @s run setblock ~7~6~3 sand 0 replace
execute at positioned as @s unless block ~7~5~3 air at @s run setblock ~7~5~3 sand 0 replace
execute at positioned as @s unless block ~7~4~3 air at @s run setblock ~7~4~3 sand 0 replace
execute at positioned as @s unless block ~7~3~3 air at @s run setblock ~7~3~3 sand 0 replace
execute at positioned as @s unless block ~7~2~3 air at @s run setblock ~7~2~3 sand 0 replace
execute at positioned as @s unless block ~7~1~3 air at @s run setblock ~7~1~3 sand 0 replace
execute at positioned as @s unless block ~7~0~3 air at @s run setblock ~7~0~3 sand 0 replace
execute at positioned as @s unless block ~7~-1~3 air at @s run setblock ~7~-1~3 sand 0 replace
execute at positioned as @s unless block ~7~-2~3 air at @s run setblock ~7~-2~3 sand 0 replace
execute at positioned as @s unless block ~7~-3~3 air at @s run setblock ~7~-3~3 sand 0 replace
execute at positioned as @s unless block ~7~-4~3 air at @s run setblock ~7~-4~3 sand 0 replace
execute at positioned as @s unless block ~7~-5~3 air at @s run setblock ~7~-5~3 sand 0 replace
execute at positioned as @s unless block ~7~7~4 air at @s run setblock ~7~7~4 sand 0 replace
execute at positioned as @s unless block ~7~6~4 air at @s run setblock ~7~6~4 sand 0 replace
execute at positioned as @s unless block ~7~5~4 air at @s run setblock ~7~5~4 sand 0 replace
execute at positioned as @s unless block ~7~4~4 air at @s run setblock ~7~4~4 sand 0 replace
execute at positioned as @s unless block ~7~3~4 air at @s run setblock ~7~3~4 sand 0 replace
execute at positioned as @s unless block ~7~2~4 air at @s run setblock ~7~2~4 sand 0 replace
execute at positioned as @s unless block ~7~1~4 air at @s run setblock ~7~1~4 sand 0 replace
execute at positioned as @s unless block ~7~0~4 air at @s run setblock ~7~0~4 sand 0 replace
execute at positioned as @s unless block ~7~-1~4 air at @s run setblock ~7~-1~4 sand 0 replace
execute at positioned as @s unless block ~7~-2~4 air at @s run setblock ~7~-2~4 sand 0 replace
execute at positioned as @s unless block ~7~-3~4 air at @s run setblock ~7~-3~4 sand 0 replace
execute at positioned as @s unless block ~7~-4~4 air at @s run setblock ~7~-4~4 sand 0 replace
execute at positioned as @s unless block ~7~-5~4 air at @s run setblock ~7~-5~4 sand 0 replace
execute at positioned as @s unless block ~7~7~5 air at @s run setblock ~7~7~5 sand 0 replace
execute at positioned as @s unless block ~7~6~5 air at @s run setblock ~7~6~5 sand 0 replace
execute at positioned as @s unless block ~7~5~5 air at @s run setblock ~7~5~5 sand 0 replace
execute at positioned as @s unless block ~7~4~5 air at @s run setblock ~7~4~5 sand 0 replace
execute at positioned as @s unless block ~7~3~5 air at @s run setblock ~7~3~5 sand 0 replace
execute at positioned as @s unless block ~7~2~5 air at @s run setblock ~7~2~5 sand 0 replace
execute at positioned as @s unless block ~7~1~5 air at @s run setblock ~7~1~5 sand 0 replace
execute at positioned as @s unless block ~7~0~5 air at @s run setblock ~7~0~5 sand 0 replace
execute at positioned as @s unless block ~7~-1~5 air at @s run setblock ~7~-1~5 sand 0 replace
execute at positioned as @s unless block ~7~-2~5 air at @s run setblock ~7~-2~5 sand 0 replace
execute at positioned as @s unless block ~7~-3~5 air at @s run setblock ~7~-3~5 sand 0 replace
execute at positioned as @s unless block ~7~-4~5 air at @s run setblock ~7~-4~5 sand 0 replace
execute at positioned as @s unless block ~7~-5~5 air at @s run setblock ~7~-5~5 sand 0 replace
execute at positioned as @s unless block ~7~7~6 air at @s run setblock ~7~7~6 sand 0 replace
execute at positioned as @s unless block ~7~6~6 air at @s run setblock ~7~6~6 sand 0 replace
execute at positioned as @s unless block ~7~5~6 air at @s run setblock ~7~5~6 sand 0 replace
execute at positioned as @s unless block ~7~4~6 air at @s run setblock ~7~4~6 sand 0 replace
execute at positioned as @s unless block ~7~3~6 air at @s run setblock ~7~3~6 sand 0 replace
execute at positioned as @s unless block ~7~2~6 air at @s run setblock ~7~2~6 sand 0 replace
execute at positioned as @s unless block ~7~1~6 air at @s run setblock ~7~1~6 sand 0 replace
execute at positioned as @s unless block ~7~0~6 air at @s run setblock ~7~0~6 sand 0 replace
execute at positioned as @s unless block ~7~-1~6 air at @s run setblock ~7~-1~6 sand 0 replace
execute at positioned as @s unless block ~7~-2~6 air at @s run setblock ~7~-2~6 sand 0 replace
execute at positioned as @s unless block ~7~-3~6 air at @s run setblock ~7~-3~6 sand 0 replace
execute at positioned as @s unless block ~7~-4~6 air at @s run setblock ~7~-4~6 sand 0 replace
execute at positioned as @s unless block ~7~-5~6 air at @s run setblock ~7~-5~6 sand 0 replace
execute at positioned as @s unless block ~7~7~7 air at @s run setblock ~7~7~7 sand 0 replace
execute at positioned as @s unless block ~7~6~7 air at @s run setblock ~7~6~7 sand 0 replace
execute at positioned as @s unless block ~7~5~7 air at @s run setblock ~7~5~7 sand 0 replace
execute at positioned as @s unless block ~7~4~7 air at @s run setblock ~7~4~7 sand 0 replace
execute at positioned as @s unless block ~7~3~7 air at @s run setblock ~7~3~7 sand 0 replace
execute at positioned as @s unless block ~7~2~7 air at @s run setblock ~7~2~7 sand 0 replace
execute at positioned as @s unless block ~7~1~7 air at @s run setblock ~7~1~7 sand 0 replace
execute at positioned as @s unless block ~7~0~7 air at @s run setblock ~7~0~7 sand 0 replace
execute at positioned as @s unless block ~7~-1~7 air at @s run setblock ~7~-1~7 sand 0 replace
execute at positioned as @s unless block ~7~-2~7 air at @s run setblock ~7~-2~7 sand 0 replace
execute at positioned as @s unless block ~7~-3~7 air at @s run setblock ~7~-3~7 sand 0 replace
execute at positioned as @s unless block ~7~-4~7 air at @s run setblock ~7~-4~7 sand 0 replace
execute at positioned as @s unless block ~7~-5~7 air at @s run setblock ~7~-5~7 sand 0 replace
