execute positioned as @s unless block ~-1~7~-1 air at @s run setblock ~-1~7~-1 sand 0 replace
execute positioned as @s unless block ~-1~6~-1 air at @s run setblock ~-1~6~-1 sand 0 replace
execute positioned as @s unless block ~-1~5~-1 air at @s run setblock ~-1~5~-1 sand 0 replace
execute positioned as @s unless block ~-1~4~-1 air at @s run setblock ~-1~4~-1 sand 0 replace
execute positioned as @s unless block ~-1~3~-1 air at @s run setblock ~-1~3~-1 sand 0 replace
execute positioned as @s unless block ~-1~2~-1 air at @s run setblock ~-1~2~-1 sand 0 replace
execute positioned as @s unless block ~-1~1~-1 air at @s run setblock ~-1~1~-1 sand 0 replace
execute positioned as @s unless block ~-1~0~-1 air at @s run setblock ~-1~0~-1 sand 0 replace
execute positioned as @s unless block ~-1~-1~-1 air at @s run setblock ~-1~-1~-1 sand 0 replace
execute positioned as @s unless block ~-1~-2~-1 air at @s run setblock ~-1~-2~-1 sand 0 replace
execute positioned as @s unless block ~-1~-3~-1 air at @s run setblock ~-1~-3~-1 sand 0 replace
execute positioned as @s unless block ~-1~-4~-1 air at @s run setblock ~-1~-4~-1 sand 0 replace
execute positioned as @s unless block ~-1~-5~-1 air at @s run setblock ~-1~-5~-1 sand 0 replace
execute positioned as @s unless block ~-1~7~0 air at @s run setblock ~-1~7~0 sand 0 replace
execute positioned as @s unless block ~-1~6~0 air at @s run setblock ~-1~6~0 sand 0 replace
execute positioned as @s unless block ~-1~5~0 air at @s run setblock ~-1~5~0 sand 0 replace
execute positioned as @s unless block ~-1~4~0 air at @s run setblock ~-1~4~0 sand 0 replace
execute positioned as @s unless block ~-1~3~0 air at @s run setblock ~-1~3~0 sand 0 replace
execute positioned as @s unless block ~-1~2~0 air at @s run setblock ~-1~2~0 sand 0 replace
execute positioned as @s unless block ~-1~1~0 air at @s run setblock ~-1~1~0 sand 0 replace
execute positioned as @s unless block ~-1~0~0 air at @s run setblock ~-1~0~0 sand 0 replace
execute positioned as @s unless block ~-1~-1~0 air at @s run setblock ~-1~-1~0 sand 0 replace
execute positioned as @s unless block ~-1~-2~0 air at @s run setblock ~-1~-2~0 sand 0 replace
execute positioned as @s unless block ~-1~-3~0 air at @s run setblock ~-1~-3~0 sand 0 replace
execute positioned as @s unless block ~-1~-4~0 air at @s run setblock ~-1~-4~0 sand 0 replace
execute positioned as @s unless block ~-1~-5~0 air at @s run setblock ~-1~-5~0 sand 0 replace
execute positioned as @s unless block ~-1~7~1 air at @s run setblock ~-1~7~1 sand 0 replace
execute positioned as @s unless block ~-1~6~1 air at @s run setblock ~-1~6~1 sand 0 replace
execute positioned as @s unless block ~-1~5~1 air at @s run setblock ~-1~5~1 sand 0 replace
execute positioned as @s unless block ~-1~4~1 air at @s run setblock ~-1~4~1 sand 0 replace
execute positioned as @s unless block ~-1~3~1 air at @s run setblock ~-1~3~1 sand 0 replace
execute positioned as @s unless block ~-1~2~1 air at @s run setblock ~-1~2~1 sand 0 replace
execute positioned as @s unless block ~-1~1~1 air at @s run setblock ~-1~1~1 sand 0 replace
execute positioned as @s unless block ~-1~0~1 air at @s run setblock ~-1~0~1 sand 0 replace
execute positioned as @s unless block ~-1~-1~1 air at @s run setblock ~-1~-1~1 sand 0 replace
execute positioned as @s unless block ~-1~-2~1 air at @s run setblock ~-1~-2~1 sand 0 replace
execute positioned as @s unless block ~-1~-3~1 air at @s run setblock ~-1~-3~1 sand 0 replace
execute positioned as @s unless block ~-1~-4~1 air at @s run setblock ~-1~-4~1 sand 0 replace
execute positioned as @s unless block ~-1~-5~1 air at @s run setblock ~-1~-5~1 sand 0 replace
execute positioned as @s unless block ~0~7~-1 air at @s run setblock ~0~7~-1 sand 0 replace
execute positioned as @s unless block ~0~6~-1 air at @s run setblock ~0~6~-1 sand 0 replace
execute positioned as @s unless block ~0~5~-1 air at @s run setblock ~0~5~-1 sand 0 replace
execute positioned as @s unless block ~0~4~-1 air at @s run setblock ~0~4~-1 sand 0 replace
execute positioned as @s unless block ~0~3~-1 air at @s run setblock ~0~3~-1 sand 0 replace
execute positioned as @s unless block ~0~2~-1 air at @s run setblock ~0~2~-1 sand 0 replace
execute positioned as @s unless block ~0~1~-1 air at @s run setblock ~0~1~-1 sand 0 replace
execute positioned as @s unless block ~0~0~-1 air at @s run setblock ~0~0~-1 sand 0 replace
execute positioned as @s unless block ~0~-1~-1 air at @s run setblock ~0~-1~-1 sand 0 replace
execute positioned as @s unless block ~0~-2~-1 air at @s run setblock ~0~-2~-1 sand 0 replace
execute positioned as @s unless block ~0~-3~-1 air at @s run setblock ~0~-3~-1 sand 0 replace
execute positioned as @s unless block ~0~-4~-1 air at @s run setblock ~0~-4~-1 sand 0 replace
execute positioned as @s unless block ~0~-5~-1 air at @s run setblock ~0~-5~-1 sand 0 replace
execute positioned as @s unless block ~0~7~1 air at @s run setblock ~0~7~1 sand 0 replace
execute positioned as @s unless block ~0~6~1 air at @s run setblock ~0~6~1 sand 0 replace
execute positioned as @s unless block ~0~5~1 air at @s run setblock ~0~5~1 sand 0 replace
execute positioned as @s unless block ~0~4~1 air at @s run setblock ~0~4~1 sand 0 replace
execute positioned as @s unless block ~0~3~1 air at @s run setblock ~0~3~1 sand 0 replace
execute positioned as @s unless block ~0~2~1 air at @s run setblock ~0~2~1 sand 0 replace
execute positioned as @s unless block ~0~1~1 air at @s run setblock ~0~1~1 sand 0 replace
execute positioned as @s unless block ~0~0~1 air at @s run setblock ~0~0~1 sand 0 replace
execute positioned as @s unless block ~0~-1~1 air at @s run setblock ~0~-1~1 sand 0 replace
execute positioned as @s unless block ~0~-2~1 air at @s run setblock ~0~-2~1 sand 0 replace
execute positioned as @s unless block ~0~-3~1 air at @s run setblock ~0~-3~1 sand 0 replace
execute positioned as @s unless block ~0~-4~1 air at @s run setblock ~0~-4~1 sand 0 replace
execute positioned as @s unless block ~0~-5~1 air at @s run setblock ~0~-5~1 sand 0 replace
execute positioned as @s unless block ~1~7~-1 air at @s run setblock ~1~7~-1 sand 0 replace
execute positioned as @s unless block ~1~6~-1 air at @s run setblock ~1~6~-1 sand 0 replace
execute positioned as @s unless block ~1~5~-1 air at @s run setblock ~1~5~-1 sand 0 replace
execute positioned as @s unless block ~1~4~-1 air at @s run setblock ~1~4~-1 sand 0 replace
execute positioned as @s unless block ~1~3~-1 air at @s run setblock ~1~3~-1 sand 0 replace
execute positioned as @s unless block ~1~2~-1 air at @s run setblock ~1~2~-1 sand 0 replace
execute positioned as @s unless block ~1~1~-1 air at @s run setblock ~1~1~-1 sand 0 replace
execute positioned as @s unless block ~1~0~-1 air at @s run setblock ~1~0~-1 sand 0 replace
execute positioned as @s unless block ~1~-1~-1 air at @s run setblock ~1~-1~-1 sand 0 replace
execute positioned as @s unless block ~1~-2~-1 air at @s run setblock ~1~-2~-1 sand 0 replace
execute positioned as @s unless block ~1~-3~-1 air at @s run setblock ~1~-3~-1 sand 0 replace
execute positioned as @s unless block ~1~-4~-1 air at @s run setblock ~1~-4~-1 sand 0 replace
execute positioned as @s unless block ~1~-5~-1 air at @s run setblock ~1~-5~-1 sand 0 replace
execute positioned as @s unless block ~1~7~0 air at @s run setblock ~1~7~0 sand 0 replace
execute positioned as @s unless block ~1~6~0 air at @s run setblock ~1~6~0 sand 0 replace
execute positioned as @s unless block ~1~5~0 air at @s run setblock ~1~5~0 sand 0 replace
execute positioned as @s unless block ~1~4~0 air at @s run setblock ~1~4~0 sand 0 replace
execute positioned as @s unless block ~1~3~0 air at @s run setblock ~1~3~0 sand 0 replace
execute positioned as @s unless block ~1~2~0 air at @s run setblock ~1~2~0 sand 0 replace
execute positioned as @s unless block ~1~1~0 air at @s run setblock ~1~1~0 sand 0 replace
execute positioned as @s unless block ~1~0~0 air at @s run setblock ~1~0~0 sand 0 replace
execute positioned as @s unless block ~1~-1~0 air at @s run setblock ~1~-1~0 sand 0 replace
execute positioned as @s unless block ~1~-2~0 air at @s run setblock ~1~-2~0 sand 0 replace
execute positioned as @s unless block ~1~-3~0 air at @s run setblock ~1~-3~0 sand 0 replace
execute positioned as @s unless block ~1~-4~0 air at @s run setblock ~1~-4~0 sand 0 replace
execute positioned as @s unless block ~1~-5~0 air at @s run setblock ~1~-5~0 sand 0 replace
execute positioned as @s unless block ~1~7~1 air at @s run setblock ~1~7~1 sand 0 replace
execute positioned as @s unless block ~1~6~1 air at @s run setblock ~1~6~1 sand 0 replace
execute positioned as @s unless block ~1~5~1 air at @s run setblock ~1~5~1 sand 0 replace
execute positioned as @s unless block ~1~4~1 air at @s run setblock ~1~4~1 sand 0 replace
execute positioned as @s unless block ~1~3~1 air at @s run setblock ~1~3~1 sand 0 replace
execute positioned as @s unless block ~1~2~1 air at @s run setblock ~1~2~1 sand 0 replace
execute positioned as @s unless block ~1~1~1 air at @s run setblock ~1~1~1 sand 0 replace
execute positioned as @s unless block ~1~0~1 air at @s run setblock ~1~0~1 sand 0 replace
execute positioned as @s unless block ~1~-1~1 air at @s run setblock ~1~-1~1 sand 0 replace
execute positioned as @s unless block ~1~-2~1 air at @s run setblock ~1~-2~1 sand 0 replace
execute positioned as @s unless block ~1~-3~1 air at @s run setblock ~1~-3~1 sand 0 replace
execute positioned as @s unless block ~1~-4~1 air at @s run setblock ~1~-4~1 sand 0 replace
execute positioned as @s unless block ~1~-5~1 air at @s run setblock ~1~-5~1 sand 0 replace
