execute positioned as @s unless block ~0~7~0 air at @s run setblock ~0~7~0 sand 0 replace
execute positioned as @s unless block ~0~6~0 air at @s run setblock ~0~6~0 sand 0 replace
execute positioned as @s unless block ~0~5~0 air at @s run setblock ~0~5~0 sand 0 replace
execute positioned as @s unless block ~0~4~0 air at @s run setblock ~0~4~0 sand 0 replace
execute positioned as @s unless block ~0~3~0 air at @s run setblock ~0~3~0 sand 0 replace
execute positioned as @s unless block ~0~2~0 air at @s run setblock ~0~2~0 sand 0 replace
execute positioned as @s unless block ~0~1~0 air at @s run setblock ~0~1~0 sand 0 replace
execute positioned as @s unless block ~0~0~0 air at @s run setblock ~0~0~0 sand 0 replace
execute positioned as @s unless block ~0~-1~0 air at @s run setblock ~0~-1~0 sand 0 replace
execute positioned as @s unless block ~0~-2~0 air at @s run setblock ~0~-2~0 sand 0 replace
execute positioned as @s unless block ~0~-3~0 air at @s run setblock ~0~-3~0 sand 0 replace
execute positioned as @s unless block ~0~-4~0 air at @s run setblock ~0~-4~0 sand 0 replace
execute positioned as @s unless block ~0~-5~0 air at @s run setblock ~0~-5~0 sand 0 replace
