execute positioned as @s unless block ~-6~7~-6 air at @s run setblock ~-6~7~-6 sand 0 replace
execute positioned as @s unless block ~-6~6~-6 air at @s run setblock ~-6~6~-6 sand 0 replace
execute positioned as @s unless block ~-6~5~-6 air at @s run setblock ~-6~5~-6 sand 0 replace
execute positioned as @s unless block ~-6~4~-6 air at @s run setblock ~-6~4~-6 sand 0 replace
execute positioned as @s unless block ~-6~3~-6 air at @s run setblock ~-6~3~-6 sand 0 replace
execute positioned as @s unless block ~-6~2~-6 air at @s run setblock ~-6~2~-6 sand 0 replace
execute positioned as @s unless block ~-6~1~-6 air at @s run setblock ~-6~1~-6 sand 0 replace
execute positioned as @s unless block ~-6~0~-6 air at @s run setblock ~-6~0~-6 sand 0 replace
execute positioned as @s unless block ~-6~-1~-6 air at @s run setblock ~-6~-1~-6 sand 0 replace
execute positioned as @s unless block ~-6~-2~-6 air at @s run setblock ~-6~-2~-6 sand 0 replace
execute positioned as @s unless block ~-6~-3~-6 air at @s run setblock ~-6~-3~-6 sand 0 replace
execute positioned as @s unless block ~-6~-4~-6 air at @s run setblock ~-6~-4~-6 sand 0 replace
execute positioned as @s unless block ~-6~-5~-6 air at @s run setblock ~-6~-5~-6 sand 0 replace
execute positioned as @s unless block ~-6~7~-5 air at @s run setblock ~-6~7~-5 sand 0 replace
execute positioned as @s unless block ~-6~6~-5 air at @s run setblock ~-6~6~-5 sand 0 replace
execute positioned as @s unless block ~-6~5~-5 air at @s run setblock ~-6~5~-5 sand 0 replace
execute positioned as @s unless block ~-6~4~-5 air at @s run setblock ~-6~4~-5 sand 0 replace
execute positioned as @s unless block ~-6~3~-5 air at @s run setblock ~-6~3~-5 sand 0 replace
execute positioned as @s unless block ~-6~2~-5 air at @s run setblock ~-6~2~-5 sand 0 replace
execute positioned as @s unless block ~-6~1~-5 air at @s run setblock ~-6~1~-5 sand 0 replace
execute positioned as @s unless block ~-6~0~-5 air at @s run setblock ~-6~0~-5 sand 0 replace
execute positioned as @s unless block ~-6~-1~-5 air at @s run setblock ~-6~-1~-5 sand 0 replace
execute positioned as @s unless block ~-6~-2~-5 air at @s run setblock ~-6~-2~-5 sand 0 replace
execute positioned as @s unless block ~-6~-3~-5 air at @s run setblock ~-6~-3~-5 sand 0 replace
execute positioned as @s unless block ~-6~-4~-5 air at @s run setblock ~-6~-4~-5 sand 0 replace
execute positioned as @s unless block ~-6~-5~-5 air at @s run setblock ~-6~-5~-5 sand 0 replace
execute positioned as @s unless block ~-6~7~-4 air at @s run setblock ~-6~7~-4 sand 0 replace
execute positioned as @s unless block ~-6~6~-4 air at @s run setblock ~-6~6~-4 sand 0 replace
execute positioned as @s unless block ~-6~5~-4 air at @s run setblock ~-6~5~-4 sand 0 replace
execute positioned as @s unless block ~-6~4~-4 air at @s run setblock ~-6~4~-4 sand 0 replace
execute positioned as @s unless block ~-6~3~-4 air at @s run setblock ~-6~3~-4 sand 0 replace
execute positioned as @s unless block ~-6~2~-4 air at @s run setblock ~-6~2~-4 sand 0 replace
execute positioned as @s unless block ~-6~1~-4 air at @s run setblock ~-6~1~-4 sand 0 replace
execute positioned as @s unless block ~-6~0~-4 air at @s run setblock ~-6~0~-4 sand 0 replace
execute positioned as @s unless block ~-6~-1~-4 air at @s run setblock ~-6~-1~-4 sand 0 replace
execute positioned as @s unless block ~-6~-2~-4 air at @s run setblock ~-6~-2~-4 sand 0 replace
execute positioned as @s unless block ~-6~-3~-4 air at @s run setblock ~-6~-3~-4 sand 0 replace
execute positioned as @s unless block ~-6~-4~-4 air at @s run setblock ~-6~-4~-4 sand 0 replace
execute positioned as @s unless block ~-6~-5~-4 air at @s run setblock ~-6~-5~-4 sand 0 replace
execute positioned as @s unless block ~-6~7~-3 air at @s run setblock ~-6~7~-3 sand 0 replace
execute positioned as @s unless block ~-6~6~-3 air at @s run setblock ~-6~6~-3 sand 0 replace
execute positioned as @s unless block ~-6~5~-3 air at @s run setblock ~-6~5~-3 sand 0 replace
execute positioned as @s unless block ~-6~4~-3 air at @s run setblock ~-6~4~-3 sand 0 replace
execute positioned as @s unless block ~-6~3~-3 air at @s run setblock ~-6~3~-3 sand 0 replace
execute positioned as @s unless block ~-6~2~-3 air at @s run setblock ~-6~2~-3 sand 0 replace
execute positioned as @s unless block ~-6~1~-3 air at @s run setblock ~-6~1~-3 sand 0 replace
execute positioned as @s unless block ~-6~0~-3 air at @s run setblock ~-6~0~-3 sand 0 replace
execute positioned as @s unless block ~-6~-1~-3 air at @s run setblock ~-6~-1~-3 sand 0 replace
execute positioned as @s unless block ~-6~-2~-3 air at @s run setblock ~-6~-2~-3 sand 0 replace
execute positioned as @s unless block ~-6~-3~-3 air at @s run setblock ~-6~-3~-3 sand 0 replace
execute positioned as @s unless block ~-6~-4~-3 air at @s run setblock ~-6~-4~-3 sand 0 replace
execute positioned as @s unless block ~-6~-5~-3 air at @s run setblock ~-6~-5~-3 sand 0 replace
execute positioned as @s unless block ~-6~7~-2 air at @s run setblock ~-6~7~-2 sand 0 replace
execute positioned as @s unless block ~-6~6~-2 air at @s run setblock ~-6~6~-2 sand 0 replace
execute positioned as @s unless block ~-6~5~-2 air at @s run setblock ~-6~5~-2 sand 0 replace
execute positioned as @s unless block ~-6~4~-2 air at @s run setblock ~-6~4~-2 sand 0 replace
execute positioned as @s unless block ~-6~3~-2 air at @s run setblock ~-6~3~-2 sand 0 replace
execute positioned as @s unless block ~-6~2~-2 air at @s run setblock ~-6~2~-2 sand 0 replace
execute positioned as @s unless block ~-6~1~-2 air at @s run setblock ~-6~1~-2 sand 0 replace
execute positioned as @s unless block ~-6~0~-2 air at @s run setblock ~-6~0~-2 sand 0 replace
execute positioned as @s unless block ~-6~-1~-2 air at @s run setblock ~-6~-1~-2 sand 0 replace
execute positioned as @s unless block ~-6~-2~-2 air at @s run setblock ~-6~-2~-2 sand 0 replace
execute positioned as @s unless block ~-6~-3~-2 air at @s run setblock ~-6~-3~-2 sand 0 replace
execute positioned as @s unless block ~-6~-4~-2 air at @s run setblock ~-6~-4~-2 sand 0 replace
execute positioned as @s unless block ~-6~-5~-2 air at @s run setblock ~-6~-5~-2 sand 0 replace
execute positioned as @s unless block ~-6~7~-1 air at @s run setblock ~-6~7~-1 sand 0 replace
execute positioned as @s unless block ~-6~6~-1 air at @s run setblock ~-6~6~-1 sand 0 replace
execute positioned as @s unless block ~-6~5~-1 air at @s run setblock ~-6~5~-1 sand 0 replace
execute positioned as @s unless block ~-6~4~-1 air at @s run setblock ~-6~4~-1 sand 0 replace
execute positioned as @s unless block ~-6~3~-1 air at @s run setblock ~-6~3~-1 sand 0 replace
execute positioned as @s unless block ~-6~2~-1 air at @s run setblock ~-6~2~-1 sand 0 replace
execute positioned as @s unless block ~-6~1~-1 air at @s run setblock ~-6~1~-1 sand 0 replace
execute positioned as @s unless block ~-6~0~-1 air at @s run setblock ~-6~0~-1 sand 0 replace
execute positioned as @s unless block ~-6~-1~-1 air at @s run setblock ~-6~-1~-1 sand 0 replace
execute positioned as @s unless block ~-6~-2~-1 air at @s run setblock ~-6~-2~-1 sand 0 replace
execute positioned as @s unless block ~-6~-3~-1 air at @s run setblock ~-6~-3~-1 sand 0 replace
execute positioned as @s unless block ~-6~-4~-1 air at @s run setblock ~-6~-4~-1 sand 0 replace
execute positioned as @s unless block ~-6~-5~-1 air at @s run setblock ~-6~-5~-1 sand 0 replace
execute positioned as @s unless block ~-6~7~0 air at @s run setblock ~-6~7~0 sand 0 replace
execute positioned as @s unless block ~-6~6~0 air at @s run setblock ~-6~6~0 sand 0 replace
execute positioned as @s unless block ~-6~5~0 air at @s run setblock ~-6~5~0 sand 0 replace
execute positioned as @s unless block ~-6~4~0 air at @s run setblock ~-6~4~0 sand 0 replace
execute positioned as @s unless block ~-6~3~0 air at @s run setblock ~-6~3~0 sand 0 replace
execute positioned as @s unless block ~-6~2~0 air at @s run setblock ~-6~2~0 sand 0 replace
execute positioned as @s unless block ~-6~1~0 air at @s run setblock ~-6~1~0 sand 0 replace
execute positioned as @s unless block ~-6~0~0 air at @s run setblock ~-6~0~0 sand 0 replace
execute positioned as @s unless block ~-6~-1~0 air at @s run setblock ~-6~-1~0 sand 0 replace
execute positioned as @s unless block ~-6~-2~0 air at @s run setblock ~-6~-2~0 sand 0 replace
execute positioned as @s unless block ~-6~-3~0 air at @s run setblock ~-6~-3~0 sand 0 replace
execute positioned as @s unless block ~-6~-4~0 air at @s run setblock ~-6~-4~0 sand 0 replace
execute positioned as @s unless block ~-6~-5~0 air at @s run setblock ~-6~-5~0 sand 0 replace
execute positioned as @s unless block ~-6~7~1 air at @s run setblock ~-6~7~1 sand 0 replace
execute positioned as @s unless block ~-6~6~1 air at @s run setblock ~-6~6~1 sand 0 replace
execute positioned as @s unless block ~-6~5~1 air at @s run setblock ~-6~5~1 sand 0 replace
execute positioned as @s unless block ~-6~4~1 air at @s run setblock ~-6~4~1 sand 0 replace
execute positioned as @s unless block ~-6~3~1 air at @s run setblock ~-6~3~1 sand 0 replace
execute positioned as @s unless block ~-6~2~1 air at @s run setblock ~-6~2~1 sand 0 replace
execute positioned as @s unless block ~-6~1~1 air at @s run setblock ~-6~1~1 sand 0 replace
execute positioned as @s unless block ~-6~0~1 air at @s run setblock ~-6~0~1 sand 0 replace
execute positioned as @s unless block ~-6~-1~1 air at @s run setblock ~-6~-1~1 sand 0 replace
execute positioned as @s unless block ~-6~-2~1 air at @s run setblock ~-6~-2~1 sand 0 replace
execute positioned as @s unless block ~-6~-3~1 air at @s run setblock ~-6~-3~1 sand 0 replace
execute positioned as @s unless block ~-6~-4~1 air at @s run setblock ~-6~-4~1 sand 0 replace
execute positioned as @s unless block ~-6~-5~1 air at @s run setblock ~-6~-5~1 sand 0 replace
execute positioned as @s unless block ~-6~7~2 air at @s run setblock ~-6~7~2 sand 0 replace
execute positioned as @s unless block ~-6~6~2 air at @s run setblock ~-6~6~2 sand 0 replace
execute positioned as @s unless block ~-6~5~2 air at @s run setblock ~-6~5~2 sand 0 replace
execute positioned as @s unless block ~-6~4~2 air at @s run setblock ~-6~4~2 sand 0 replace
execute positioned as @s unless block ~-6~3~2 air at @s run setblock ~-6~3~2 sand 0 replace
execute positioned as @s unless block ~-6~2~2 air at @s run setblock ~-6~2~2 sand 0 replace
execute positioned as @s unless block ~-6~1~2 air at @s run setblock ~-6~1~2 sand 0 replace
execute positioned as @s unless block ~-6~0~2 air at @s run setblock ~-6~0~2 sand 0 replace
execute positioned as @s unless block ~-6~-1~2 air at @s run setblock ~-6~-1~2 sand 0 replace
execute positioned as @s unless block ~-6~-2~2 air at @s run setblock ~-6~-2~2 sand 0 replace
execute positioned as @s unless block ~-6~-3~2 air at @s run setblock ~-6~-3~2 sand 0 replace
execute positioned as @s unless block ~-6~-4~2 air at @s run setblock ~-6~-4~2 sand 0 replace
execute positioned as @s unless block ~-6~-5~2 air at @s run setblock ~-6~-5~2 sand 0 replace
execute positioned as @s unless block ~-6~7~3 air at @s run setblock ~-6~7~3 sand 0 replace
execute positioned as @s unless block ~-6~6~3 air at @s run setblock ~-6~6~3 sand 0 replace
execute positioned as @s unless block ~-6~5~3 air at @s run setblock ~-6~5~3 sand 0 replace
execute positioned as @s unless block ~-6~4~3 air at @s run setblock ~-6~4~3 sand 0 replace
execute positioned as @s unless block ~-6~3~3 air at @s run setblock ~-6~3~3 sand 0 replace
execute positioned as @s unless block ~-6~2~3 air at @s run setblock ~-6~2~3 sand 0 replace
execute positioned as @s unless block ~-6~1~3 air at @s run setblock ~-6~1~3 sand 0 replace
execute positioned as @s unless block ~-6~0~3 air at @s run setblock ~-6~0~3 sand 0 replace
execute positioned as @s unless block ~-6~-1~3 air at @s run setblock ~-6~-1~3 sand 0 replace
execute positioned as @s unless block ~-6~-2~3 air at @s run setblock ~-6~-2~3 sand 0 replace
execute positioned as @s unless block ~-6~-3~3 air at @s run setblock ~-6~-3~3 sand 0 replace
execute positioned as @s unless block ~-6~-4~3 air at @s run setblock ~-6~-4~3 sand 0 replace
execute positioned as @s unless block ~-6~-5~3 air at @s run setblock ~-6~-5~3 sand 0 replace
execute positioned as @s unless block ~-6~7~4 air at @s run setblock ~-6~7~4 sand 0 replace
execute positioned as @s unless block ~-6~6~4 air at @s run setblock ~-6~6~4 sand 0 replace
execute positioned as @s unless block ~-6~5~4 air at @s run setblock ~-6~5~4 sand 0 replace
execute positioned as @s unless block ~-6~4~4 air at @s run setblock ~-6~4~4 sand 0 replace
execute positioned as @s unless block ~-6~3~4 air at @s run setblock ~-6~3~4 sand 0 replace
execute positioned as @s unless block ~-6~2~4 air at @s run setblock ~-6~2~4 sand 0 replace
execute positioned as @s unless block ~-6~1~4 air at @s run setblock ~-6~1~4 sand 0 replace
execute positioned as @s unless block ~-6~0~4 air at @s run setblock ~-6~0~4 sand 0 replace
execute positioned as @s unless block ~-6~-1~4 air at @s run setblock ~-6~-1~4 sand 0 replace
execute positioned as @s unless block ~-6~-2~4 air at @s run setblock ~-6~-2~4 sand 0 replace
execute positioned as @s unless block ~-6~-3~4 air at @s run setblock ~-6~-3~4 sand 0 replace
execute positioned as @s unless block ~-6~-4~4 air at @s run setblock ~-6~-4~4 sand 0 replace
execute positioned as @s unless block ~-6~-5~4 air at @s run setblock ~-6~-5~4 sand 0 replace
execute positioned as @s unless block ~-6~7~5 air at @s run setblock ~-6~7~5 sand 0 replace
execute positioned as @s unless block ~-6~6~5 air at @s run setblock ~-6~6~5 sand 0 replace
execute positioned as @s unless block ~-6~5~5 air at @s run setblock ~-6~5~5 sand 0 replace
execute positioned as @s unless block ~-6~4~5 air at @s run setblock ~-6~4~5 sand 0 replace
execute positioned as @s unless block ~-6~3~5 air at @s run setblock ~-6~3~5 sand 0 replace
execute positioned as @s unless block ~-6~2~5 air at @s run setblock ~-6~2~5 sand 0 replace
execute positioned as @s unless block ~-6~1~5 air at @s run setblock ~-6~1~5 sand 0 replace
execute positioned as @s unless block ~-6~0~5 air at @s run setblock ~-6~0~5 sand 0 replace
execute positioned as @s unless block ~-6~-1~5 air at @s run setblock ~-6~-1~5 sand 0 replace
execute positioned as @s unless block ~-6~-2~5 air at @s run setblock ~-6~-2~5 sand 0 replace
execute positioned as @s unless block ~-6~-3~5 air at @s run setblock ~-6~-3~5 sand 0 replace
execute positioned as @s unless block ~-6~-4~5 air at @s run setblock ~-6~-4~5 sand 0 replace
execute positioned as @s unless block ~-6~-5~5 air at @s run setblock ~-6~-5~5 sand 0 replace
execute positioned as @s unless block ~-6~7~6 air at @s run setblock ~-6~7~6 sand 0 replace
execute positioned as @s unless block ~-6~6~6 air at @s run setblock ~-6~6~6 sand 0 replace
execute positioned as @s unless block ~-6~5~6 air at @s run setblock ~-6~5~6 sand 0 replace
execute positioned as @s unless block ~-6~4~6 air at @s run setblock ~-6~4~6 sand 0 replace
execute positioned as @s unless block ~-6~3~6 air at @s run setblock ~-6~3~6 sand 0 replace
execute positioned as @s unless block ~-6~2~6 air at @s run setblock ~-6~2~6 sand 0 replace
execute positioned as @s unless block ~-6~1~6 air at @s run setblock ~-6~1~6 sand 0 replace
execute positioned as @s unless block ~-6~0~6 air at @s run setblock ~-6~0~6 sand 0 replace
execute positioned as @s unless block ~-6~-1~6 air at @s run setblock ~-6~-1~6 sand 0 replace
execute positioned as @s unless block ~-6~-2~6 air at @s run setblock ~-6~-2~6 sand 0 replace
execute positioned as @s unless block ~-6~-3~6 air at @s run setblock ~-6~-3~6 sand 0 replace
execute positioned as @s unless block ~-6~-4~6 air at @s run setblock ~-6~-4~6 sand 0 replace
execute positioned as @s unless block ~-6~-5~6 air at @s run setblock ~-6~-5~6 sand 0 replace
execute positioned as @s unless block ~-5~7~-6 air at @s run setblock ~-5~7~-6 sand 0 replace
execute positioned as @s unless block ~-5~6~-6 air at @s run setblock ~-5~6~-6 sand 0 replace
execute positioned as @s unless block ~-5~5~-6 air at @s run setblock ~-5~5~-6 sand 0 replace
execute positioned as @s unless block ~-5~4~-6 air at @s run setblock ~-5~4~-6 sand 0 replace
execute positioned as @s unless block ~-5~3~-6 air at @s run setblock ~-5~3~-6 sand 0 replace
execute positioned as @s unless block ~-5~2~-6 air at @s run setblock ~-5~2~-6 sand 0 replace
execute positioned as @s unless block ~-5~1~-6 air at @s run setblock ~-5~1~-6 sand 0 replace
execute positioned as @s unless block ~-5~0~-6 air at @s run setblock ~-5~0~-6 sand 0 replace
execute positioned as @s unless block ~-5~-1~-6 air at @s run setblock ~-5~-1~-6 sand 0 replace
execute positioned as @s unless block ~-5~-2~-6 air at @s run setblock ~-5~-2~-6 sand 0 replace
execute positioned as @s unless block ~-5~-3~-6 air at @s run setblock ~-5~-3~-6 sand 0 replace
execute positioned as @s unless block ~-5~-4~-6 air at @s run setblock ~-5~-4~-6 sand 0 replace
execute positioned as @s unless block ~-5~-5~-6 air at @s run setblock ~-5~-5~-6 sand 0 replace
execute positioned as @s unless block ~-5~7~6 air at @s run setblock ~-5~7~6 sand 0 replace
execute positioned as @s unless block ~-5~6~6 air at @s run setblock ~-5~6~6 sand 0 replace
execute positioned as @s unless block ~-5~5~6 air at @s run setblock ~-5~5~6 sand 0 replace
execute positioned as @s unless block ~-5~4~6 air at @s run setblock ~-5~4~6 sand 0 replace
execute positioned as @s unless block ~-5~3~6 air at @s run setblock ~-5~3~6 sand 0 replace
execute positioned as @s unless block ~-5~2~6 air at @s run setblock ~-5~2~6 sand 0 replace
execute positioned as @s unless block ~-5~1~6 air at @s run setblock ~-5~1~6 sand 0 replace
execute positioned as @s unless block ~-5~0~6 air at @s run setblock ~-5~0~6 sand 0 replace
execute positioned as @s unless block ~-5~-1~6 air at @s run setblock ~-5~-1~6 sand 0 replace
execute positioned as @s unless block ~-5~-2~6 air at @s run setblock ~-5~-2~6 sand 0 replace
execute positioned as @s unless block ~-5~-3~6 air at @s run setblock ~-5~-3~6 sand 0 replace
execute positioned as @s unless block ~-5~-4~6 air at @s run setblock ~-5~-4~6 sand 0 replace
execute positioned as @s unless block ~-5~-5~6 air at @s run setblock ~-5~-5~6 sand 0 replace
execute positioned as @s unless block ~-4~7~-6 air at @s run setblock ~-4~7~-6 sand 0 replace
execute positioned as @s unless block ~-4~6~-6 air at @s run setblock ~-4~6~-6 sand 0 replace
execute positioned as @s unless block ~-4~5~-6 air at @s run setblock ~-4~5~-6 sand 0 replace
execute positioned as @s unless block ~-4~4~-6 air at @s run setblock ~-4~4~-6 sand 0 replace
execute positioned as @s unless block ~-4~3~-6 air at @s run setblock ~-4~3~-6 sand 0 replace
execute positioned as @s unless block ~-4~2~-6 air at @s run setblock ~-4~2~-6 sand 0 replace
execute positioned as @s unless block ~-4~1~-6 air at @s run setblock ~-4~1~-6 sand 0 replace
execute positioned as @s unless block ~-4~0~-6 air at @s run setblock ~-4~0~-6 sand 0 replace
execute positioned as @s unless block ~-4~-1~-6 air at @s run setblock ~-4~-1~-6 sand 0 replace
execute positioned as @s unless block ~-4~-2~-6 air at @s run setblock ~-4~-2~-6 sand 0 replace
execute positioned as @s unless block ~-4~-3~-6 air at @s run setblock ~-4~-3~-6 sand 0 replace
execute positioned as @s unless block ~-4~-4~-6 air at @s run setblock ~-4~-4~-6 sand 0 replace
execute positioned as @s unless block ~-4~-5~-6 air at @s run setblock ~-4~-5~-6 sand 0 replace
execute positioned as @s unless block ~-4~7~6 air at @s run setblock ~-4~7~6 sand 0 replace
execute positioned as @s unless block ~-4~6~6 air at @s run setblock ~-4~6~6 sand 0 replace
execute positioned as @s unless block ~-4~5~6 air at @s run setblock ~-4~5~6 sand 0 replace
execute positioned as @s unless block ~-4~4~6 air at @s run setblock ~-4~4~6 sand 0 replace
execute positioned as @s unless block ~-4~3~6 air at @s run setblock ~-4~3~6 sand 0 replace
execute positioned as @s unless block ~-4~2~6 air at @s run setblock ~-4~2~6 sand 0 replace
execute positioned as @s unless block ~-4~1~6 air at @s run setblock ~-4~1~6 sand 0 replace
execute positioned as @s unless block ~-4~0~6 air at @s run setblock ~-4~0~6 sand 0 replace
execute positioned as @s unless block ~-4~-1~6 air at @s run setblock ~-4~-1~6 sand 0 replace
execute positioned as @s unless block ~-4~-2~6 air at @s run setblock ~-4~-2~6 sand 0 replace
execute positioned as @s unless block ~-4~-3~6 air at @s run setblock ~-4~-3~6 sand 0 replace
execute positioned as @s unless block ~-4~-4~6 air at @s run setblock ~-4~-4~6 sand 0 replace
execute positioned as @s unless block ~-4~-5~6 air at @s run setblock ~-4~-5~6 sand 0 replace
execute positioned as @s unless block ~-3~7~-6 air at @s run setblock ~-3~7~-6 sand 0 replace
execute positioned as @s unless block ~-3~6~-6 air at @s run setblock ~-3~6~-6 sand 0 replace
execute positioned as @s unless block ~-3~5~-6 air at @s run setblock ~-3~5~-6 sand 0 replace
execute positioned as @s unless block ~-3~4~-6 air at @s run setblock ~-3~4~-6 sand 0 replace
execute positioned as @s unless block ~-3~3~-6 air at @s run setblock ~-3~3~-6 sand 0 replace
execute positioned as @s unless block ~-3~2~-6 air at @s run setblock ~-3~2~-6 sand 0 replace
execute positioned as @s unless block ~-3~1~-6 air at @s run setblock ~-3~1~-6 sand 0 replace
execute positioned as @s unless block ~-3~0~-6 air at @s run setblock ~-3~0~-6 sand 0 replace
execute positioned as @s unless block ~-3~-1~-6 air at @s run setblock ~-3~-1~-6 sand 0 replace
execute positioned as @s unless block ~-3~-2~-6 air at @s run setblock ~-3~-2~-6 sand 0 replace
execute positioned as @s unless block ~-3~-3~-6 air at @s run setblock ~-3~-3~-6 sand 0 replace
execute positioned as @s unless block ~-3~-4~-6 air at @s run setblock ~-3~-4~-6 sand 0 replace
execute positioned as @s unless block ~-3~-5~-6 air at @s run setblock ~-3~-5~-6 sand 0 replace
execute positioned as @s unless block ~-3~7~6 air at @s run setblock ~-3~7~6 sand 0 replace
execute positioned as @s unless block ~-3~6~6 air at @s run setblock ~-3~6~6 sand 0 replace
execute positioned as @s unless block ~-3~5~6 air at @s run setblock ~-3~5~6 sand 0 replace
execute positioned as @s unless block ~-3~4~6 air at @s run setblock ~-3~4~6 sand 0 replace
execute positioned as @s unless block ~-3~3~6 air at @s run setblock ~-3~3~6 sand 0 replace
execute positioned as @s unless block ~-3~2~6 air at @s run setblock ~-3~2~6 sand 0 replace
execute positioned as @s unless block ~-3~1~6 air at @s run setblock ~-3~1~6 sand 0 replace
execute positioned as @s unless block ~-3~0~6 air at @s run setblock ~-3~0~6 sand 0 replace
execute positioned as @s unless block ~-3~-1~6 air at @s run setblock ~-3~-1~6 sand 0 replace
execute positioned as @s unless block ~-3~-2~6 air at @s run setblock ~-3~-2~6 sand 0 replace
execute positioned as @s unless block ~-3~-3~6 air at @s run setblock ~-3~-3~6 sand 0 replace
execute positioned as @s unless block ~-3~-4~6 air at @s run setblock ~-3~-4~6 sand 0 replace
execute positioned as @s unless block ~-3~-5~6 air at @s run setblock ~-3~-5~6 sand 0 replace
execute positioned as @s unless block ~-2~7~-6 air at @s run setblock ~-2~7~-6 sand 0 replace
execute positioned as @s unless block ~-2~6~-6 air at @s run setblock ~-2~6~-6 sand 0 replace
execute positioned as @s unless block ~-2~5~-6 air at @s run setblock ~-2~5~-6 sand 0 replace
execute positioned as @s unless block ~-2~4~-6 air at @s run setblock ~-2~4~-6 sand 0 replace
execute positioned as @s unless block ~-2~3~-6 air at @s run setblock ~-2~3~-6 sand 0 replace
execute positioned as @s unless block ~-2~2~-6 air at @s run setblock ~-2~2~-6 sand 0 replace
execute positioned as @s unless block ~-2~1~-6 air at @s run setblock ~-2~1~-6 sand 0 replace
execute positioned as @s unless block ~-2~0~-6 air at @s run setblock ~-2~0~-6 sand 0 replace
execute positioned as @s unless block ~-2~-1~-6 air at @s run setblock ~-2~-1~-6 sand 0 replace
execute positioned as @s unless block ~-2~-2~-6 air at @s run setblock ~-2~-2~-6 sand 0 replace
execute positioned as @s unless block ~-2~-3~-6 air at @s run setblock ~-2~-3~-6 sand 0 replace
execute positioned as @s unless block ~-2~-4~-6 air at @s run setblock ~-2~-4~-6 sand 0 replace
execute positioned as @s unless block ~-2~-5~-6 air at @s run setblock ~-2~-5~-6 sand 0 replace
execute positioned as @s unless block ~-2~7~6 air at @s run setblock ~-2~7~6 sand 0 replace
execute positioned as @s unless block ~-2~6~6 air at @s run setblock ~-2~6~6 sand 0 replace
execute positioned as @s unless block ~-2~5~6 air at @s run setblock ~-2~5~6 sand 0 replace
execute positioned as @s unless block ~-2~4~6 air at @s run setblock ~-2~4~6 sand 0 replace
execute positioned as @s unless block ~-2~3~6 air at @s run setblock ~-2~3~6 sand 0 replace
execute positioned as @s unless block ~-2~2~6 air at @s run setblock ~-2~2~6 sand 0 replace
execute positioned as @s unless block ~-2~1~6 air at @s run setblock ~-2~1~6 sand 0 replace
execute positioned as @s unless block ~-2~0~6 air at @s run setblock ~-2~0~6 sand 0 replace
execute positioned as @s unless block ~-2~-1~6 air at @s run setblock ~-2~-1~6 sand 0 replace
execute positioned as @s unless block ~-2~-2~6 air at @s run setblock ~-2~-2~6 sand 0 replace
execute positioned as @s unless block ~-2~-3~6 air at @s run setblock ~-2~-3~6 sand 0 replace
execute positioned as @s unless block ~-2~-4~6 air at @s run setblock ~-2~-4~6 sand 0 replace
execute positioned as @s unless block ~-2~-5~6 air at @s run setblock ~-2~-5~6 sand 0 replace
execute positioned as @s unless block ~-1~7~-6 air at @s run setblock ~-1~7~-6 sand 0 replace
execute positioned as @s unless block ~-1~6~-6 air at @s run setblock ~-1~6~-6 sand 0 replace
execute positioned as @s unless block ~-1~5~-6 air at @s run setblock ~-1~5~-6 sand 0 replace
execute positioned as @s unless block ~-1~4~-6 air at @s run setblock ~-1~4~-6 sand 0 replace
execute positioned as @s unless block ~-1~3~-6 air at @s run setblock ~-1~3~-6 sand 0 replace
execute positioned as @s unless block ~-1~2~-6 air at @s run setblock ~-1~2~-6 sand 0 replace
execute positioned as @s unless block ~-1~1~-6 air at @s run setblock ~-1~1~-6 sand 0 replace
execute positioned as @s unless block ~-1~0~-6 air at @s run setblock ~-1~0~-6 sand 0 replace
execute positioned as @s unless block ~-1~-1~-6 air at @s run setblock ~-1~-1~-6 sand 0 replace
execute positioned as @s unless block ~-1~-2~-6 air at @s run setblock ~-1~-2~-6 sand 0 replace
execute positioned as @s unless block ~-1~-3~-6 air at @s run setblock ~-1~-3~-6 sand 0 replace
execute positioned as @s unless block ~-1~-4~-6 air at @s run setblock ~-1~-4~-6 sand 0 replace
execute positioned as @s unless block ~-1~-5~-6 air at @s run setblock ~-1~-5~-6 sand 0 replace
execute positioned as @s unless block ~-1~7~6 air at @s run setblock ~-1~7~6 sand 0 replace
execute positioned as @s unless block ~-1~6~6 air at @s run setblock ~-1~6~6 sand 0 replace
execute positioned as @s unless block ~-1~5~6 air at @s run setblock ~-1~5~6 sand 0 replace
execute positioned as @s unless block ~-1~4~6 air at @s run setblock ~-1~4~6 sand 0 replace
execute positioned as @s unless block ~-1~3~6 air at @s run setblock ~-1~3~6 sand 0 replace
execute positioned as @s unless block ~-1~2~6 air at @s run setblock ~-1~2~6 sand 0 replace
execute positioned as @s unless block ~-1~1~6 air at @s run setblock ~-1~1~6 sand 0 replace
execute positioned as @s unless block ~-1~0~6 air at @s run setblock ~-1~0~6 sand 0 replace
execute positioned as @s unless block ~-1~-1~6 air at @s run setblock ~-1~-1~6 sand 0 replace
execute positioned as @s unless block ~-1~-2~6 air at @s run setblock ~-1~-2~6 sand 0 replace
execute positioned as @s unless block ~-1~-3~6 air at @s run setblock ~-1~-3~6 sand 0 replace
execute positioned as @s unless block ~-1~-4~6 air at @s run setblock ~-1~-4~6 sand 0 replace
execute positioned as @s unless block ~-1~-5~6 air at @s run setblock ~-1~-5~6 sand 0 replace
execute positioned as @s unless block ~0~7~-6 air at @s run setblock ~0~7~-6 sand 0 replace
execute positioned as @s unless block ~0~6~-6 air at @s run setblock ~0~6~-6 sand 0 replace
execute positioned as @s unless block ~0~5~-6 air at @s run setblock ~0~5~-6 sand 0 replace
execute positioned as @s unless block ~0~4~-6 air at @s run setblock ~0~4~-6 sand 0 replace
execute positioned as @s unless block ~0~3~-6 air at @s run setblock ~0~3~-6 sand 0 replace
execute positioned as @s unless block ~0~2~-6 air at @s run setblock ~0~2~-6 sand 0 replace
execute positioned as @s unless block ~0~1~-6 air at @s run setblock ~0~1~-6 sand 0 replace
execute positioned as @s unless block ~0~0~-6 air at @s run setblock ~0~0~-6 sand 0 replace
execute positioned as @s unless block ~0~-1~-6 air at @s run setblock ~0~-1~-6 sand 0 replace
execute positioned as @s unless block ~0~-2~-6 air at @s run setblock ~0~-2~-6 sand 0 replace
execute positioned as @s unless block ~0~-3~-6 air at @s run setblock ~0~-3~-6 sand 0 replace
execute positioned as @s unless block ~0~-4~-6 air at @s run setblock ~0~-4~-6 sand 0 replace
execute positioned as @s unless block ~0~-5~-6 air at @s run setblock ~0~-5~-6 sand 0 replace
execute positioned as @s unless block ~0~7~6 air at @s run setblock ~0~7~6 sand 0 replace
execute positioned as @s unless block ~0~6~6 air at @s run setblock ~0~6~6 sand 0 replace
execute positioned as @s unless block ~0~5~6 air at @s run setblock ~0~5~6 sand 0 replace
execute positioned as @s unless block ~0~4~6 air at @s run setblock ~0~4~6 sand 0 replace
execute positioned as @s unless block ~0~3~6 air at @s run setblock ~0~3~6 sand 0 replace
execute positioned as @s unless block ~0~2~6 air at @s run setblock ~0~2~6 sand 0 replace
execute positioned as @s unless block ~0~1~6 air at @s run setblock ~0~1~6 sand 0 replace
execute positioned as @s unless block ~0~0~6 air at @s run setblock ~0~0~6 sand 0 replace
execute positioned as @s unless block ~0~-1~6 air at @s run setblock ~0~-1~6 sand 0 replace
execute positioned as @s unless block ~0~-2~6 air at @s run setblock ~0~-2~6 sand 0 replace
execute positioned as @s unless block ~0~-3~6 air at @s run setblock ~0~-3~6 sand 0 replace
execute positioned as @s unless block ~0~-4~6 air at @s run setblock ~0~-4~6 sand 0 replace
execute positioned as @s unless block ~0~-5~6 air at @s run setblock ~0~-5~6 sand 0 replace
execute positioned as @s unless block ~1~7~-6 air at @s run setblock ~1~7~-6 sand 0 replace
execute positioned as @s unless block ~1~6~-6 air at @s run setblock ~1~6~-6 sand 0 replace
execute positioned as @s unless block ~1~5~-6 air at @s run setblock ~1~5~-6 sand 0 replace
execute positioned as @s unless block ~1~4~-6 air at @s run setblock ~1~4~-6 sand 0 replace
execute positioned as @s unless block ~1~3~-6 air at @s run setblock ~1~3~-6 sand 0 replace
execute positioned as @s unless block ~1~2~-6 air at @s run setblock ~1~2~-6 sand 0 replace
execute positioned as @s unless block ~1~1~-6 air at @s run setblock ~1~1~-6 sand 0 replace
execute positioned as @s unless block ~1~0~-6 air at @s run setblock ~1~0~-6 sand 0 replace
execute positioned as @s unless block ~1~-1~-6 air at @s run setblock ~1~-1~-6 sand 0 replace
execute positioned as @s unless block ~1~-2~-6 air at @s run setblock ~1~-2~-6 sand 0 replace
execute positioned as @s unless block ~1~-3~-6 air at @s run setblock ~1~-3~-6 sand 0 replace
execute positioned as @s unless block ~1~-4~-6 air at @s run setblock ~1~-4~-6 sand 0 replace
execute positioned as @s unless block ~1~-5~-6 air at @s run setblock ~1~-5~-6 sand 0 replace
execute positioned as @s unless block ~1~7~6 air at @s run setblock ~1~7~6 sand 0 replace
execute positioned as @s unless block ~1~6~6 air at @s run setblock ~1~6~6 sand 0 replace
execute positioned as @s unless block ~1~5~6 air at @s run setblock ~1~5~6 sand 0 replace
execute positioned as @s unless block ~1~4~6 air at @s run setblock ~1~4~6 sand 0 replace
execute positioned as @s unless block ~1~3~6 air at @s run setblock ~1~3~6 sand 0 replace
execute positioned as @s unless block ~1~2~6 air at @s run setblock ~1~2~6 sand 0 replace
execute positioned as @s unless block ~1~1~6 air at @s run setblock ~1~1~6 sand 0 replace
execute positioned as @s unless block ~1~0~6 air at @s run setblock ~1~0~6 sand 0 replace
execute positioned as @s unless block ~1~-1~6 air at @s run setblock ~1~-1~6 sand 0 replace
execute positioned as @s unless block ~1~-2~6 air at @s run setblock ~1~-2~6 sand 0 replace
execute positioned as @s unless block ~1~-3~6 air at @s run setblock ~1~-3~6 sand 0 replace
execute positioned as @s unless block ~1~-4~6 air at @s run setblock ~1~-4~6 sand 0 replace
execute positioned as @s unless block ~1~-5~6 air at @s run setblock ~1~-5~6 sand 0 replace
execute positioned as @s unless block ~2~7~-6 air at @s run setblock ~2~7~-6 sand 0 replace
execute positioned as @s unless block ~2~6~-6 air at @s run setblock ~2~6~-6 sand 0 replace
execute positioned as @s unless block ~2~5~-6 air at @s run setblock ~2~5~-6 sand 0 replace
execute positioned as @s unless block ~2~4~-6 air at @s run setblock ~2~4~-6 sand 0 replace
execute positioned as @s unless block ~2~3~-6 air at @s run setblock ~2~3~-6 sand 0 replace
execute positioned as @s unless block ~2~2~-6 air at @s run setblock ~2~2~-6 sand 0 replace
execute positioned as @s unless block ~2~1~-6 air at @s run setblock ~2~1~-6 sand 0 replace
execute positioned as @s unless block ~2~0~-6 air at @s run setblock ~2~0~-6 sand 0 replace
execute positioned as @s unless block ~2~-1~-6 air at @s run setblock ~2~-1~-6 sand 0 replace
execute positioned as @s unless block ~2~-2~-6 air at @s run setblock ~2~-2~-6 sand 0 replace
execute positioned as @s unless block ~2~-3~-6 air at @s run setblock ~2~-3~-6 sand 0 replace
execute positioned as @s unless block ~2~-4~-6 air at @s run setblock ~2~-4~-6 sand 0 replace
execute positioned as @s unless block ~2~-5~-6 air at @s run setblock ~2~-5~-6 sand 0 replace
execute positioned as @s unless block ~2~7~6 air at @s run setblock ~2~7~6 sand 0 replace
execute positioned as @s unless block ~2~6~6 air at @s run setblock ~2~6~6 sand 0 replace
execute positioned as @s unless block ~2~5~6 air at @s run setblock ~2~5~6 sand 0 replace
execute positioned as @s unless block ~2~4~6 air at @s run setblock ~2~4~6 sand 0 replace
execute positioned as @s unless block ~2~3~6 air at @s run setblock ~2~3~6 sand 0 replace
execute positioned as @s unless block ~2~2~6 air at @s run setblock ~2~2~6 sand 0 replace
execute positioned as @s unless block ~2~1~6 air at @s run setblock ~2~1~6 sand 0 replace
execute positioned as @s unless block ~2~0~6 air at @s run setblock ~2~0~6 sand 0 replace
execute positioned as @s unless block ~2~-1~6 air at @s run setblock ~2~-1~6 sand 0 replace
execute positioned as @s unless block ~2~-2~6 air at @s run setblock ~2~-2~6 sand 0 replace
execute positioned as @s unless block ~2~-3~6 air at @s run setblock ~2~-3~6 sand 0 replace
execute positioned as @s unless block ~2~-4~6 air at @s run setblock ~2~-4~6 sand 0 replace
execute positioned as @s unless block ~2~-5~6 air at @s run setblock ~2~-5~6 sand 0 replace
execute positioned as @s unless block ~3~7~-6 air at @s run setblock ~3~7~-6 sand 0 replace
execute positioned as @s unless block ~3~6~-6 air at @s run setblock ~3~6~-6 sand 0 replace
execute positioned as @s unless block ~3~5~-6 air at @s run setblock ~3~5~-6 sand 0 replace
execute positioned as @s unless block ~3~4~-6 air at @s run setblock ~3~4~-6 sand 0 replace
execute positioned as @s unless block ~3~3~-6 air at @s run setblock ~3~3~-6 sand 0 replace
execute positioned as @s unless block ~3~2~-6 air at @s run setblock ~3~2~-6 sand 0 replace
execute positioned as @s unless block ~3~1~-6 air at @s run setblock ~3~1~-6 sand 0 replace
execute positioned as @s unless block ~3~0~-6 air at @s run setblock ~3~0~-6 sand 0 replace
execute positioned as @s unless block ~3~-1~-6 air at @s run setblock ~3~-1~-6 sand 0 replace
execute positioned as @s unless block ~3~-2~-6 air at @s run setblock ~3~-2~-6 sand 0 replace
execute positioned as @s unless block ~3~-3~-6 air at @s run setblock ~3~-3~-6 sand 0 replace
execute positioned as @s unless block ~3~-4~-6 air at @s run setblock ~3~-4~-6 sand 0 replace
execute positioned as @s unless block ~3~-5~-6 air at @s run setblock ~3~-5~-6 sand 0 replace
execute positioned as @s unless block ~3~7~6 air at @s run setblock ~3~7~6 sand 0 replace
execute positioned as @s unless block ~3~6~6 air at @s run setblock ~3~6~6 sand 0 replace
execute positioned as @s unless block ~3~5~6 air at @s run setblock ~3~5~6 sand 0 replace
execute positioned as @s unless block ~3~4~6 air at @s run setblock ~3~4~6 sand 0 replace
execute positioned as @s unless block ~3~3~6 air at @s run setblock ~3~3~6 sand 0 replace
execute positioned as @s unless block ~3~2~6 air at @s run setblock ~3~2~6 sand 0 replace
execute positioned as @s unless block ~3~1~6 air at @s run setblock ~3~1~6 sand 0 replace
execute positioned as @s unless block ~3~0~6 air at @s run setblock ~3~0~6 sand 0 replace
execute positioned as @s unless block ~3~-1~6 air at @s run setblock ~3~-1~6 sand 0 replace
execute positioned as @s unless block ~3~-2~6 air at @s run setblock ~3~-2~6 sand 0 replace
execute positioned as @s unless block ~3~-3~6 air at @s run setblock ~3~-3~6 sand 0 replace
execute positioned as @s unless block ~3~-4~6 air at @s run setblock ~3~-4~6 sand 0 replace
execute positioned as @s unless block ~3~-5~6 air at @s run setblock ~3~-5~6 sand 0 replace
execute positioned as @s unless block ~4~7~-6 air at @s run setblock ~4~7~-6 sand 0 replace
execute positioned as @s unless block ~4~6~-6 air at @s run setblock ~4~6~-6 sand 0 replace
execute positioned as @s unless block ~4~5~-6 air at @s run setblock ~4~5~-6 sand 0 replace
execute positioned as @s unless block ~4~4~-6 air at @s run setblock ~4~4~-6 sand 0 replace
execute positioned as @s unless block ~4~3~-6 air at @s run setblock ~4~3~-6 sand 0 replace
execute positioned as @s unless block ~4~2~-6 air at @s run setblock ~4~2~-6 sand 0 replace
execute positioned as @s unless block ~4~1~-6 air at @s run setblock ~4~1~-6 sand 0 replace
execute positioned as @s unless block ~4~0~-6 air at @s run setblock ~4~0~-6 sand 0 replace
execute positioned as @s unless block ~4~-1~-6 air at @s run setblock ~4~-1~-6 sand 0 replace
execute positioned as @s unless block ~4~-2~-6 air at @s run setblock ~4~-2~-6 sand 0 replace
execute positioned as @s unless block ~4~-3~-6 air at @s run setblock ~4~-3~-6 sand 0 replace
execute positioned as @s unless block ~4~-4~-6 air at @s run setblock ~4~-4~-6 sand 0 replace
execute positioned as @s unless block ~4~-5~-6 air at @s run setblock ~4~-5~-6 sand 0 replace
execute positioned as @s unless block ~4~7~6 air at @s run setblock ~4~7~6 sand 0 replace
execute positioned as @s unless block ~4~6~6 air at @s run setblock ~4~6~6 sand 0 replace
execute positioned as @s unless block ~4~5~6 air at @s run setblock ~4~5~6 sand 0 replace
execute positioned as @s unless block ~4~4~6 air at @s run setblock ~4~4~6 sand 0 replace
execute positioned as @s unless block ~4~3~6 air at @s run setblock ~4~3~6 sand 0 replace
execute positioned as @s unless block ~4~2~6 air at @s run setblock ~4~2~6 sand 0 replace
execute positioned as @s unless block ~4~1~6 air at @s run setblock ~4~1~6 sand 0 replace
execute positioned as @s unless block ~4~0~6 air at @s run setblock ~4~0~6 sand 0 replace
execute positioned as @s unless block ~4~-1~6 air at @s run setblock ~4~-1~6 sand 0 replace
execute positioned as @s unless block ~4~-2~6 air at @s run setblock ~4~-2~6 sand 0 replace
execute positioned as @s unless block ~4~-3~6 air at @s run setblock ~4~-3~6 sand 0 replace
execute positioned as @s unless block ~4~-4~6 air at @s run setblock ~4~-4~6 sand 0 replace
execute positioned as @s unless block ~4~-5~6 air at @s run setblock ~4~-5~6 sand 0 replace
execute positioned as @s unless block ~5~7~-6 air at @s run setblock ~5~7~-6 sand 0 replace
execute positioned as @s unless block ~5~6~-6 air at @s run setblock ~5~6~-6 sand 0 replace
execute positioned as @s unless block ~5~5~-6 air at @s run setblock ~5~5~-6 sand 0 replace
execute positioned as @s unless block ~5~4~-6 air at @s run setblock ~5~4~-6 sand 0 replace
execute positioned as @s unless block ~5~3~-6 air at @s run setblock ~5~3~-6 sand 0 replace
execute positioned as @s unless block ~5~2~-6 air at @s run setblock ~5~2~-6 sand 0 replace
execute positioned as @s unless block ~5~1~-6 air at @s run setblock ~5~1~-6 sand 0 replace
execute positioned as @s unless block ~5~0~-6 air at @s run setblock ~5~0~-6 sand 0 replace
execute positioned as @s unless block ~5~-1~-6 air at @s run setblock ~5~-1~-6 sand 0 replace
execute positioned as @s unless block ~5~-2~-6 air at @s run setblock ~5~-2~-6 sand 0 replace
execute positioned as @s unless block ~5~-3~-6 air at @s run setblock ~5~-3~-6 sand 0 replace
execute positioned as @s unless block ~5~-4~-6 air at @s run setblock ~5~-4~-6 sand 0 replace
execute positioned as @s unless block ~5~-5~-6 air at @s run setblock ~5~-5~-6 sand 0 replace
execute positioned as @s unless block ~5~7~6 air at @s run setblock ~5~7~6 sand 0 replace
execute positioned as @s unless block ~5~6~6 air at @s run setblock ~5~6~6 sand 0 replace
execute positioned as @s unless block ~5~5~6 air at @s run setblock ~5~5~6 sand 0 replace
execute positioned as @s unless block ~5~4~6 air at @s run setblock ~5~4~6 sand 0 replace
execute positioned as @s unless block ~5~3~6 air at @s run setblock ~5~3~6 sand 0 replace
execute positioned as @s unless block ~5~2~6 air at @s run setblock ~5~2~6 sand 0 replace
execute positioned as @s unless block ~5~1~6 air at @s run setblock ~5~1~6 sand 0 replace
execute positioned as @s unless block ~5~0~6 air at @s run setblock ~5~0~6 sand 0 replace
execute positioned as @s unless block ~5~-1~6 air at @s run setblock ~5~-1~6 sand 0 replace
execute positioned as @s unless block ~5~-2~6 air at @s run setblock ~5~-2~6 sand 0 replace
execute positioned as @s unless block ~5~-3~6 air at @s run setblock ~5~-3~6 sand 0 replace
execute positioned as @s unless block ~5~-4~6 air at @s run setblock ~5~-4~6 sand 0 replace
execute positioned as @s unless block ~5~-5~6 air at @s run setblock ~5~-5~6 sand 0 replace
execute positioned as @s unless block ~6~7~-6 air at @s run setblock ~6~7~-6 sand 0 replace
execute positioned as @s unless block ~6~6~-6 air at @s run setblock ~6~6~-6 sand 0 replace
execute positioned as @s unless block ~6~5~-6 air at @s run setblock ~6~5~-6 sand 0 replace
execute positioned as @s unless block ~6~4~-6 air at @s run setblock ~6~4~-6 sand 0 replace
execute positioned as @s unless block ~6~3~-6 air at @s run setblock ~6~3~-6 sand 0 replace
execute positioned as @s unless block ~6~2~-6 air at @s run setblock ~6~2~-6 sand 0 replace
execute positioned as @s unless block ~6~1~-6 air at @s run setblock ~6~1~-6 sand 0 replace
execute positioned as @s unless block ~6~0~-6 air at @s run setblock ~6~0~-6 sand 0 replace
execute positioned as @s unless block ~6~-1~-6 air at @s run setblock ~6~-1~-6 sand 0 replace
execute positioned as @s unless block ~6~-2~-6 air at @s run setblock ~6~-2~-6 sand 0 replace
execute positioned as @s unless block ~6~-3~-6 air at @s run setblock ~6~-3~-6 sand 0 replace
execute positioned as @s unless block ~6~-4~-6 air at @s run setblock ~6~-4~-6 sand 0 replace
execute positioned as @s unless block ~6~-5~-6 air at @s run setblock ~6~-5~-6 sand 0 replace
execute positioned as @s unless block ~6~7~-5 air at @s run setblock ~6~7~-5 sand 0 replace
execute positioned as @s unless block ~6~6~-5 air at @s run setblock ~6~6~-5 sand 0 replace
execute positioned as @s unless block ~6~5~-5 air at @s run setblock ~6~5~-5 sand 0 replace
execute positioned as @s unless block ~6~4~-5 air at @s run setblock ~6~4~-5 sand 0 replace
execute positioned as @s unless block ~6~3~-5 air at @s run setblock ~6~3~-5 sand 0 replace
execute positioned as @s unless block ~6~2~-5 air at @s run setblock ~6~2~-5 sand 0 replace
execute positioned as @s unless block ~6~1~-5 air at @s run setblock ~6~1~-5 sand 0 replace
execute positioned as @s unless block ~6~0~-5 air at @s run setblock ~6~0~-5 sand 0 replace
execute positioned as @s unless block ~6~-1~-5 air at @s run setblock ~6~-1~-5 sand 0 replace
execute positioned as @s unless block ~6~-2~-5 air at @s run setblock ~6~-2~-5 sand 0 replace
execute positioned as @s unless block ~6~-3~-5 air at @s run setblock ~6~-3~-5 sand 0 replace
execute positioned as @s unless block ~6~-4~-5 air at @s run setblock ~6~-4~-5 sand 0 replace
execute positioned as @s unless block ~6~-5~-5 air at @s run setblock ~6~-5~-5 sand 0 replace
execute positioned as @s unless block ~6~7~-4 air at @s run setblock ~6~7~-4 sand 0 replace
execute positioned as @s unless block ~6~6~-4 air at @s run setblock ~6~6~-4 sand 0 replace
execute positioned as @s unless block ~6~5~-4 air at @s run setblock ~6~5~-4 sand 0 replace
execute positioned as @s unless block ~6~4~-4 air at @s run setblock ~6~4~-4 sand 0 replace
execute positioned as @s unless block ~6~3~-4 air at @s run setblock ~6~3~-4 sand 0 replace
execute positioned as @s unless block ~6~2~-4 air at @s run setblock ~6~2~-4 sand 0 replace
execute positioned as @s unless block ~6~1~-4 air at @s run setblock ~6~1~-4 sand 0 replace
execute positioned as @s unless block ~6~0~-4 air at @s run setblock ~6~0~-4 sand 0 replace
execute positioned as @s unless block ~6~-1~-4 air at @s run setblock ~6~-1~-4 sand 0 replace
execute positioned as @s unless block ~6~-2~-4 air at @s run setblock ~6~-2~-4 sand 0 replace
execute positioned as @s unless block ~6~-3~-4 air at @s run setblock ~6~-3~-4 sand 0 replace
execute positioned as @s unless block ~6~-4~-4 air at @s run setblock ~6~-4~-4 sand 0 replace
execute positioned as @s unless block ~6~-5~-4 air at @s run setblock ~6~-5~-4 sand 0 replace
execute positioned as @s unless block ~6~7~-3 air at @s run setblock ~6~7~-3 sand 0 replace
execute positioned as @s unless block ~6~6~-3 air at @s run setblock ~6~6~-3 sand 0 replace
execute positioned as @s unless block ~6~5~-3 air at @s run setblock ~6~5~-3 sand 0 replace
execute positioned as @s unless block ~6~4~-3 air at @s run setblock ~6~4~-3 sand 0 replace
execute positioned as @s unless block ~6~3~-3 air at @s run setblock ~6~3~-3 sand 0 replace
execute positioned as @s unless block ~6~2~-3 air at @s run setblock ~6~2~-3 sand 0 replace
execute positioned as @s unless block ~6~1~-3 air at @s run setblock ~6~1~-3 sand 0 replace
execute positioned as @s unless block ~6~0~-3 air at @s run setblock ~6~0~-3 sand 0 replace
execute positioned as @s unless block ~6~-1~-3 air at @s run setblock ~6~-1~-3 sand 0 replace
execute positioned as @s unless block ~6~-2~-3 air at @s run setblock ~6~-2~-3 sand 0 replace
execute positioned as @s unless block ~6~-3~-3 air at @s run setblock ~6~-3~-3 sand 0 replace
execute positioned as @s unless block ~6~-4~-3 air at @s run setblock ~6~-4~-3 sand 0 replace
execute positioned as @s unless block ~6~-5~-3 air at @s run setblock ~6~-5~-3 sand 0 replace
execute positioned as @s unless block ~6~7~-2 air at @s run setblock ~6~7~-2 sand 0 replace
execute positioned as @s unless block ~6~6~-2 air at @s run setblock ~6~6~-2 sand 0 replace
execute positioned as @s unless block ~6~5~-2 air at @s run setblock ~6~5~-2 sand 0 replace
execute positioned as @s unless block ~6~4~-2 air at @s run setblock ~6~4~-2 sand 0 replace
execute positioned as @s unless block ~6~3~-2 air at @s run setblock ~6~3~-2 sand 0 replace
execute positioned as @s unless block ~6~2~-2 air at @s run setblock ~6~2~-2 sand 0 replace
execute positioned as @s unless block ~6~1~-2 air at @s run setblock ~6~1~-2 sand 0 replace
execute positioned as @s unless block ~6~0~-2 air at @s run setblock ~6~0~-2 sand 0 replace
execute positioned as @s unless block ~6~-1~-2 air at @s run setblock ~6~-1~-2 sand 0 replace
execute positioned as @s unless block ~6~-2~-2 air at @s run setblock ~6~-2~-2 sand 0 replace
execute positioned as @s unless block ~6~-3~-2 air at @s run setblock ~6~-3~-2 sand 0 replace
execute positioned as @s unless block ~6~-4~-2 air at @s run setblock ~6~-4~-2 sand 0 replace
execute positioned as @s unless block ~6~-5~-2 air at @s run setblock ~6~-5~-2 sand 0 replace
execute positioned as @s unless block ~6~7~-1 air at @s run setblock ~6~7~-1 sand 0 replace
execute positioned as @s unless block ~6~6~-1 air at @s run setblock ~6~6~-1 sand 0 replace
execute positioned as @s unless block ~6~5~-1 air at @s run setblock ~6~5~-1 sand 0 replace
execute positioned as @s unless block ~6~4~-1 air at @s run setblock ~6~4~-1 sand 0 replace
execute positioned as @s unless block ~6~3~-1 air at @s run setblock ~6~3~-1 sand 0 replace
execute positioned as @s unless block ~6~2~-1 air at @s run setblock ~6~2~-1 sand 0 replace
execute positioned as @s unless block ~6~1~-1 air at @s run setblock ~6~1~-1 sand 0 replace
execute positioned as @s unless block ~6~0~-1 air at @s run setblock ~6~0~-1 sand 0 replace
execute positioned as @s unless block ~6~-1~-1 air at @s run setblock ~6~-1~-1 sand 0 replace
execute positioned as @s unless block ~6~-2~-1 air at @s run setblock ~6~-2~-1 sand 0 replace
execute positioned as @s unless block ~6~-3~-1 air at @s run setblock ~6~-3~-1 sand 0 replace
execute positioned as @s unless block ~6~-4~-1 air at @s run setblock ~6~-4~-1 sand 0 replace
execute positioned as @s unless block ~6~-5~-1 air at @s run setblock ~6~-5~-1 sand 0 replace
execute positioned as @s unless block ~6~7~0 air at @s run setblock ~6~7~0 sand 0 replace
execute positioned as @s unless block ~6~6~0 air at @s run setblock ~6~6~0 sand 0 replace
execute positioned as @s unless block ~6~5~0 air at @s run setblock ~6~5~0 sand 0 replace
execute positioned as @s unless block ~6~4~0 air at @s run setblock ~6~4~0 sand 0 replace
execute positioned as @s unless block ~6~3~0 air at @s run setblock ~6~3~0 sand 0 replace
execute positioned as @s unless block ~6~2~0 air at @s run setblock ~6~2~0 sand 0 replace
execute positioned as @s unless block ~6~1~0 air at @s run setblock ~6~1~0 sand 0 replace
execute positioned as @s unless block ~6~0~0 air at @s run setblock ~6~0~0 sand 0 replace
execute positioned as @s unless block ~6~-1~0 air at @s run setblock ~6~-1~0 sand 0 replace
execute positioned as @s unless block ~6~-2~0 air at @s run setblock ~6~-2~0 sand 0 replace
execute positioned as @s unless block ~6~-3~0 air at @s run setblock ~6~-3~0 sand 0 replace
execute positioned as @s unless block ~6~-4~0 air at @s run setblock ~6~-4~0 sand 0 replace
execute positioned as @s unless block ~6~-5~0 air at @s run setblock ~6~-5~0 sand 0 replace
execute positioned as @s unless block ~6~7~1 air at @s run setblock ~6~7~1 sand 0 replace
execute positioned as @s unless block ~6~6~1 air at @s run setblock ~6~6~1 sand 0 replace
execute positioned as @s unless block ~6~5~1 air at @s run setblock ~6~5~1 sand 0 replace
execute positioned as @s unless block ~6~4~1 air at @s run setblock ~6~4~1 sand 0 replace
execute positioned as @s unless block ~6~3~1 air at @s run setblock ~6~3~1 sand 0 replace
execute positioned as @s unless block ~6~2~1 air at @s run setblock ~6~2~1 sand 0 replace
execute positioned as @s unless block ~6~1~1 air at @s run setblock ~6~1~1 sand 0 replace
execute positioned as @s unless block ~6~0~1 air at @s run setblock ~6~0~1 sand 0 replace
execute positioned as @s unless block ~6~-1~1 air at @s run setblock ~6~-1~1 sand 0 replace
execute positioned as @s unless block ~6~-2~1 air at @s run setblock ~6~-2~1 sand 0 replace
execute positioned as @s unless block ~6~-3~1 air at @s run setblock ~6~-3~1 sand 0 replace
execute positioned as @s unless block ~6~-4~1 air at @s run setblock ~6~-4~1 sand 0 replace
execute positioned as @s unless block ~6~-5~1 air at @s run setblock ~6~-5~1 sand 0 replace
execute positioned as @s unless block ~6~7~2 air at @s run setblock ~6~7~2 sand 0 replace
execute positioned as @s unless block ~6~6~2 air at @s run setblock ~6~6~2 sand 0 replace
execute positioned as @s unless block ~6~5~2 air at @s run setblock ~6~5~2 sand 0 replace
execute positioned as @s unless block ~6~4~2 air at @s run setblock ~6~4~2 sand 0 replace
execute positioned as @s unless block ~6~3~2 air at @s run setblock ~6~3~2 sand 0 replace
execute positioned as @s unless block ~6~2~2 air at @s run setblock ~6~2~2 sand 0 replace
execute positioned as @s unless block ~6~1~2 air at @s run setblock ~6~1~2 sand 0 replace
execute positioned as @s unless block ~6~0~2 air at @s run setblock ~6~0~2 sand 0 replace
execute positioned as @s unless block ~6~-1~2 air at @s run setblock ~6~-1~2 sand 0 replace
execute positioned as @s unless block ~6~-2~2 air at @s run setblock ~6~-2~2 sand 0 replace
execute positioned as @s unless block ~6~-3~2 air at @s run setblock ~6~-3~2 sand 0 replace
execute positioned as @s unless block ~6~-4~2 air at @s run setblock ~6~-4~2 sand 0 replace
execute positioned as @s unless block ~6~-5~2 air at @s run setblock ~6~-5~2 sand 0 replace
execute positioned as @s unless block ~6~7~3 air at @s run setblock ~6~7~3 sand 0 replace
execute positioned as @s unless block ~6~6~3 air at @s run setblock ~6~6~3 sand 0 replace
execute positioned as @s unless block ~6~5~3 air at @s run setblock ~6~5~3 sand 0 replace
execute positioned as @s unless block ~6~4~3 air at @s run setblock ~6~4~3 sand 0 replace
execute positioned as @s unless block ~6~3~3 air at @s run setblock ~6~3~3 sand 0 replace
execute positioned as @s unless block ~6~2~3 air at @s run setblock ~6~2~3 sand 0 replace
execute positioned as @s unless block ~6~1~3 air at @s run setblock ~6~1~3 sand 0 replace
execute positioned as @s unless block ~6~0~3 air at @s run setblock ~6~0~3 sand 0 replace
execute positioned as @s unless block ~6~-1~3 air at @s run setblock ~6~-1~3 sand 0 replace
execute positioned as @s unless block ~6~-2~3 air at @s run setblock ~6~-2~3 sand 0 replace
execute positioned as @s unless block ~6~-3~3 air at @s run setblock ~6~-3~3 sand 0 replace
execute positioned as @s unless block ~6~-4~3 air at @s run setblock ~6~-4~3 sand 0 replace
execute positioned as @s unless block ~6~-5~3 air at @s run setblock ~6~-5~3 sand 0 replace
execute positioned as @s unless block ~6~7~4 air at @s run setblock ~6~7~4 sand 0 replace
execute positioned as @s unless block ~6~6~4 air at @s run setblock ~6~6~4 sand 0 replace
execute positioned as @s unless block ~6~5~4 air at @s run setblock ~6~5~4 sand 0 replace
execute positioned as @s unless block ~6~4~4 air at @s run setblock ~6~4~4 sand 0 replace
execute positioned as @s unless block ~6~3~4 air at @s run setblock ~6~3~4 sand 0 replace
execute positioned as @s unless block ~6~2~4 air at @s run setblock ~6~2~4 sand 0 replace
execute positioned as @s unless block ~6~1~4 air at @s run setblock ~6~1~4 sand 0 replace
execute positioned as @s unless block ~6~0~4 air at @s run setblock ~6~0~4 sand 0 replace
execute positioned as @s unless block ~6~-1~4 air at @s run setblock ~6~-1~4 sand 0 replace
execute positioned as @s unless block ~6~-2~4 air at @s run setblock ~6~-2~4 sand 0 replace
execute positioned as @s unless block ~6~-3~4 air at @s run setblock ~6~-3~4 sand 0 replace
execute positioned as @s unless block ~6~-4~4 air at @s run setblock ~6~-4~4 sand 0 replace
execute positioned as @s unless block ~6~-5~4 air at @s run setblock ~6~-5~4 sand 0 replace
execute positioned as @s unless block ~6~7~5 air at @s run setblock ~6~7~5 sand 0 replace
execute positioned as @s unless block ~6~6~5 air at @s run setblock ~6~6~5 sand 0 replace
execute positioned as @s unless block ~6~5~5 air at @s run setblock ~6~5~5 sand 0 replace
execute positioned as @s unless block ~6~4~5 air at @s run setblock ~6~4~5 sand 0 replace
execute positioned as @s unless block ~6~3~5 air at @s run setblock ~6~3~5 sand 0 replace
execute positioned as @s unless block ~6~2~5 air at @s run setblock ~6~2~5 sand 0 replace
execute positioned as @s unless block ~6~1~5 air at @s run setblock ~6~1~5 sand 0 replace
execute positioned as @s unless block ~6~0~5 air at @s run setblock ~6~0~5 sand 0 replace
execute positioned as @s unless block ~6~-1~5 air at @s run setblock ~6~-1~5 sand 0 replace
execute positioned as @s unless block ~6~-2~5 air at @s run setblock ~6~-2~5 sand 0 replace
execute positioned as @s unless block ~6~-3~5 air at @s run setblock ~6~-3~5 sand 0 replace
execute positioned as @s unless block ~6~-4~5 air at @s run setblock ~6~-4~5 sand 0 replace
execute positioned as @s unless block ~6~-5~5 air at @s run setblock ~6~-5~5 sand 0 replace
execute positioned as @s unless block ~6~7~6 air at @s run setblock ~6~7~6 sand 0 replace
execute positioned as @s unless block ~6~6~6 air at @s run setblock ~6~6~6 sand 0 replace
execute positioned as @s unless block ~6~5~6 air at @s run setblock ~6~5~6 sand 0 replace
execute positioned as @s unless block ~6~4~6 air at @s run setblock ~6~4~6 sand 0 replace
execute positioned as @s unless block ~6~3~6 air at @s run setblock ~6~3~6 sand 0 replace
execute positioned as @s unless block ~6~2~6 air at @s run setblock ~6~2~6 sand 0 replace
execute positioned as @s unless block ~6~1~6 air at @s run setblock ~6~1~6 sand 0 replace
execute positioned as @s unless block ~6~0~6 air at @s run setblock ~6~0~6 sand 0 replace
execute positioned as @s unless block ~6~-1~6 air at @s run setblock ~6~-1~6 sand 0 replace
execute positioned as @s unless block ~6~-2~6 air at @s run setblock ~6~-2~6 sand 0 replace
execute positioned as @s unless block ~6~-3~6 air at @s run setblock ~6~-3~6 sand 0 replace
execute positioned as @s unless block ~6~-4~6 air at @s run setblock ~6~-4~6 sand 0 replace
execute positioned as @s unless block ~6~-5~6 air at @s run setblock ~6~-5~6 sand 0 replace
