execute as @s unless block ~-3~7~-3 air at @s run setblock ~-3~7~-3 sand 0 replace
execute as @s unless block ~-3~6~-3 air at @s run setblock ~-3~6~-3 sand 0 replace
execute as @s unless block ~-3~5~-3 air at @s run setblock ~-3~5~-3 sand 0 replace
execute as @s unless block ~-3~4~-3 air at @s run setblock ~-3~4~-3 sand 0 replace
execute as @s unless block ~-3~3~-3 air at @s run setblock ~-3~3~-3 sand 0 replace
execute as @s unless block ~-3~2~-3 air at @s run setblock ~-3~2~-3 sand 0 replace
execute as @s unless block ~-3~1~-3 air at @s run setblock ~-3~1~-3 sand 0 replace
execute as @s unless block ~-3~0~-3 air at @s run setblock ~-3~0~-3 sand 0 replace
execute as @s unless block ~-3~-1~-3 air at @s run setblock ~-3~-1~-3 sand 0 replace
execute as @s unless block ~-3~-2~-3 air at @s run setblock ~-3~-2~-3 sand 0 replace
execute as @s unless block ~-3~-3~-3 air at @s run setblock ~-3~-3~-3 sand 0 replace
execute as @s unless block ~-3~-4~-3 air at @s run setblock ~-3~-4~-3 sand 0 replace
execute as @s unless block ~-3~-5~-3 air at @s run setblock ~-3~-5~-3 sand 0 replace
execute as @s unless block ~-3~7~-2 air at @s run setblock ~-3~7~-2 sand 0 replace
execute as @s unless block ~-3~6~-2 air at @s run setblock ~-3~6~-2 sand 0 replace
execute as @s unless block ~-3~5~-2 air at @s run setblock ~-3~5~-2 sand 0 replace
execute as @s unless block ~-3~4~-2 air at @s run setblock ~-3~4~-2 sand 0 replace
execute as @s unless block ~-3~3~-2 air at @s run setblock ~-3~3~-2 sand 0 replace
execute as @s unless block ~-3~2~-2 air at @s run setblock ~-3~2~-2 sand 0 replace
execute as @s unless block ~-3~1~-2 air at @s run setblock ~-3~1~-2 sand 0 replace
execute as @s unless block ~-3~0~-2 air at @s run setblock ~-3~0~-2 sand 0 replace
execute as @s unless block ~-3~-1~-2 air at @s run setblock ~-3~-1~-2 sand 0 replace
execute as @s unless block ~-3~-2~-2 air at @s run setblock ~-3~-2~-2 sand 0 replace
execute as @s unless block ~-3~-3~-2 air at @s run setblock ~-3~-3~-2 sand 0 replace
execute as @s unless block ~-3~-4~-2 air at @s run setblock ~-3~-4~-2 sand 0 replace
execute as @s unless block ~-3~-5~-2 air at @s run setblock ~-3~-5~-2 sand 0 replace
execute as @s unless block ~-3~7~-1 air at @s run setblock ~-3~7~-1 sand 0 replace
execute as @s unless block ~-3~6~-1 air at @s run setblock ~-3~6~-1 sand 0 replace
execute as @s unless block ~-3~5~-1 air at @s run setblock ~-3~5~-1 sand 0 replace
execute as @s unless block ~-3~4~-1 air at @s run setblock ~-3~4~-1 sand 0 replace
execute as @s unless block ~-3~3~-1 air at @s run setblock ~-3~3~-1 sand 0 replace
execute as @s unless block ~-3~2~-1 air at @s run setblock ~-3~2~-1 sand 0 replace
execute as @s unless block ~-3~1~-1 air at @s run setblock ~-3~1~-1 sand 0 replace
execute as @s unless block ~-3~0~-1 air at @s run setblock ~-3~0~-1 sand 0 replace
execute as @s unless block ~-3~-1~-1 air at @s run setblock ~-3~-1~-1 sand 0 replace
execute as @s unless block ~-3~-2~-1 air at @s run setblock ~-3~-2~-1 sand 0 replace
execute as @s unless block ~-3~-3~-1 air at @s run setblock ~-3~-3~-1 sand 0 replace
execute as @s unless block ~-3~-4~-1 air at @s run setblock ~-3~-4~-1 sand 0 replace
execute as @s unless block ~-3~-5~-1 air at @s run setblock ~-3~-5~-1 sand 0 replace
execute as @s unless block ~-3~7~0 air at @s run setblock ~-3~7~0 sand 0 replace
execute as @s unless block ~-3~6~0 air at @s run setblock ~-3~6~0 sand 0 replace
execute as @s unless block ~-3~5~0 air at @s run setblock ~-3~5~0 sand 0 replace
execute as @s unless block ~-3~4~0 air at @s run setblock ~-3~4~0 sand 0 replace
execute as @s unless block ~-3~3~0 air at @s run setblock ~-3~3~0 sand 0 replace
execute as @s unless block ~-3~2~0 air at @s run setblock ~-3~2~0 sand 0 replace
execute as @s unless block ~-3~1~0 air at @s run setblock ~-3~1~0 sand 0 replace
execute as @s unless block ~-3~0~0 air at @s run setblock ~-3~0~0 sand 0 replace
execute as @s unless block ~-3~-1~0 air at @s run setblock ~-3~-1~0 sand 0 replace
execute as @s unless block ~-3~-2~0 air at @s run setblock ~-3~-2~0 sand 0 replace
execute as @s unless block ~-3~-3~0 air at @s run setblock ~-3~-3~0 sand 0 replace
execute as @s unless block ~-3~-4~0 air at @s run setblock ~-3~-4~0 sand 0 replace
execute as @s unless block ~-3~-5~0 air at @s run setblock ~-3~-5~0 sand 0 replace
execute as @s unless block ~-3~7~1 air at @s run setblock ~-3~7~1 sand 0 replace
execute as @s unless block ~-3~6~1 air at @s run setblock ~-3~6~1 sand 0 replace
execute as @s unless block ~-3~5~1 air at @s run setblock ~-3~5~1 sand 0 replace
execute as @s unless block ~-3~4~1 air at @s run setblock ~-3~4~1 sand 0 replace
execute as @s unless block ~-3~3~1 air at @s run setblock ~-3~3~1 sand 0 replace
execute as @s unless block ~-3~2~1 air at @s run setblock ~-3~2~1 sand 0 replace
execute as @s unless block ~-3~1~1 air at @s run setblock ~-3~1~1 sand 0 replace
execute as @s unless block ~-3~0~1 air at @s run setblock ~-3~0~1 sand 0 replace
execute as @s unless block ~-3~-1~1 air at @s run setblock ~-3~-1~1 sand 0 replace
execute as @s unless block ~-3~-2~1 air at @s run setblock ~-3~-2~1 sand 0 replace
execute as @s unless block ~-3~-3~1 air at @s run setblock ~-3~-3~1 sand 0 replace
execute as @s unless block ~-3~-4~1 air at @s run setblock ~-3~-4~1 sand 0 replace
execute as @s unless block ~-3~-5~1 air at @s run setblock ~-3~-5~1 sand 0 replace
execute as @s unless block ~-3~7~2 air at @s run setblock ~-3~7~2 sand 0 replace
execute as @s unless block ~-3~6~2 air at @s run setblock ~-3~6~2 sand 0 replace
execute as @s unless block ~-3~5~2 air at @s run setblock ~-3~5~2 sand 0 replace
execute as @s unless block ~-3~4~2 air at @s run setblock ~-3~4~2 sand 0 replace
execute as @s unless block ~-3~3~2 air at @s run setblock ~-3~3~2 sand 0 replace
execute as @s unless block ~-3~2~2 air at @s run setblock ~-3~2~2 sand 0 replace
execute as @s unless block ~-3~1~2 air at @s run setblock ~-3~1~2 sand 0 replace
execute as @s unless block ~-3~0~2 air at @s run setblock ~-3~0~2 sand 0 replace
execute as @s unless block ~-3~-1~2 air at @s run setblock ~-3~-1~2 sand 0 replace
execute as @s unless block ~-3~-2~2 air at @s run setblock ~-3~-2~2 sand 0 replace
execute as @s unless block ~-3~-3~2 air at @s run setblock ~-3~-3~2 sand 0 replace
execute as @s unless block ~-3~-4~2 air at @s run setblock ~-3~-4~2 sand 0 replace
execute as @s unless block ~-3~-5~2 air at @s run setblock ~-3~-5~2 sand 0 replace
execute as @s unless block ~-3~7~3 air at @s run setblock ~-3~7~3 sand 0 replace
execute as @s unless block ~-3~6~3 air at @s run setblock ~-3~6~3 sand 0 replace
execute as @s unless block ~-3~5~3 air at @s run setblock ~-3~5~3 sand 0 replace
execute as @s unless block ~-3~4~3 air at @s run setblock ~-3~4~3 sand 0 replace
execute as @s unless block ~-3~3~3 air at @s run setblock ~-3~3~3 sand 0 replace
execute as @s unless block ~-3~2~3 air at @s run setblock ~-3~2~3 sand 0 replace
execute as @s unless block ~-3~1~3 air at @s run setblock ~-3~1~3 sand 0 replace
execute as @s unless block ~-3~0~3 air at @s run setblock ~-3~0~3 sand 0 replace
execute as @s unless block ~-3~-1~3 air at @s run setblock ~-3~-1~3 sand 0 replace
execute as @s unless block ~-3~-2~3 air at @s run setblock ~-3~-2~3 sand 0 replace
execute as @s unless block ~-3~-3~3 air at @s run setblock ~-3~-3~3 sand 0 replace
execute as @s unless block ~-3~-4~3 air at @s run setblock ~-3~-4~3 sand 0 replace
execute as @s unless block ~-3~-5~3 air at @s run setblock ~-3~-5~3 sand 0 replace
execute as @s unless block ~-2~7~-3 air at @s run setblock ~-2~7~-3 sand 0 replace
execute as @s unless block ~-2~6~-3 air at @s run setblock ~-2~6~-3 sand 0 replace
execute as @s unless block ~-2~5~-3 air at @s run setblock ~-2~5~-3 sand 0 replace
execute as @s unless block ~-2~4~-3 air at @s run setblock ~-2~4~-3 sand 0 replace
execute as @s unless block ~-2~3~-3 air at @s run setblock ~-2~3~-3 sand 0 replace
execute as @s unless block ~-2~2~-3 air at @s run setblock ~-2~2~-3 sand 0 replace
execute as @s unless block ~-2~1~-3 air at @s run setblock ~-2~1~-3 sand 0 replace
execute as @s unless block ~-2~0~-3 air at @s run setblock ~-2~0~-3 sand 0 replace
execute as @s unless block ~-2~-1~-3 air at @s run setblock ~-2~-1~-3 sand 0 replace
execute as @s unless block ~-2~-2~-3 air at @s run setblock ~-2~-2~-3 sand 0 replace
execute as @s unless block ~-2~-3~-3 air at @s run setblock ~-2~-3~-3 sand 0 replace
execute as @s unless block ~-2~-4~-3 air at @s run setblock ~-2~-4~-3 sand 0 replace
execute as @s unless block ~-2~-5~-3 air at @s run setblock ~-2~-5~-3 sand 0 replace
execute as @s unless block ~-2~7~3 air at @s run setblock ~-2~7~3 sand 0 replace
execute as @s unless block ~-2~6~3 air at @s run setblock ~-2~6~3 sand 0 replace
execute as @s unless block ~-2~5~3 air at @s run setblock ~-2~5~3 sand 0 replace
execute as @s unless block ~-2~4~3 air at @s run setblock ~-2~4~3 sand 0 replace
execute as @s unless block ~-2~3~3 air at @s run setblock ~-2~3~3 sand 0 replace
execute as @s unless block ~-2~2~3 air at @s run setblock ~-2~2~3 sand 0 replace
execute as @s unless block ~-2~1~3 air at @s run setblock ~-2~1~3 sand 0 replace
execute as @s unless block ~-2~0~3 air at @s run setblock ~-2~0~3 sand 0 replace
execute as @s unless block ~-2~-1~3 air at @s run setblock ~-2~-1~3 sand 0 replace
execute as @s unless block ~-2~-2~3 air at @s run setblock ~-2~-2~3 sand 0 replace
execute as @s unless block ~-2~-3~3 air at @s run setblock ~-2~-3~3 sand 0 replace
execute as @s unless block ~-2~-4~3 air at @s run setblock ~-2~-4~3 sand 0 replace
execute as @s unless block ~-2~-5~3 air at @s run setblock ~-2~-5~3 sand 0 replace
execute as @s unless block ~-1~7~-3 air at @s run setblock ~-1~7~-3 sand 0 replace
execute as @s unless block ~-1~6~-3 air at @s run setblock ~-1~6~-3 sand 0 replace
execute as @s unless block ~-1~5~-3 air at @s run setblock ~-1~5~-3 sand 0 replace
execute as @s unless block ~-1~4~-3 air at @s run setblock ~-1~4~-3 sand 0 replace
execute as @s unless block ~-1~3~-3 air at @s run setblock ~-1~3~-3 sand 0 replace
execute as @s unless block ~-1~2~-3 air at @s run setblock ~-1~2~-3 sand 0 replace
execute as @s unless block ~-1~1~-3 air at @s run setblock ~-1~1~-3 sand 0 replace
execute as @s unless block ~-1~0~-3 air at @s run setblock ~-1~0~-3 sand 0 replace
execute as @s unless block ~-1~-1~-3 air at @s run setblock ~-1~-1~-3 sand 0 replace
execute as @s unless block ~-1~-2~-3 air at @s run setblock ~-1~-2~-3 sand 0 replace
execute as @s unless block ~-1~-3~-3 air at @s run setblock ~-1~-3~-3 sand 0 replace
execute as @s unless block ~-1~-4~-3 air at @s run setblock ~-1~-4~-3 sand 0 replace
execute as @s unless block ~-1~-5~-3 air at @s run setblock ~-1~-5~-3 sand 0 replace
execute as @s unless block ~-1~7~3 air at @s run setblock ~-1~7~3 sand 0 replace
execute as @s unless block ~-1~6~3 air at @s run setblock ~-1~6~3 sand 0 replace
execute as @s unless block ~-1~5~3 air at @s run setblock ~-1~5~3 sand 0 replace
execute as @s unless block ~-1~4~3 air at @s run setblock ~-1~4~3 sand 0 replace
execute as @s unless block ~-1~3~3 air at @s run setblock ~-1~3~3 sand 0 replace
execute as @s unless block ~-1~2~3 air at @s run setblock ~-1~2~3 sand 0 replace
execute as @s unless block ~-1~1~3 air at @s run setblock ~-1~1~3 sand 0 replace
execute as @s unless block ~-1~0~3 air at @s run setblock ~-1~0~3 sand 0 replace
execute as @s unless block ~-1~-1~3 air at @s run setblock ~-1~-1~3 sand 0 replace
execute as @s unless block ~-1~-2~3 air at @s run setblock ~-1~-2~3 sand 0 replace
execute as @s unless block ~-1~-3~3 air at @s run setblock ~-1~-3~3 sand 0 replace
execute as @s unless block ~-1~-4~3 air at @s run setblock ~-1~-4~3 sand 0 replace
execute as @s unless block ~-1~-5~3 air at @s run setblock ~-1~-5~3 sand 0 replace
execute as @s unless block ~0~7~-3 air at @s run setblock ~0~7~-3 sand 0 replace
execute as @s unless block ~0~6~-3 air at @s run setblock ~0~6~-3 sand 0 replace
execute as @s unless block ~0~5~-3 air at @s run setblock ~0~5~-3 sand 0 replace
execute as @s unless block ~0~4~-3 air at @s run setblock ~0~4~-3 sand 0 replace
execute as @s unless block ~0~3~-3 air at @s run setblock ~0~3~-3 sand 0 replace
execute as @s unless block ~0~2~-3 air at @s run setblock ~0~2~-3 sand 0 replace
execute as @s unless block ~0~1~-3 air at @s run setblock ~0~1~-3 sand 0 replace
execute as @s unless block ~0~0~-3 air at @s run setblock ~0~0~-3 sand 0 replace
execute as @s unless block ~0~-1~-3 air at @s run setblock ~0~-1~-3 sand 0 replace
execute as @s unless block ~0~-2~-3 air at @s run setblock ~0~-2~-3 sand 0 replace
execute as @s unless block ~0~-3~-3 air at @s run setblock ~0~-3~-3 sand 0 replace
execute as @s unless block ~0~-4~-3 air at @s run setblock ~0~-4~-3 sand 0 replace
execute as @s unless block ~0~-5~-3 air at @s run setblock ~0~-5~-3 sand 0 replace
execute as @s unless block ~0~7~3 air at @s run setblock ~0~7~3 sand 0 replace
execute as @s unless block ~0~6~3 air at @s run setblock ~0~6~3 sand 0 replace
execute as @s unless block ~0~5~3 air at @s run setblock ~0~5~3 sand 0 replace
execute as @s unless block ~0~4~3 air at @s run setblock ~0~4~3 sand 0 replace
execute as @s unless block ~0~3~3 air at @s run setblock ~0~3~3 sand 0 replace
execute as @s unless block ~0~2~3 air at @s run setblock ~0~2~3 sand 0 replace
execute as @s unless block ~0~1~3 air at @s run setblock ~0~1~3 sand 0 replace
execute as @s unless block ~0~0~3 air at @s run setblock ~0~0~3 sand 0 replace
execute as @s unless block ~0~-1~3 air at @s run setblock ~0~-1~3 sand 0 replace
execute as @s unless block ~0~-2~3 air at @s run setblock ~0~-2~3 sand 0 replace
execute as @s unless block ~0~-3~3 air at @s run setblock ~0~-3~3 sand 0 replace
execute as @s unless block ~0~-4~3 air at @s run setblock ~0~-4~3 sand 0 replace
execute as @s unless block ~0~-5~3 air at @s run setblock ~0~-5~3 sand 0 replace
execute as @s unless block ~1~7~-3 air at @s run setblock ~1~7~-3 sand 0 replace
execute as @s unless block ~1~6~-3 air at @s run setblock ~1~6~-3 sand 0 replace
execute as @s unless block ~1~5~-3 air at @s run setblock ~1~5~-3 sand 0 replace
execute as @s unless block ~1~4~-3 air at @s run setblock ~1~4~-3 sand 0 replace
execute as @s unless block ~1~3~-3 air at @s run setblock ~1~3~-3 sand 0 replace
execute as @s unless block ~1~2~-3 air at @s run setblock ~1~2~-3 sand 0 replace
execute as @s unless block ~1~1~-3 air at @s run setblock ~1~1~-3 sand 0 replace
execute as @s unless block ~1~0~-3 air at @s run setblock ~1~0~-3 sand 0 replace
execute as @s unless block ~1~-1~-3 air at @s run setblock ~1~-1~-3 sand 0 replace
execute as @s unless block ~1~-2~-3 air at @s run setblock ~1~-2~-3 sand 0 replace
execute as @s unless block ~1~-3~-3 air at @s run setblock ~1~-3~-3 sand 0 replace
execute as @s unless block ~1~-4~-3 air at @s run setblock ~1~-4~-3 sand 0 replace
execute as @s unless block ~1~-5~-3 air at @s run setblock ~1~-5~-3 sand 0 replace
execute as @s unless block ~1~7~3 air at @s run setblock ~1~7~3 sand 0 replace
execute as @s unless block ~1~6~3 air at @s run setblock ~1~6~3 sand 0 replace
execute as @s unless block ~1~5~3 air at @s run setblock ~1~5~3 sand 0 replace
execute as @s unless block ~1~4~3 air at @s run setblock ~1~4~3 sand 0 replace
execute as @s unless block ~1~3~3 air at @s run setblock ~1~3~3 sand 0 replace
execute as @s unless block ~1~2~3 air at @s run setblock ~1~2~3 sand 0 replace
execute as @s unless block ~1~1~3 air at @s run setblock ~1~1~3 sand 0 replace
execute as @s unless block ~1~0~3 air at @s run setblock ~1~0~3 sand 0 replace
execute as @s unless block ~1~-1~3 air at @s run setblock ~1~-1~3 sand 0 replace
execute as @s unless block ~1~-2~3 air at @s run setblock ~1~-2~3 sand 0 replace
execute as @s unless block ~1~-3~3 air at @s run setblock ~1~-3~3 sand 0 replace
execute as @s unless block ~1~-4~3 air at @s run setblock ~1~-4~3 sand 0 replace
execute as @s unless block ~1~-5~3 air at @s run setblock ~1~-5~3 sand 0 replace
execute as @s unless block ~2~7~-3 air at @s run setblock ~2~7~-3 sand 0 replace
execute as @s unless block ~2~6~-3 air at @s run setblock ~2~6~-3 sand 0 replace
execute as @s unless block ~2~5~-3 air at @s run setblock ~2~5~-3 sand 0 replace
execute as @s unless block ~2~4~-3 air at @s run setblock ~2~4~-3 sand 0 replace
execute as @s unless block ~2~3~-3 air at @s run setblock ~2~3~-3 sand 0 replace
execute as @s unless block ~2~2~-3 air at @s run setblock ~2~2~-3 sand 0 replace
execute as @s unless block ~2~1~-3 air at @s run setblock ~2~1~-3 sand 0 replace
execute as @s unless block ~2~0~-3 air at @s run setblock ~2~0~-3 sand 0 replace
execute as @s unless block ~2~-1~-3 air at @s run setblock ~2~-1~-3 sand 0 replace
execute as @s unless block ~2~-2~-3 air at @s run setblock ~2~-2~-3 sand 0 replace
execute as @s unless block ~2~-3~-3 air at @s run setblock ~2~-3~-3 sand 0 replace
execute as @s unless block ~2~-4~-3 air at @s run setblock ~2~-4~-3 sand 0 replace
execute as @s unless block ~2~-5~-3 air at @s run setblock ~2~-5~-3 sand 0 replace
execute as @s unless block ~2~7~3 air at @s run setblock ~2~7~3 sand 0 replace
execute as @s unless block ~2~6~3 air at @s run setblock ~2~6~3 sand 0 replace
execute as @s unless block ~2~5~3 air at @s run setblock ~2~5~3 sand 0 replace
execute as @s unless block ~2~4~3 air at @s run setblock ~2~4~3 sand 0 replace
execute as @s unless block ~2~3~3 air at @s run setblock ~2~3~3 sand 0 replace
execute as @s unless block ~2~2~3 air at @s run setblock ~2~2~3 sand 0 replace
execute as @s unless block ~2~1~3 air at @s run setblock ~2~1~3 sand 0 replace
execute as @s unless block ~2~0~3 air at @s run setblock ~2~0~3 sand 0 replace
execute as @s unless block ~2~-1~3 air at @s run setblock ~2~-1~3 sand 0 replace
execute as @s unless block ~2~-2~3 air at @s run setblock ~2~-2~3 sand 0 replace
execute as @s unless block ~2~-3~3 air at @s run setblock ~2~-3~3 sand 0 replace
execute as @s unless block ~2~-4~3 air at @s run setblock ~2~-4~3 sand 0 replace
execute as @s unless block ~2~-5~3 air at @s run setblock ~2~-5~3 sand 0 replace
execute as @s unless block ~3~7~-3 air at @s run setblock ~3~7~-3 sand 0 replace
execute as @s unless block ~3~6~-3 air at @s run setblock ~3~6~-3 sand 0 replace
execute as @s unless block ~3~5~-3 air at @s run setblock ~3~5~-3 sand 0 replace
execute as @s unless block ~3~4~-3 air at @s run setblock ~3~4~-3 sand 0 replace
execute as @s unless block ~3~3~-3 air at @s run setblock ~3~3~-3 sand 0 replace
execute as @s unless block ~3~2~-3 air at @s run setblock ~3~2~-3 sand 0 replace
execute as @s unless block ~3~1~-3 air at @s run setblock ~3~1~-3 sand 0 replace
execute as @s unless block ~3~0~-3 air at @s run setblock ~3~0~-3 sand 0 replace
execute as @s unless block ~3~-1~-3 air at @s run setblock ~3~-1~-3 sand 0 replace
execute as @s unless block ~3~-2~-3 air at @s run setblock ~3~-2~-3 sand 0 replace
execute as @s unless block ~3~-3~-3 air at @s run setblock ~3~-3~-3 sand 0 replace
execute as @s unless block ~3~-4~-3 air at @s run setblock ~3~-4~-3 sand 0 replace
execute as @s unless block ~3~-5~-3 air at @s run setblock ~3~-5~-3 sand 0 replace
execute as @s unless block ~3~7~-2 air at @s run setblock ~3~7~-2 sand 0 replace
execute as @s unless block ~3~6~-2 air at @s run setblock ~3~6~-2 sand 0 replace
execute as @s unless block ~3~5~-2 air at @s run setblock ~3~5~-2 sand 0 replace
execute as @s unless block ~3~4~-2 air at @s run setblock ~3~4~-2 sand 0 replace
execute as @s unless block ~3~3~-2 air at @s run setblock ~3~3~-2 sand 0 replace
execute as @s unless block ~3~2~-2 air at @s run setblock ~3~2~-2 sand 0 replace
execute as @s unless block ~3~1~-2 air at @s run setblock ~3~1~-2 sand 0 replace
execute as @s unless block ~3~0~-2 air at @s run setblock ~3~0~-2 sand 0 replace
execute as @s unless block ~3~-1~-2 air at @s run setblock ~3~-1~-2 sand 0 replace
execute as @s unless block ~3~-2~-2 air at @s run setblock ~3~-2~-2 sand 0 replace
execute as @s unless block ~3~-3~-2 air at @s run setblock ~3~-3~-2 sand 0 replace
execute as @s unless block ~3~-4~-2 air at @s run setblock ~3~-4~-2 sand 0 replace
execute as @s unless block ~3~-5~-2 air at @s run setblock ~3~-5~-2 sand 0 replace
execute as @s unless block ~3~7~-1 air at @s run setblock ~3~7~-1 sand 0 replace
execute as @s unless block ~3~6~-1 air at @s run setblock ~3~6~-1 sand 0 replace
execute as @s unless block ~3~5~-1 air at @s run setblock ~3~5~-1 sand 0 replace
execute as @s unless block ~3~4~-1 air at @s run setblock ~3~4~-1 sand 0 replace
execute as @s unless block ~3~3~-1 air at @s run setblock ~3~3~-1 sand 0 replace
execute as @s unless block ~3~2~-1 air at @s run setblock ~3~2~-1 sand 0 replace
execute as @s unless block ~3~1~-1 air at @s run setblock ~3~1~-1 sand 0 replace
execute as @s unless block ~3~0~-1 air at @s run setblock ~3~0~-1 sand 0 replace
execute as @s unless block ~3~-1~-1 air at @s run setblock ~3~-1~-1 sand 0 replace
execute as @s unless block ~3~-2~-1 air at @s run setblock ~3~-2~-1 sand 0 replace
execute as @s unless block ~3~-3~-1 air at @s run setblock ~3~-3~-1 sand 0 replace
execute as @s unless block ~3~-4~-1 air at @s run setblock ~3~-4~-1 sand 0 replace
execute as @s unless block ~3~-5~-1 air at @s run setblock ~3~-5~-1 sand 0 replace
execute as @s unless block ~3~7~0 air at @s run setblock ~3~7~0 sand 0 replace
execute as @s unless block ~3~6~0 air at @s run setblock ~3~6~0 sand 0 replace
execute as @s unless block ~3~5~0 air at @s run setblock ~3~5~0 sand 0 replace
execute as @s unless block ~3~4~0 air at @s run setblock ~3~4~0 sand 0 replace
execute as @s unless block ~3~3~0 air at @s run setblock ~3~3~0 sand 0 replace
execute as @s unless block ~3~2~0 air at @s run setblock ~3~2~0 sand 0 replace
execute as @s unless block ~3~1~0 air at @s run setblock ~3~1~0 sand 0 replace
execute as @s unless block ~3~0~0 air at @s run setblock ~3~0~0 sand 0 replace
execute as @s unless block ~3~-1~0 air at @s run setblock ~3~-1~0 sand 0 replace
execute as @s unless block ~3~-2~0 air at @s run setblock ~3~-2~0 sand 0 replace
execute as @s unless block ~3~-3~0 air at @s run setblock ~3~-3~0 sand 0 replace
execute as @s unless block ~3~-4~0 air at @s run setblock ~3~-4~0 sand 0 replace
execute as @s unless block ~3~-5~0 air at @s run setblock ~3~-5~0 sand 0 replace
execute as @s unless block ~3~7~1 air at @s run setblock ~3~7~1 sand 0 replace
execute as @s unless block ~3~6~1 air at @s run setblock ~3~6~1 sand 0 replace
execute as @s unless block ~3~5~1 air at @s run setblock ~3~5~1 sand 0 replace
execute as @s unless block ~3~4~1 air at @s run setblock ~3~4~1 sand 0 replace
execute as @s unless block ~3~3~1 air at @s run setblock ~3~3~1 sand 0 replace
execute as @s unless block ~3~2~1 air at @s run setblock ~3~2~1 sand 0 replace
execute as @s unless block ~3~1~1 air at @s run setblock ~3~1~1 sand 0 replace
execute as @s unless block ~3~0~1 air at @s run setblock ~3~0~1 sand 0 replace
execute as @s unless block ~3~-1~1 air at @s run setblock ~3~-1~1 sand 0 replace
execute as @s unless block ~3~-2~1 air at @s run setblock ~3~-2~1 sand 0 replace
execute as @s unless block ~3~-3~1 air at @s run setblock ~3~-3~1 sand 0 replace
execute as @s unless block ~3~-4~1 air at @s run setblock ~3~-4~1 sand 0 replace
execute as @s unless block ~3~-5~1 air at @s run setblock ~3~-5~1 sand 0 replace
execute as @s unless block ~3~7~2 air at @s run setblock ~3~7~2 sand 0 replace
execute as @s unless block ~3~6~2 air at @s run setblock ~3~6~2 sand 0 replace
execute as @s unless block ~3~5~2 air at @s run setblock ~3~5~2 sand 0 replace
execute as @s unless block ~3~4~2 air at @s run setblock ~3~4~2 sand 0 replace
execute as @s unless block ~3~3~2 air at @s run setblock ~3~3~2 sand 0 replace
execute as @s unless block ~3~2~2 air at @s run setblock ~3~2~2 sand 0 replace
execute as @s unless block ~3~1~2 air at @s run setblock ~3~1~2 sand 0 replace
execute as @s unless block ~3~0~2 air at @s run setblock ~3~0~2 sand 0 replace
execute as @s unless block ~3~-1~2 air at @s run setblock ~3~-1~2 sand 0 replace
execute as @s unless block ~3~-2~2 air at @s run setblock ~3~-2~2 sand 0 replace
execute as @s unless block ~3~-3~2 air at @s run setblock ~3~-3~2 sand 0 replace
execute as @s unless block ~3~-4~2 air at @s run setblock ~3~-4~2 sand 0 replace
execute as @s unless block ~3~-5~2 air at @s run setblock ~3~-5~2 sand 0 replace
execute as @s unless block ~3~7~3 air at @s run setblock ~3~7~3 sand 0 replace
execute as @s unless block ~3~6~3 air at @s run setblock ~3~6~3 sand 0 replace
execute as @s unless block ~3~5~3 air at @s run setblock ~3~5~3 sand 0 replace
execute as @s unless block ~3~4~3 air at @s run setblock ~3~4~3 sand 0 replace
execute as @s unless block ~3~3~3 air at @s run setblock ~3~3~3 sand 0 replace
execute as @s unless block ~3~2~3 air at @s run setblock ~3~2~3 sand 0 replace
execute as @s unless block ~3~1~3 air at @s run setblock ~3~1~3 sand 0 replace
execute as @s unless block ~3~0~3 air at @s run setblock ~3~0~3 sand 0 replace
execute as @s unless block ~3~-1~3 air at @s run setblock ~3~-1~3 sand 0 replace
execute as @s unless block ~3~-2~3 air at @s run setblock ~3~-2~3 sand 0 replace
execute as @s unless block ~3~-3~3 air at @s run setblock ~3~-3~3 sand 0 replace
execute as @s unless block ~3~-4~3 air at @s run setblock ~3~-4~3 sand 0 replace
execute as @s unless block ~3~-5~3 air at @s run setblock ~3~-5~3 sand 0 replace
