execute as @s unless block ~-9~7~-9 air at @s run setblock ~-9~7~-9 sand 0 replace
execute as @s unless block ~-9~6~-9 air at @s run setblock ~-9~6~-9 sand 0 replace
execute as @s unless block ~-9~5~-9 air at @s run setblock ~-9~5~-9 sand 0 replace
execute as @s unless block ~-9~4~-9 air at @s run setblock ~-9~4~-9 sand 0 replace
execute as @s unless block ~-9~3~-9 air at @s run setblock ~-9~3~-9 sand 0 replace
execute as @s unless block ~-9~2~-9 air at @s run setblock ~-9~2~-9 sand 0 replace
execute as @s unless block ~-9~1~-9 air at @s run setblock ~-9~1~-9 sand 0 replace
execute as @s unless block ~-9~0~-9 air at @s run setblock ~-9~0~-9 sand 0 replace
execute as @s unless block ~-9~-1~-9 air at @s run setblock ~-9~-1~-9 sand 0 replace
execute as @s unless block ~-9~-2~-9 air at @s run setblock ~-9~-2~-9 sand 0 replace
execute as @s unless block ~-9~-3~-9 air at @s run setblock ~-9~-3~-9 sand 0 replace
execute as @s unless block ~-9~-4~-9 air at @s run setblock ~-9~-4~-9 sand 0 replace
execute as @s unless block ~-9~-5~-9 air at @s run setblock ~-9~-5~-9 sand 0 replace
execute as @s unless block ~-9~7~-8 air at @s run setblock ~-9~7~-8 sand 0 replace
execute as @s unless block ~-9~6~-8 air at @s run setblock ~-9~6~-8 sand 0 replace
execute as @s unless block ~-9~5~-8 air at @s run setblock ~-9~5~-8 sand 0 replace
execute as @s unless block ~-9~4~-8 air at @s run setblock ~-9~4~-8 sand 0 replace
execute as @s unless block ~-9~3~-8 air at @s run setblock ~-9~3~-8 sand 0 replace
execute as @s unless block ~-9~2~-8 air at @s run setblock ~-9~2~-8 sand 0 replace
execute as @s unless block ~-9~1~-8 air at @s run setblock ~-9~1~-8 sand 0 replace
execute as @s unless block ~-9~0~-8 air at @s run setblock ~-9~0~-8 sand 0 replace
execute as @s unless block ~-9~-1~-8 air at @s run setblock ~-9~-1~-8 sand 0 replace
execute as @s unless block ~-9~-2~-8 air at @s run setblock ~-9~-2~-8 sand 0 replace
execute as @s unless block ~-9~-3~-8 air at @s run setblock ~-9~-3~-8 sand 0 replace
execute as @s unless block ~-9~-4~-8 air at @s run setblock ~-9~-4~-8 sand 0 replace
execute as @s unless block ~-9~-5~-8 air at @s run setblock ~-9~-5~-8 sand 0 replace
execute as @s unless block ~-9~7~-7 air at @s run setblock ~-9~7~-7 sand 0 replace
execute as @s unless block ~-9~6~-7 air at @s run setblock ~-9~6~-7 sand 0 replace
execute as @s unless block ~-9~5~-7 air at @s run setblock ~-9~5~-7 sand 0 replace
execute as @s unless block ~-9~4~-7 air at @s run setblock ~-9~4~-7 sand 0 replace
execute as @s unless block ~-9~3~-7 air at @s run setblock ~-9~3~-7 sand 0 replace
execute as @s unless block ~-9~2~-7 air at @s run setblock ~-9~2~-7 sand 0 replace
execute as @s unless block ~-9~1~-7 air at @s run setblock ~-9~1~-7 sand 0 replace
execute as @s unless block ~-9~0~-7 air at @s run setblock ~-9~0~-7 sand 0 replace
execute as @s unless block ~-9~-1~-7 air at @s run setblock ~-9~-1~-7 sand 0 replace
execute as @s unless block ~-9~-2~-7 air at @s run setblock ~-9~-2~-7 sand 0 replace
execute as @s unless block ~-9~-3~-7 air at @s run setblock ~-9~-3~-7 sand 0 replace
execute as @s unless block ~-9~-4~-7 air at @s run setblock ~-9~-4~-7 sand 0 replace
execute as @s unless block ~-9~-5~-7 air at @s run setblock ~-9~-5~-7 sand 0 replace
execute as @s unless block ~-9~7~-6 air at @s run setblock ~-9~7~-6 sand 0 replace
execute as @s unless block ~-9~6~-6 air at @s run setblock ~-9~6~-6 sand 0 replace
execute as @s unless block ~-9~5~-6 air at @s run setblock ~-9~5~-6 sand 0 replace
execute as @s unless block ~-9~4~-6 air at @s run setblock ~-9~4~-6 sand 0 replace
execute as @s unless block ~-9~3~-6 air at @s run setblock ~-9~3~-6 sand 0 replace
execute as @s unless block ~-9~2~-6 air at @s run setblock ~-9~2~-6 sand 0 replace
execute as @s unless block ~-9~1~-6 air at @s run setblock ~-9~1~-6 sand 0 replace
execute as @s unless block ~-9~0~-6 air at @s run setblock ~-9~0~-6 sand 0 replace
execute as @s unless block ~-9~-1~-6 air at @s run setblock ~-9~-1~-6 sand 0 replace
execute as @s unless block ~-9~-2~-6 air at @s run setblock ~-9~-2~-6 sand 0 replace
execute as @s unless block ~-9~-3~-6 air at @s run setblock ~-9~-3~-6 sand 0 replace
execute as @s unless block ~-9~-4~-6 air at @s run setblock ~-9~-4~-6 sand 0 replace
execute as @s unless block ~-9~-5~-6 air at @s run setblock ~-9~-5~-6 sand 0 replace
execute as @s unless block ~-9~7~-5 air at @s run setblock ~-9~7~-5 sand 0 replace
execute as @s unless block ~-9~6~-5 air at @s run setblock ~-9~6~-5 sand 0 replace
execute as @s unless block ~-9~5~-5 air at @s run setblock ~-9~5~-5 sand 0 replace
execute as @s unless block ~-9~4~-5 air at @s run setblock ~-9~4~-5 sand 0 replace
execute as @s unless block ~-9~3~-5 air at @s run setblock ~-9~3~-5 sand 0 replace
execute as @s unless block ~-9~2~-5 air at @s run setblock ~-9~2~-5 sand 0 replace
execute as @s unless block ~-9~1~-5 air at @s run setblock ~-9~1~-5 sand 0 replace
execute as @s unless block ~-9~0~-5 air at @s run setblock ~-9~0~-5 sand 0 replace
execute as @s unless block ~-9~-1~-5 air at @s run setblock ~-9~-1~-5 sand 0 replace
execute as @s unless block ~-9~-2~-5 air at @s run setblock ~-9~-2~-5 sand 0 replace
execute as @s unless block ~-9~-3~-5 air at @s run setblock ~-9~-3~-5 sand 0 replace
execute as @s unless block ~-9~-4~-5 air at @s run setblock ~-9~-4~-5 sand 0 replace
execute as @s unless block ~-9~-5~-5 air at @s run setblock ~-9~-5~-5 sand 0 replace
execute as @s unless block ~-9~7~-4 air at @s run setblock ~-9~7~-4 sand 0 replace
execute as @s unless block ~-9~6~-4 air at @s run setblock ~-9~6~-4 sand 0 replace
execute as @s unless block ~-9~5~-4 air at @s run setblock ~-9~5~-4 sand 0 replace
execute as @s unless block ~-9~4~-4 air at @s run setblock ~-9~4~-4 sand 0 replace
execute as @s unless block ~-9~3~-4 air at @s run setblock ~-9~3~-4 sand 0 replace
execute as @s unless block ~-9~2~-4 air at @s run setblock ~-9~2~-4 sand 0 replace
execute as @s unless block ~-9~1~-4 air at @s run setblock ~-9~1~-4 sand 0 replace
execute as @s unless block ~-9~0~-4 air at @s run setblock ~-9~0~-4 sand 0 replace
execute as @s unless block ~-9~-1~-4 air at @s run setblock ~-9~-1~-4 sand 0 replace
execute as @s unless block ~-9~-2~-4 air at @s run setblock ~-9~-2~-4 sand 0 replace
execute as @s unless block ~-9~-3~-4 air at @s run setblock ~-9~-3~-4 sand 0 replace
execute as @s unless block ~-9~-4~-4 air at @s run setblock ~-9~-4~-4 sand 0 replace
execute as @s unless block ~-9~-5~-4 air at @s run setblock ~-9~-5~-4 sand 0 replace
execute as @s unless block ~-9~7~-3 air at @s run setblock ~-9~7~-3 sand 0 replace
execute as @s unless block ~-9~6~-3 air at @s run setblock ~-9~6~-3 sand 0 replace
execute as @s unless block ~-9~5~-3 air at @s run setblock ~-9~5~-3 sand 0 replace
execute as @s unless block ~-9~4~-3 air at @s run setblock ~-9~4~-3 sand 0 replace
execute as @s unless block ~-9~3~-3 air at @s run setblock ~-9~3~-3 sand 0 replace
execute as @s unless block ~-9~2~-3 air at @s run setblock ~-9~2~-3 sand 0 replace
execute as @s unless block ~-9~1~-3 air at @s run setblock ~-9~1~-3 sand 0 replace
execute as @s unless block ~-9~0~-3 air at @s run setblock ~-9~0~-3 sand 0 replace
execute as @s unless block ~-9~-1~-3 air at @s run setblock ~-9~-1~-3 sand 0 replace
execute as @s unless block ~-9~-2~-3 air at @s run setblock ~-9~-2~-3 sand 0 replace
execute as @s unless block ~-9~-3~-3 air at @s run setblock ~-9~-3~-3 sand 0 replace
execute as @s unless block ~-9~-4~-3 air at @s run setblock ~-9~-4~-3 sand 0 replace
execute as @s unless block ~-9~-5~-3 air at @s run setblock ~-9~-5~-3 sand 0 replace
execute as @s unless block ~-9~7~-2 air at @s run setblock ~-9~7~-2 sand 0 replace
execute as @s unless block ~-9~6~-2 air at @s run setblock ~-9~6~-2 sand 0 replace
execute as @s unless block ~-9~5~-2 air at @s run setblock ~-9~5~-2 sand 0 replace
execute as @s unless block ~-9~4~-2 air at @s run setblock ~-9~4~-2 sand 0 replace
execute as @s unless block ~-9~3~-2 air at @s run setblock ~-9~3~-2 sand 0 replace
execute as @s unless block ~-9~2~-2 air at @s run setblock ~-9~2~-2 sand 0 replace
execute as @s unless block ~-9~1~-2 air at @s run setblock ~-9~1~-2 sand 0 replace
execute as @s unless block ~-9~0~-2 air at @s run setblock ~-9~0~-2 sand 0 replace
execute as @s unless block ~-9~-1~-2 air at @s run setblock ~-9~-1~-2 sand 0 replace
execute as @s unless block ~-9~-2~-2 air at @s run setblock ~-9~-2~-2 sand 0 replace
execute as @s unless block ~-9~-3~-2 air at @s run setblock ~-9~-3~-2 sand 0 replace
execute as @s unless block ~-9~-4~-2 air at @s run setblock ~-9~-4~-2 sand 0 replace
execute as @s unless block ~-9~-5~-2 air at @s run setblock ~-9~-5~-2 sand 0 replace
execute as @s unless block ~-9~7~-1 air at @s run setblock ~-9~7~-1 sand 0 replace
execute as @s unless block ~-9~6~-1 air at @s run setblock ~-9~6~-1 sand 0 replace
execute as @s unless block ~-9~5~-1 air at @s run setblock ~-9~5~-1 sand 0 replace
execute as @s unless block ~-9~4~-1 air at @s run setblock ~-9~4~-1 sand 0 replace
execute as @s unless block ~-9~3~-1 air at @s run setblock ~-9~3~-1 sand 0 replace
execute as @s unless block ~-9~2~-1 air at @s run setblock ~-9~2~-1 sand 0 replace
execute as @s unless block ~-9~1~-1 air at @s run setblock ~-9~1~-1 sand 0 replace
execute as @s unless block ~-9~0~-1 air at @s run setblock ~-9~0~-1 sand 0 replace
execute as @s unless block ~-9~-1~-1 air at @s run setblock ~-9~-1~-1 sand 0 replace
execute as @s unless block ~-9~-2~-1 air at @s run setblock ~-9~-2~-1 sand 0 replace
execute as @s unless block ~-9~-3~-1 air at @s run setblock ~-9~-3~-1 sand 0 replace
execute as @s unless block ~-9~-4~-1 air at @s run setblock ~-9~-4~-1 sand 0 replace
execute as @s unless block ~-9~-5~-1 air at @s run setblock ~-9~-5~-1 sand 0 replace
execute as @s unless block ~-9~7~0 air at @s run setblock ~-9~7~0 sand 0 replace
execute as @s unless block ~-9~6~0 air at @s run setblock ~-9~6~0 sand 0 replace
execute as @s unless block ~-9~5~0 air at @s run setblock ~-9~5~0 sand 0 replace
execute as @s unless block ~-9~4~0 air at @s run setblock ~-9~4~0 sand 0 replace
execute as @s unless block ~-9~3~0 air at @s run setblock ~-9~3~0 sand 0 replace
execute as @s unless block ~-9~2~0 air at @s run setblock ~-9~2~0 sand 0 replace
execute as @s unless block ~-9~1~0 air at @s run setblock ~-9~1~0 sand 0 replace
execute as @s unless block ~-9~0~0 air at @s run setblock ~-9~0~0 sand 0 replace
execute as @s unless block ~-9~-1~0 air at @s run setblock ~-9~-1~0 sand 0 replace
execute as @s unless block ~-9~-2~0 air at @s run setblock ~-9~-2~0 sand 0 replace
execute as @s unless block ~-9~-3~0 air at @s run setblock ~-9~-3~0 sand 0 replace
execute as @s unless block ~-9~-4~0 air at @s run setblock ~-9~-4~0 sand 0 replace
execute as @s unless block ~-9~-5~0 air at @s run setblock ~-9~-5~0 sand 0 replace
execute as @s unless block ~-9~7~1 air at @s run setblock ~-9~7~1 sand 0 replace
execute as @s unless block ~-9~6~1 air at @s run setblock ~-9~6~1 sand 0 replace
execute as @s unless block ~-9~5~1 air at @s run setblock ~-9~5~1 sand 0 replace
execute as @s unless block ~-9~4~1 air at @s run setblock ~-9~4~1 sand 0 replace
execute as @s unless block ~-9~3~1 air at @s run setblock ~-9~3~1 sand 0 replace
execute as @s unless block ~-9~2~1 air at @s run setblock ~-9~2~1 sand 0 replace
execute as @s unless block ~-9~1~1 air at @s run setblock ~-9~1~1 sand 0 replace
execute as @s unless block ~-9~0~1 air at @s run setblock ~-9~0~1 sand 0 replace
execute as @s unless block ~-9~-1~1 air at @s run setblock ~-9~-1~1 sand 0 replace
execute as @s unless block ~-9~-2~1 air at @s run setblock ~-9~-2~1 sand 0 replace
execute as @s unless block ~-9~-3~1 air at @s run setblock ~-9~-3~1 sand 0 replace
execute as @s unless block ~-9~-4~1 air at @s run setblock ~-9~-4~1 sand 0 replace
execute as @s unless block ~-9~-5~1 air at @s run setblock ~-9~-5~1 sand 0 replace
execute as @s unless block ~-9~7~2 air at @s run setblock ~-9~7~2 sand 0 replace
execute as @s unless block ~-9~6~2 air at @s run setblock ~-9~6~2 sand 0 replace
execute as @s unless block ~-9~5~2 air at @s run setblock ~-9~5~2 sand 0 replace
execute as @s unless block ~-9~4~2 air at @s run setblock ~-9~4~2 sand 0 replace
execute as @s unless block ~-9~3~2 air at @s run setblock ~-9~3~2 sand 0 replace
execute as @s unless block ~-9~2~2 air at @s run setblock ~-9~2~2 sand 0 replace
execute as @s unless block ~-9~1~2 air at @s run setblock ~-9~1~2 sand 0 replace
execute as @s unless block ~-9~0~2 air at @s run setblock ~-9~0~2 sand 0 replace
execute as @s unless block ~-9~-1~2 air at @s run setblock ~-9~-1~2 sand 0 replace
execute as @s unless block ~-9~-2~2 air at @s run setblock ~-9~-2~2 sand 0 replace
execute as @s unless block ~-9~-3~2 air at @s run setblock ~-9~-3~2 sand 0 replace
execute as @s unless block ~-9~-4~2 air at @s run setblock ~-9~-4~2 sand 0 replace
execute as @s unless block ~-9~-5~2 air at @s run setblock ~-9~-5~2 sand 0 replace
execute as @s unless block ~-9~7~3 air at @s run setblock ~-9~7~3 sand 0 replace
execute as @s unless block ~-9~6~3 air at @s run setblock ~-9~6~3 sand 0 replace
execute as @s unless block ~-9~5~3 air at @s run setblock ~-9~5~3 sand 0 replace
execute as @s unless block ~-9~4~3 air at @s run setblock ~-9~4~3 sand 0 replace
execute as @s unless block ~-9~3~3 air at @s run setblock ~-9~3~3 sand 0 replace
execute as @s unless block ~-9~2~3 air at @s run setblock ~-9~2~3 sand 0 replace
execute as @s unless block ~-9~1~3 air at @s run setblock ~-9~1~3 sand 0 replace
execute as @s unless block ~-9~0~3 air at @s run setblock ~-9~0~3 sand 0 replace
execute as @s unless block ~-9~-1~3 air at @s run setblock ~-9~-1~3 sand 0 replace
execute as @s unless block ~-9~-2~3 air at @s run setblock ~-9~-2~3 sand 0 replace
execute as @s unless block ~-9~-3~3 air at @s run setblock ~-9~-3~3 sand 0 replace
execute as @s unless block ~-9~-4~3 air at @s run setblock ~-9~-4~3 sand 0 replace
execute as @s unless block ~-9~-5~3 air at @s run setblock ~-9~-5~3 sand 0 replace
execute as @s unless block ~-9~7~4 air at @s run setblock ~-9~7~4 sand 0 replace
execute as @s unless block ~-9~6~4 air at @s run setblock ~-9~6~4 sand 0 replace
execute as @s unless block ~-9~5~4 air at @s run setblock ~-9~5~4 sand 0 replace
execute as @s unless block ~-9~4~4 air at @s run setblock ~-9~4~4 sand 0 replace
execute as @s unless block ~-9~3~4 air at @s run setblock ~-9~3~4 sand 0 replace
execute as @s unless block ~-9~2~4 air at @s run setblock ~-9~2~4 sand 0 replace
execute as @s unless block ~-9~1~4 air at @s run setblock ~-9~1~4 sand 0 replace
execute as @s unless block ~-9~0~4 air at @s run setblock ~-9~0~4 sand 0 replace
execute as @s unless block ~-9~-1~4 air at @s run setblock ~-9~-1~4 sand 0 replace
execute as @s unless block ~-9~-2~4 air at @s run setblock ~-9~-2~4 sand 0 replace
execute as @s unless block ~-9~-3~4 air at @s run setblock ~-9~-3~4 sand 0 replace
execute as @s unless block ~-9~-4~4 air at @s run setblock ~-9~-4~4 sand 0 replace
execute as @s unless block ~-9~-5~4 air at @s run setblock ~-9~-5~4 sand 0 replace
execute as @s unless block ~-9~7~5 air at @s run setblock ~-9~7~5 sand 0 replace
execute as @s unless block ~-9~6~5 air at @s run setblock ~-9~6~5 sand 0 replace
execute as @s unless block ~-9~5~5 air at @s run setblock ~-9~5~5 sand 0 replace
execute as @s unless block ~-9~4~5 air at @s run setblock ~-9~4~5 sand 0 replace
execute as @s unless block ~-9~3~5 air at @s run setblock ~-9~3~5 sand 0 replace
execute as @s unless block ~-9~2~5 air at @s run setblock ~-9~2~5 sand 0 replace
execute as @s unless block ~-9~1~5 air at @s run setblock ~-9~1~5 sand 0 replace
execute as @s unless block ~-9~0~5 air at @s run setblock ~-9~0~5 sand 0 replace
execute as @s unless block ~-9~-1~5 air at @s run setblock ~-9~-1~5 sand 0 replace
execute as @s unless block ~-9~-2~5 air at @s run setblock ~-9~-2~5 sand 0 replace
execute as @s unless block ~-9~-3~5 air at @s run setblock ~-9~-3~5 sand 0 replace
execute as @s unless block ~-9~-4~5 air at @s run setblock ~-9~-4~5 sand 0 replace
execute as @s unless block ~-9~-5~5 air at @s run setblock ~-9~-5~5 sand 0 replace
execute as @s unless block ~-9~7~6 air at @s run setblock ~-9~7~6 sand 0 replace
execute as @s unless block ~-9~6~6 air at @s run setblock ~-9~6~6 sand 0 replace
execute as @s unless block ~-9~5~6 air at @s run setblock ~-9~5~6 sand 0 replace
execute as @s unless block ~-9~4~6 air at @s run setblock ~-9~4~6 sand 0 replace
execute as @s unless block ~-9~3~6 air at @s run setblock ~-9~3~6 sand 0 replace
execute as @s unless block ~-9~2~6 air at @s run setblock ~-9~2~6 sand 0 replace
execute as @s unless block ~-9~1~6 air at @s run setblock ~-9~1~6 sand 0 replace
execute as @s unless block ~-9~0~6 air at @s run setblock ~-9~0~6 sand 0 replace
execute as @s unless block ~-9~-1~6 air at @s run setblock ~-9~-1~6 sand 0 replace
execute as @s unless block ~-9~-2~6 air at @s run setblock ~-9~-2~6 sand 0 replace
execute as @s unless block ~-9~-3~6 air at @s run setblock ~-9~-3~6 sand 0 replace
execute as @s unless block ~-9~-4~6 air at @s run setblock ~-9~-4~6 sand 0 replace
execute as @s unless block ~-9~-5~6 air at @s run setblock ~-9~-5~6 sand 0 replace
execute as @s unless block ~-9~7~7 air at @s run setblock ~-9~7~7 sand 0 replace
execute as @s unless block ~-9~6~7 air at @s run setblock ~-9~6~7 sand 0 replace
execute as @s unless block ~-9~5~7 air at @s run setblock ~-9~5~7 sand 0 replace
execute as @s unless block ~-9~4~7 air at @s run setblock ~-9~4~7 sand 0 replace
execute as @s unless block ~-9~3~7 air at @s run setblock ~-9~3~7 sand 0 replace
execute as @s unless block ~-9~2~7 air at @s run setblock ~-9~2~7 sand 0 replace
execute as @s unless block ~-9~1~7 air at @s run setblock ~-9~1~7 sand 0 replace
execute as @s unless block ~-9~0~7 air at @s run setblock ~-9~0~7 sand 0 replace
execute as @s unless block ~-9~-1~7 air at @s run setblock ~-9~-1~7 sand 0 replace
execute as @s unless block ~-9~-2~7 air at @s run setblock ~-9~-2~7 sand 0 replace
execute as @s unless block ~-9~-3~7 air at @s run setblock ~-9~-3~7 sand 0 replace
execute as @s unless block ~-9~-4~7 air at @s run setblock ~-9~-4~7 sand 0 replace
execute as @s unless block ~-9~-5~7 air at @s run setblock ~-9~-5~7 sand 0 replace
execute as @s unless block ~-9~7~8 air at @s run setblock ~-9~7~8 sand 0 replace
execute as @s unless block ~-9~6~8 air at @s run setblock ~-9~6~8 sand 0 replace
execute as @s unless block ~-9~5~8 air at @s run setblock ~-9~5~8 sand 0 replace
execute as @s unless block ~-9~4~8 air at @s run setblock ~-9~4~8 sand 0 replace
execute as @s unless block ~-9~3~8 air at @s run setblock ~-9~3~8 sand 0 replace
execute as @s unless block ~-9~2~8 air at @s run setblock ~-9~2~8 sand 0 replace
execute as @s unless block ~-9~1~8 air at @s run setblock ~-9~1~8 sand 0 replace
execute as @s unless block ~-9~0~8 air at @s run setblock ~-9~0~8 sand 0 replace
execute as @s unless block ~-9~-1~8 air at @s run setblock ~-9~-1~8 sand 0 replace
execute as @s unless block ~-9~-2~8 air at @s run setblock ~-9~-2~8 sand 0 replace
execute as @s unless block ~-9~-3~8 air at @s run setblock ~-9~-3~8 sand 0 replace
execute as @s unless block ~-9~-4~8 air at @s run setblock ~-9~-4~8 sand 0 replace
execute as @s unless block ~-9~-5~8 air at @s run setblock ~-9~-5~8 sand 0 replace
execute as @s unless block ~-9~7~9 air at @s run setblock ~-9~7~9 sand 0 replace
execute as @s unless block ~-9~6~9 air at @s run setblock ~-9~6~9 sand 0 replace
execute as @s unless block ~-9~5~9 air at @s run setblock ~-9~5~9 sand 0 replace
execute as @s unless block ~-9~4~9 air at @s run setblock ~-9~4~9 sand 0 replace
execute as @s unless block ~-9~3~9 air at @s run setblock ~-9~3~9 sand 0 replace
execute as @s unless block ~-9~2~9 air at @s run setblock ~-9~2~9 sand 0 replace
execute as @s unless block ~-9~1~9 air at @s run setblock ~-9~1~9 sand 0 replace
execute as @s unless block ~-9~0~9 air at @s run setblock ~-9~0~9 sand 0 replace
execute as @s unless block ~-9~-1~9 air at @s run setblock ~-9~-1~9 sand 0 replace
execute as @s unless block ~-9~-2~9 air at @s run setblock ~-9~-2~9 sand 0 replace
execute as @s unless block ~-9~-3~9 air at @s run setblock ~-9~-3~9 sand 0 replace
execute as @s unless block ~-9~-4~9 air at @s run setblock ~-9~-4~9 sand 0 replace
execute as @s unless block ~-9~-5~9 air at @s run setblock ~-9~-5~9 sand 0 replace
execute as @s unless block ~-8~7~-9 air at @s run setblock ~-8~7~-9 sand 0 replace
execute as @s unless block ~-8~6~-9 air at @s run setblock ~-8~6~-9 sand 0 replace
execute as @s unless block ~-8~5~-9 air at @s run setblock ~-8~5~-9 sand 0 replace
execute as @s unless block ~-8~4~-9 air at @s run setblock ~-8~4~-9 sand 0 replace
execute as @s unless block ~-8~3~-9 air at @s run setblock ~-8~3~-9 sand 0 replace
execute as @s unless block ~-8~2~-9 air at @s run setblock ~-8~2~-9 sand 0 replace
execute as @s unless block ~-8~1~-9 air at @s run setblock ~-8~1~-9 sand 0 replace
execute as @s unless block ~-8~0~-9 air at @s run setblock ~-8~0~-9 sand 0 replace
execute as @s unless block ~-8~-1~-9 air at @s run setblock ~-8~-1~-9 sand 0 replace
execute as @s unless block ~-8~-2~-9 air at @s run setblock ~-8~-2~-9 sand 0 replace
execute as @s unless block ~-8~-3~-9 air at @s run setblock ~-8~-3~-9 sand 0 replace
execute as @s unless block ~-8~-4~-9 air at @s run setblock ~-8~-4~-9 sand 0 replace
execute as @s unless block ~-8~-5~-9 air at @s run setblock ~-8~-5~-9 sand 0 replace
execute as @s unless block ~-8~7~9 air at @s run setblock ~-8~7~9 sand 0 replace
execute as @s unless block ~-8~6~9 air at @s run setblock ~-8~6~9 sand 0 replace
execute as @s unless block ~-8~5~9 air at @s run setblock ~-8~5~9 sand 0 replace
execute as @s unless block ~-8~4~9 air at @s run setblock ~-8~4~9 sand 0 replace
execute as @s unless block ~-8~3~9 air at @s run setblock ~-8~3~9 sand 0 replace
execute as @s unless block ~-8~2~9 air at @s run setblock ~-8~2~9 sand 0 replace
execute as @s unless block ~-8~1~9 air at @s run setblock ~-8~1~9 sand 0 replace
execute as @s unless block ~-8~0~9 air at @s run setblock ~-8~0~9 sand 0 replace
execute as @s unless block ~-8~-1~9 air at @s run setblock ~-8~-1~9 sand 0 replace
execute as @s unless block ~-8~-2~9 air at @s run setblock ~-8~-2~9 sand 0 replace
execute as @s unless block ~-8~-3~9 air at @s run setblock ~-8~-3~9 sand 0 replace
execute as @s unless block ~-8~-4~9 air at @s run setblock ~-8~-4~9 sand 0 replace
execute as @s unless block ~-8~-5~9 air at @s run setblock ~-8~-5~9 sand 0 replace
execute as @s unless block ~-7~7~-9 air at @s run setblock ~-7~7~-9 sand 0 replace
execute as @s unless block ~-7~6~-9 air at @s run setblock ~-7~6~-9 sand 0 replace
execute as @s unless block ~-7~5~-9 air at @s run setblock ~-7~5~-9 sand 0 replace
execute as @s unless block ~-7~4~-9 air at @s run setblock ~-7~4~-9 sand 0 replace
execute as @s unless block ~-7~3~-9 air at @s run setblock ~-7~3~-9 sand 0 replace
execute as @s unless block ~-7~2~-9 air at @s run setblock ~-7~2~-9 sand 0 replace
execute as @s unless block ~-7~1~-9 air at @s run setblock ~-7~1~-9 sand 0 replace
execute as @s unless block ~-7~0~-9 air at @s run setblock ~-7~0~-9 sand 0 replace
execute as @s unless block ~-7~-1~-9 air at @s run setblock ~-7~-1~-9 sand 0 replace
execute as @s unless block ~-7~-2~-9 air at @s run setblock ~-7~-2~-9 sand 0 replace
execute as @s unless block ~-7~-3~-9 air at @s run setblock ~-7~-3~-9 sand 0 replace
execute as @s unless block ~-7~-4~-9 air at @s run setblock ~-7~-4~-9 sand 0 replace
execute as @s unless block ~-7~-5~-9 air at @s run setblock ~-7~-5~-9 sand 0 replace
execute as @s unless block ~-7~7~9 air at @s run setblock ~-7~7~9 sand 0 replace
execute as @s unless block ~-7~6~9 air at @s run setblock ~-7~6~9 sand 0 replace
execute as @s unless block ~-7~5~9 air at @s run setblock ~-7~5~9 sand 0 replace
execute as @s unless block ~-7~4~9 air at @s run setblock ~-7~4~9 sand 0 replace
execute as @s unless block ~-7~3~9 air at @s run setblock ~-7~3~9 sand 0 replace
execute as @s unless block ~-7~2~9 air at @s run setblock ~-7~2~9 sand 0 replace
execute as @s unless block ~-7~1~9 air at @s run setblock ~-7~1~9 sand 0 replace
execute as @s unless block ~-7~0~9 air at @s run setblock ~-7~0~9 sand 0 replace
execute as @s unless block ~-7~-1~9 air at @s run setblock ~-7~-1~9 sand 0 replace
execute as @s unless block ~-7~-2~9 air at @s run setblock ~-7~-2~9 sand 0 replace
execute as @s unless block ~-7~-3~9 air at @s run setblock ~-7~-3~9 sand 0 replace
execute as @s unless block ~-7~-4~9 air at @s run setblock ~-7~-4~9 sand 0 replace
execute as @s unless block ~-7~-5~9 air at @s run setblock ~-7~-5~9 sand 0 replace
execute as @s unless block ~-6~7~-9 air at @s run setblock ~-6~7~-9 sand 0 replace
execute as @s unless block ~-6~6~-9 air at @s run setblock ~-6~6~-9 sand 0 replace
execute as @s unless block ~-6~5~-9 air at @s run setblock ~-6~5~-9 sand 0 replace
execute as @s unless block ~-6~4~-9 air at @s run setblock ~-6~4~-9 sand 0 replace
execute as @s unless block ~-6~3~-9 air at @s run setblock ~-6~3~-9 sand 0 replace
execute as @s unless block ~-6~2~-9 air at @s run setblock ~-6~2~-9 sand 0 replace
execute as @s unless block ~-6~1~-9 air at @s run setblock ~-6~1~-9 sand 0 replace
execute as @s unless block ~-6~0~-9 air at @s run setblock ~-6~0~-9 sand 0 replace
execute as @s unless block ~-6~-1~-9 air at @s run setblock ~-6~-1~-9 sand 0 replace
execute as @s unless block ~-6~-2~-9 air at @s run setblock ~-6~-2~-9 sand 0 replace
execute as @s unless block ~-6~-3~-9 air at @s run setblock ~-6~-3~-9 sand 0 replace
execute as @s unless block ~-6~-4~-9 air at @s run setblock ~-6~-4~-9 sand 0 replace
execute as @s unless block ~-6~-5~-9 air at @s run setblock ~-6~-5~-9 sand 0 replace
execute as @s unless block ~-6~7~9 air at @s run setblock ~-6~7~9 sand 0 replace
execute as @s unless block ~-6~6~9 air at @s run setblock ~-6~6~9 sand 0 replace
execute as @s unless block ~-6~5~9 air at @s run setblock ~-6~5~9 sand 0 replace
execute as @s unless block ~-6~4~9 air at @s run setblock ~-6~4~9 sand 0 replace
execute as @s unless block ~-6~3~9 air at @s run setblock ~-6~3~9 sand 0 replace
execute as @s unless block ~-6~2~9 air at @s run setblock ~-6~2~9 sand 0 replace
execute as @s unless block ~-6~1~9 air at @s run setblock ~-6~1~9 sand 0 replace
execute as @s unless block ~-6~0~9 air at @s run setblock ~-6~0~9 sand 0 replace
execute as @s unless block ~-6~-1~9 air at @s run setblock ~-6~-1~9 sand 0 replace
execute as @s unless block ~-6~-2~9 air at @s run setblock ~-6~-2~9 sand 0 replace
execute as @s unless block ~-6~-3~9 air at @s run setblock ~-6~-3~9 sand 0 replace
execute as @s unless block ~-6~-4~9 air at @s run setblock ~-6~-4~9 sand 0 replace
execute as @s unless block ~-6~-5~9 air at @s run setblock ~-6~-5~9 sand 0 replace
execute as @s unless block ~-5~7~-9 air at @s run setblock ~-5~7~-9 sand 0 replace
execute as @s unless block ~-5~6~-9 air at @s run setblock ~-5~6~-9 sand 0 replace
execute as @s unless block ~-5~5~-9 air at @s run setblock ~-5~5~-9 sand 0 replace
execute as @s unless block ~-5~4~-9 air at @s run setblock ~-5~4~-9 sand 0 replace
execute as @s unless block ~-5~3~-9 air at @s run setblock ~-5~3~-9 sand 0 replace
execute as @s unless block ~-5~2~-9 air at @s run setblock ~-5~2~-9 sand 0 replace
execute as @s unless block ~-5~1~-9 air at @s run setblock ~-5~1~-9 sand 0 replace
execute as @s unless block ~-5~0~-9 air at @s run setblock ~-5~0~-9 sand 0 replace
execute as @s unless block ~-5~-1~-9 air at @s run setblock ~-5~-1~-9 sand 0 replace
execute as @s unless block ~-5~-2~-9 air at @s run setblock ~-5~-2~-9 sand 0 replace
execute as @s unless block ~-5~-3~-9 air at @s run setblock ~-5~-3~-9 sand 0 replace
execute as @s unless block ~-5~-4~-9 air at @s run setblock ~-5~-4~-9 sand 0 replace
execute as @s unless block ~-5~-5~-9 air at @s run setblock ~-5~-5~-9 sand 0 replace
execute as @s unless block ~-5~7~9 air at @s run setblock ~-5~7~9 sand 0 replace
execute as @s unless block ~-5~6~9 air at @s run setblock ~-5~6~9 sand 0 replace
execute as @s unless block ~-5~5~9 air at @s run setblock ~-5~5~9 sand 0 replace
execute as @s unless block ~-5~4~9 air at @s run setblock ~-5~4~9 sand 0 replace
execute as @s unless block ~-5~3~9 air at @s run setblock ~-5~3~9 sand 0 replace
execute as @s unless block ~-5~2~9 air at @s run setblock ~-5~2~9 sand 0 replace
execute as @s unless block ~-5~1~9 air at @s run setblock ~-5~1~9 sand 0 replace
execute as @s unless block ~-5~0~9 air at @s run setblock ~-5~0~9 sand 0 replace
execute as @s unless block ~-5~-1~9 air at @s run setblock ~-5~-1~9 sand 0 replace
execute as @s unless block ~-5~-2~9 air at @s run setblock ~-5~-2~9 sand 0 replace
execute as @s unless block ~-5~-3~9 air at @s run setblock ~-5~-3~9 sand 0 replace
execute as @s unless block ~-5~-4~9 air at @s run setblock ~-5~-4~9 sand 0 replace
execute as @s unless block ~-5~-5~9 air at @s run setblock ~-5~-5~9 sand 0 replace
execute as @s unless block ~-4~7~-9 air at @s run setblock ~-4~7~-9 sand 0 replace
execute as @s unless block ~-4~6~-9 air at @s run setblock ~-4~6~-9 sand 0 replace
execute as @s unless block ~-4~5~-9 air at @s run setblock ~-4~5~-9 sand 0 replace
execute as @s unless block ~-4~4~-9 air at @s run setblock ~-4~4~-9 sand 0 replace
execute as @s unless block ~-4~3~-9 air at @s run setblock ~-4~3~-9 sand 0 replace
execute as @s unless block ~-4~2~-9 air at @s run setblock ~-4~2~-9 sand 0 replace
execute as @s unless block ~-4~1~-9 air at @s run setblock ~-4~1~-9 sand 0 replace
execute as @s unless block ~-4~0~-9 air at @s run setblock ~-4~0~-9 sand 0 replace
execute as @s unless block ~-4~-1~-9 air at @s run setblock ~-4~-1~-9 sand 0 replace
execute as @s unless block ~-4~-2~-9 air at @s run setblock ~-4~-2~-9 sand 0 replace
execute as @s unless block ~-4~-3~-9 air at @s run setblock ~-4~-3~-9 sand 0 replace
execute as @s unless block ~-4~-4~-9 air at @s run setblock ~-4~-4~-9 sand 0 replace
execute as @s unless block ~-4~-5~-9 air at @s run setblock ~-4~-5~-9 sand 0 replace
execute as @s unless block ~-4~7~9 air at @s run setblock ~-4~7~9 sand 0 replace
execute as @s unless block ~-4~6~9 air at @s run setblock ~-4~6~9 sand 0 replace
execute as @s unless block ~-4~5~9 air at @s run setblock ~-4~5~9 sand 0 replace
execute as @s unless block ~-4~4~9 air at @s run setblock ~-4~4~9 sand 0 replace
execute as @s unless block ~-4~3~9 air at @s run setblock ~-4~3~9 sand 0 replace
execute as @s unless block ~-4~2~9 air at @s run setblock ~-4~2~9 sand 0 replace
execute as @s unless block ~-4~1~9 air at @s run setblock ~-4~1~9 sand 0 replace
execute as @s unless block ~-4~0~9 air at @s run setblock ~-4~0~9 sand 0 replace
execute as @s unless block ~-4~-1~9 air at @s run setblock ~-4~-1~9 sand 0 replace
execute as @s unless block ~-4~-2~9 air at @s run setblock ~-4~-2~9 sand 0 replace
execute as @s unless block ~-4~-3~9 air at @s run setblock ~-4~-3~9 sand 0 replace
execute as @s unless block ~-4~-4~9 air at @s run setblock ~-4~-4~9 sand 0 replace
execute as @s unless block ~-4~-5~9 air at @s run setblock ~-4~-5~9 sand 0 replace
execute as @s unless block ~-3~7~-9 air at @s run setblock ~-3~7~-9 sand 0 replace
execute as @s unless block ~-3~6~-9 air at @s run setblock ~-3~6~-9 sand 0 replace
execute as @s unless block ~-3~5~-9 air at @s run setblock ~-3~5~-9 sand 0 replace
execute as @s unless block ~-3~4~-9 air at @s run setblock ~-3~4~-9 sand 0 replace
execute as @s unless block ~-3~3~-9 air at @s run setblock ~-3~3~-9 sand 0 replace
execute as @s unless block ~-3~2~-9 air at @s run setblock ~-3~2~-9 sand 0 replace
execute as @s unless block ~-3~1~-9 air at @s run setblock ~-3~1~-9 sand 0 replace
execute as @s unless block ~-3~0~-9 air at @s run setblock ~-3~0~-9 sand 0 replace
execute as @s unless block ~-3~-1~-9 air at @s run setblock ~-3~-1~-9 sand 0 replace
execute as @s unless block ~-3~-2~-9 air at @s run setblock ~-3~-2~-9 sand 0 replace
execute as @s unless block ~-3~-3~-9 air at @s run setblock ~-3~-3~-9 sand 0 replace
execute as @s unless block ~-3~-4~-9 air at @s run setblock ~-3~-4~-9 sand 0 replace
execute as @s unless block ~-3~-5~-9 air at @s run setblock ~-3~-5~-9 sand 0 replace
execute as @s unless block ~-3~7~9 air at @s run setblock ~-3~7~9 sand 0 replace
execute as @s unless block ~-3~6~9 air at @s run setblock ~-3~6~9 sand 0 replace
execute as @s unless block ~-3~5~9 air at @s run setblock ~-3~5~9 sand 0 replace
execute as @s unless block ~-3~4~9 air at @s run setblock ~-3~4~9 sand 0 replace
execute as @s unless block ~-3~3~9 air at @s run setblock ~-3~3~9 sand 0 replace
execute as @s unless block ~-3~2~9 air at @s run setblock ~-3~2~9 sand 0 replace
execute as @s unless block ~-3~1~9 air at @s run setblock ~-3~1~9 sand 0 replace
execute as @s unless block ~-3~0~9 air at @s run setblock ~-3~0~9 sand 0 replace
execute as @s unless block ~-3~-1~9 air at @s run setblock ~-3~-1~9 sand 0 replace
execute as @s unless block ~-3~-2~9 air at @s run setblock ~-3~-2~9 sand 0 replace
execute as @s unless block ~-3~-3~9 air at @s run setblock ~-3~-3~9 sand 0 replace
execute as @s unless block ~-3~-4~9 air at @s run setblock ~-3~-4~9 sand 0 replace
execute as @s unless block ~-3~-5~9 air at @s run setblock ~-3~-5~9 sand 0 replace
execute as @s unless block ~-2~7~-9 air at @s run setblock ~-2~7~-9 sand 0 replace
execute as @s unless block ~-2~6~-9 air at @s run setblock ~-2~6~-9 sand 0 replace
execute as @s unless block ~-2~5~-9 air at @s run setblock ~-2~5~-9 sand 0 replace
execute as @s unless block ~-2~4~-9 air at @s run setblock ~-2~4~-9 sand 0 replace
execute as @s unless block ~-2~3~-9 air at @s run setblock ~-2~3~-9 sand 0 replace
execute as @s unless block ~-2~2~-9 air at @s run setblock ~-2~2~-9 sand 0 replace
execute as @s unless block ~-2~1~-9 air at @s run setblock ~-2~1~-9 sand 0 replace
execute as @s unless block ~-2~0~-9 air at @s run setblock ~-2~0~-9 sand 0 replace
execute as @s unless block ~-2~-1~-9 air at @s run setblock ~-2~-1~-9 sand 0 replace
execute as @s unless block ~-2~-2~-9 air at @s run setblock ~-2~-2~-9 sand 0 replace
execute as @s unless block ~-2~-3~-9 air at @s run setblock ~-2~-3~-9 sand 0 replace
execute as @s unless block ~-2~-4~-9 air at @s run setblock ~-2~-4~-9 sand 0 replace
execute as @s unless block ~-2~-5~-9 air at @s run setblock ~-2~-5~-9 sand 0 replace
execute as @s unless block ~-2~7~9 air at @s run setblock ~-2~7~9 sand 0 replace
execute as @s unless block ~-2~6~9 air at @s run setblock ~-2~6~9 sand 0 replace
execute as @s unless block ~-2~5~9 air at @s run setblock ~-2~5~9 sand 0 replace
execute as @s unless block ~-2~4~9 air at @s run setblock ~-2~4~9 sand 0 replace
execute as @s unless block ~-2~3~9 air at @s run setblock ~-2~3~9 sand 0 replace
execute as @s unless block ~-2~2~9 air at @s run setblock ~-2~2~9 sand 0 replace
execute as @s unless block ~-2~1~9 air at @s run setblock ~-2~1~9 sand 0 replace
execute as @s unless block ~-2~0~9 air at @s run setblock ~-2~0~9 sand 0 replace
execute as @s unless block ~-2~-1~9 air at @s run setblock ~-2~-1~9 sand 0 replace
execute as @s unless block ~-2~-2~9 air at @s run setblock ~-2~-2~9 sand 0 replace
execute as @s unless block ~-2~-3~9 air at @s run setblock ~-2~-3~9 sand 0 replace
execute as @s unless block ~-2~-4~9 air at @s run setblock ~-2~-4~9 sand 0 replace
execute as @s unless block ~-2~-5~9 air at @s run setblock ~-2~-5~9 sand 0 replace
execute as @s unless block ~-1~7~-9 air at @s run setblock ~-1~7~-9 sand 0 replace
execute as @s unless block ~-1~6~-9 air at @s run setblock ~-1~6~-9 sand 0 replace
execute as @s unless block ~-1~5~-9 air at @s run setblock ~-1~5~-9 sand 0 replace
execute as @s unless block ~-1~4~-9 air at @s run setblock ~-1~4~-9 sand 0 replace
execute as @s unless block ~-1~3~-9 air at @s run setblock ~-1~3~-9 sand 0 replace
execute as @s unless block ~-1~2~-9 air at @s run setblock ~-1~2~-9 sand 0 replace
execute as @s unless block ~-1~1~-9 air at @s run setblock ~-1~1~-9 sand 0 replace
execute as @s unless block ~-1~0~-9 air at @s run setblock ~-1~0~-9 sand 0 replace
execute as @s unless block ~-1~-1~-9 air at @s run setblock ~-1~-1~-9 sand 0 replace
execute as @s unless block ~-1~-2~-9 air at @s run setblock ~-1~-2~-9 sand 0 replace
execute as @s unless block ~-1~-3~-9 air at @s run setblock ~-1~-3~-9 sand 0 replace
execute as @s unless block ~-1~-4~-9 air at @s run setblock ~-1~-4~-9 sand 0 replace
execute as @s unless block ~-1~-5~-9 air at @s run setblock ~-1~-5~-9 sand 0 replace
execute as @s unless block ~-1~7~9 air at @s run setblock ~-1~7~9 sand 0 replace
execute as @s unless block ~-1~6~9 air at @s run setblock ~-1~6~9 sand 0 replace
execute as @s unless block ~-1~5~9 air at @s run setblock ~-1~5~9 sand 0 replace
execute as @s unless block ~-1~4~9 air at @s run setblock ~-1~4~9 sand 0 replace
execute as @s unless block ~-1~3~9 air at @s run setblock ~-1~3~9 sand 0 replace
execute as @s unless block ~-1~2~9 air at @s run setblock ~-1~2~9 sand 0 replace
execute as @s unless block ~-1~1~9 air at @s run setblock ~-1~1~9 sand 0 replace
execute as @s unless block ~-1~0~9 air at @s run setblock ~-1~0~9 sand 0 replace
execute as @s unless block ~-1~-1~9 air at @s run setblock ~-1~-1~9 sand 0 replace
execute as @s unless block ~-1~-2~9 air at @s run setblock ~-1~-2~9 sand 0 replace
execute as @s unless block ~-1~-3~9 air at @s run setblock ~-1~-3~9 sand 0 replace
execute as @s unless block ~-1~-4~9 air at @s run setblock ~-1~-4~9 sand 0 replace
execute as @s unless block ~-1~-5~9 air at @s run setblock ~-1~-5~9 sand 0 replace
execute as @s unless block ~0~7~-9 air at @s run setblock ~0~7~-9 sand 0 replace
execute as @s unless block ~0~6~-9 air at @s run setblock ~0~6~-9 sand 0 replace
execute as @s unless block ~0~5~-9 air at @s run setblock ~0~5~-9 sand 0 replace
execute as @s unless block ~0~4~-9 air at @s run setblock ~0~4~-9 sand 0 replace
execute as @s unless block ~0~3~-9 air at @s run setblock ~0~3~-9 sand 0 replace
execute as @s unless block ~0~2~-9 air at @s run setblock ~0~2~-9 sand 0 replace
execute as @s unless block ~0~1~-9 air at @s run setblock ~0~1~-9 sand 0 replace
execute as @s unless block ~0~0~-9 air at @s run setblock ~0~0~-9 sand 0 replace
execute as @s unless block ~0~-1~-9 air at @s run setblock ~0~-1~-9 sand 0 replace
execute as @s unless block ~0~-2~-9 air at @s run setblock ~0~-2~-9 sand 0 replace
execute as @s unless block ~0~-3~-9 air at @s run setblock ~0~-3~-9 sand 0 replace
execute as @s unless block ~0~-4~-9 air at @s run setblock ~0~-4~-9 sand 0 replace
execute as @s unless block ~0~-5~-9 air at @s run setblock ~0~-5~-9 sand 0 replace
execute as @s unless block ~0~7~9 air at @s run setblock ~0~7~9 sand 0 replace
execute as @s unless block ~0~6~9 air at @s run setblock ~0~6~9 sand 0 replace
execute as @s unless block ~0~5~9 air at @s run setblock ~0~5~9 sand 0 replace
execute as @s unless block ~0~4~9 air at @s run setblock ~0~4~9 sand 0 replace
execute as @s unless block ~0~3~9 air at @s run setblock ~0~3~9 sand 0 replace
execute as @s unless block ~0~2~9 air at @s run setblock ~0~2~9 sand 0 replace
execute as @s unless block ~0~1~9 air at @s run setblock ~0~1~9 sand 0 replace
execute as @s unless block ~0~0~9 air at @s run setblock ~0~0~9 sand 0 replace
execute as @s unless block ~0~-1~9 air at @s run setblock ~0~-1~9 sand 0 replace
execute as @s unless block ~0~-2~9 air at @s run setblock ~0~-2~9 sand 0 replace
execute as @s unless block ~0~-3~9 air at @s run setblock ~0~-3~9 sand 0 replace
execute as @s unless block ~0~-4~9 air at @s run setblock ~0~-4~9 sand 0 replace
execute as @s unless block ~0~-5~9 air at @s run setblock ~0~-5~9 sand 0 replace
execute as @s unless block ~1~7~-9 air at @s run setblock ~1~7~-9 sand 0 replace
execute as @s unless block ~1~6~-9 air at @s run setblock ~1~6~-9 sand 0 replace
execute as @s unless block ~1~5~-9 air at @s run setblock ~1~5~-9 sand 0 replace
execute as @s unless block ~1~4~-9 air at @s run setblock ~1~4~-9 sand 0 replace
execute as @s unless block ~1~3~-9 air at @s run setblock ~1~3~-9 sand 0 replace
execute as @s unless block ~1~2~-9 air at @s run setblock ~1~2~-9 sand 0 replace
execute as @s unless block ~1~1~-9 air at @s run setblock ~1~1~-9 sand 0 replace
execute as @s unless block ~1~0~-9 air at @s run setblock ~1~0~-9 sand 0 replace
execute as @s unless block ~1~-1~-9 air at @s run setblock ~1~-1~-9 sand 0 replace
execute as @s unless block ~1~-2~-9 air at @s run setblock ~1~-2~-9 sand 0 replace
execute as @s unless block ~1~-3~-9 air at @s run setblock ~1~-3~-9 sand 0 replace
execute as @s unless block ~1~-4~-9 air at @s run setblock ~1~-4~-9 sand 0 replace
execute as @s unless block ~1~-5~-9 air at @s run setblock ~1~-5~-9 sand 0 replace
execute as @s unless block ~1~7~9 air at @s run setblock ~1~7~9 sand 0 replace
execute as @s unless block ~1~6~9 air at @s run setblock ~1~6~9 sand 0 replace
execute as @s unless block ~1~5~9 air at @s run setblock ~1~5~9 sand 0 replace
execute as @s unless block ~1~4~9 air at @s run setblock ~1~4~9 sand 0 replace
execute as @s unless block ~1~3~9 air at @s run setblock ~1~3~9 sand 0 replace
execute as @s unless block ~1~2~9 air at @s run setblock ~1~2~9 sand 0 replace
execute as @s unless block ~1~1~9 air at @s run setblock ~1~1~9 sand 0 replace
execute as @s unless block ~1~0~9 air at @s run setblock ~1~0~9 sand 0 replace
execute as @s unless block ~1~-1~9 air at @s run setblock ~1~-1~9 sand 0 replace
execute as @s unless block ~1~-2~9 air at @s run setblock ~1~-2~9 sand 0 replace
execute as @s unless block ~1~-3~9 air at @s run setblock ~1~-3~9 sand 0 replace
execute as @s unless block ~1~-4~9 air at @s run setblock ~1~-4~9 sand 0 replace
execute as @s unless block ~1~-5~9 air at @s run setblock ~1~-5~9 sand 0 replace
execute as @s unless block ~2~7~-9 air at @s run setblock ~2~7~-9 sand 0 replace
execute as @s unless block ~2~6~-9 air at @s run setblock ~2~6~-9 sand 0 replace
execute as @s unless block ~2~5~-9 air at @s run setblock ~2~5~-9 sand 0 replace
execute as @s unless block ~2~4~-9 air at @s run setblock ~2~4~-9 sand 0 replace
execute as @s unless block ~2~3~-9 air at @s run setblock ~2~3~-9 sand 0 replace
execute as @s unless block ~2~2~-9 air at @s run setblock ~2~2~-9 sand 0 replace
execute as @s unless block ~2~1~-9 air at @s run setblock ~2~1~-9 sand 0 replace
execute as @s unless block ~2~0~-9 air at @s run setblock ~2~0~-9 sand 0 replace
execute as @s unless block ~2~-1~-9 air at @s run setblock ~2~-1~-9 sand 0 replace
execute as @s unless block ~2~-2~-9 air at @s run setblock ~2~-2~-9 sand 0 replace
execute as @s unless block ~2~-3~-9 air at @s run setblock ~2~-3~-9 sand 0 replace
execute as @s unless block ~2~-4~-9 air at @s run setblock ~2~-4~-9 sand 0 replace
execute as @s unless block ~2~-5~-9 air at @s run setblock ~2~-5~-9 sand 0 replace
execute as @s unless block ~2~7~9 air at @s run setblock ~2~7~9 sand 0 replace
execute as @s unless block ~2~6~9 air at @s run setblock ~2~6~9 sand 0 replace
execute as @s unless block ~2~5~9 air at @s run setblock ~2~5~9 sand 0 replace
execute as @s unless block ~2~4~9 air at @s run setblock ~2~4~9 sand 0 replace
execute as @s unless block ~2~3~9 air at @s run setblock ~2~3~9 sand 0 replace
execute as @s unless block ~2~2~9 air at @s run setblock ~2~2~9 sand 0 replace
execute as @s unless block ~2~1~9 air at @s run setblock ~2~1~9 sand 0 replace
execute as @s unless block ~2~0~9 air at @s run setblock ~2~0~9 sand 0 replace
execute as @s unless block ~2~-1~9 air at @s run setblock ~2~-1~9 sand 0 replace
execute as @s unless block ~2~-2~9 air at @s run setblock ~2~-2~9 sand 0 replace
execute as @s unless block ~2~-3~9 air at @s run setblock ~2~-3~9 sand 0 replace
execute as @s unless block ~2~-4~9 air at @s run setblock ~2~-4~9 sand 0 replace
execute as @s unless block ~2~-5~9 air at @s run setblock ~2~-5~9 sand 0 replace
execute as @s unless block ~3~7~-9 air at @s run setblock ~3~7~-9 sand 0 replace
execute as @s unless block ~3~6~-9 air at @s run setblock ~3~6~-9 sand 0 replace
execute as @s unless block ~3~5~-9 air at @s run setblock ~3~5~-9 sand 0 replace
execute as @s unless block ~3~4~-9 air at @s run setblock ~3~4~-9 sand 0 replace
execute as @s unless block ~3~3~-9 air at @s run setblock ~3~3~-9 sand 0 replace
execute as @s unless block ~3~2~-9 air at @s run setblock ~3~2~-9 sand 0 replace
execute as @s unless block ~3~1~-9 air at @s run setblock ~3~1~-9 sand 0 replace
execute as @s unless block ~3~0~-9 air at @s run setblock ~3~0~-9 sand 0 replace
execute as @s unless block ~3~-1~-9 air at @s run setblock ~3~-1~-9 sand 0 replace
execute as @s unless block ~3~-2~-9 air at @s run setblock ~3~-2~-9 sand 0 replace
execute as @s unless block ~3~-3~-9 air at @s run setblock ~3~-3~-9 sand 0 replace
execute as @s unless block ~3~-4~-9 air at @s run setblock ~3~-4~-9 sand 0 replace
execute as @s unless block ~3~-5~-9 air at @s run setblock ~3~-5~-9 sand 0 replace
execute as @s unless block ~3~7~9 air at @s run setblock ~3~7~9 sand 0 replace
execute as @s unless block ~3~6~9 air at @s run setblock ~3~6~9 sand 0 replace
execute as @s unless block ~3~5~9 air at @s run setblock ~3~5~9 sand 0 replace
execute as @s unless block ~3~4~9 air at @s run setblock ~3~4~9 sand 0 replace
execute as @s unless block ~3~3~9 air at @s run setblock ~3~3~9 sand 0 replace
execute as @s unless block ~3~2~9 air at @s run setblock ~3~2~9 sand 0 replace
execute as @s unless block ~3~1~9 air at @s run setblock ~3~1~9 sand 0 replace
execute as @s unless block ~3~0~9 air at @s run setblock ~3~0~9 sand 0 replace
execute as @s unless block ~3~-1~9 air at @s run setblock ~3~-1~9 sand 0 replace
execute as @s unless block ~3~-2~9 air at @s run setblock ~3~-2~9 sand 0 replace
execute as @s unless block ~3~-3~9 air at @s run setblock ~3~-3~9 sand 0 replace
execute as @s unless block ~3~-4~9 air at @s run setblock ~3~-4~9 sand 0 replace
execute as @s unless block ~3~-5~9 air at @s run setblock ~3~-5~9 sand 0 replace
execute as @s unless block ~4~7~-9 air at @s run setblock ~4~7~-9 sand 0 replace
execute as @s unless block ~4~6~-9 air at @s run setblock ~4~6~-9 sand 0 replace
execute as @s unless block ~4~5~-9 air at @s run setblock ~4~5~-9 sand 0 replace
execute as @s unless block ~4~4~-9 air at @s run setblock ~4~4~-9 sand 0 replace
execute as @s unless block ~4~3~-9 air at @s run setblock ~4~3~-9 sand 0 replace
execute as @s unless block ~4~2~-9 air at @s run setblock ~4~2~-9 sand 0 replace
execute as @s unless block ~4~1~-9 air at @s run setblock ~4~1~-9 sand 0 replace
execute as @s unless block ~4~0~-9 air at @s run setblock ~4~0~-9 sand 0 replace
execute as @s unless block ~4~-1~-9 air at @s run setblock ~4~-1~-9 sand 0 replace
execute as @s unless block ~4~-2~-9 air at @s run setblock ~4~-2~-9 sand 0 replace
execute as @s unless block ~4~-3~-9 air at @s run setblock ~4~-3~-9 sand 0 replace
execute as @s unless block ~4~-4~-9 air at @s run setblock ~4~-4~-9 sand 0 replace
execute as @s unless block ~4~-5~-9 air at @s run setblock ~4~-5~-9 sand 0 replace
execute as @s unless block ~4~7~9 air at @s run setblock ~4~7~9 sand 0 replace
execute as @s unless block ~4~6~9 air at @s run setblock ~4~6~9 sand 0 replace
execute as @s unless block ~4~5~9 air at @s run setblock ~4~5~9 sand 0 replace
execute as @s unless block ~4~4~9 air at @s run setblock ~4~4~9 sand 0 replace
execute as @s unless block ~4~3~9 air at @s run setblock ~4~3~9 sand 0 replace
execute as @s unless block ~4~2~9 air at @s run setblock ~4~2~9 sand 0 replace
execute as @s unless block ~4~1~9 air at @s run setblock ~4~1~9 sand 0 replace
execute as @s unless block ~4~0~9 air at @s run setblock ~4~0~9 sand 0 replace
execute as @s unless block ~4~-1~9 air at @s run setblock ~4~-1~9 sand 0 replace
execute as @s unless block ~4~-2~9 air at @s run setblock ~4~-2~9 sand 0 replace
execute as @s unless block ~4~-3~9 air at @s run setblock ~4~-3~9 sand 0 replace
execute as @s unless block ~4~-4~9 air at @s run setblock ~4~-4~9 sand 0 replace
execute as @s unless block ~4~-5~9 air at @s run setblock ~4~-5~9 sand 0 replace
execute as @s unless block ~5~7~-9 air at @s run setblock ~5~7~-9 sand 0 replace
execute as @s unless block ~5~6~-9 air at @s run setblock ~5~6~-9 sand 0 replace
execute as @s unless block ~5~5~-9 air at @s run setblock ~5~5~-9 sand 0 replace
execute as @s unless block ~5~4~-9 air at @s run setblock ~5~4~-9 sand 0 replace
execute as @s unless block ~5~3~-9 air at @s run setblock ~5~3~-9 sand 0 replace
execute as @s unless block ~5~2~-9 air at @s run setblock ~5~2~-9 sand 0 replace
execute as @s unless block ~5~1~-9 air at @s run setblock ~5~1~-9 sand 0 replace
execute as @s unless block ~5~0~-9 air at @s run setblock ~5~0~-9 sand 0 replace
execute as @s unless block ~5~-1~-9 air at @s run setblock ~5~-1~-9 sand 0 replace
execute as @s unless block ~5~-2~-9 air at @s run setblock ~5~-2~-9 sand 0 replace
execute as @s unless block ~5~-3~-9 air at @s run setblock ~5~-3~-9 sand 0 replace
execute as @s unless block ~5~-4~-9 air at @s run setblock ~5~-4~-9 sand 0 replace
execute as @s unless block ~5~-5~-9 air at @s run setblock ~5~-5~-9 sand 0 replace
execute as @s unless block ~5~7~9 air at @s run setblock ~5~7~9 sand 0 replace
execute as @s unless block ~5~6~9 air at @s run setblock ~5~6~9 sand 0 replace
execute as @s unless block ~5~5~9 air at @s run setblock ~5~5~9 sand 0 replace
execute as @s unless block ~5~4~9 air at @s run setblock ~5~4~9 sand 0 replace
execute as @s unless block ~5~3~9 air at @s run setblock ~5~3~9 sand 0 replace
execute as @s unless block ~5~2~9 air at @s run setblock ~5~2~9 sand 0 replace
execute as @s unless block ~5~1~9 air at @s run setblock ~5~1~9 sand 0 replace
execute as @s unless block ~5~0~9 air at @s run setblock ~5~0~9 sand 0 replace
execute as @s unless block ~5~-1~9 air at @s run setblock ~5~-1~9 sand 0 replace
execute as @s unless block ~5~-2~9 air at @s run setblock ~5~-2~9 sand 0 replace
execute as @s unless block ~5~-3~9 air at @s run setblock ~5~-3~9 sand 0 replace
execute as @s unless block ~5~-4~9 air at @s run setblock ~5~-4~9 sand 0 replace
execute as @s unless block ~5~-5~9 air at @s run setblock ~5~-5~9 sand 0 replace
execute as @s unless block ~6~7~-9 air at @s run setblock ~6~7~-9 sand 0 replace
execute as @s unless block ~6~6~-9 air at @s run setblock ~6~6~-9 sand 0 replace
execute as @s unless block ~6~5~-9 air at @s run setblock ~6~5~-9 sand 0 replace
execute as @s unless block ~6~4~-9 air at @s run setblock ~6~4~-9 sand 0 replace
execute as @s unless block ~6~3~-9 air at @s run setblock ~6~3~-9 sand 0 replace
execute as @s unless block ~6~2~-9 air at @s run setblock ~6~2~-9 sand 0 replace
execute as @s unless block ~6~1~-9 air at @s run setblock ~6~1~-9 sand 0 replace
execute as @s unless block ~6~0~-9 air at @s run setblock ~6~0~-9 sand 0 replace
execute as @s unless block ~6~-1~-9 air at @s run setblock ~6~-1~-9 sand 0 replace
execute as @s unless block ~6~-2~-9 air at @s run setblock ~6~-2~-9 sand 0 replace
execute as @s unless block ~6~-3~-9 air at @s run setblock ~6~-3~-9 sand 0 replace
execute as @s unless block ~6~-4~-9 air at @s run setblock ~6~-4~-9 sand 0 replace
execute as @s unless block ~6~-5~-9 air at @s run setblock ~6~-5~-9 sand 0 replace
execute as @s unless block ~6~7~9 air at @s run setblock ~6~7~9 sand 0 replace
execute as @s unless block ~6~6~9 air at @s run setblock ~6~6~9 sand 0 replace
execute as @s unless block ~6~5~9 air at @s run setblock ~6~5~9 sand 0 replace
execute as @s unless block ~6~4~9 air at @s run setblock ~6~4~9 sand 0 replace
execute as @s unless block ~6~3~9 air at @s run setblock ~6~3~9 sand 0 replace
execute as @s unless block ~6~2~9 air at @s run setblock ~6~2~9 sand 0 replace
execute as @s unless block ~6~1~9 air at @s run setblock ~6~1~9 sand 0 replace
execute as @s unless block ~6~0~9 air at @s run setblock ~6~0~9 sand 0 replace
execute as @s unless block ~6~-1~9 air at @s run setblock ~6~-1~9 sand 0 replace
execute as @s unless block ~6~-2~9 air at @s run setblock ~6~-2~9 sand 0 replace
execute as @s unless block ~6~-3~9 air at @s run setblock ~6~-3~9 sand 0 replace
execute as @s unless block ~6~-4~9 air at @s run setblock ~6~-4~9 sand 0 replace
execute as @s unless block ~6~-5~9 air at @s run setblock ~6~-5~9 sand 0 replace
execute as @s unless block ~7~7~-9 air at @s run setblock ~7~7~-9 sand 0 replace
execute as @s unless block ~7~6~-9 air at @s run setblock ~7~6~-9 sand 0 replace
execute as @s unless block ~7~5~-9 air at @s run setblock ~7~5~-9 sand 0 replace
execute as @s unless block ~7~4~-9 air at @s run setblock ~7~4~-9 sand 0 replace
execute as @s unless block ~7~3~-9 air at @s run setblock ~7~3~-9 sand 0 replace
execute as @s unless block ~7~2~-9 air at @s run setblock ~7~2~-9 sand 0 replace
execute as @s unless block ~7~1~-9 air at @s run setblock ~7~1~-9 sand 0 replace
execute as @s unless block ~7~0~-9 air at @s run setblock ~7~0~-9 sand 0 replace
execute as @s unless block ~7~-1~-9 air at @s run setblock ~7~-1~-9 sand 0 replace
execute as @s unless block ~7~-2~-9 air at @s run setblock ~7~-2~-9 sand 0 replace
execute as @s unless block ~7~-3~-9 air at @s run setblock ~7~-3~-9 sand 0 replace
execute as @s unless block ~7~-4~-9 air at @s run setblock ~7~-4~-9 sand 0 replace
execute as @s unless block ~7~-5~-9 air at @s run setblock ~7~-5~-9 sand 0 replace
execute as @s unless block ~7~7~9 air at @s run setblock ~7~7~9 sand 0 replace
execute as @s unless block ~7~6~9 air at @s run setblock ~7~6~9 sand 0 replace
execute as @s unless block ~7~5~9 air at @s run setblock ~7~5~9 sand 0 replace
execute as @s unless block ~7~4~9 air at @s run setblock ~7~4~9 sand 0 replace
execute as @s unless block ~7~3~9 air at @s run setblock ~7~3~9 sand 0 replace
execute as @s unless block ~7~2~9 air at @s run setblock ~7~2~9 sand 0 replace
execute as @s unless block ~7~1~9 air at @s run setblock ~7~1~9 sand 0 replace
execute as @s unless block ~7~0~9 air at @s run setblock ~7~0~9 sand 0 replace
execute as @s unless block ~7~-1~9 air at @s run setblock ~7~-1~9 sand 0 replace
execute as @s unless block ~7~-2~9 air at @s run setblock ~7~-2~9 sand 0 replace
execute as @s unless block ~7~-3~9 air at @s run setblock ~7~-3~9 sand 0 replace
execute as @s unless block ~7~-4~9 air at @s run setblock ~7~-4~9 sand 0 replace
execute as @s unless block ~7~-5~9 air at @s run setblock ~7~-5~9 sand 0 replace
execute as @s unless block ~8~7~-9 air at @s run setblock ~8~7~-9 sand 0 replace
execute as @s unless block ~8~6~-9 air at @s run setblock ~8~6~-9 sand 0 replace
execute as @s unless block ~8~5~-9 air at @s run setblock ~8~5~-9 sand 0 replace
execute as @s unless block ~8~4~-9 air at @s run setblock ~8~4~-9 sand 0 replace
execute as @s unless block ~8~3~-9 air at @s run setblock ~8~3~-9 sand 0 replace
execute as @s unless block ~8~2~-9 air at @s run setblock ~8~2~-9 sand 0 replace
execute as @s unless block ~8~1~-9 air at @s run setblock ~8~1~-9 sand 0 replace
execute as @s unless block ~8~0~-9 air at @s run setblock ~8~0~-9 sand 0 replace
execute as @s unless block ~8~-1~-9 air at @s run setblock ~8~-1~-9 sand 0 replace
execute as @s unless block ~8~-2~-9 air at @s run setblock ~8~-2~-9 sand 0 replace
execute as @s unless block ~8~-3~-9 air at @s run setblock ~8~-3~-9 sand 0 replace
execute as @s unless block ~8~-4~-9 air at @s run setblock ~8~-4~-9 sand 0 replace
execute as @s unless block ~8~-5~-9 air at @s run setblock ~8~-5~-9 sand 0 replace
execute as @s unless block ~8~7~9 air at @s run setblock ~8~7~9 sand 0 replace
execute as @s unless block ~8~6~9 air at @s run setblock ~8~6~9 sand 0 replace
execute as @s unless block ~8~5~9 air at @s run setblock ~8~5~9 sand 0 replace
execute as @s unless block ~8~4~9 air at @s run setblock ~8~4~9 sand 0 replace
execute as @s unless block ~8~3~9 air at @s run setblock ~8~3~9 sand 0 replace
execute as @s unless block ~8~2~9 air at @s run setblock ~8~2~9 sand 0 replace
execute as @s unless block ~8~1~9 air at @s run setblock ~8~1~9 sand 0 replace
execute as @s unless block ~8~0~9 air at @s run setblock ~8~0~9 sand 0 replace
execute as @s unless block ~8~-1~9 air at @s run setblock ~8~-1~9 sand 0 replace
execute as @s unless block ~8~-2~9 air at @s run setblock ~8~-2~9 sand 0 replace
execute as @s unless block ~8~-3~9 air at @s run setblock ~8~-3~9 sand 0 replace
execute as @s unless block ~8~-4~9 air at @s run setblock ~8~-4~9 sand 0 replace
execute as @s unless block ~8~-5~9 air at @s run setblock ~8~-5~9 sand 0 replace
execute as @s unless block ~9~7~-9 air at @s run setblock ~9~7~-9 sand 0 replace
execute as @s unless block ~9~6~-9 air at @s run setblock ~9~6~-9 sand 0 replace
execute as @s unless block ~9~5~-9 air at @s run setblock ~9~5~-9 sand 0 replace
execute as @s unless block ~9~4~-9 air at @s run setblock ~9~4~-9 sand 0 replace
execute as @s unless block ~9~3~-9 air at @s run setblock ~9~3~-9 sand 0 replace
execute as @s unless block ~9~2~-9 air at @s run setblock ~9~2~-9 sand 0 replace
execute as @s unless block ~9~1~-9 air at @s run setblock ~9~1~-9 sand 0 replace
execute as @s unless block ~9~0~-9 air at @s run setblock ~9~0~-9 sand 0 replace
execute as @s unless block ~9~-1~-9 air at @s run setblock ~9~-1~-9 sand 0 replace
execute as @s unless block ~9~-2~-9 air at @s run setblock ~9~-2~-9 sand 0 replace
execute as @s unless block ~9~-3~-9 air at @s run setblock ~9~-3~-9 sand 0 replace
execute as @s unless block ~9~-4~-9 air at @s run setblock ~9~-4~-9 sand 0 replace
execute as @s unless block ~9~-5~-9 air at @s run setblock ~9~-5~-9 sand 0 replace
execute as @s unless block ~9~7~-8 air at @s run setblock ~9~7~-8 sand 0 replace
execute as @s unless block ~9~6~-8 air at @s run setblock ~9~6~-8 sand 0 replace
execute as @s unless block ~9~5~-8 air at @s run setblock ~9~5~-8 sand 0 replace
execute as @s unless block ~9~4~-8 air at @s run setblock ~9~4~-8 sand 0 replace
execute as @s unless block ~9~3~-8 air at @s run setblock ~9~3~-8 sand 0 replace
execute as @s unless block ~9~2~-8 air at @s run setblock ~9~2~-8 sand 0 replace
execute as @s unless block ~9~1~-8 air at @s run setblock ~9~1~-8 sand 0 replace
execute as @s unless block ~9~0~-8 air at @s run setblock ~9~0~-8 sand 0 replace
execute as @s unless block ~9~-1~-8 air at @s run setblock ~9~-1~-8 sand 0 replace
execute as @s unless block ~9~-2~-8 air at @s run setblock ~9~-2~-8 sand 0 replace
execute as @s unless block ~9~-3~-8 air at @s run setblock ~9~-3~-8 sand 0 replace
execute as @s unless block ~9~-4~-8 air at @s run setblock ~9~-4~-8 sand 0 replace
execute as @s unless block ~9~-5~-8 air at @s run setblock ~9~-5~-8 sand 0 replace
execute as @s unless block ~9~7~-7 air at @s run setblock ~9~7~-7 sand 0 replace
execute as @s unless block ~9~6~-7 air at @s run setblock ~9~6~-7 sand 0 replace
execute as @s unless block ~9~5~-7 air at @s run setblock ~9~5~-7 sand 0 replace
execute as @s unless block ~9~4~-7 air at @s run setblock ~9~4~-7 sand 0 replace
execute as @s unless block ~9~3~-7 air at @s run setblock ~9~3~-7 sand 0 replace
execute as @s unless block ~9~2~-7 air at @s run setblock ~9~2~-7 sand 0 replace
execute as @s unless block ~9~1~-7 air at @s run setblock ~9~1~-7 sand 0 replace
execute as @s unless block ~9~0~-7 air at @s run setblock ~9~0~-7 sand 0 replace
execute as @s unless block ~9~-1~-7 air at @s run setblock ~9~-1~-7 sand 0 replace
execute as @s unless block ~9~-2~-7 air at @s run setblock ~9~-2~-7 sand 0 replace
execute as @s unless block ~9~-3~-7 air at @s run setblock ~9~-3~-7 sand 0 replace
execute as @s unless block ~9~-4~-7 air at @s run setblock ~9~-4~-7 sand 0 replace
execute as @s unless block ~9~-5~-7 air at @s run setblock ~9~-5~-7 sand 0 replace
execute as @s unless block ~9~7~-6 air at @s run setblock ~9~7~-6 sand 0 replace
execute as @s unless block ~9~6~-6 air at @s run setblock ~9~6~-6 sand 0 replace
execute as @s unless block ~9~5~-6 air at @s run setblock ~9~5~-6 sand 0 replace
execute as @s unless block ~9~4~-6 air at @s run setblock ~9~4~-6 sand 0 replace
execute as @s unless block ~9~3~-6 air at @s run setblock ~9~3~-6 sand 0 replace
execute as @s unless block ~9~2~-6 air at @s run setblock ~9~2~-6 sand 0 replace
execute as @s unless block ~9~1~-6 air at @s run setblock ~9~1~-6 sand 0 replace
execute as @s unless block ~9~0~-6 air at @s run setblock ~9~0~-6 sand 0 replace
execute as @s unless block ~9~-1~-6 air at @s run setblock ~9~-1~-6 sand 0 replace
execute as @s unless block ~9~-2~-6 air at @s run setblock ~9~-2~-6 sand 0 replace
execute as @s unless block ~9~-3~-6 air at @s run setblock ~9~-3~-6 sand 0 replace
execute as @s unless block ~9~-4~-6 air at @s run setblock ~9~-4~-6 sand 0 replace
execute as @s unless block ~9~-5~-6 air at @s run setblock ~9~-5~-6 sand 0 replace
execute as @s unless block ~9~7~-5 air at @s run setblock ~9~7~-5 sand 0 replace
execute as @s unless block ~9~6~-5 air at @s run setblock ~9~6~-5 sand 0 replace
execute as @s unless block ~9~5~-5 air at @s run setblock ~9~5~-5 sand 0 replace
execute as @s unless block ~9~4~-5 air at @s run setblock ~9~4~-5 sand 0 replace
execute as @s unless block ~9~3~-5 air at @s run setblock ~9~3~-5 sand 0 replace
execute as @s unless block ~9~2~-5 air at @s run setblock ~9~2~-5 sand 0 replace
execute as @s unless block ~9~1~-5 air at @s run setblock ~9~1~-5 sand 0 replace
execute as @s unless block ~9~0~-5 air at @s run setblock ~9~0~-5 sand 0 replace
execute as @s unless block ~9~-1~-5 air at @s run setblock ~9~-1~-5 sand 0 replace
execute as @s unless block ~9~-2~-5 air at @s run setblock ~9~-2~-5 sand 0 replace
execute as @s unless block ~9~-3~-5 air at @s run setblock ~9~-3~-5 sand 0 replace
execute as @s unless block ~9~-4~-5 air at @s run setblock ~9~-4~-5 sand 0 replace
execute as @s unless block ~9~-5~-5 air at @s run setblock ~9~-5~-5 sand 0 replace
execute as @s unless block ~9~7~-4 air at @s run setblock ~9~7~-4 sand 0 replace
execute as @s unless block ~9~6~-4 air at @s run setblock ~9~6~-4 sand 0 replace
execute as @s unless block ~9~5~-4 air at @s run setblock ~9~5~-4 sand 0 replace
execute as @s unless block ~9~4~-4 air at @s run setblock ~9~4~-4 sand 0 replace
execute as @s unless block ~9~3~-4 air at @s run setblock ~9~3~-4 sand 0 replace
execute as @s unless block ~9~2~-4 air at @s run setblock ~9~2~-4 sand 0 replace
execute as @s unless block ~9~1~-4 air at @s run setblock ~9~1~-4 sand 0 replace
execute as @s unless block ~9~0~-4 air at @s run setblock ~9~0~-4 sand 0 replace
execute as @s unless block ~9~-1~-4 air at @s run setblock ~9~-1~-4 sand 0 replace
execute as @s unless block ~9~-2~-4 air at @s run setblock ~9~-2~-4 sand 0 replace
execute as @s unless block ~9~-3~-4 air at @s run setblock ~9~-3~-4 sand 0 replace
execute as @s unless block ~9~-4~-4 air at @s run setblock ~9~-4~-4 sand 0 replace
execute as @s unless block ~9~-5~-4 air at @s run setblock ~9~-5~-4 sand 0 replace
execute as @s unless block ~9~7~-3 air at @s run setblock ~9~7~-3 sand 0 replace
execute as @s unless block ~9~6~-3 air at @s run setblock ~9~6~-3 sand 0 replace
execute as @s unless block ~9~5~-3 air at @s run setblock ~9~5~-3 sand 0 replace
execute as @s unless block ~9~4~-3 air at @s run setblock ~9~4~-3 sand 0 replace
execute as @s unless block ~9~3~-3 air at @s run setblock ~9~3~-3 sand 0 replace
execute as @s unless block ~9~2~-3 air at @s run setblock ~9~2~-3 sand 0 replace
execute as @s unless block ~9~1~-3 air at @s run setblock ~9~1~-3 sand 0 replace
execute as @s unless block ~9~0~-3 air at @s run setblock ~9~0~-3 sand 0 replace
execute as @s unless block ~9~-1~-3 air at @s run setblock ~9~-1~-3 sand 0 replace
execute as @s unless block ~9~-2~-3 air at @s run setblock ~9~-2~-3 sand 0 replace
execute as @s unless block ~9~-3~-3 air at @s run setblock ~9~-3~-3 sand 0 replace
execute as @s unless block ~9~-4~-3 air at @s run setblock ~9~-4~-3 sand 0 replace
execute as @s unless block ~9~-5~-3 air at @s run setblock ~9~-5~-3 sand 0 replace
execute as @s unless block ~9~7~-2 air at @s run setblock ~9~7~-2 sand 0 replace
execute as @s unless block ~9~6~-2 air at @s run setblock ~9~6~-2 sand 0 replace
execute as @s unless block ~9~5~-2 air at @s run setblock ~9~5~-2 sand 0 replace
execute as @s unless block ~9~4~-2 air at @s run setblock ~9~4~-2 sand 0 replace
execute as @s unless block ~9~3~-2 air at @s run setblock ~9~3~-2 sand 0 replace
execute as @s unless block ~9~2~-2 air at @s run setblock ~9~2~-2 sand 0 replace
execute as @s unless block ~9~1~-2 air at @s run setblock ~9~1~-2 sand 0 replace
execute as @s unless block ~9~0~-2 air at @s run setblock ~9~0~-2 sand 0 replace
execute as @s unless block ~9~-1~-2 air at @s run setblock ~9~-1~-2 sand 0 replace
execute as @s unless block ~9~-2~-2 air at @s run setblock ~9~-2~-2 sand 0 replace
execute as @s unless block ~9~-3~-2 air at @s run setblock ~9~-3~-2 sand 0 replace
execute as @s unless block ~9~-4~-2 air at @s run setblock ~9~-4~-2 sand 0 replace
execute as @s unless block ~9~-5~-2 air at @s run setblock ~9~-5~-2 sand 0 replace
execute as @s unless block ~9~7~-1 air at @s run setblock ~9~7~-1 sand 0 replace
execute as @s unless block ~9~6~-1 air at @s run setblock ~9~6~-1 sand 0 replace
execute as @s unless block ~9~5~-1 air at @s run setblock ~9~5~-1 sand 0 replace
execute as @s unless block ~9~4~-1 air at @s run setblock ~9~4~-1 sand 0 replace
execute as @s unless block ~9~3~-1 air at @s run setblock ~9~3~-1 sand 0 replace
execute as @s unless block ~9~2~-1 air at @s run setblock ~9~2~-1 sand 0 replace
execute as @s unless block ~9~1~-1 air at @s run setblock ~9~1~-1 sand 0 replace
execute as @s unless block ~9~0~-1 air at @s run setblock ~9~0~-1 sand 0 replace
execute as @s unless block ~9~-1~-1 air at @s run setblock ~9~-1~-1 sand 0 replace
execute as @s unless block ~9~-2~-1 air at @s run setblock ~9~-2~-1 sand 0 replace
execute as @s unless block ~9~-3~-1 air at @s run setblock ~9~-3~-1 sand 0 replace
execute as @s unless block ~9~-4~-1 air at @s run setblock ~9~-4~-1 sand 0 replace
execute as @s unless block ~9~-5~-1 air at @s run setblock ~9~-5~-1 sand 0 replace
execute as @s unless block ~9~7~0 air at @s run setblock ~9~7~0 sand 0 replace
execute as @s unless block ~9~6~0 air at @s run setblock ~9~6~0 sand 0 replace
execute as @s unless block ~9~5~0 air at @s run setblock ~9~5~0 sand 0 replace
execute as @s unless block ~9~4~0 air at @s run setblock ~9~4~0 sand 0 replace
execute as @s unless block ~9~3~0 air at @s run setblock ~9~3~0 sand 0 replace
execute as @s unless block ~9~2~0 air at @s run setblock ~9~2~0 sand 0 replace
execute as @s unless block ~9~1~0 air at @s run setblock ~9~1~0 sand 0 replace
execute as @s unless block ~9~0~0 air at @s run setblock ~9~0~0 sand 0 replace
execute as @s unless block ~9~-1~0 air at @s run setblock ~9~-1~0 sand 0 replace
execute as @s unless block ~9~-2~0 air at @s run setblock ~9~-2~0 sand 0 replace
execute as @s unless block ~9~-3~0 air at @s run setblock ~9~-3~0 sand 0 replace
execute as @s unless block ~9~-4~0 air at @s run setblock ~9~-4~0 sand 0 replace
execute as @s unless block ~9~-5~0 air at @s run setblock ~9~-5~0 sand 0 replace
execute as @s unless block ~9~7~1 air at @s run setblock ~9~7~1 sand 0 replace
execute as @s unless block ~9~6~1 air at @s run setblock ~9~6~1 sand 0 replace
execute as @s unless block ~9~5~1 air at @s run setblock ~9~5~1 sand 0 replace
execute as @s unless block ~9~4~1 air at @s run setblock ~9~4~1 sand 0 replace
execute as @s unless block ~9~3~1 air at @s run setblock ~9~3~1 sand 0 replace
execute as @s unless block ~9~2~1 air at @s run setblock ~9~2~1 sand 0 replace
execute as @s unless block ~9~1~1 air at @s run setblock ~9~1~1 sand 0 replace
execute as @s unless block ~9~0~1 air at @s run setblock ~9~0~1 sand 0 replace
execute as @s unless block ~9~-1~1 air at @s run setblock ~9~-1~1 sand 0 replace
execute as @s unless block ~9~-2~1 air at @s run setblock ~9~-2~1 sand 0 replace
execute as @s unless block ~9~-3~1 air at @s run setblock ~9~-3~1 sand 0 replace
execute as @s unless block ~9~-4~1 air at @s run setblock ~9~-4~1 sand 0 replace
execute as @s unless block ~9~-5~1 air at @s run setblock ~9~-5~1 sand 0 replace
execute as @s unless block ~9~7~2 air at @s run setblock ~9~7~2 sand 0 replace
execute as @s unless block ~9~6~2 air at @s run setblock ~9~6~2 sand 0 replace
execute as @s unless block ~9~5~2 air at @s run setblock ~9~5~2 sand 0 replace
execute as @s unless block ~9~4~2 air at @s run setblock ~9~4~2 sand 0 replace
execute as @s unless block ~9~3~2 air at @s run setblock ~9~3~2 sand 0 replace
execute as @s unless block ~9~2~2 air at @s run setblock ~9~2~2 sand 0 replace
execute as @s unless block ~9~1~2 air at @s run setblock ~9~1~2 sand 0 replace
execute as @s unless block ~9~0~2 air at @s run setblock ~9~0~2 sand 0 replace
execute as @s unless block ~9~-1~2 air at @s run setblock ~9~-1~2 sand 0 replace
execute as @s unless block ~9~-2~2 air at @s run setblock ~9~-2~2 sand 0 replace
execute as @s unless block ~9~-3~2 air at @s run setblock ~9~-3~2 sand 0 replace
execute as @s unless block ~9~-4~2 air at @s run setblock ~9~-4~2 sand 0 replace
execute as @s unless block ~9~-5~2 air at @s run setblock ~9~-5~2 sand 0 replace
execute as @s unless block ~9~7~3 air at @s run setblock ~9~7~3 sand 0 replace
execute as @s unless block ~9~6~3 air at @s run setblock ~9~6~3 sand 0 replace
execute as @s unless block ~9~5~3 air at @s run setblock ~9~5~3 sand 0 replace
execute as @s unless block ~9~4~3 air at @s run setblock ~9~4~3 sand 0 replace
execute as @s unless block ~9~3~3 air at @s run setblock ~9~3~3 sand 0 replace
execute as @s unless block ~9~2~3 air at @s run setblock ~9~2~3 sand 0 replace
execute as @s unless block ~9~1~3 air at @s run setblock ~9~1~3 sand 0 replace
execute as @s unless block ~9~0~3 air at @s run setblock ~9~0~3 sand 0 replace
execute as @s unless block ~9~-1~3 air at @s run setblock ~9~-1~3 sand 0 replace
execute as @s unless block ~9~-2~3 air at @s run setblock ~9~-2~3 sand 0 replace
execute as @s unless block ~9~-3~3 air at @s run setblock ~9~-3~3 sand 0 replace
execute as @s unless block ~9~-4~3 air at @s run setblock ~9~-4~3 sand 0 replace
execute as @s unless block ~9~-5~3 air at @s run setblock ~9~-5~3 sand 0 replace
execute as @s unless block ~9~7~4 air at @s run setblock ~9~7~4 sand 0 replace
execute as @s unless block ~9~6~4 air at @s run setblock ~9~6~4 sand 0 replace
execute as @s unless block ~9~5~4 air at @s run setblock ~9~5~4 sand 0 replace
execute as @s unless block ~9~4~4 air at @s run setblock ~9~4~4 sand 0 replace
execute as @s unless block ~9~3~4 air at @s run setblock ~9~3~4 sand 0 replace
execute as @s unless block ~9~2~4 air at @s run setblock ~9~2~4 sand 0 replace
execute as @s unless block ~9~1~4 air at @s run setblock ~9~1~4 sand 0 replace
execute as @s unless block ~9~0~4 air at @s run setblock ~9~0~4 sand 0 replace
execute as @s unless block ~9~-1~4 air at @s run setblock ~9~-1~4 sand 0 replace
execute as @s unless block ~9~-2~4 air at @s run setblock ~9~-2~4 sand 0 replace
execute as @s unless block ~9~-3~4 air at @s run setblock ~9~-3~4 sand 0 replace
execute as @s unless block ~9~-4~4 air at @s run setblock ~9~-4~4 sand 0 replace
execute as @s unless block ~9~-5~4 air at @s run setblock ~9~-5~4 sand 0 replace
execute as @s unless block ~9~7~5 air at @s run setblock ~9~7~5 sand 0 replace
execute as @s unless block ~9~6~5 air at @s run setblock ~9~6~5 sand 0 replace
execute as @s unless block ~9~5~5 air at @s run setblock ~9~5~5 sand 0 replace
execute as @s unless block ~9~4~5 air at @s run setblock ~9~4~5 sand 0 replace
execute as @s unless block ~9~3~5 air at @s run setblock ~9~3~5 sand 0 replace
execute as @s unless block ~9~2~5 air at @s run setblock ~9~2~5 sand 0 replace
execute as @s unless block ~9~1~5 air at @s run setblock ~9~1~5 sand 0 replace
execute as @s unless block ~9~0~5 air at @s run setblock ~9~0~5 sand 0 replace
execute as @s unless block ~9~-1~5 air at @s run setblock ~9~-1~5 sand 0 replace
execute as @s unless block ~9~-2~5 air at @s run setblock ~9~-2~5 sand 0 replace
execute as @s unless block ~9~-3~5 air at @s run setblock ~9~-3~5 sand 0 replace
execute as @s unless block ~9~-4~5 air at @s run setblock ~9~-4~5 sand 0 replace
execute as @s unless block ~9~-5~5 air at @s run setblock ~9~-5~5 sand 0 replace
execute as @s unless block ~9~7~6 air at @s run setblock ~9~7~6 sand 0 replace
execute as @s unless block ~9~6~6 air at @s run setblock ~9~6~6 sand 0 replace
execute as @s unless block ~9~5~6 air at @s run setblock ~9~5~6 sand 0 replace
execute as @s unless block ~9~4~6 air at @s run setblock ~9~4~6 sand 0 replace
execute as @s unless block ~9~3~6 air at @s run setblock ~9~3~6 sand 0 replace
execute as @s unless block ~9~2~6 air at @s run setblock ~9~2~6 sand 0 replace
execute as @s unless block ~9~1~6 air at @s run setblock ~9~1~6 sand 0 replace
execute as @s unless block ~9~0~6 air at @s run setblock ~9~0~6 sand 0 replace
execute as @s unless block ~9~-1~6 air at @s run setblock ~9~-1~6 sand 0 replace
execute as @s unless block ~9~-2~6 air at @s run setblock ~9~-2~6 sand 0 replace
execute as @s unless block ~9~-3~6 air at @s run setblock ~9~-3~6 sand 0 replace
execute as @s unless block ~9~-4~6 air at @s run setblock ~9~-4~6 sand 0 replace
execute as @s unless block ~9~-5~6 air at @s run setblock ~9~-5~6 sand 0 replace
execute as @s unless block ~9~7~7 air at @s run setblock ~9~7~7 sand 0 replace
execute as @s unless block ~9~6~7 air at @s run setblock ~9~6~7 sand 0 replace
execute as @s unless block ~9~5~7 air at @s run setblock ~9~5~7 sand 0 replace
execute as @s unless block ~9~4~7 air at @s run setblock ~9~4~7 sand 0 replace
execute as @s unless block ~9~3~7 air at @s run setblock ~9~3~7 sand 0 replace
execute as @s unless block ~9~2~7 air at @s run setblock ~9~2~7 sand 0 replace
execute as @s unless block ~9~1~7 air at @s run setblock ~9~1~7 sand 0 replace
execute as @s unless block ~9~0~7 air at @s run setblock ~9~0~7 sand 0 replace
execute as @s unless block ~9~-1~7 air at @s run setblock ~9~-1~7 sand 0 replace
execute as @s unless block ~9~-2~7 air at @s run setblock ~9~-2~7 sand 0 replace
execute as @s unless block ~9~-3~7 air at @s run setblock ~9~-3~7 sand 0 replace
execute as @s unless block ~9~-4~7 air at @s run setblock ~9~-4~7 sand 0 replace
execute as @s unless block ~9~-5~7 air at @s run setblock ~9~-5~7 sand 0 replace
execute as @s unless block ~9~7~8 air at @s run setblock ~9~7~8 sand 0 replace
execute as @s unless block ~9~6~8 air at @s run setblock ~9~6~8 sand 0 replace
execute as @s unless block ~9~5~8 air at @s run setblock ~9~5~8 sand 0 replace
execute as @s unless block ~9~4~8 air at @s run setblock ~9~4~8 sand 0 replace
execute as @s unless block ~9~3~8 air at @s run setblock ~9~3~8 sand 0 replace
execute as @s unless block ~9~2~8 air at @s run setblock ~9~2~8 sand 0 replace
execute as @s unless block ~9~1~8 air at @s run setblock ~9~1~8 sand 0 replace
execute as @s unless block ~9~0~8 air at @s run setblock ~9~0~8 sand 0 replace
execute as @s unless block ~9~-1~8 air at @s run setblock ~9~-1~8 sand 0 replace
execute as @s unless block ~9~-2~8 air at @s run setblock ~9~-2~8 sand 0 replace
execute as @s unless block ~9~-3~8 air at @s run setblock ~9~-3~8 sand 0 replace
execute as @s unless block ~9~-4~8 air at @s run setblock ~9~-4~8 sand 0 replace
execute as @s unless block ~9~-5~8 air at @s run setblock ~9~-5~8 sand 0 replace
execute as @s unless block ~9~7~9 air at @s run setblock ~9~7~9 sand 0 replace
execute as @s unless block ~9~6~9 air at @s run setblock ~9~6~9 sand 0 replace
execute as @s unless block ~9~5~9 air at @s run setblock ~9~5~9 sand 0 replace
execute as @s unless block ~9~4~9 air at @s run setblock ~9~4~9 sand 0 replace
execute as @s unless block ~9~3~9 air at @s run setblock ~9~3~9 sand 0 replace
execute as @s unless block ~9~2~9 air at @s run setblock ~9~2~9 sand 0 replace
execute as @s unless block ~9~1~9 air at @s run setblock ~9~1~9 sand 0 replace
execute as @s unless block ~9~0~9 air at @s run setblock ~9~0~9 sand 0 replace
execute as @s unless block ~9~-1~9 air at @s run setblock ~9~-1~9 sand 0 replace
execute as @s unless block ~9~-2~9 air at @s run setblock ~9~-2~9 sand 0 replace
execute as @s unless block ~9~-3~9 air at @s run setblock ~9~-3~9 sand 0 replace
execute as @s unless block ~9~-4~9 air at @s run setblock ~9~-4~9 sand 0 replace
execute as @s unless block ~9~-5~9 air at @s run setblock ~9~-5~9 sand 0 replace
