execute positioned as @s unless block ~-2~7~-2 air at @s run setblock ~-2~7~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~6~-2 air at @s run setblock ~-2~6~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~5~-2 air at @s run setblock ~-2~5~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~4~-2 air at @s run setblock ~-2~4~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~3~-2 air at @s run setblock ~-2~3~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~2~-2 air at @s run setblock ~-2~2~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~1~-2 air at @s run setblock ~-2~1~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~0~-2 air at @s run setblock ~-2~0~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-1~-2 air at @s run setblock ~-2~-1~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-2~-2 air at @s run setblock ~-2~-2~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-3~-2 air at @s run setblock ~-2~-3~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-4~-2 air at @s run setblock ~-2~-4~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-5~-2 air at @s run setblock ~-2~-5~-2 blue_ice 0 replace
execute positioned as @s unless block ~-2~7~-1 air at @s run setblock ~-2~7~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~6~-1 air at @s run setblock ~-2~6~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~5~-1 air at @s run setblock ~-2~5~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~4~-1 air at @s run setblock ~-2~4~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~3~-1 air at @s run setblock ~-2~3~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~2~-1 air at @s run setblock ~-2~2~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~1~-1 air at @s run setblock ~-2~1~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~0~-1 air at @s run setblock ~-2~0~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-1~-1 air at @s run setblock ~-2~-1~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-2~-1 air at @s run setblock ~-2~-2~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-3~-1 air at @s run setblock ~-2~-3~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-4~-1 air at @s run setblock ~-2~-4~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-5~-1 air at @s run setblock ~-2~-5~-1 blue_ice 0 replace
execute positioned as @s unless block ~-2~7~0 air at @s run setblock ~-2~7~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~6~0 air at @s run setblock ~-2~6~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~5~0 air at @s run setblock ~-2~5~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~4~0 air at @s run setblock ~-2~4~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~3~0 air at @s run setblock ~-2~3~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~2~0 air at @s run setblock ~-2~2~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~1~0 air at @s run setblock ~-2~1~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~0~0 air at @s run setblock ~-2~0~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~-1~0 air at @s run setblock ~-2~-1~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~-2~0 air at @s run setblock ~-2~-2~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~-3~0 air at @s run setblock ~-2~-3~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~-4~0 air at @s run setblock ~-2~-4~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~-5~0 air at @s run setblock ~-2~-5~0 blue_ice 0 replace
execute positioned as @s unless block ~-2~7~1 air at @s run setblock ~-2~7~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~6~1 air at @s run setblock ~-2~6~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~5~1 air at @s run setblock ~-2~5~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~4~1 air at @s run setblock ~-2~4~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~3~1 air at @s run setblock ~-2~3~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~2~1 air at @s run setblock ~-2~2~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~1~1 air at @s run setblock ~-2~1~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~0~1 air at @s run setblock ~-2~0~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-1~1 air at @s run setblock ~-2~-1~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-2~1 air at @s run setblock ~-2~-2~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-3~1 air at @s run setblock ~-2~-3~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-4~1 air at @s run setblock ~-2~-4~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~-5~1 air at @s run setblock ~-2~-5~1 blue_ice 0 replace
execute positioned as @s unless block ~-2~7~2 air at @s run setblock ~-2~7~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~6~2 air at @s run setblock ~-2~6~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~5~2 air at @s run setblock ~-2~5~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~4~2 air at @s run setblock ~-2~4~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~3~2 air at @s run setblock ~-2~3~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~2~2 air at @s run setblock ~-2~2~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~1~2 air at @s run setblock ~-2~1~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~0~2 air at @s run setblock ~-2~0~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-1~2 air at @s run setblock ~-2~-1~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-2~2 air at @s run setblock ~-2~-2~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-3~2 air at @s run setblock ~-2~-3~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-4~2 air at @s run setblock ~-2~-4~2 blue_ice 0 replace
execute positioned as @s unless block ~-2~-5~2 air at @s run setblock ~-2~-5~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~7~-2 air at @s run setblock ~-1~7~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~6~-2 air at @s run setblock ~-1~6~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~5~-2 air at @s run setblock ~-1~5~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~4~-2 air at @s run setblock ~-1~4~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~3~-2 air at @s run setblock ~-1~3~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~2~-2 air at @s run setblock ~-1~2~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~1~-2 air at @s run setblock ~-1~1~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~0~-2 air at @s run setblock ~-1~0~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-1~-2 air at @s run setblock ~-1~-1~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-2~-2 air at @s run setblock ~-1~-2~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-3~-2 air at @s run setblock ~-1~-3~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-4~-2 air at @s run setblock ~-1~-4~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-5~-2 air at @s run setblock ~-1~-5~-2 blue_ice 0 replace
execute positioned as @s unless block ~-1~7~2 air at @s run setblock ~-1~7~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~6~2 air at @s run setblock ~-1~6~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~5~2 air at @s run setblock ~-1~5~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~4~2 air at @s run setblock ~-1~4~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~3~2 air at @s run setblock ~-1~3~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~2~2 air at @s run setblock ~-1~2~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~1~2 air at @s run setblock ~-1~1~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~0~2 air at @s run setblock ~-1~0~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-1~2 air at @s run setblock ~-1~-1~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-2~2 air at @s run setblock ~-1~-2~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-3~2 air at @s run setblock ~-1~-3~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-4~2 air at @s run setblock ~-1~-4~2 blue_ice 0 replace
execute positioned as @s unless block ~-1~-5~2 air at @s run setblock ~-1~-5~2 blue_ice 0 replace
execute positioned as @s unless block ~0~7~-2 air at @s run setblock ~0~7~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~6~-2 air at @s run setblock ~0~6~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~5~-2 air at @s run setblock ~0~5~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~4~-2 air at @s run setblock ~0~4~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~3~-2 air at @s run setblock ~0~3~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~2~-2 air at @s run setblock ~0~2~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~1~-2 air at @s run setblock ~0~1~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~0~-2 air at @s run setblock ~0~0~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~-1~-2 air at @s run setblock ~0~-1~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~-2~-2 air at @s run setblock ~0~-2~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~-3~-2 air at @s run setblock ~0~-3~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~-4~-2 air at @s run setblock ~0~-4~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~-5~-2 air at @s run setblock ~0~-5~-2 blue_ice 0 replace
execute positioned as @s unless block ~0~7~2 air at @s run setblock ~0~7~2 blue_ice 0 replace
execute positioned as @s unless block ~0~6~2 air at @s run setblock ~0~6~2 blue_ice 0 replace
execute positioned as @s unless block ~0~5~2 air at @s run setblock ~0~5~2 blue_ice 0 replace
execute positioned as @s unless block ~0~4~2 air at @s run setblock ~0~4~2 blue_ice 0 replace
execute positioned as @s unless block ~0~3~2 air at @s run setblock ~0~3~2 blue_ice 0 replace
execute positioned as @s unless block ~0~2~2 air at @s run setblock ~0~2~2 blue_ice 0 replace
execute positioned as @s unless block ~0~1~2 air at @s run setblock ~0~1~2 blue_ice 0 replace
execute positioned as @s unless block ~0~0~2 air at @s run setblock ~0~0~2 blue_ice 0 replace
execute positioned as @s unless block ~0~-1~2 air at @s run setblock ~0~-1~2 blue_ice 0 replace
execute positioned as @s unless block ~0~-2~2 air at @s run setblock ~0~-2~2 blue_ice 0 replace
execute positioned as @s unless block ~0~-3~2 air at @s run setblock ~0~-3~2 blue_ice 0 replace
execute positioned as @s unless block ~0~-4~2 air at @s run setblock ~0~-4~2 blue_ice 0 replace
execute positioned as @s unless block ~0~-5~2 air at @s run setblock ~0~-5~2 blue_ice 0 replace
execute positioned as @s unless block ~1~7~-2 air at @s run setblock ~1~7~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~6~-2 air at @s run setblock ~1~6~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~5~-2 air at @s run setblock ~1~5~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~4~-2 air at @s run setblock ~1~4~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~3~-2 air at @s run setblock ~1~3~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~2~-2 air at @s run setblock ~1~2~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~1~-2 air at @s run setblock ~1~1~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~0~-2 air at @s run setblock ~1~0~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~-1~-2 air at @s run setblock ~1~-1~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~-2~-2 air at @s run setblock ~1~-2~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~-3~-2 air at @s run setblock ~1~-3~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~-4~-2 air at @s run setblock ~1~-4~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~-5~-2 air at @s run setblock ~1~-5~-2 blue_ice 0 replace
execute positioned as @s unless block ~1~7~2 air at @s run setblock ~1~7~2 blue_ice 0 replace
execute positioned as @s unless block ~1~6~2 air at @s run setblock ~1~6~2 blue_ice 0 replace
execute positioned as @s unless block ~1~5~2 air at @s run setblock ~1~5~2 blue_ice 0 replace
execute positioned as @s unless block ~1~4~2 air at @s run setblock ~1~4~2 blue_ice 0 replace
execute positioned as @s unless block ~1~3~2 air at @s run setblock ~1~3~2 blue_ice 0 replace
execute positioned as @s unless block ~1~2~2 air at @s run setblock ~1~2~2 blue_ice 0 replace
execute positioned as @s unless block ~1~1~2 air at @s run setblock ~1~1~2 blue_ice 0 replace
execute positioned as @s unless block ~1~0~2 air at @s run setblock ~1~0~2 blue_ice 0 replace
execute positioned as @s unless block ~1~-1~2 air at @s run setblock ~1~-1~2 blue_ice 0 replace
execute positioned as @s unless block ~1~-2~2 air at @s run setblock ~1~-2~2 blue_ice 0 replace
execute positioned as @s unless block ~1~-3~2 air at @s run setblock ~1~-3~2 blue_ice 0 replace
execute positioned as @s unless block ~1~-4~2 air at @s run setblock ~1~-4~2 blue_ice 0 replace
execute positioned as @s unless block ~1~-5~2 air at @s run setblock ~1~-5~2 blue_ice 0 replace
execute positioned as @s unless block ~2~7~-2 air at @s run setblock ~2~7~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~6~-2 air at @s run setblock ~2~6~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~5~-2 air at @s run setblock ~2~5~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~4~-2 air at @s run setblock ~2~4~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~3~-2 air at @s run setblock ~2~3~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~2~-2 air at @s run setblock ~2~2~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~1~-2 air at @s run setblock ~2~1~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~0~-2 air at @s run setblock ~2~0~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~-1~-2 air at @s run setblock ~2~-1~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~-2~-2 air at @s run setblock ~2~-2~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~-3~-2 air at @s run setblock ~2~-3~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~-4~-2 air at @s run setblock ~2~-4~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~-5~-2 air at @s run setblock ~2~-5~-2 blue_ice 0 replace
execute positioned as @s unless block ~2~7~-1 air at @s run setblock ~2~7~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~6~-1 air at @s run setblock ~2~6~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~5~-1 air at @s run setblock ~2~5~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~4~-1 air at @s run setblock ~2~4~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~3~-1 air at @s run setblock ~2~3~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~2~-1 air at @s run setblock ~2~2~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~1~-1 air at @s run setblock ~2~1~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~0~-1 air at @s run setblock ~2~0~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~-1~-1 air at @s run setblock ~2~-1~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~-2~-1 air at @s run setblock ~2~-2~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~-3~-1 air at @s run setblock ~2~-3~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~-4~-1 air at @s run setblock ~2~-4~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~-5~-1 air at @s run setblock ~2~-5~-1 blue_ice 0 replace
execute positioned as @s unless block ~2~7~0 air at @s run setblock ~2~7~0 blue_ice 0 replace
execute positioned as @s unless block ~2~6~0 air at @s run setblock ~2~6~0 blue_ice 0 replace
execute positioned as @s unless block ~2~5~0 air at @s run setblock ~2~5~0 blue_ice 0 replace
execute positioned as @s unless block ~2~4~0 air at @s run setblock ~2~4~0 blue_ice 0 replace
execute positioned as @s unless block ~2~3~0 air at @s run setblock ~2~3~0 blue_ice 0 replace
execute positioned as @s unless block ~2~2~0 air at @s run setblock ~2~2~0 blue_ice 0 replace
execute positioned as @s unless block ~2~1~0 air at @s run setblock ~2~1~0 blue_ice 0 replace
execute positioned as @s unless block ~2~0~0 air at @s run setblock ~2~0~0 blue_ice 0 replace
execute positioned as @s unless block ~2~-1~0 air at @s run setblock ~2~-1~0 blue_ice 0 replace
execute positioned as @s unless block ~2~-2~0 air at @s run setblock ~2~-2~0 blue_ice 0 replace
execute positioned as @s unless block ~2~-3~0 air at @s run setblock ~2~-3~0 blue_ice 0 replace
execute positioned as @s unless block ~2~-4~0 air at @s run setblock ~2~-4~0 blue_ice 0 replace
execute positioned as @s unless block ~2~-5~0 air at @s run setblock ~2~-5~0 blue_ice 0 replace
execute positioned as @s unless block ~2~7~1 air at @s run setblock ~2~7~1 blue_ice 0 replace
execute positioned as @s unless block ~2~6~1 air at @s run setblock ~2~6~1 blue_ice 0 replace
execute positioned as @s unless block ~2~5~1 air at @s run setblock ~2~5~1 blue_ice 0 replace
execute positioned as @s unless block ~2~4~1 air at @s run setblock ~2~4~1 blue_ice 0 replace
execute positioned as @s unless block ~2~3~1 air at @s run setblock ~2~3~1 blue_ice 0 replace
execute positioned as @s unless block ~2~2~1 air at @s run setblock ~2~2~1 blue_ice 0 replace
execute positioned as @s unless block ~2~1~1 air at @s run setblock ~2~1~1 blue_ice 0 replace
execute positioned as @s unless block ~2~0~1 air at @s run setblock ~2~0~1 blue_ice 0 replace
execute positioned as @s unless block ~2~-1~1 air at @s run setblock ~2~-1~1 blue_ice 0 replace
execute positioned as @s unless block ~2~-2~1 air at @s run setblock ~2~-2~1 blue_ice 0 replace
execute positioned as @s unless block ~2~-3~1 air at @s run setblock ~2~-3~1 blue_ice 0 replace
execute positioned as @s unless block ~2~-4~1 air at @s run setblock ~2~-4~1 blue_ice 0 replace
execute positioned as @s unless block ~2~-5~1 air at @s run setblock ~2~-5~1 blue_ice 0 replace
execute positioned as @s unless block ~2~7~2 air at @s run setblock ~2~7~2 blue_ice 0 replace
execute positioned as @s unless block ~2~6~2 air at @s run setblock ~2~6~2 blue_ice 0 replace
execute positioned as @s unless block ~2~5~2 air at @s run setblock ~2~5~2 blue_ice 0 replace
execute positioned as @s unless block ~2~4~2 air at @s run setblock ~2~4~2 blue_ice 0 replace
execute positioned as @s unless block ~2~3~2 air at @s run setblock ~2~3~2 blue_ice 0 replace
execute positioned as @s unless block ~2~2~2 air at @s run setblock ~2~2~2 blue_ice 0 replace
execute positioned as @s unless block ~2~1~2 air at @s run setblock ~2~1~2 blue_ice 0 replace
execute positioned as @s unless block ~2~0~2 air at @s run setblock ~2~0~2 blue_ice 0 replace
execute positioned as @s unless block ~2~-1~2 air at @s run setblock ~2~-1~2 blue_ice 0 replace
execute positioned as @s unless block ~2~-2~2 air at @s run setblock ~2~-2~2 blue_ice 0 replace
execute positioned as @s unless block ~2~-3~2 air at @s run setblock ~2~-3~2 blue_ice 0 replace
execute positioned as @s unless block ~2~-4~2 air at @s run setblock ~2~-4~2 blue_ice 0 replace
execute positioned as @s unless block ~2~-5~2 air at @s run setblock ~2~-5~2 blue_ice 0 replace
