execute @e[type=player,r=1,c=1] ~~~ detect ^1^1^ snow -1 setblock ^1^1^ water
execute @e[type=player,r=1,c=1] ~~~ detect ^-1^1^ snow -1 setblock ^-1^1^ water
execute @e[type=player,r=1,c=1] ~~~ detect ^^1^1 snow -1 setblock ^^1^1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^1^-1 snow -1 setblock ^^1^-1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^1^-1 snow -1 setblock ^^1^-1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^-1^2^ snow -1 setblock ^-1^2^ water
execute @e[type=player,r=1,c=1] ~~~ detect ^^2^1 snow -1 setblock ^^2^1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^2^-1 snow -1 setblock ^^2^-1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^3^ snow -1 setblock ^^3^ water

execute @e[type=player,r=1,c=1] ~~~ detect ^1^1^ powder_snow -1 setblock ^1^1^ water
execute @e[type=player,r=1,c=1] ~~~ detect ^-1^1^ powder_snow -1 setblock ^-1^1^ water
execute @e[type=player,r=1,c=1] ~~~ detect ^^1^1 powder_snow -1 setblock ^^1^1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^1^-1 powder_snow -1 setblock ^^1^-1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^1^-1 powder_snow -1 setblock ^^1^-1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^-1^2^ powder_snow -1 setblock ^-1^2^ water
execute @e[type=player,r=1,c=1] ~~~ detect ^^2^1 powder_snow -1 setblock ^^2^1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^2^-1 powder_snow -1 setblock ^^2^-1 water
execute @e[type=player,r=1,c=1] ~~~ detect ^^3^ powder_snow -1 setblock ^^3^ water
